### ISSUE TITLE
where are the DeltaRpooling and DeltaCpooling in dcn?

### ISSUE THREAD

**Issue by caiduoduo12138** [open-mmlab/mmcv#1003]
I want to build some code from mmdet1.0 to mmdet2.0, but some apis have been written into mmcv now.  In mmcv/ops/dcn_roi_pool.py , DeltaRpooling and DeltaCpooling were not found.  Can you give me some advice? Thanks a lot.

**Comment by zhouzaida** [comment]
@hhaAndroid

**Comment by zhouzaida** [comment]
hi @caiduoduo12138 , is the issue resolved?

**Comment by caiduoduo12138** [comment]
Not yet,  I still could not found the function!

**Comment by zhouzaida** [comment]
Could you provide the version of `mmdet` containing DeltaRpooling and DeltaCpooling

**Comment by caiduoduo12138** [comment]
I solve it, thank you.

**Comment by fuweifu-vtoo** [comment]
@caiduoduo12138 ,can you tell me how you solve it ?  I also want to use DeltaCPooling and DeltaRpooling

**Comment by qjh666888** [comment]
请问应该怎么解决呀
