### ISSUE TITLE
Pass `None` to `cfg` in `build_from_cfg`

### ISSUE THREAD

**Issue by mzr1996** [open-mmlab/mmcv#1008]
**Describe the feature**
When we use `build_from_cfg`, I think `cfg` should be for users to customize configs and `default_args` is for developers to set default config.
However, now if we pass `None` to `cfg`, `build_from_cfg` will report an error.
https://github.com/open-mmlab/mmcv/blob/c4aa4146f50e60638b3455870c5d0ff1c2af10d5/mmcv/utils/registry.py#L19-L20
I think we should allow passing `None` to `cfg` if `build_from_cfg` is not None.

**Comment by zhouzaida** [comment]
hi, @mzr1996
```
I think we should allow passing None to cfg if build_from_cfg is not None.
```
Could you tell me why it needs to be revised like this?

**Comment by mzr1996** [comment]
Closed
