### ISSUE TITLE
Add fp16 unit tests to the CUDA ops when pytorch >= 1.6

### ISSUE THREAD

**Issue by AronLin** [open-mmlab/mmcv#1028]
**Describe the Issue**

I notice that there was a runtime error #1004 and it was fixed in mmcv 1.3.4.
However, the same problem still exists when using DCNv2.

So I suggest to check the support of CUDA ops for fp16 or add unit tests to CUDA ops to support fp16，when pytorch >= 1.6.

**Environment**
pytorch >= 1.6.0
mmcv >= 1.3.2

I will send a PR to fix the bug when using DCNv2 with the same way in PR #1014

**Comment by zhouzaida** [comment]
thanks
