### ISSUE TITLE
cant install in windows

### ISSUE THREAD

**Issue by sxlyiyiyi** [open-mmlab/mmcv#1035]
when i run “ python setup.py build_ext”，there some wrong happened

building 'mmcv._ext' extension
creating C:\Users\sxl\mmcv\build
creating C:\Users\sxl\mmcv\build\temp.win-amd64-3.7
creating C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release
creating C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\mmcv
creating C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\mmcv\ops
creating C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\mmcv\ops\csrc
creating C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\mmcv\ops\csrc\pytorch
Emitting ninja build file C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\build.ninja...
Compiling objects...
Using envvar MAX_JOBS (4) as the number of workers...
1.10.2
creating C:\Users\sxl\mmcv\build\lib.win-amd64-3.7
creating C:\Users\sxl\mmcv\build\lib.win-amd64-3.7\mmcv
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\sxl\anaconda3\envs\transformer\lib\site-packages\torch\lib "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\lib/x64" /LIBPATH:C:\Users\sxl\anaconda3\envs\transformer\libs /LIBPATH:C:\Users\sxl\anaconda3\envs\transformer\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x64" c10.lib torch.lib torch_cpu.lib torch_python.lib cudart.lib c10_cuda.lib torch_cuda_cu.lib torch_cuda_cpp.lib /EXPORT:PyInit__ext C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\bbox_overlaps.obj C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\bbox_overlaps_cuda.obj C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\box_iou_rotated.obj C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\box_iou_rotated_cpu.obj C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\box_iou_rotated_cuda.obj C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\carafe.obj C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\carafe_cuda.obj C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\carafe_naive.obj C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\carafe_naive_cuda.obj C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\cc_attention.obj C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\cc_attention_cuda.obj C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\contour_expand.obj C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\corner_pool.obj C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\deform_conv.obj C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\deform_conv_cuda.obj C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\deform_roi_pool.obj C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\deform_roi_pool_cuda.obj C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\focal_loss.obj C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\focal_loss_cuda.obj C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\fused_bias_leakyrelu.obj C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\fused_bias_leakyrelu_cuda.obj C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\info.obj C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\masked_conv2d.obj C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\masked_conv2d_cuda.obj C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\modulated_deform_conv.obj C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\modulated_deform_conv_cuda.obj C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\ms_deform_attn.obj C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\ms_deform_attn_cuda.obj C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\nms.obj C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\nms_cuda.obj C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\nms_rotated.obj C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\nms_rotated_cpu.obj C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\nms_rotated_cuda.obj C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\pixel_group.obj C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\psamask.obj C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\psamask_cuda.obj C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\pybind.obj C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\roi_align.obj C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\roi_align_cpu.obj C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\roi_align_cuda.obj C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\roi_align_rotated.obj C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\roi_align_rotated_cpu.obj C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\roi_align_rotated_cuda.obj C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\roi_pool.obj C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\roi_pool_cuda.obj C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\sync_bn.obj C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\sync_bn_cuda.obj C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\tin_shift.obj C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\tin_shift_cuda.obj C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\upfirdn2d.obj C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\upfirdn2d_kernel.obj /OUT:build\lib.win-amd64-3.7\mmcv\_ext.cp37-win_amd64.pyd /IMPLIB:C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\_ext.cp37-win_amd64.lib
LINK : fatal error LNK1181: 无法打开输入文件“C:\Users\sxl\mmcv\build\temp.win-amd64-3.7\Release\.\mmcv\ops\csrc\pytorch\bbox_overlaps.obj”
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29910\\bin\\HostX86\\x64\\link.exe' failed with exit status 1181

**Comment by ZwwWayne** [comment]
Please use the template of `unexpected results`.

**Comment by Gaoxj2020** [comment]
Have you soloved it？
