### ISSUE TITLE
How to define initialization type for bias?

### ISSUE THREAD

**Issue by mzr1996** [open-mmlab/mmcv#1047]
In many initialization modules, docstring says that bias can be initialized to the specified type.
https://github.com/open-mmlab/mmcv/blob/55b4847a4105b722e440fb263864e805d2d0a911/mmcv/cnn/utils/weight_init.py#L130-L131
But it seems not implemented.
https://github.com/open-mmlab/mmcv/blob/55b4847a4105b722e440fb263864e805d2d0a911/mmcv/cnn/utils/weight_init.py#L144-L150
https://github.com/open-mmlab/mmcv/blob/55b4847a4105b722e440fb263864e805d2d0a911/mmcv/cnn/utils/weight_init.py#L16-L20
If in design, we can specify bias initialization type, we need to implement it.

**Comment by MeowZheng** [comment]
Hi Zerun,

Many thanks for your issue.

It is not in design to randomly initialize bias, and I'll fix the docstring asap.

Best regards,
Meow
