### ISSUE TITLE
ERROR: Failed building wheel for mmcv-full

### ISSUE THREAD

**Issue by sunboyan1024** [open-mmlab/mmcv#1049]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the FAQ documentation but cannot get the expected help.
When I install mmcv, an error is displayed:ERROR: Failed building wheel for mmcv-full
![image](https://user-images.githubusercontent.com/72020623/119358969-b413fa80-bcdb-11eb-8562-e07b376575b3.png)

**Comment by zhouzaida** [comment]
please provide the full error infomation
