### ISSUE TITLE
Spelling mistake in Config.auto_argparser()

### ISSUE THREAD

**Issue by zhanzy178** [open-mmlab/mmcv#105]
The [line](https://github.com/open-mmlab/mmcv/blob/master/mmcv/utils/config.py#L106) has a little spelling mistake that `cfg = Config.from_file(cfg_file)` in `Config.auto_argparser()` function should be `cfg = Config.fromfile(cfg_file)`.

**Comment by hellock** [comment]
Thanks! You can create a pull request to fix it if you would like to.

**Comment by zhanzy178** [comment]
I would do this. It is my pleasure!
