### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by epiphany97** [open-mmlab/mmcv#1052]
when I run  command  to end-to-end test a single image  for both text detection and recognition,
i got the result below:

ImportError: usr/.local/lib/python3.6/site-packages/mmcv/_ext.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIdEEPKNS_6detail12TypeMetaDataEv

the environment I use : cu92+torch1.7.0,mmcv-full=1.3.0

can you give me some advice?thanks a lot

**Comment by zhouzaida** [comment]
Hi @epiphany97 ,  It is very likely that your MMCV is compiled in an environment but ran in another environment. Please refer to open-mmlab/mmdetection#3871.
