### ISSUE TITLE
How to fix seed?

### ISSUE THREAD

**Issue by 2000ZRL** [open-mmlab/mmcv#1061]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the FAQ documentation but cannot get the expected help.

I know that I can set random seed by `mmcv.runner.set_random_seed(seed, deterministic=True)`. But it doesn't work. I only use the implementation of deformable convnets in my scripts. Before the training process, I fix seed of torch, numpy, python, cuda, and mmcv. But when I use the deformable convnets, the loss of first iter would be different. 

Here are my codes:
setup seed:
`def setup_seed(seed=8):`
    `random.seed(seed)`
    `os.environ['PYTHONHASHSEED'] = str(seed)`
    `np.random.seed(seed)`
    `torch.manual_seed(seed)`
    `torch.cuda.manual_seed(seed)`
    `torch.cuda.manual_seed_all(seed)`
    `torch.backends.cudnn.deterministic = True`
    `runner.set_random_seed(seed, deterministic=True)`

use deformable convnets:
`from mmcv.ops import DeformConv2d, ModulatedDeformConv2d`

Since I need to return the offsets and modulated scalars, I don't use the DeformConv2dPack.
Can anyone help me? Thanks.

**Comment by ZwwWayne** [comment]
Though the seed is fixed, the randomly initialized weights are still different during each run. So we are not able to help here.
