### ISSUE TITLE
Can we save checkpoints of last several epochs?

### ISSUE THREAD

**Issue by mzr1996** [open-mmlab/mmcv#1064]
**Describe the feature**
If max epoch is 300, only save checkpoints of epoch 290~300.
Or save checkpoints each 10 epochs before epoch 290, and save every checkpoint after epoch 290.

**Motivation**
Because of storage limit, sometimes we cannot save every checkpoint. But we need to choose the best checkpoint in the final period, or merge several last checkpoints.

**Comment by zhouzaida** [comment]
Are you willing to create a PR to resolve it?

**Comment by mzr1996** [comment]
> Are you willing to create a PR to resolve it?

Have created, see https://github.com/open-mmlab/mmcv/pull/1068

**Comment by zhouzaida** [comment]
got it

**Comment by mzr1996** [comment]
Closed by #1068
