### ISSUE TITLE
Could evaluation hook use key_indicator in a case-insensitive manner?

### ISSUE THREAD

**Issue by ly015** [open-mmlab/mmcv#1065]
Would it be better to use key_indicator.lower() to infer the rule in a case-insensitive manner? E.g., "MAP" and "mAP" would both be okay, so the user won't have to pay attention to it.

https://github.com/open-mmlab/mmcv/blob/717d15719c713fd3ee9ab0d8eb3d98116758036e/mmcv/runner/hooks/evaluation.py#L125

**Comment by zhouzaida** [comment]
@dreamerlin

**Comment by ly015** [comment]
A PR https://github.com/open-mmlab/mmcv/pull/1076 has been submitted for this.

**Comment by zhouzaida** [comment]
Resolved by #1076
