### ISSUE TITLE
Why not support the multiple gpus train in non-distributed mode? 

### ISSUE THREAD

**Issue by icedream2** [open-mmlab/mmcv#1069]
I noticed that in the older version (like 0.4.2) , there is no limit on multiple gpu trains in non-distributed mode. But in current version, there is an assertion to restrict in in mmcv/parallel/data_parallel.py

We ask problem because that we found that the model's results are different when training in distributed and non-distributed modes, and sometimes non-distributed training obtains better result (not in object detection tasks)

**Comment by ZwwWayne** [comment]
Because the `nn.DataParallel` in PyTorch is slower and has potential bugs. According to the official documentation, for multi-GPU training, we use distributed training.
The accuracy should be the same, theoretically. The difference might be caused by randomness.
