### ISSUE TITLE
Can I export deformable convolution with ONNX?

### ISSUE THREAD

**Issue by AyanKumarBhunia** [open-mmlab/mmcv#1072]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the FAQ documentation but cannot get the expected help.

**Comment by zhouzaida** [comment]
@RunningLeon

**Comment by RunningLeon** [comment]
@AyanKumarBhunia Hi,  we can't export deformable convolution to ONNX in mmcv. This op is not supported by [onnx](https://github.com/onnx/onnx/blob/master/docs/Operators.md) and [onnxruntime](https://github.com/microsoft/onnxruntime/blob/master/docs/OperatorKernels.md).

**Comment by RunningLeon** [comment]
Closed due to age.

**Comment by 1204Gin** [comment]
Hello, I have the same question. I used DCNv2 in the YOLO model, but when I export onnx, I get an error until Error: Exporting the operator deform_comv2d to ONNX opset version 14 is not supported. Have you resolved this issue?
