### ISSUE TITLE
When can mmcv-full support Python 3.9?

### ISSUE THREAD

**Issue by Quebradawill** [open-mmlab/mmcv#1087]
Ubuntu has released 21.04, the default python version is 3.9, when can mmcv-full support Python 3.9?

**Comment by zhouzaida** [comment]
We will add python3.9 in CI to check

**Comment by zhouzaida** [comment]
Hi @Quebradawill , in the latest version (v1.3.15), we provide pre-compiled packages for the Python 3.9 environment.
