### ISSUE TITLE
Fix typo in docstring

### ISSUE THREAD

**Issue by ZwwWayne** [open-mmlab/mmcv#1111]
Fix Line https://github.com/open-mmlab/mmcv/blob/004c00675f912b9ac59ba07655295c86a39e29d1/mmcv/utils/config.py#L558

**Comment by Junjun2016** [comment]
https://github.com/open-mmlab/mmcv/blob/96c4b70ccbb9cbf452ff79695a35187f919b0c9d/mmcv/cnn/utils/weight_init.py#L449

kay --> key

**Comment by Junjun2016** [comment]
https://github.com/open-mmlab/mmcv/blob/96c4b70ccbb9cbf452ff79695a35187f919b0c9d/mmcv/runner/hooks/evaluation.py#L50

rule rule --> rule

**Comment by ZwwWayne** [comment]
This issue will be closed as its original change request has been fixed. Please @Junjun2016 comment and leave a message in this PR https://github.com/open-mmlab/mmcv/pull/1190.

**Comment by Junjun2016** [comment]
I will have a PR to fix these typos!
