### ISSUE TITLE
Can not create Registry instance in IPython

### ISSUE THREAD

**Issue by kennymckormick** [open-mmlab/mmcv#1116]
![image](https://user-images.githubusercontent.com/34324155/122662275-3650eb00-d1c4-11eb-9fe3-80ce7e9fa668.png)

**Comment by yarkable** [comment]
In my case, mmcv 1.2.7 works fine, but 1.3.5 fails.

**Comment by zhouzaida** [comment]
You can initialize registry by setting `scope` argument like `registry = Registry('mmcv', scope='xxx')`

**Comment by Flyingdog-Huang** [comment]
![image](https://user-images.githubusercontent.com/43697342/201599229-573ca6c0-9825-4db1-8e47-cf6d8daa2d01.png)
![image](https://user-images.githubusercontent.com/43697342/201599252-1d2539a5-171b-4f79-8252-36edf9227404.png)
