### ISSUE TITLE
TypeError: can't pickle dict_values objects

### ISSUE THREAD

**Issue by CodingWZP** [open-mmlab/mmcv#1127]
I encountered a problem when i use customized chinese label. Pleaese help me to solve this issue.

`Traceback (most recent call last):
  File "/home/codingwzp/CodesOfUbuntu/Work/ShuyeqiClassification/code_mmcls/train.py", line 157, in <module>
    main()
  File "/home/codingwzp/CodesOfUbuntu/Work/ShuyeqiClassification/code_mmcls/train.py", line 153, in main
    meta=meta)
  File "/home/codingwzp/CodesOfUbuntu/Work/ShuyeqiClassification/mmclassification/mmcls/apis/train.py", line 159, in train_model
    runner.run(data_loaders, cfg.workflow)
  File "/home/codingwzp/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/codingwzp/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  
File "/home/codingwzp/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/codingwzp/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/hooks/checkpoint.py", line 69, in after_train_epoch
    self._save_checkpoint(runner)
  File "/home/codingwzp/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/codingwzp/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/hooks/checkpoint.py", line 75, in _save_checkpoint
    self.out_dir, save_optimizer=self.save_optimizer, **self.args)
  File "/home/codingwzp/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 164, in save_checkpoint
    save_checkpoint(self.model, filepath, optimizer=optimizer, meta=meta)
  File "/home/codingwzp/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 671, in save_checkpoint
    torch.save(checkpoint, f)
  File "/home/codingwzp/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/serialization.py", line 372, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)
  File "/home/codingwzp/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/serialization.py", line 476, in _save
    pickler.dump(obj)
TypeError: can't pickle dict_values objects`

**Comment by zhouzaida** [comment]
hi @CodingWZP , could you provide the code how to reproduce the bug

**Comment by CodingWZP** [comment]
> hi @CodingWZP , could you provide the code how to reproduce the bug

**Comment by CodingWZP** [comment]
> hi @CodingWZP , could you provide the code how to reproduce the bug

我把mmcls/datasets/__init__.py修改了，添加了自己的数据集。
![image](https://user-images.githubusercontent.com/53462529/123212974-0c673380-d4f8-11eb-8f07-a5348127df07.png)

新的数据集标签如图所示
![image](https://user-images.githubusercontent.com/53462529/123213110-328cd380-d4f8-11eb-98ee-dd699a42e8db.png)
![image](https://user-images.githubusercontent.com/53462529/123213125-37ea1e00-d4f8-11eb-9f85-ac213d89ce97.png)

然后创建了新的文件夹作为项目目录，新增了一个dataset setting
```
# dataset settings
dataset_type = 'ShuYeQi'
img_norm_cfg = dict(
    mean=[129.304, 124.070, 112.434],
    std=[68.170, 65.392, 70.418],
    to_rgb=False)
train_pipeline = [
    # dict(type='RandomCrop', size=512, padding=4),
    dict(type='Resize', size=512),
    dict(type='RandomFlip', flip_prob=0.5, direction='horizontal'),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='ToTensor', keys=['gt_label']),
    dict(type='Collect', keys=['img', 'gt_label'])
]
test_pipeline = [
    dict(type='Resize', size=512),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='Collect', keys=['img'])
]
data = dict(
    samples_per_gpu=16,
    workers_per_gpu=2,
    train=dict(
        type=dataset_type,
        data_prefix='data/sml',
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        data_prefix='data/sml_val',
        pipeline=test_pipeline,
        test_mode=True),
    test=dict(
        type=dataset_type,
        data_prefix='data/sml_test',
        pipeline=test_pipeline,
        test_mode=True))

```

然后训练就报那个错误了，找了好久也不知道什么原因，求助~

**Comment by zhouzaida** [comment]
@mzr1996

**Comment by mzr1996** [comment]
> TypeError: can't pickle dict_values objects`

Hello, could you please provide your detailed implement of `ShuYeQi` class?

**Comment by CodingWZP** [comment]
```
import mmcv
import numpy as np
import os

from .builder import DATASETS
from .base_dataset import BaseDataset
import cv2


@DATASETS.register_module()
class ShuYeQi(BaseDataset):
    label_dic = {"正例（25B黄色）": 0,
                 "正例（25B）": 0,
                 "褶皱与划伤（25BTC透明+黄色）": 1,
                 "破损（25BTC）": 2,
                 "膜反（25BTC）": 3,
                 "膜反（25B）": 3,
                 "空膜（25BTC）": 4,
                 "空膜（25B）": 4,
                 "划痕（25B）": 5,
                 "焊轻（25BTC）": 6,
                 "焊轻（25B）": 6,
                 "焊偏（25BTC）": 7,
                 "焊偏（25B）": 7,
                 "焊化（25B）": 8,
                 "多膜（25BTC）": 9,
                 "多膜（25B）": 9,
                 "白点（25BTC）": 10,
                 "白点（25B）": 10,
                 }
    val_dic = {  0: "正例（25B黄色）",
                 # 0: "正例（25B）",
                 1: "褶皱与划伤（25BTC透明+黄色）",
                 2: "破损（25BTC）",
                 3: "膜反（25BTC）",
                 # 3: "膜反（25B）",
                 4: "空膜（25BTC）",
                 # 4: "空膜（25B）",
                 5: "划痕（25B）",
                 6: "焊轻（25BTC）",
                 # 6: "焊轻（25B）",
                 7: "焊偏（25BTC）",
                 # 7: "焊偏（25B）",
                 8: "焊化（25B）",
                 9: "多膜（25BTC）",
                 # 9: "多膜（25B）",
                 10: "白点（25BTC）",
                 # 10: "白点（25B）",
                 }

    def get_classes(self, classes=None):
        return self.val_dic.values()

    def load_annotations(self):

        print(self.CLASSES)

        imgs = []
        gt_labels = []
        for file in self.CLASSES:
            for img_path in os.listdir(os.path.join(self.data_prefix, file, "a")):
                # imgs.append(os.path.join(file, "a", img_path))
                imgs.append(cv2.imread(os.path.join(self.data_prefix, file, "a", img_path)))
                gt_labels.append(file)

        data_infos = []
        for img, gt_label in zip(imgs, gt_labels):
            info = {'img_prefix': self.data_prefix}
            # info['img_info'] = {'filename': filename}
            info['img'] = img
            info['gt_label'] = np.array(self.label_dic[gt_label], dtype=np.int64)
            data_infos.append(info)
        return data_infos
```

**Comment by mzr1996** [comment]
>     def get_classes(self, classes=None):
>         return self.val_dic.values()

Here, `dict.values()` returns `dict_values` type, and Python cannot pickle it. Please try to use
```python
    def get_classes(self, classes=None):
        return list(self.val_dic.values())
```

**Comment by CodingWZP** [comment]
终于好了！ 谢谢！
