### ISSUE TITLE
Filter unexpected results in nms_rotated

### ISSUE THREAD

**Issue by JunLeecus** [open-mmlab/mmcv#1133]
**Describe the Issue**
For oriented object detection, I modified 'dict{nms}' in test_cfg as 'dict{nms_rotated}'. But some true positive results which has none overlaps with other boxes are supressed. I first find this by visulizing, then I remove nms_rotated op (do not execute nms op and direct draw the results), all the mis-suppressed boxes appear. I guess there must be some bugs in nms_rotated op, but I can't find why on the C++ codes. Thanks a lot.

**Reproduction**

1. For reproduction, because mmdet have no oriented detection models, it's hard to check by running a project model in mmdet. But feed some Synthetic DATA maybe available.

**Environment**

1. mmcv version==1.3.2
2. mmdetection version==2.13

**Comment by hhaAndroid** [comment]
Hi @JunLeecus mmdetection does not support rotate object detection at the moment. Is it the code you modified yourself?

**Comment by hhaAndroid** [comment]
Hi @JunLeecus mmdetection does not support rotate object detection at the moment. Is it the code you modified yourself?

**Comment by JunLeecus** [comment]
Yes. In mmcv.ops.nms.py,I find the ext_op 'nms_rotated', and I just call it and modified the 'batch_nms' in mmdetection to a rotated version. 
The fotmat of tensor are followed the annos in function 'nms_rotated':
"Rotated boxes in shape (N, 5). They are expected to be in (x_ctr, y_ctr, width, height, angle_radian) format."

other kargs are follows 'batch_nms'.

**Comment by hhaAndroid** [comment]
@JunLeecus Is there any progress？

**Comment by zhouzaida** [comment]
Closed for no response
