### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python objec

### ISSUE THREAD

**Issue by yanxp** [open-mmlab/mmcv#1135]
File "/xx/mmcv/parallel/collate.py", line 77, in <listcomp>
    return [collate(samples, samples_per_gpu) for samples in transposed]
  File "/xx/mmcv/parallel/collate.py", line 23, in collate
    if not isinstance(batch, Sequence):
  File "/data1/anaconda3/envs/py37/lib/python3.7/abc.py", line 139, in __instancecheck__
    return _abc_instancecheck(cls, instance)
  File "/data1/anaconda3/envs/py37/lib/python3.7/abc.py", line 143, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
RecursionError: maximum recursion depth exceeded while calling a Python object

#####
Can't find why report the bug?

**Comment by hitxiaoting** [comment]
> File "/xx/mmcv/parallel/collate.py", line 77, in
> return [collate(samples, samples_per_gpu) for samples in transposed]
> File "/xx/mmcv/parallel/collate.py", line 23, in collate
> if not isinstance(batch, Sequence):
> File "/data1/anaconda3/envs/py37/lib/python3.7/abc.py", line 139, in **instancecheck**
> return _abc_instancecheck(cls, instance)
> File "/data1/anaconda3/envs/py37/lib/python3.7/abc.py", line 143, in **subclasscheck**
> return _abc_subclasscheck(cls, subclass)
> RecursionError: maximum recursion depth exceeded while calling a Python object
> 
> Can't find why report the bug?

Hi, I also meet the same problem, how do you solved it?

**Comment by yanxp** [comment]
@hitxiaoting You may add other keys in the sample, check the base_dataset.py.

**Comment by shaotiancai** [comment]
It may be caused by inconsistencies in the dimensions of the input

**Comment by shaotiancai** [comment]
It may be caused by inconsistencies in the dimensions of the input. Printing out the dimensions of the input might explain why
