### ISSUE TITLE
SyncBatchNorm breaks after PyTorch 1.9.0

### ISSUE THREAD

**Issue by gaotongxiao** [open-mmlab/mmcv#1137]
**Describe the Issue**
`torch.nn.SyncBatchNorm` has been updated since PyTorch 1.9.0 and `_specify_ddp_gpu_num()` is no longer available, breaking the following code snippet: https://github.com/open-mmlab/mmcv/blob/eb08835fa246ea81263eb25fbe2caa54ef11271c/mmcv/utils/parrots_wrapper.py#L83-L87

More details: https://github.com/open-mmlab/mmocr/issues/325

**Comment by zhouzaida** [comment]
The issue will be resloved by PR #1138
