### ISSUE TITLE
mmcv 安装环境问题

### ISSUE THREAD

**Issue by hahnjiang** [open-mmlab/mmcv#1142]
当我安装 mmcv 的时候，我发现使用 ```MMCV_WITH_OPS=1 pip install -e .``` 指令在有无 GPU 的情况下，会出现不同结果。
如果有 GPU 则正常；
如果安装时没有 GPU，则镜像放到 GPU 服务器上运行时会出现异常，如下。
```
RuntimeError: nms is not compiled with GPU support
```

这个是我安装的问题，还是 mmcv 就是需要在有 GPU 的环境下安装呢？

谢谢

**Comment by zhouzaida** [comment]
编译的时候只要有编译需要的库就行，但运行的时候肯定是需要GPU的

**Comment by hahnjiang** [comment]
在 build docker 的时候，之前的层已经有 cuda 等库了。是不是环境变量的问题呢，除了 ```MMCV_WITH_OPS=1```，安装的时候还需要什么环境变量呢？

**Comment by zhouzaida** [comment]
安装过程有显示报错信息么

**Comment by hahnjiang** [comment]
安装的时候，没有报错。
我做了多次试验，比如在 Dockerfile 里面使用下面指令安装
```
RUN pip install mmcv_full==1.3.7
```
这样安装之后，还是有 ```RuntimeError: nms is not compiled with GPU support```

然后在 Jupyter 里面，使用相同指令运行重装 mmcv_full，就没有问题。

**Comment by zhouzaida** [comment]
> mmcv_full==1.3.7

这样装是不行的，如果想支持cuda运算，需要这样装 pip install mmcv-full=1.3.7 -f https://download.openmmlab.com/mmcv/dist/{cu_version}/{torch_version}/index.html

**Comment by lingcong-k** [comment]
@hahnjiang did u solve the issue? am having the same issue now

**Comment by hahnjiang** [comment]
我最新的测试用这个可以。不过还没有找到为什么之前不行的原因。
```
pip install mmcv-full=1.3.7 -f https://download.openmmlab.com/mmcv/dist/{cu_version}/{torch_version}/index.html
```

**Comment by zhouzaida** [comment]
> did u solve the issue? am having the same issue now

you can try `pip install mmcv-full=1.3.7 -f https://download.openmmlab.com/mmcv/dist/{cu_version}/{torch_version}/index.html`

**Comment by lingcong-k** [comment]
> > did u solve the issue? am having the same issue now
> 
> you can try `pip install mmcv-full=1.3.7 -f https://download.openmmlab.com/mmcv/dist/{cu_version}/{torch_version}/index.html`

i tried it. it works on my machine with torch 1.7.1, cuda 11.1. but am building it inside the docker.. then it always gives me "nms is not compiled with GPU support".. the base docker image am using is 1.8.0 cuda 11.1 which should work with 1.3.8..

I dont know why.. i also tried build from source (git clone....), both failed ;/

**Comment by lingcong-k** [comment]
> > > did u solve the issue? am having the same issue now
> > 
> > 
> > you can try `pip install mmcv-full=1.3.7 -f https://download.openmmlab.com/mmcv/dist/{cu_version}/{torch_version}/index.html`
> 
> @zhouzaida
> i tried it. it works on my machine with torch 1.7.1, cuda 11.1. but am building it inside the docker.. then it always gives me "nms is not compiled with GPU support".. the base docker image am using is 1.8.0 cuda 11.1 which should work with 1.3.8..
> 
> I dont know why.. i also tried build from source (git clone....), both failed ;/

HI, i find when i install in Docker with the command u reccomend:
pip install mmcv-full=1.3.7 -f https://download.openmmlab.com/mmcv/dist/{cu_version}/{torch_version}/index.html

it always has the following error.. 
ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory

It didnt throw any error when installing it tho.. 
I am using this nvidia base image: FROM nvcr.io/nvidia/pytorch:21.02-py3
so do you think i need to install cuda separately and set cuda env specifically inside the Dockerfile before intalling it?
Any idea will be highly appreciated! Stuck for a while

**Comment by zhouzaida** [comment]
> > > > did u solve the issue? am having the same issue now
> > > 
> > > 
> > > you can try `pip install mmcv-full=1.3.7 -f https://download.openmmlab.com/mmcv/dist/{cu_version}/{torch_version}/index.html`
> > 
> > 
> > @zhouzaida
> > i tried it. it works on my machine with torch 1.7.1, cuda 11.1. but am building it inside the docker.. then it always gives me "nms is not compiled with GPU support".. the base docker image am using is 1.8.0 cuda 11.1 which should work with 1.3.8..
> > I dont know why.. i also tried build from source (git clone....), both failed ;/
> 
> @zhouzaida
> HI, i find when i install in Docker with the command u reccomend:
> pip install mmcv-full=1.3.7 -f [https://download.openmmlab.com/mmcv/dist/{cu_version}/{torch_version}/index.html](https://download.openmmlab.com/mmcv/dist/%7Bcu_version%7D/%7Btorch_version%7D/index.html)
> 
> it always has the following error..
> ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
> 
> It didnt throw any error when installing it tho..
> I am using this nvidia base image: FROM nvcr.io/nvidia/pytorch:21.02-py3
> so do you think i need to install cuda separately and set cuda env specifically inside the Dockerfile before intalling it?
> Any idea will be highly appreciated! Stuck for a while

I meet the same error when I install mmcv-full in the container pulled from nvcr.io/nvidia/pytorch:21.02-py3. I try to find out why the error occurred.

**Comment by lingcong-k** [comment]
> > > > > did u solve the issue? am having the same issue now
> > > > 
> > > > 
> > > > you can try `pip install mmcv-full=1.3.7 -f https://download.openmmlab.com/mmcv/dist/{cu_version}/{torch_version}/index.html`
> > > 
> > > 
> > > @zhouzaida
> > > i tried it. it works on my machine with torch 1.7.1, cuda 11.1. but am building it inside the docker.. then it always gives me "nms is not compiled with GPU support".. the base docker image am using is 1.8.0 cuda 11.1 which should work with 1.3.8..
> > > I dont know why.. i also tried build from source (git clone....), both failed ;/
> > 
> > 
> > @zhouzaida
> > HI, i find when i install in Docker with the command u reccomend:
> > pip install mmcv-full=1.3.7 -f [https://download.openmmlab.com/mmcv/dist/{cu_version}/{torch_version}/index.html](https://download.openmmlab.com/mmcv/dist/%7Bcu_version%7D/%7Btorch_version%7D/index.html)
> > it always has the following error..
> > ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
> > It didnt throw any error when installing it tho..
> > I am using this nvidia base image: FROM nvcr.io/nvidia/pytorch:21.02-py3
> > so do you think i need to install cuda separately and set cuda env specifically inside the Dockerfile before intalling it?
> > Any idea will be highly appreciated! Stuck for a while
> 
> I meet the same error when I install mmcv-full in the container pulled from nvcr.io/nvidia/pytorch:21.02-py3. I try to find out why the error occurred.

@zhouzaida 

thats great that u can reproduce it.. 
Today I tried with the new version 1.3.9 with cuda 11.2 on: FROM nvcr.io/nvidia/pytorch:21.02-py3

The built seems go so well, it took around 10mins to fully build mmcv-full and it says successfully installed.
But then this nms is not compiled with GPU support  happen again..
Am so confused and run out of ideas now.  could u also reproduce this error ? thanks

![image](https://user-images.githubusercontent.com/73646719/125170138-acd27e80-e1ad-11eb-91f2-55ee8d9d75ee.png)

**Comment by zhouzaida** [comment]
hi @lingcong-k , I close the issue and have a discussion in your issue #1154
