### ISSUE TITLE
will you release pre-built mmcv packages with env(win10+cuda11.1+pytorch1.8)

### ISSUE THREAD

**Issue by wuwusky** [open-mmlab/mmcv#1149]
help~( ╯□╰ )

**Comment by zhouzaida** [comment]
You can refer to the https://mmcv.readthedocs.io/en/latest/build.html#build-on-windows to build from source. And the pre-build for windows is in our plan.

**Comment by wuwusky** [comment]
thx

**Comment by fcakyon** [comment]
> You can refer to the https://mmcv.readthedocs.io/en/latest/build.html#build-on-windows to build from source. And the pre-build for windows is in our plan.

that link is not working, can you give the correct one?

**Comment by zhouzaida** [comment]
https://mmcv.readthedocs.io/en/latest/get_started/build.html#build-on-windows
