### ISSUE TITLE
imrescale error when the input image shape is arbitrary 

### ISSUE THREAD

**Issue by OblivionStaff** [open-mmlab/mmcv#116]
When resize images keeping aspect ratio, it seems that the imrescale calculate a wrong scale factor in some case, for example: (600, 1200) ->(1024, 608)
```python
max_long_edge = max(scale)
max_short_edge = min(scale)
scale_factor = min(max_long_edge / max(h, w), max_short_edge / min(h, w))
```
Assume the input scale is (width, height), the scale factor should be
```python
scale_factor = min(float(scale[1]) / h, float(scale[0]) / w)
```

**Comment by hellock** [comment]
The documentation does not explain the behavior very clearly. The argument `scale` of `imrescale` means the maximum scale, i.e., the long edge and short edge, not width and height.
