### ISSUE TITLE
Config.fromfile sames can not work when use grammar like {{ _base_.item1 }}

### ISSUE THREAD

**Issue by BuxianChen** [open-mmlab/mmcv#1171]
I read the docs: [https://mmcv.readthedocs.io/en/latest/utils.html#reference-variables-from-base](https://mmcv.readthedocs.io/en/latest/utils.html#reference-variables-from-base) and try the example in the document, but got an error:

AttributeError: 'list' object has no attribute 'item1'

**Comment by zhouzaida** [comment]
please show your config

**Comment by BuxianChen** [comment]
exactly same as the document
```python
# base.py
item1 = 'a'
item2 = dict(item3 = 'b')
```
```python
# config_g.py
_base_ = ['./base.py']
item = dict(a = {{ _base_.item1 }}, b = {{ _base_.item2.item3 }})
```
and use this to generate Config
```
import mmcv
mmcv.utils.Config.fromfile('./config_g.py')
```
but got error:
AttributeError: 'list' object has no attribute 'item1'

**Comment by zhouzaida** [comment]
The feature is supported in mmcv-full v1.3.8 and I guess your version is lower than 1.3.8

**Comment by BuxianChen** [comment]
Got it, thanks.
