### ISSUE TITLE
How to build tensorrt plugins with TensorRT8.0

### ISSUE THREAD

**Issue by lawpdas** [open-mmlab/mmcv#1180]
Hi, thanks for your excellent work.
Now I want to convert my model to a tensorRT engine. Because there is a roi align layer in my model, I need to use the plugin.
I can build these plugins successfully with tensorRT7.2.3.4.
However, with tensorRT8.0.1.6, there are always some compiling errors like this: 
```shell
...
In file included from /data2/Documents/Experiments/BaseT/externals/mmcv_trt_plugin/mmcv/ops/csrc/tensorrt/plugins/trt_roi_align.cpp:1:0:
/data2/Documents/Experiments/BaseT/externals/mmcv_trt_plugin/mmcv/ops/csrc/tensorrt/trt_roi_align.hpp:90:42: error: looser throw specifier for ‘virtual const nvinfer1::PluginFieldCollection* RoIAlignPluginDynamicCreator::getFieldNames()’
   const nvinfer1::PluginFieldCollection *getFieldNames() override;
                                          ^~~~~~~~~~~~~
In file included from /home/space/Public/TensorRT-8.0.1.6/include/NvInferLegacyDims.h:53:0,
                 from /home/space/Public/TensorRT-8.0.1.6/include/NvInfer.h:53,
                 from /home/space/Public/TensorRT-8.0.1.6/include/NvInferPlugin.h:53,
                 from /data2/Documents/Experiments/BaseT/externals/mmcv_trt_plugin/mmcv/ops/csrc/tensorrt/trt_plugin_helper.hpp:5,
                 from /data2/Documents/Experiments/BaseT/externals/mmcv_trt_plugin/mmcv/ops/csrc/tensorrt/trt_roi_align.hpp:9,
                 from /data2/Documents/Experiments/BaseT/externals/mmcv_trt_plugin/mmcv/ops/csrc/tensorrt/plugins/trt_roi_align.cpp:1:
/home/space/Public/TensorRT-8.0.1.6/include/NvInferRuntimeCommon.h:954:42: error:   overriding ‘virtual const nvinfer1::PluginFieldCollection* nvinfer1::IPluginCreator::getFieldNames() noexcept’
     virtual PluginFieldCollection const* getFieldNames() noexcept = 0;
                                          ^~~~~~~~~~~~~
...
```
Because tensorRT7 doesn't support some nodes of my model, I have to use the newer version.
Could you help me?

**Comment by grimoire** [comment]
Hi, we do not support TensorRT7 for now and we are working on adding support to TensorRT8.
[here](https://github.com/NVIDIA/TensorRT/blob/master/plugin/geluPlugin/geluPlugin.h) is an example of TensorRT official plugin with TensorRT8 support(I guess). You can try to find the difference with our plugin and do some modify(for example, add `noexcept` at the end of the function definition).

**Comment by lawpdas** [comment]
Many thanks!
I have built and tested it successfully by adding `noexcept` at the end of the function definition and removing protected members: 
https://github.com/open-mmlab/mmcv/blob/db580dda8d2bf4c0e3aee3639e053cef6c58b80f/mmcv/ops/csrc/tensorrt/trt_roi_align.hpp#L71-L80
