### ISSUE TITLE
PLEASE Assert/Describe valid video format for "video.io.VideoReader"

### ISSUE THREAD

**Issue by chenxinfeng4** [open-mmlab/mmcv#1203]
**Describe the bug**
Read video from mmcv.video.io , but get no data frame.

**Motivation**
Open cv backbond cannot support h264 video read somehow. And open-cv also does not raise an error when encountering h264 videos.

I hope the "video.io.VideoReader" has more support for video formats. Or just raise an error for unsupported videos.

**Comment by zhouzaida** [comment]
got it. Thanks for your feedback.
