### ISSUE TITLE
api problem

### ISSUE THREAD

**Issue by wangm-word** [open-mmlab/mmcv#1215]
Thanks for reporting the unexpected results and we appreciate it a lot.

![image](https://user-images.githubusercontent.com/72743278/126894841-61bff389-7c94-4198-969e-bfea3a44c8fe.png)
what about the config format ？could you give me a example? thank you very much!
@zhouzaida

**Comment by zhouzaida** [comment]
hi @wangm-word , have you made sure whether the LiteHRNet has been registered in models?

**Comment by wangm-word** [comment]
yes，i‘m sure

**Comment by zhouzaida** [comment]
This issue has been resolved by [mmpose](https://github.com/open-mmlab/mmpose/issues/811).

**Comment by wangm-word** [comment]
thank you
but,it doesn't work...
i have tried all
@zhouzaida

**Comment by zhouzaida** [comment]
hi @wangm-word , LiteHRNet was not implemented in v0.16.0. Please use the latest master which has supported LiteHRNet.
