### ISSUE TITLE
pip install mmcv-full failed

### ISSUE THREAD

**Issue by canghaiyunfan** [open-mmlab/mmcv#1222]
WARNING: Generating metadata for package mmcv-full produced metadata for project name mmcv. Fix your #egg=mmcv-full fragments.
WARNING: Discarding https://files.pythonhosted.org/packages/0c/35/e3c775d3fbe931d1b1d7b354e638dd7ec007120cdc52d1312421587d34ac/mmcv-full-1.3.10.tar.gz#sha256=f7586f1d38a7075e7a6dac5d245d9b0c981a4719c5c92115cf6aea1f0affebb0 (from https://pypi.org/simple/mmcv-full/). Requested mmcv from https://files.pythonhosted.org/packages/0c/35/e3c775d3fbe931d1b1d7b354e638dd7ec007120cdc52d1312421587d34ac/mmcv-full-1.3.10.tar.gz#sha256=f7586f1d38a7075e7a6dac5d245d9b0c981a4719c5c92115cf6aea1f0affebb0 has inconsistent name: filename has 'mmcv-full', but metadata has 'mmcv'

**Comment by zhouzaida** [comment]
hi @canghaiyunfan , please provide the error information

**Comment by canghaiyunfan** [comment]
There is no error.
This is the output information if pip install mmcv-full

`Collecting mmcv-full
  Downloading mmcv-full-1.3.10.tar.gz (352 kB)
     |████████████████████████████████| 352 kB 23 kB/s 
  WARNING: Generating metadata for package mmcv-full produced metadata for project name mmcv. Fix your #egg=mmcv-full fragments.
WARNING: Discarding https://files.pythonhosted.org/packages/0c/35/e3c775d3fbe931d1b1d7b354e638dd7ec007120cdc52d1312421587d34ac/mmcv-full-1.3.10.tar.gz#sha256=f7586f1d38a7075e7a6dac5d245d9b0c981a4719c5c92115cf6aea1f0affebb0 (from https://pypi.org/simple/mmcv-full/). Requested mmcv from https://files.pythonhosted.org/packages/0c/35/e3c775d3fbe931d1b1d7b354e638dd7ec007120cdc52d1312421587d34ac/mmcv-full-1.3.10.tar.gz#sha256=f7586f1d38a7075e7a6dac5d245d9b0c981a4719c5c92115cf6aea1f0affebb0 has inconsistent name: filename has 'mmcv-full', but metadata has 'mmcv'
  Downloading mmcv-full-1.3.9.tar.gz (313 kB)
     |████▏                           | 40 kB 17 kB/s eta 0:00:16^C`

**Comment by zhouzaida** [comment]
what is your version of python? 3.6?

**Comment by canghaiyunfan** [comment]
python: 3.8.10
pytorch: 1.8.1
cuda: 11.1

**Comment by zhouzaida** [comment]
pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.8.0/index.html

**Comment by zhouzaida** [comment]
> has 'mmcv-full', but metadata has 'mmcv'

It is a mistake when publishing `mmcv-full`

**Comment by zhouzaida** [comment]
> please try the command
> 
> ```
> pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.8.0/index.html
> ```

Did it resolve the issue?

**Comment by jiarenyf** [comment]
> > please try the command
> > ```
> > pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.8.0/index.html
> > ```
> 
> Did it resolve the issue?

No ...

**Comment by zhouzaida** [comment]
hi @jiarenyf , we have released a new version of mmcv and you could try it again.
