### ISSUE TITLE
ModuleNotFoundError: No module named 'mmcv'. ( With mmcv-full installed and mmcv uninstalled)

### ISSUE THREAD

**Issue by Leo0408** [open-mmlab/mmcv#1226]
The problem turns out to be"ModuleNotFoundError: No module named 'mmcv' .
Most of the solutions online told me that is because the mmcv-full version is needed. However i do uninstall the mmcv version with 'pip install mmcv' and intall the mmcv-full in many different ways ( from url or by pip or download it first) but all ends in the same error '"ModuleNotFoundError: No module named 'mmcv' '.

**Comment by zhouzaida** [comment]
hi @Leo0408 please follow those steps
```python
pip uninstall mmcv
pip uninstall mmcv-full
pip install mmcv-full
```
more datails at https://github.com/open-mmlab/mmcv#installation

**Comment by Leo0408** [comment]
@zhouzaida I am very appreciate it that you response it so quickly. 
I have uninstall mmcv and install mmcv-full successfully now. There is only mmcv-full when i type 'pip install'.
But now another error occurs: 'import mmcv:ModuleNotFoundError: No module named 'mmcv'"?

**Comment by zhouzaida** [comment]
Could you provide the full log?

**Comment by Leo0408** [comment]
@zhouzaida  Thank you very much!
i wonder if that's because i did it on a public server? Or it 's because of the envrionment path or something?

(open-mmlab) qian@qian:~$ pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu100/torch1.3.0/index.html
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/, https://pypi.tuna.tsinghua.edu.cn/simple/
Looking in links: https://download.openmmlab.com/mmcv/dist/cu100/torch1.3.0/index.html
Collecting mmcv-full
  Using cached https://download.openmmlab.com/mmcv/dist/cu100/torch1.3.0/mmcv_full-1.3.10-cp37-cp37m-manylinux1_x86_64.whl (23.9 MB)
Requirement already satisfied: numpy in ./miniconda3/lib/python3.7/site-packages (from mmcv-full) (1.19.5)
Requirement already satisfied: opencv-python>=3 in ./miniconda3/lib/python3.7/site-packages (from mmcv-full) (4.1.2.30)
Requirement already satisfied: yapf in ./miniconda3/lib/python3.7/site-packages (from mmcv-full) (0.31.0)
Requirement already satisfied: pyyaml in ./miniconda3/lib/python3.7/site-packages (from mmcv-full) (5.2)
Requirement already satisfied: Pillow in ./miniconda3/lib/python3.7/site-packages (from mmcv-full) (8.2.0)
Requirement already satisfied: setuptools>=52 in ./miniconda3/lib/python3.7/site-packages (from mmcv-full) (57.4.0)
Requirement already satisfied: addict in ./miniconda3/lib/python3.7/site-packages (from mmcv-full) (2.2.1)
Installing collected packages: mmcv-full
Successfully installed mmcv-full-1.3.10
(open-mmlab) qian@qian:~$ cd jiang
(open-mmlab) qian@qian:~/jiang$ cd mmdetection
(open-mmlab) qian@qian:~/jiang/mmdetection$ python setup.py develop
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
running develop
running egg_info
writing mmdet.egg-info/PKG-INFO
writing dependency_links to mmdet.egg-info/dependency_links.txt
writing requirements to mmdet.egg-info/requires.txt
writing top-level names to mmdet.egg-info/top_level.txt
reading manifest file 'mmdet.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'mmdet/VERSION'
warning: no files found matching 'mmdet/.mim/demo/*/*'
adding license file 'LICENSE'
writing manifest file 'mmdet.egg-info/SOURCES.txt'
running build_ext
Creating /home/qian/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet.egg-link (link to .)
mmdet 2.14.0 is already the active version in easy-install.pth

Installed /home/qian/jiang/mmdetection
Processing dependencies for mmdet==2.14.0
Searching for pycocotools==2.0.2
Best match: pycocotools 2.0.2
Processing pycocotools-2.0.2-py3.7-linux-x86_64.egg
pycocotools 2.0.2 is already the active version in easy-install.pth

Using /home/qian/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/pycocotools-2.0.2-py3.7-linux-x86_64.egg
Searching for terminaltables==3.1.0
Best match: terminaltables 3.1.0
Processing terminaltables-3.1.0-py3.7.egg
terminaltables 3.1.0 is already the active version in easy-install.pth

Using /home/qian/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/terminaltables-3.1.0-py3.7.egg
Searching for six==1.16.0
Best match: six 1.16.0
Adding six 1.16.0 to easy-install.pth file

Using /home/qian/miniconda3/envs/open-mmlab/lib/python3.7/site-packages
Searching for numpy==1.19.2
Best match: numpy 1.19.2
Adding numpy 1.19.2 to easy-install.pth file
Installing f2py script to /home/qian/miniconda3/envs/open-mmlab/bin
Installing f2py3 script to /home/qian/miniconda3/envs/open-mmlab/bin
Installing f2py3.7 script to /home/qian/miniconda3/envs/open-mmlab/bin

Using /home/qian/miniconda3/envs/open-mmlab/lib/python3.7/site-packages
Searching for matplotlib==3.4.2
Best match: matplotlib 3.4.2
Processing matplotlib-3.4.2-py3.7-linux-x86_64.egg
matplotlib 3.4.2 is already the active version in easy-install.pth

Using /home/qian/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/matplotlib-3.4.2-py3.7-linux-x86_64.egg
Searching for Cython==0.29.24
Best match: Cython 0.29.24
Processing Cython-0.29.24-py3.7-linux-x86_64.egg
Cython 0.29.24 is already the active version in easy-install.pth
Installing cygdb script to /home/qian/miniconda3/envs/open-mmlab/bin
Installing cython script to /home/qian/miniconda3/envs/open-mmlab/bin
Installing cythonize script to /home/qian/miniconda3/envs/open-mmlab/bin

Using /home/qian/jiang/mmdetection/.eggs/Cython-0.29.24-py3.7-linux-x86_64.egg
Searching for setuptools==57.4.0
Best match: setuptools 57.4.0
Adding setuptools 57.4.0 to easy-install.pth file

Using /home/qian/miniconda3/envs/open-mmlab/lib/python3.7/site-packages
Searching for python-dateutil==2.8.2
Best match: python-dateutil 2.8.2
Processing python_dateutil-2.8.2-py3.7.egg
python-dateutil 2.8.2 is already the active version in easy-install.pth

Using /home/qian/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/python_dateutil-2.8.2-py3.7.egg
Searching for pyparsing==3.0.0b2
Best match: pyparsing 3.0.0b2
Processing pyparsing-3.0.0b2-py3.7.egg
pyparsing 3.0.0b2 is already the active version in easy-install.pth

Using /home/qian/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/pyparsing-3.0.0b2-py3.7.egg
Searching for Pillow==8.3.1
Best match: Pillow 8.3.1
Adding Pillow 8.3.1 to easy-install.pth file

Using /home/qian/miniconda3/envs/open-mmlab/lib/python3.7/site-packages
Searching for kiwisolver==1.3.1
Best match: kiwisolver 1.3.1
Processing kiwisolver-1.3.1-py3.7-linux-x86_64.egg
kiwisolver 1.3.1 is already the active version in easy-install.pth

Using /home/qian/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/kiwisolver-1.3.1-py3.7-linux-x86_64.egg
Searching for cycler==0.10.0
Best match: cycler 0.10.0
Processing cycler-0.10.0-py3.7.egg
cycler 0.10.0 is already the active version in easy-install.pth

Using /home/qian/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/cycler-0.10.0-py3.7.egg
Finished processing dependencies for mmdet==2.14.0
(open-mmlab) qian@qian:~/jiang/mmdetection$ python tools/test.py ${CONFIG_FILE} ${CHECKPOINT_FILE} [--out ${RESULT_FILE}] [--eval ${EVAL_METRICS}] [--show]
Traceback (most recent call last):
  File "tools/test.py", line 7, in <module>
    import mmcv
ModuleNotFoundError: No module named 'mmcv'

**Comment by zhouzaida** [comment]
Can you successfully import mmcv in your terminal?
`python -c 'import mmcv'`

**Comment by Leo0408** [comment]
@zhouzaida  No it has the same error
ModuleNotFoundError: No module named 'mmcv

**Comment by zhouzaida** [comment]
It is so weird

**Comment by zhouzaida** [comment]
Could you try to create a new conda environment and install mmcv-full again?

**Comment by Leo0408** [comment]
@zhouzaida Okay i will try again, thank you

**Comment by zhouzaida** [comment]
@Leo0408 , has the issue been resloved?

**Comment by Leo0408** [comment]
@zhouzaida yes ,thank you! It works successfully in windows
