### ISSUE TITLE
mmcls pre-trained vgg19

### ISSUE THREAD

**Issue by jin-s13** [open-mmlab/mmcv#1229]
It seems that the path to the vgg is wrong. 
 "vgg19": "https://download.openmmlab.com/mmclassification/v0/vgg/vgg19_bn_batch256_imagenet_20210208-da620c4f.pth",
It is identical to 
"vgg19_bn": "https://download.openmmlab.com/mmclassification/v0/vgg/vgg19_bn_batch256_imagenet_20210208-da620c4f.pth",

**Comment by zhouzaida** [comment]
yet, thanks for your feedback. We will update it.
