### ISSUE TITLE
[BUG] nms op with different result in gpu and cpu

### ISSUE THREAD

**Issue by raoshenglong** [open-mmlab/mmcv#1239]
Thanks for reporting the unexpected results and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmcv.readthedocs.io/en/latest/trouble_shooting.html) but cannot get the expected help.
3. The unexpected results still exist in the latest version.

**Describe the Issue**
When you use mmcv.ops.mmcv  API with the same input data in cpu and gpu respectively, you will get different results.

**Reproduction**

1. What command, code, or script did you run?

```bash
import torch
import mmcv
from mmcv.ops import *
box = torch.rand(10000,4)
score = torch.rand(10000)
mmcv.ops.nms(box, score, 0.0, 0)
mmcv.ops.nms(box.cuda(), score.cuda(), 0.0, 0)
```

2. Did you make any modifications on the code? Did you understand what you have modified?

**Environment**

1. Please run `python -c "from mmcv.utils import collect_env; print(collect_env())"` to collect necessary environment information and paste it here.

Any envirenment with mmcv is OK, I think, you just need to set the iou_threshold to 0.0.

2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error traceback here.

```none
A placeholder for traceback.
```

**Bug fix**
The implementation of cpu and cuda is different, you just need to modify the cpu implementation.

**Comment by grimoire** [comment]
Hi
nms behavior is different on invalid box with `x1<x0` or `y1<y0`. Which will almost never happen in real detector.
Try test it on valid boxes.

**Comment by raoshenglong** [comment]
> Hi
> nms behavior is different on invalid box with `x1<x0` or `y1<y0`. Which will almost never happen in real detector.
> Try test it on valid boxes.

Hello, thanks for your reply. I mean when you use the valid boxes and scores and set the `iou_threshold ` to be 0.0, the cpu implementation will only select one valid box, but the gpu implementation may select several valid boxes. Because the    the cpu implementation will filter out the boxes when the condition is `I / U >= iou_threshold`, but the gpu implementation will filter out boxes when the condition is `I  / U > iou_threshold`. In general, I think we should keep the judgement condition to be the same in cpu and gpu.

**Comment by grimoire** [comment]
`iou_threshold=0.0` is also a rare case.
And yes, we agree that we should share the same condition between different implementations. You are welcome to send a PR to fix it.

**Comment by raoshenglong** [comment]
> `iou_threshold=0.0` is also a rare case.
> And yes, we agree that it is a good idea to share the same condition between different implementations. You are welcome to send a PR to fix it.

OK, please help to check this PR https://github.com/open-mmlab/mmcv/pull/1244. Thanks.
