### ISSUE TITLE
Log for val results does not save correctly when `IterBasedRunner` is used.

### ISSUE THREAD

**Issue by haotian-liu** [open-mmlab/mmcv#1248]
When I am using `IterBasedRunner` is used, and the evaluation runs during the training (triggered by evaluation hook `evaluation=dict(interval=5000)`), the eval results are not logged with val mode, and are logged as train mode. This is different from `EpochBasedRunner`.

Specifically, for `EpochBasedRunner`, training losses will be logged in Tensorboard with prefix `train/` (e.g., train/loss, train/loss_cls, etc.), and evaluation results will be logged with prefix `val/` (e.g., val/table, val/acc, val/miou, etc.). However, in `IterBasedRunner`, they are all logged with prefix `train/` (e.g., train/loss, train/table, train/acc, train/miou), which is weird and causes troubles for visualization.

It seems that when evaluation hook is triggered in `after_iter` stage, the mode will not be changed to `eval` and remains as `train` instead, which might be the cause of the issue.

Please kindly advise if there is anything that I am not doing correctly, thank you so much!

**Comment by zhouzaida** [comment]
hi @haotian-liu , thanks for you feedback, we are fixing the bug

**Comment by haotian-liu** [comment]
Thank you so much!

**Comment by zhouzaida** [comment]
closed by #1252
