### ISSUE TITLE
你好，请问关于focal loss一些问题

### ISSUE THREAD

**Issue by luyiqwerrewq** [open-mmlab/mmcv#125]
我想请问一下您，focal loss有没有被封装过，我没有找到focal loss梯度下降求偏导数部分。
我能否进入相应的函数内部，修改其超参定义，而不是仅仅修改 type='FocalLoss', use_sigmoid=True, gamma=2.0,alpha=0.25这些超参，我更想修改其相关定义，请告诉我能否修改，是否已经被封装在里面了

**Comment by hellock** [comment]
Please use English or English&Chinese for issues.
BTW, this issue should be in the mmdetection repo instead of mmcv.
