### ISSUE TITLE
runner/utils.py bugfix

### ISSUE THREAD

**Issue by svl-ai** [open-mmlab/mmcv#126]
Could you please make calling dist.is_initialized() conditional on dist.is_available()? Not all platforms (e.g. Windows) support it.

    if torch.__version__ < '1.0':
        initialized = dist._initialized
    else:
	  if dist.is_available() :
		        initialized = dist.is_initialized()
	  else:
		        initialized = 0

Thanks.

**Comment by hellock** [comment]
Thanks for reporting the issue! It should be fixed in #128.
