### ISSUE TITLE
Convert binary label masks into COCO format

### ISSUE THREAD

**Issue by AKMourato** [open-mmlab/mmcv#1269]
Greetings.
Do you have any available functionality to transform labels in binary masks format into COCO format?

**Comment by zhouzaida** [comment]
hi @AKMourato , mmcv has no available function to achieve it. And can you provide the format of binary masks?

**Comment by AKMourato** [comment]
Thanks. In normal image format png/jpeg

**Comment by zhouzaida** [comment]
Maybe you can have a help in mmdetection
