### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by FANG-MING** [open-mmlab/mmcv#1292]
when carry：
env_info['MMCV Compiler'] = get_compiler_version()
env_info['MMCV CUDA Compiler'] = get_compiling_cuda_version()
arise Segmentation fault
version：mmcv-full        1.3.11

**Comment by zhouzaida** [comment]
hi @FANG-MING , Could you provide more information to reproduce the error? I guest it is not a bug of mmcv.
