### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

### ISSUE THREAD

**Issue by rogercmq** [open-mmlab/mmcv#1298]
This issue has been submitted in https://github.com/open-mmlab/mmaction2/issues/1109 and the authors recommend me to raise an issue here.

In a nutshell, I am re-imeplementing an feature visualization algorithm (GradCAM) on a **fastrnn** based video action detection backbone and now I have difficulties in backwarding roi. See https://github.com/open-mmlab/mmaction2/issues/1109 for details.

As for my human bbox proposals, they have been extracted already and the MMAction2 cls backbones take them as gradient-free inputs.

```
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1, 5]] is at version 4; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
```

I know that the inplaced tensor is my roi proposal, but I am not sure where the inplace op occurs. I would be appreciate it if you could help me out.

**Comment by zhouzaida** [comment]
It is a duplicate issue with mmaction2 and it has not been responded to for a long time in mmaction2, I will close the issue here.
