### ISSUE TITLE
About video sub-module

### ISSUE THREAD

**Issue by lindahua** [open-mmlab/mmcv#13]
Two options:

1. Move out ``video`` submodule and merge it into the repo ``mmvideo``.

or 

2. Have some basic functionalities related to videos in ``mmcv``, and have ``mmvideo`` focus on video analytics frameworks like TSN.

@hellock Please talk to Yuanjun and Yue to figure out.

**Comment by patrickpoirson** [comment]
Hi, thanks for the great libraries! Is mmvideo still in the works? Any idea when the release might be?
