### ISSUE TITLE
  Could not find a version that satisfies the requirement opencv-python (from mmcv==0.2.13) (from versions: 

### ISSUE THREAD

**Issue by job2003** [open-mmlab/mmcv#130]
bozhao@bozhao-desktop:~/workspace/mmcv$ pip3 install -e .
Obtaining file:///home/bozhao/workspace/mmcv
Collecting numpy>=1.11.1 (from mmcv==0.2.13)
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /simple/numpy/
  Using cached https://files.pythonhosted.org/packages/cb/79/96df883cd6df0c86cb010e6f4ff790b7a30a45016a9509c94ea72c8695cd/numpy-1.17.1.zip
Collecting pyyaml (from mmcv==0.2.13)
  Using cached https://files.pythonhosted.org/packages/e3/e8/b3212641ee2718d556df0f23f78de8303f068fe29cdaa7a91018849582fe/PyYAML-5.1.2.tar.gz
Collecting six (from mmcv==0.2.13)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting addict (from mmcv==0.2.13)
  Using cached https://files.pythonhosted.org/packages/14/6f/beb258220417c1a0fe11e842f2e012a1be7eeeaa72a1d10ba17a804da367/addict-2.2.1-py3-none-any.whl
Collecting requests (from mmcv==0.2.13)
  Using cached https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl
Collecting opencv-python (from mmcv==0.2.13)
  Could not find a version that satisfies the requirement opencv-python (from mmcv==0.2.13) (from versions: )
No matching distribution found for opencv-python (from mmcv==0.2.13)

what's the problem?
I have install opencv-python, and no problem when using  import cv2

**Comment by hellock** [comment]
Try the latest version. If the issue still exists, feel free to reopen it.
