### ISSUE TITLE
version

### ISSUE THREAD

**Issue by 5859wang** [open-mmlab/mmcv#1306]
mmcv==1.3.12
mmcv_full==1.3.3
i want the version==1.3.3,how deal with the problem

**Comment by zhouzaida** [comment]
pip install mmcv-full=={mmcv_version} -f https://download.openmmlab.com/mmcv/dist/{cu_version}/{torch_version}/index.html

**Comment by zhouzaida** [comment]
hi @5859wang , is there any progress?

**Comment by shinianzhihou** [comment]
If i can only install the mmcv **offline**, what should i do?

**Comment by zhouzaida** [comment]
suppose your cuda is 11.1 and torch is 1.9.0, you can download the wheel from https://download.openmmlab.com/mmcv/dist/cu111/torch1.9.0/index.html.

**Comment by shinianzhihou** [comment]
solved~~~
