### ISSUE TITLE
python setup.py build_ext  ERROR

### ISSUE THREAD

**Issue by hyunjung0208** [open-mmlab/mmcv#1311]
I'm going to build mmcv as a source in Windows 10.
https://mmcv.readthedocs.io/en/latest/get_started/build.html 
As per the document here, I followed the official version with cuda. 
By the way, python setup.py build_ext continues to error here.
error is  'RuntimeError: Error compiling objects for extension'
Can you tell me the cause of the error? May I know how to resolve this error or install mmcv in Windows 10? 
I would like to install mmcv for mmdetection. 
(We want to build mmcv as source due to continuous 'pip install mmcv-full ~~' failure)

Below is the whole error I got.
sorry, The output was too long for me to copy and paste the whole thing.

**Comment by apanand14** [comment]
I'm getting this error while I build mmcv from source using cuda 10.2, torch 1.8.0+cu102.on my windows.
./mmcv/ops/csrc/pytorch\info.cpp(8): fatal error C1083: "cuda_runtime_api.h": No such file or directory 
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
 
Please help me out to find the solution. Thank you in advance.

**Comment by zhouzaida** [comment]
> Below is the whole error I got.
> sorry, The output was too long for me to copy and paste the whole thing.

Maybe you need to provide more information. `RuntimeError: Error compiling objects for extension` is not enough

**Comment by zhouzaida** [comment]
> I'm getting this error while I build mmcv from source using cuda 10.2, torch 1.8.0+cu102.on my windows.
> ./mmcv/ops/csrc/pytorch\info.cpp(8): fatal error C1083: "cuda_runtime_api.h": No such file or directory
> error: command 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe' failed with exit status 2
> 
> Please help me out to find the solution. Thank you in advance.

please refer to https://mmcv.readthedocs.io/en/latest/get_started/build.html#option-3-build-mmcv-full-version-with-cuda to check your steps

**Comment by apanand14** [comment]
I have followed those steps as well.  I'm still figuring out what went wrong. If you get then please help me out. Thank you for your response.

**Comment by apanand14** [comment]
Currently, I installed mmcv-full and mmdet
Successfully installed addict-2.4.0 **mmcv-full-1.3.12** packaging-21.0 pyparsing-2.4.7 pyyaml-5.4.1 regex-2021.8.28 yapf-0.31.0
Successfully installed cycler-0.10.0 kiwisolver-1.3.2 matplotlib-3.4.3 **mmdet-2.16.0** pycocotools-windows-2.0.0.2 python-dateutil-2.8.2 six-1.16.0 terminaltables-3.1.0

After that when I try to run tools/train.py with config file then I got this below error:
 File "tools/train.py", line 16, in <module>
    from mmdet.apis import set_random_seed, train_detector
  File "C:\Developer\Git\Inspection\AI\RefineMask\venv\lib\site-packages\mmdet\apis\__init__.py", line 2, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "C:\Developer\Git\Inspection\AI\RefineMask\venv\lib\site-packages\mmdet\apis\inference.py", line 7, in <module>
    from mmcv.ops import RoIPool
  File "C:\Developer\Git\Inspection\AI\RefineMask\venv\lib\site-packages\mmcv\ops\__init__.py", line 2, in <module>
    from .bbox import bbox_overlaps
  File "C:\Developer\Git\Inspection\AI\RefineMask\venv\lib\site-packages\mmcv\ops\bbox.py", line 4, in <module>
    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
  File "C:\Developer\Git\Inspection\AI\RefineMask\venv\lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "C:\Users\topseven\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed: The specified procedure could not be found.

Can you tell me what is the reason behind this? It would be helpful. Thank you in advance.

**Comment by zhouzaida** [comment]
It seems like the ddl cannot be found. Maybe the `mmcv-full` is not installed correctly. You can check whether `_ext.cp37-win_amd64.pyd` is generated in `./mmcv`

**Comment by zhouzaida** [comment]
is there any progress?

**Comment by zhouzaida** [comment]
Closed for no response.
