### ISSUE TITLE
Pip install mmcv-full causes pc crash

### ISSUE THREAD

**Issue by christian-holland** [open-mmlab/mmcv#1312]
Pc crashes because it runs out of memory when trying to install: (16gb ram)
Memory usage increases until pc freezes.

Host system: Ubuntu 20.10
Running in: Docker with Ubuntu 18.04.3
Works with version 1.3.11: `pip install mmcv-full==1.3.11`
Does not work: `pip install mmcv-full`

**Comment by zhouzaida** [comment]
It is weird. You can try  `pip install mmcv-full==1.3.12`

**Comment by zhouzaida** [comment]
I closed this issue. Feel free to reopen it if it is not resolved.
