### ISSUE TITLE
NO ROCm runtime is found,using ROCM_HOME='/opt/rocm'. 

### ISSUE THREAD

**Issue by qq1628qq** [open-mmlab/mmcv#1314]
An error was reported during training: NO ROCm runtime is found,using ROCM_HOME='/opt/rocm'.
But the model can be trained and is converging.
The training speed is very slow, data_time is greater than 2.

**Comment by qq1628qq** [comment]
thanks you very much.
When I enter the command(from torch.utils.cpp_extension import ROCM_HOME), the computer outputs this"NO ROCm runtime is found,using ROCM_HOME='/opt/rocm'.".
But why my training time is so long and the speed is so slow? data_time>3or data_time>3. 
What's the problem? Is there any connection with rocm?

**Comment by zhouzaida** [comment]
Is there any progress? It seems like that your PyTorch was not correctly installd.
