### ISSUE TITLE
Too slow. 

### ISSUE THREAD

**Issue by qq1628qq** [open-mmlab/mmcv#1315]
Why does YOLOX need two days to train 6000 images? And data||_time>2. Too slow. 
vocdataset,4GPU,8batch_size.

**Comment by zhouzaida** [comment]
If your PyTorch version is greater than or equal to 1.7, you can set [persistent_workers=True](https://pytorch.org/docs/stable/data.html?highlight=dataloader#torch.utils.data.DataLoader). It will be helpful.
If you have any other questions, you can ask for help in [mmdet](https://github.com/open-mmlab/mmdetection/issues)
