### ISSUE TITLE
NO ROCm runtime is found,using ROCM_HOME='/opt/rocm'.".

### ISSUE THREAD

**Issue by qq1628qq** [open-mmlab/mmcv#1316]
thanks you very much.
When I enter the command(from torch.utils.cpp_extension import ROCM_HOME), the computer outputs this"NO ROCm runtime is found,using ROCM_HOME='/opt/rocm'.".
But why my training time is so long and the speed is so slow? data_time>3or data_time>3.
What's the problem? Is there any connection with rocm?

**Comment by zhouzaida** [comment]
It seems like that your PyTorch was not correctly installd.

**Comment by zhouzaida** [comment]
repeate with #1314
