### ISSUE TITLE
TypeError: init_weights() missing 1 required positional argument: 'pretrained'

### ISSUE THREAD

**Issue by apanand14** [open-mmlab/mmcv#1317]
File "tools/train.py", line 189, in <module>
    main()
  File "tools/train.py", line 163, in main
    model.init_weights()
  File "C:\Users\topseven\anaconda3\envs\mmcv\lib\site-packages\mmcv\runner\base_module.py", line 117, in init_weights
    m.init_weights()
**TypeError: init_weights() missing 1 required positional argument: 'pretrained'**

**Comment by zhouzaida** [comment]
Did you override the `init_weights()` method in your module?

**Comment by apanand14** [comment]
I think so but not sure. I think there is another model.init_weights() in train.py But When I comment it out then I'm able to train the model. I do not know is it right way or Am I missing something?

**Comment by zhouzaida** [comment]
What codebase are you using?

**Comment by apanand14** [comment]
mmdetection repository and training file from tools/train.py

**Comment by zhouzaida** [comment]
please provide your mmdet version and what config you are using?

**Comment by apanand14** [comment]
mmcv-full : 1.3.12
mmdet: 2.16.0

When I run with default mask_rcnn and config: mask_rcnn_r50_caffe_fpn_mstrain-poly_1x_coco.py, it runs fine.
Thank you for replying back

**Comment by zhouzaida** [comment]
so why the error happened? Did you modify the mask_rcnn model?

**Comment by apanand14** [comment]
No. Basically I'm using this custom implementation.
https://github.com/zhanggang001/RefineMask
If I run this then I probably got an error.

**Comment by zhouzaida** [comment]
please @hhaAndroid  have a look

**Comment by hhaAndroid** [comment]
@apanand14 Please refer to https://github.com/open-mmlab/mmdetection/blob/master/docs/changelog.md#backwards-incompatible-changes. In v2.12.0 MMDetection, we have adopted `init_cfg` uniformly, you need to refer to https://github.com/open-mmlab/mmdetection/pull/4750 for custom code.  If you still can’t solve it, we will further help you solve it.

**Comment by apanand14** [comment]
Hello @hhaAndroid , I tried to solve this issue for custom code. But I'm getting same error no matter what I chnage. Is it possible that you look into and help me to solve it please?  Here is the custom implementation I use on mmcv-full 1.3.12 and mmdet 2.16.0 . As you mentioned backward incompatibale changes causes above mentioned error. Can you help me to run this custom implementation on mmcv-full and mmdet (latest versions)? 

https://github.com/zhanggang001/RefineMask
In this custom implementation there are two custom implementation are done. 
1. refinemask/mmdet/models/roi_heads/refine_roi_head.py and 
2. refinemask/mmdet/models/roi_heads/mask_heads/refine_mask_head.py

As I told you before, I use init_cfg in cfg file. Also, I do not get any error while I train with default Mask Rcnn. (Training and inference works well). In custom implementation, training works if I make a comment of model.init_weights() but it throws an error (mentioned in title) with it. Please help me out. Thank you in advance!!

**Comment by hhaAndroid** [comment]
If you do not want to modify the current code, I suggest that your mmdet version should not be higher than v2.12.0, because there is BC-Breaking.

**Comment by apanand14** [comment]
Thank you for the reply. I will try to downgrade mmdet version and check it out.

**Comment by zhouzaida** [comment]
hi @apanand14 , is there any progress?

**Comment by apanand14** [comment]
Hello @zhouzaida , I'm able to run the customized mmdetection by installing the lower versions. Thank you for your help. I will let you know once I change the code on the latest versions of the mmdetection and then it works or not.

**Comment by zhouzaida** [comment]
> Hello @zhouzaida , I'm able to run the customized mmdetection by installing the lower versions. Thank you for your help. I will let you know once I change the code on the latest versions of the mmdetection and then it works or not.

hi @apanand14 , is there any progress?

**Comment by apanand14** [comment]
No, I'm focused on the training and optimizing stuffs with lower versions only. I will let you know in maximum weeks.
