### ISSUE TITLE
mmcv._ext FOR windows10

### ISSUE THREAD

**Issue by hyunjung0208** [open-mmlab/mmcv#1325]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the FAQ documentation but cannot get the expected help.

I am going to test the mmdetention in Windows 10 (a model trained in Linux).
With difficulty, I succeeded in testing demo images on Windows 10, and I also succeeded in testing with my model.
And I keep trying to work on the pinstaller and I'm failing.
But this time,
There was a problem with 'mmcv._ext' that came out as an error during the mmdetection demo test.
If the demo test was successful, then "mmcv._ext" is on my computer, right?
May I know where mmcv._ext is?
Or is there a way to test whether mmcv._ext exists correctly in the window?
Or is there a way to install mmcv._ext on the window?

**Comment by zhouzaida** [comment]
hi @hyunjung0208 , you can simply test it via `import mmcv.ops`

**Comment by zhouzaida** [comment]
Closed for no responce. Feel free to reopen it if the issue was not resloved.
