### ISSUE TITLE
pytorch1.81 build failed

### ISSUE THREAD

**Issue by zgsxwsdxg** [open-mmlab/mmcv#1326]
(mmcv) [duxiaogang@e29f81cded21 mmcv]$ MMCV_WITH_OPS=1 pip install -e .
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Obtaining file:///home/duxiaogang/mmcv
Collecting addict
  Using cached https://mirrors.aliyun.com/pypi/packages/6a/00/b08f23b7d7e1e14ce01419a467b583edbb93c6cdb8654e54a9cc579cd61f/addict-2.4.0-py3-none-any.whl (3.8 kB)
Requirement already satisfied: numpy in /home/duxiaogang/anaconda3/envs/mmcv/lib/python3.6/site-packages (from mmcv-full==1.3.12) (1.19.5)
Collecting packaging
  Using cached https://mirrors.aliyun.com/pypi/packages/3c/77/e2362b676dc5008d81be423070dd9577fa03be5da2ba1105811900fda546/packaging-21.0-py3-none-any.whl (40 kB)
Requirement already satisfied: Pillow in /home/duxiaogang/anaconda3/envs/mmcv/lib/python3.6/site-packages (from mmcv-full==1.3.12) (8.3.1)
Collecting pyyaml
  Using cached https://mirrors.aliyun.com/pypi/packages/7a/5b/bc0b5ab38247bba158504a410112b6c03f153c652734ece1849749e5f518/PyYAML-5.4.1-cp36-cp36m-manylinux1_x86_64.whl (640 kB)
Collecting yapf
  Using cached https://mirrors.aliyun.com/pypi/packages/5f/0d/8814e79eb865eab42d95023b58b650d01dec6f8ea87fc9260978b1bf2167/yapf-0.31.0-py2.py3-none-any.whl (185 kB)
Collecting opencv-python>=3
  Using cached https://mirrors.aliyun.com/pypi/packages/7f/45/32b09b11c76c354beb94c6549d844241709366fac02f253aa7f7b9ec9861/opencv_python-4.5.3.56-cp36-cp36m-manylinux2014_x86_64.whl (49.9 MB)
Collecting pyparsing>=2.0.2
  Using cached https://mirrors.aliyun.com/pypi/packages/8a/bb/488841f56197b13700afd5658fc279a2025a39e22449b7cf29864669b15d/pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Installing collected packages: pyparsing, yapf, pyyaml, packaging, opencv-python, addict, mmcv-full
  Running setup.py develop for mmcv-full
    ERROR: Command errored out with exit status 1:
     command: /home/duxiaogang/anaconda3/envs/mmcv/bin/python3.6 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/duxiaogang/mmcv/setup.py'"'"'; __file__='"'"'/home/duxiaogang/mmcv/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/duxiaogang/mmcv/
    Complete output (103 lines):
    running develop
    running egg_info
    creating mmcv_full.egg-info
    writing mmcv_full.egg-info/PKG-INFO
    writing dependency_links to mmcv_full.egg-info/dependency_links.txt
    writing requirements to mmcv_full.egg-info/requires.txt
    writing top-level names to mmcv_full.egg-info/top_level.txt
    writing manifest file 'mmcv_full.egg-info/SOURCES.txt'
    reading manifest file 'mmcv_full.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    adding license file 'LICENSE'
    adding license file 'LICENSES.md'
    writing manifest file 'mmcv_full.egg-info/SOURCES.txt'
    running build_ext
    building 'mmcv._ext' extension
    creating /home/duxiaogang/mmcv/build
    creating /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6
    creating /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/mmcv
    creating /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/mmcv/ops
    creating /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/mmcv/ops/csrc
    creating /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/mmcv/ops/csrc/pytorch
    creating /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/mmcv/ops/csrc/pytorch/cuda
    Emitting ninja build file /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/build.ninja...
    Compiling objects...
    Using envvar MAX_JOBS (4) as the number of workers...
    /home/duxiaogang/anaconda3/envs/mmcv/lib/python3.6/site-packages/torch/utils/cpp_extension.py:286: UserWarning:
    
                                   !! WARNING !!
    
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    Your compiler (c++) is not compatible with the compiler Pytorch was
    built with for this platform, which is g++ on linux. Please
    use g++ to to compile your extension. Alternatively, you may
    compile PyTorch from source using c++, and then you can also use
    c++ to compile your extension.
    
    See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
    with compiling PyTorch from source.
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    
                                  !! WARNING !!
    
      platform=sys.platform))
    1.10.2
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/mmcv
    g++ -pthread -shared -B /home/duxiaogang/anaconda3/envs/mmcv/compiler_compat -L/home/duxiaogang/anaconda3/envs/mmcv/lib -Wl,-rpath=/home/duxiaogang/anaconda3/envs/mmcv/lib -Wl,--no-as-needed -Wl,--sysroot=/ /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/bbox_overlaps.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/border_align.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/box_iou_rotated.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/box_iou_rotated_cpu.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/carafe.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/carafe_naive.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/cc_attention.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/contour_expand.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/corner_pool.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/deform_conv.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/deform_conv_cpu.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/deform_roi_pool.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/focal_loss.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/fused_bias_leakyrelu.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/info.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/masked_conv2d.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/modulated_deform_conv.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/modulated_deform_conv_cpu.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/ms_deform_attn.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/nms.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/nms_rotated.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/nms_rotated_cpu.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/pixel_group.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/psamask.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/pybind.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/roi_align.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/roi_align_cpu.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/roi_align_rotated.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/roi_align_rotated_cpu.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/roi_pool.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/sync_bn.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/tin_shift.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/upfirdn2d.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/cuda/bbox_overlaps_cuda.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/cuda/border_align_cuda.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/cuda/box_iou_rotated_cuda.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/cuda/carafe_cuda.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/cuda/carafe_naive_cuda.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/cuda/cc_attention_cuda.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/cuda/deform_conv_cuda.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/cuda/deform_roi_pool_cuda.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/cuda/focal_loss_cuda.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/cuda/fused_bias_leakyrelu_cuda.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/cuda/masked_conv2d_cuda.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/cuda/modulated_deform_conv_cuda.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/cuda/ms_deform_attn_cuda.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/cuda/nms_cuda.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/cuda/nms_rotated_cuda.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/cuda/psamask_cuda.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/cuda/roi_align_cuda.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/cuda/roi_align_rotated_cuda.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/cuda/roi_pool_cuda.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/cuda/sync_bn_cuda.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/cuda/tin_shift_cuda.o /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/cuda/upfirdn2d_kernel.o -L/home/duxiaogang/anaconda3/envs/mmcv/lib/python3.6/site-packages/torch/lib -L/usr/local/cuda-11.2/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda_cu -ltorch_cuda_cpp -o build/lib.linux-x86_64-3.6/mmcv/_ext.cpython-36m-x86_64-linux-gnu.so
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/bbox_overlaps.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/border_align.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/box_iou_rotated.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/box_iou_rotated_cpu.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/carafe.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/carafe_naive.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/cc_attention.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/contour_expand.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/corner_pool.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/deform_conv.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/deform_conv_cpu.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/deform_roi_pool.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/focal_loss.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/fused_bias_leakyrelu.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/info.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/masked_conv2d.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/modulated_deform_conv.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/modulated_deform_conv_cpu.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/ms_deform_attn.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/nms.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/nms_rotated.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/nms_rotated_cpu.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/pixel_group.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/psamask.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/pybind.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/roi_align.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/roi_align_cpu.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/roi_align_rotated.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/roi_align_rotated_cpu.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/roi_pool.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/sync_bn.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/tin_shift.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/upfirdn2d.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/cuda/bbox_overlaps_cuda.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/cuda/border_align_cuda.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/cuda/box_iou_rotated_cuda.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/cuda/carafe_cuda.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/cuda/carafe_naive_cuda.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/cuda/cc_attention_cuda.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/cuda/deform_conv_cuda.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/cuda/deform_roi_pool_cuda.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/cuda/focal_loss_cuda.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/cuda/fused_bias_leakyrelu_cuda.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/cuda/masked_conv2d_cuda.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/cuda/modulated_deform_conv_cuda.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/cuda/ms_deform_attn_cuda.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/cuda/nms_cuda.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/cuda/nms_rotated_cuda.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/cuda/psamask_cuda.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/cuda/roi_align_cuda.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/cuda/roi_align_rotated_cuda.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/cuda/roi_pool_cuda.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/cuda/sync_bn_cuda.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/cuda/tin_shift_cuda.o: No such file or directory
    g++: error: /home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/cuda/upfirdn2d_kernel.o: No such file or directory
    error: command 'g++' failed with exit status 1
----------------------------------------
ERROR: Command errored out with exit status 1: /home/duxiaogang/anaconda3/envs/mmcv/bin/python3.6 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/duxiaogang/mmcv/setup.py'"'"'; __file__='"'"'/home/duxiaogang/mmcv/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

everyone，a request for help for me. ths

**Comment by zhouzaida** [comment]
hi @zgsxwsdxg , please provide more information according to the issue template

**Comment by zgsxwsdxg** [comment]
> hi @zgsxwsdxg , please provide more information according to the issue template

你指的是什么模板？我用的centos7 cuda11.1，pytorch-1.8.1

**Comment by zhouzaida** [comment]
nvcc 和 g++ 的版本

**Comment by zgsxwsdxg** [comment]
> nvcc 和 g++ 的版本

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Feb_14_21:12:58_PST_2021
Cuda compilation tools, release 11.2, V11.2.152
Build cuda_11.2.r11.2/compiler.29618528_0

g++ (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE

**Comment by zgsxwsdxg** [comment]
> nvcc 和 g++ 的版本
torch 版本
conda install pytorch==1.8.0 torchvision==0.9.0 torchaudio==0.8.0 cudatoolkit=11.1

**Comment by zhouzaida** [comment]
可以删除 mmcv/build 再试试

**Comment by zgsxwsdxg** [comment]
> 可以删除 mmcv/build 再试试

删除build 试过了，还是不行，g++ 编译ops时找不到.o文件

**Comment by zgsxwsdxg** [comment]
> 可以删除 mmcv/build 再试试

编译命令 MMCV_WITH_OPS=1 pip install -e . 这个没错把？

**Comment by zhouzaida** [comment]
这个命令是没问题的

**Comment by zgsxwsdxg** [comment]
> 这个命令是没问题的

 问下你，一般编译ops找不到 .o文件时什么原因？setup.py 哪个地方会设置.o的输出路径？谢谢

**Comment by zhouzaida** [comment]
从log看是链接阶段没能在 `/home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/cuda/` 中找到 .o 文件，你可以看一下这个目录，如果没有那就是编译过程出的问题

**Comment by zgsxwsdxg** [comment]
> 从log看是链接阶段没能在 `/home/duxiaogang/mmcv/build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/cuda/` 中找到 .o 文件，你可以看一下这个目录，如果没有那就是编译过程出的问题

谢谢你的答复，我看了这个目录没有.o文件

**Comment by zhouzaida** [comment]
使用 `MMCV_WITH_OPS=1 python setup.py develop` 试试

**Comment by zgsxwsdxg** [comment]
> MMCV_WITH_OPS=1 python setup.py develop

试了，还不行

**Comment by zgsxwsdxg** [comment]
> > MMCV_WITH_OPS=1 python setup.py develop
> 
> 试了，还不行

重装系统解决了
