### ISSUE TITLE
is there a plan to add GPU version for the custom onnx runtime ops?

### ISSUE THREAD

**Issue by ideafold** [open-mmlab/mmcv#1328]
**Describe the feature**

**Motivation**
A clear and concise description of the motivation of the feature.
Ex1. It is inconvenient when [....].
Ex2. There is a recent paper [....], which is very helpful for [....].

**Related resources**
If there is an official code release or third-party implementations, please also provide the information here, which would be very helpful.

**Additional context**
If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.

**Comment by ideafold** [comment]
@grimoire

**Comment by grimoire** [comment]
GPU custom ONNX Runtime ops are not on our TODO list for now. TensorRT is highly recommend if you want to deploy your model on Nvidia devices.

**Comment by ideafold** [comment]
> GPU custom ONNX Runtime ops are not on our TODO list for now. TensorRT is highly recommend if you want to deploy your model on Nvidia devices.

Got. Thanks.
