### ISSUE TITLE
源码安装方式安装后，如何卸载mmcv

### ISSUE THREAD

**Issue by zgsxwsdxg** [open-mmlab/mmcv#1334]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the FAQ documentation but cannot get the expected help.

你好！
我 MMCV_WITH_OPS=1 pip install -e . 安装之后，安装成功了，我尝试卸载 pip uninstall mmcv 报警如下：WARNING: Skipping mmcv as it is not installed。 重新import mmcv，发现还可以，说明没有卸载成功。

我想请教下，如何卸载mmcv，谢谢！

**Comment by zhouzaida** [comment]
因为安装的时候设置了`MMCV_WITH_OPS=1`标识，所以安装的包名为 mmcv-full，所以卸载的时候得用 `pip uninstall mmcv-full`

**Comment by zgsxwsdxg** [comment]
> 因为安装的时候设置了`MMCV_WITH_OPS=1`标识，所以安装的包名为 mmcv-full，所以卸载的时候得用 `pip uninstall mmcv-full`

谢谢，你的回复！顺便问下，为什么安装了mmcv-full，但是导入的是mmcv 即 import mmcv

**Comment by zgsxwsdxg** [comment]
> 因为安装的时候设置了`MMCV_WITH_OPS=1`标识，所以安装的包名为 mmcv-full，所以卸载的时候得用 `pip uninstall mmcv-full`

https://github.com/open-mmlab/mmcv/blob/master/setup.py 324行 
setup(
    name='mmcv' if os.getenv('MMCV_WITH_OPS', '0') == '0' else 'mmcv-full',
    version=get_version(),
    description='OpenMMLab Computer Vision Foundation',
    keywords='computer vision',
    packages=find_packages(),
    include_package_data=True,
    classifiers=[
        'Development Status :: 4 - Beta',
        'License :: OSI Approved :: Apache Software License',
        'Operating System :: OS Independent',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Topic :: Utilities',
    ],
    url='https://github.com/open-mmlab/mmcv',
    author='MMCV Contributors',
    author_email='openmmlab@gmail.com',
    setup_requires=['pytest-runner'],
    tests_require=['pytest'],
    install_requires=install_requires,
    ext_modules=get_extensions(),
    cmdclass=cmd_class,
    zip_safe=False)

name 变成了 mmcv-full，为什么导入还是要用mmcv即 import mmcv，我是个初学者，请教下你，谢谢！

**Comment by zhouzaida** [comment]
这里要理清repo名（算法库名）、包名、模块名

- repo名（算法库名）
  
  https://github.com/open-mmlab/mmcv
  这里的 mmcv 就是算法库名

- 模块名
  ```
  |-- docs
  |-- docs_zh_CN
  |-- examples
  |-- mmcv （模块名）
  |-- requirements
  |-- requirements.txt
  |-- setup.cfg
  |-- setup.py
  `-- tests
  ```

- 包名
https://github.com/open-mmlab/mmcv/blob/1216e5fe7fbff3299d94f5e153cba74ce854f567/setup.py#L323-L329

  这里决定包名，如果设置了`MMCV_WITH_OPS=1`标识，则包名为 mmcv-full，否则为 mmcv。

总结：pip install 包名，import 模块名。因此，包名可能是 mmcv，也可能是 mmcv-full（这取决于有没有设置`MMCV_WITH_OPS=1`标识），而模块名只能是 mmcv

**Comment by zgsxwsdxg** [comment]
> 包名可能是 mmcv，也可能是 mmcv-full

非常感谢您，我理解透彻了！赞！

**Comment by zgsxwsdxg** [comment]
> 这里要理清repo名（算法库名）、包名、模块名
> 
> * repo名（算法库名）
>   https://github.com/open-mmlab/mmcv
>   这里的 mmcv 就是算法库名
> * 模块名
>   ```
>   |-- docs
>   |-- docs_zh_CN
>   |-- examples
>   |-- mmcv （模块名）
>   |-- requirements
>   |-- requirements.txt
>   |-- setup.cfg
>   |-- setup.py
>   `-- tests
>   ```
> * 包名
>   https://github.com/open-mmlab/mmcv/blob/1216e5fe7fbff3299d94f5e153cba74ce854f567/setup.py#L323-L329
>   
>   这里决定包名，如果设置了`MMCV_WITH_OPS=1`标识，则包名为 mmcv-full，否则为 mmcv。
> 
> 总结：pip install 包名，import 模块名。因此，包名可能是 mmcv，也可能是 mmcv-full（这取决于有没有设置`MMCV_WITH_OPS=1`标识），而模块名只能是 mmcv

这里，我就不再重新开一个issue了，顺便问下你mmcv中ops为什么编译完了只能cuda下用，不能同时兼顾cpu？同时的话会是不是会更好？让程序自动判断张量device type 调用不同ops， 期待您回复，谢谢！

**Comment by zhouzaida** [comment]
> > 这里要理清repo名（算法库名）、包名、模块名
> > 
> > * repo名（算法库名）
> >   https://github.com/open-mmlab/mmcv
> >   这里的 mmcv 就是算法库名
> > * 模块名
> >   ```
> >   |-- docs
> >   |-- docs_zh_CN
> >   |-- examples
> >   |-- mmcv （模块名）
> >   |-- requirements
> >   |-- requirements.txt
> >   |-- setup.cfg
> >   |-- setup.py
> >   `-- tests
> >   ```
> > * 包名
> >   https://github.com/open-mmlab/mmcv/blob/1216e5fe7fbff3299d94f5e153cba74ce854f567/setup.py#L323-L329
> >   
> >   这里决定包名，如果设置了`MMCV_WITH_OPS=1`标识，则包名为 mmcv-full，否则为 mmcv。
> > 
> > 总结：pip install 包名，import 模块名。因此，包名可能是 mmcv，也可能是 mmcv-full（这取决于有没有设置`MMCV_WITH_OPS=1`标识），而模块名只能是 mmcv
> 
> 这里，我就不再重新开一个issue了，顺便问下你mmcv中ops为什么编译完了只能cuda下用，不能同时兼顾cpu？同时的话会是不是会更好？让程序自动判断张量device type 调用不同ops， 期待您回复，谢谢！

有些算子同时包含cuda和cpu的实现，但大多数算子只有cuda的实现，因为我们使用cuda实现算子的原因在于加速。

**Comment by zgsxwsdxg** [comment]
> > > 这里要理清repo名（算法库名）、包名、模块名
> > > 
> > > * repo名（算法库名）
> > >   https://github.com/open-mmlab/mmcv
> > >   这里的 mmcv 就是算法库名
> > > * 模块名
> > >   ```
> > >   |-- docs
> > >   |-- docs_zh_CN
> > >   |-- examples
> > >   |-- mmcv （模块名）
> > >   |-- requirements
> > >   |-- requirements.txt
> > >   |-- setup.cfg
> > >   |-- setup.py
> > >   `-- tests
> > >   ```
> > > * 包名
> > >   https://github.com/open-mmlab/mmcv/blob/1216e5fe7fbff3299d94f5e153cba74ce854f567/setup.py#L323-L329
> > >   
> > >   这里决定包名，如果设置了`MMCV_WITH_OPS=1`标识，则包名为 mmcv-full，否则为 mmcv。
> > > 
> > > 总结：pip install 包名，import 模块名。因此，包名可能是 mmcv，也可能是 mmcv-full（这取决于有没有设置`MMCV_WITH_OPS=1`标识），而模块名只能是 mmcv
> > 
> > 
> > 这里，我就不再重新开一个issue了，顺便问下你mmcv中ops为什么编译完了只能cuda下用，不能同时兼顾cpu？同时的话会是不是会更好？让程序自动判断张量device type 调用不同ops， 期待您回复，谢谢！
> 
> 有些算子同时包含cuda和cpu的实现，但大多数算子只有cuda的实现，因为我们使用cuda实现算子的原因在于加速。
在setup.py 255行到268行这段代码，我有点疑惑，希望释疑。
        elif torch.cuda.is_available() or os.getenv('FORCE_CUDA', '0') == '1':
            define_macros += [('MMCV_WITH_CUDA', None)]
            cuda_args = os.getenv('MMCV_CUDA_ARGS')
            extra_compile_args['nvcc'] = [cuda_args] if cuda_args else []
            op_files = glob.glob('./mmcv/ops/csrc/pytorch/*.cpp') + \
                glob.glob('./mmcv/ops/csrc/pytorch/cuda/*.cu')
            extension = CUDAExtension
            include_dirs.append(os.path.abspath('./mmcv/ops/csrc/common'))
            include_dirs.append(os.path.abspath('./mmcv/ops/csrc/common/cuda'))
        else:
            print(f'Compiling {ext_name} without CUDA')
            op_files = glob.glob('./mmcv/ops/csrc/pytorch/*.cpp')
            extension = CppExtension
            include_dirs.append(os.path.abspath('./mmcv/ops/csrc/common'))

我的疑惑是 elif torch.cuda.is_available() or os.getenv('FORCE_CUDA', '0') == '1': 代码块是编译cuda ops，else代码块编译cpu os

那为什么有cuda的时候，就不能编译cpu ops ？如果去掉else 判断，这样是不是就同时支持cpu和cuda ops了？

**Comment by zgsxwsdxg** [comment]
> > > 这里要理清repo名（算法库名）、包名、模块名
> > > 
> > > * repo名（算法库名）
> > >   https://github.com/open-mmlab/mmcv
> > >   这里的 mmcv 就是算法库名
> > > * 模块名
> > >   ```
> > >   |-- docs
> > >   |-- docs_zh_CN
> > >   |-- examples
> > >   |-- mmcv （模块名）
> > >   |-- requirements
> > >   |-- requirements.txt
> > >   |-- setup.cfg
> > >   |-- setup.py
> > >   `-- tests
> > >   ```
> > > * 包名
> > >   https://github.com/open-mmlab/mmcv/blob/1216e5fe7fbff3299d94f5e153cba74ce854f567/setup.py#L323-L329
> > >   
> > >   这里决定包名，如果设置了`MMCV_WITH_OPS=1`标识，则包名为 mmcv-full，否则为 mmcv。
> > > 
> > > 总结：pip install 包名，import 模块名。因此，包名可能是 mmcv，也可能是 mmcv-full（这取决于有没有设置`MMCV_WITH_OPS=1`标识），而模块名只能是 mmcv
> > 
> > 
> > 这里，我就不再重新开一个issue了，顺便问下你mmcv中ops为什么编译完了只能cuda下用，不能同时兼顾cpu？同时的话会是不是会更好？让程序自动判断张量device type 调用不同ops， 期待您回复，谢谢！
> 
> 有些算子同时包含cuda和cpu的实现，但大多数算子只有cuda的实现，因为我们使用cuda实现算子的原因在于加速。

       https://github.com/open-mmlab/mmcv/blob/1216e5fe7fbff3299d94f5e153cba74ce854f567/setup.py#L323-L329
