### ISSUE TITLE
Argument src_type in cast_tensor_type play no role.

### ISSUE THREAD

**Issue by Abyssaledge** [open-mmlab/mmcv#1340]
https://github.com/open-mmlab/mmcv/blob/c47c9196d067a0900b7b8987a8e82768edab2fff/mmcv/runner/fp16_utils.py#L24
If my understanding is correct, argument `src_type` here has no effect on the behavior of the function.
Any type of Tensors will be cast to `dst_type` as following line shows.
https://github.com/open-mmlab/mmcv/blob/c47c9196d067a0900b7b8987a8e82768edab2fff/mmcv/runner/fp16_utils.py#L38
I got an unexpected results using `force_fp32(out_fp16=True)`: a int tensor is cast to half when returned.
Am I right? Do I miss something?

**Comment by zhouzaida** [comment]
yet, you are right. src_type has no effect on cast_tensor_type

**Comment by zhouzaida** [comment]
> https://github.com/open-mmlab/mmcv/blob/c47c9196d067a0900b7b8987a8e82768edab2fff/mmcv/runner/fp16_utils.py#L24
> 
> 
> If my understanding is correct, argument `src_type` here has no effect on the behavior of the function.
> Any type of Tensors will be cast to `dst_type` as following line shows.
> https://github.com/open-mmlab/mmcv/blob/c47c9196d067a0900b7b8987a8e82768edab2fff/mmcv/runner/fp16_utils.py#L38
> 
> 
> I got an unexpected results using `force_fp32(out_fp16=True)`: a int tensor is cast to half when returned.
> Am I right? Do I miss something?

what the results of `force_fp32(out_fp16=True)` do you expect
