### ISSUE TITLE
Can mmcv be installed in Xavier?

### ISSUE THREAD

**Issue by liu2011tao** [open-mmlab/mmcv#1341]
Hi, I try to install mmcv in Xavier, and I use such command.
pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu102/torch1.8.0/index.html
but is post mistake about arch64.so I am wondering that  can mmcv run on Xavier?

**Comment by CarryHJR** [comment]
mmcv can be installed in Xavier, just need to build it from source instead of the prebuilt version

**Comment by zhouzaida** [comment]
hi @liu2011tao , is there any progress?
