### ISSUE TITLE
MMCV support Cambricon MLU computing

### ISSUE THREAD

**Issue by yushinliu** [open-mmlab/mmcv#1345]
**Describe the feature**

**Motivation**
Support running models and ops on Cambricon MLU device.

**Related resources**

## Environments

python == 3.6.8
setuptools == 46.1.3
cntoolkit == 2.3.2
catch == 0.19.1

## Installation

- Install Cambricon CATCH through resource or wheel.

- Install MMCV with MLU ops .

    1. export MMCV_WITH_OPS=1

    2. Move to MMCV root and run installation: python setup.py install

## Demo

- run mmcv/tests/test_ops/test_focal_loss.py

**Additional context**
2021.09.18: sigmoid_focal_loss is supported as first MLU op on MMCV.

**Comment by zhouzaida** [comment]
closed by #1346
