### ISSUE TITLE
ImportError: DLL load failed while importing _ext: 找不到指定的模块。

### ISSUE THREAD

**Issue by dugudongfangshuo** [open-mmlab/mmcv#1347]
File "E:\Anaconda\envs\lastCVpy38cuda102\lib\site-packages\mmcv\cnn\bricks\transformer.py", line 18, in <module>
    from mmcv.ops.multi_scale_deform_attn import MultiScaleDeformableAttention  # noqa F401
  File "E:\Anaconda\envs\lastCVpy38cuda102\lib\site-packages\mmcv\ops\__init__.py", line 2, in <module>
    from .bbox import bbox_overlaps
  File "E:\Anaconda\envs\lastCVpy38cuda102\lib\site-packages\mmcv\ops\bbox.py", line 4, in <module>
    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
  File "E:\Anaconda\envs\lastCVpy38cuda102\lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "E:\Anaconda\envs\lastCVpy38cuda102\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing _ext: 找不到指定的模块。

已经安装了完整的mmcv, 然后复制到了离线状态的服务器  然后from mmcv.ops.multi_scale_deform_attn import MultiScaleDeformableAttention  # noqa F401就报错 ，不知道为啥，这个模块明明在安装的内容里可以找到

**Comment by dugudongfangshuo** [comment]
# Avoid BC-breaking of importing MultiScaleDeformableAttention from this file
try:
    from mmcv.ops.multi_scale_deform_attn import MultiScaleDeformableAttention  # noqa F401
    warnings.warn(
        ImportWarning(
            '``MultiScaleDeformableAttention`` has been moved to '
            '``mmcv.ops.multi_scale_deform_attn``, please change original path '  # noqa E501
            '``from mmcv.cnn.bricks.transformer import MultiScaleDeformableAttention`` '  # noqa E501
            'to ``from mmcv.ops.multi_scale_deform_attn import MultiScaleDeformableAttention`` '  # noqa E501
        ))

except ImportError:
    warnings.warn('Fail to import ``MultiScaleDeformableAttention`` from '
                  '``mmcv.ops.multi_scale_deform_attn``, '
                  'You should install ``mmcv-full`` if you need this module. ')

就是这个地方import的问题，为啥improt 不进来

**Comment by zhouzaida** [comment]
hi @dugudongfangshuo , you should install mmcv-full rather than mmcv if you need the _ext module.

**Comment by dugudongfangshuo** [comment]
安装了mmcv-full版本的，然后把环境复制到另一台电脑就不行了。。。  能提供windowsserver版本的whl包吗

**Comment by zhouzaida** [comment]
不好意思，暂时还提供不了 windows 的预编译包

**Comment by dugudongfangshuo** [comment]
好的

**Comment by SunGd123** [comment]
你好，我也遇到了这个问题，请问你现在解决了吗

**Comment by dugudongfangshuo** [comment]
没用解决已经放弃这个框架 不是很友好对windows系统来说  老老实实用pytorch就挺好的我觉得

**Comment by zhouzaida** [comment]
> 你好，我也遇到了这个问题，请问你现在解决了吗

你好，请问编译的时候有设置 `MMCV_WITH_OPS=1` 吗？

**Comment by SunGd123** [comment]
> > 你好，我也遇到了这个问题，请问你现在解决了吗
> 
> 你好，请问编译的时候有设置 `MMCV_WITH_OPS=1` 吗？

这个在环境创建的时候没有使用，直接运行的
```
pip install mmcv-full==1.1.4
```
请问是要加上这个吗？
```
MMCV_WITH_OPS=1 pip install mmcv-full==1.1.4
```

**Comment by 850977164** [comment]
> 你好，我也遇到了这个问题，请问你现在解决了吗

**Comment by Meansnj** [comment]
你好，我也遇到了这个问题，请问你现在解决了吗

**Comment by rkj12345** [comment]
> 你好，我也遇到了这个问题，请问你现在解决了吗

请问你现在解决了嘛

**Comment by 850977164** [comment]
你好，我解决了，我重新安装了更高版本的cuda和pytorch，你也可以新建个环境尝试一下。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年01月12日 18:18 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [open-mmlab/mmcv] ImportError: DLL load failed while importing _ext: 找不到指定的模块。 (#1347) |

你好，我也遇到了这个问题，请问你现在解决了吗

请问你现在解决了嘛

**Comment by Meansnj** [comment]
非常感谢你的建议，我会尝试更新到更高版本的cuda和pytorch，Thanks！！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/mmcv"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月13日(星期六) 下午3:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-mmlab/mmcv] ImportError: DLL load failed while importing _ext: 找不到指定的模块。 (#1347)





 你好，我解决了，我重新安装了更高版本的cuda和pytorch，你也可以新建个环境尝试一下。
 
 
 
 ---- 回复的原邮件 ----
 | 发件人 | ***@***.***&gt; |
 | 日期 | 2024年01月12日 18:18 |
 | 收件人 | ***@***.***&gt; |
 | 抄送至 | ***@***.***&gt;***@***.***&gt; |
 | 主题 | Re: [open-mmlab/mmcv] ImportError: DLL load failed while importing _ext: 找不到指定的模块。 (#1347) |
 
 你好，我也遇到了这个问题，请问你现在解决了吗
 
 请问你现在解决了嘛

**Comment by macaulishxcoo** [comment]
> 你好，我解决了，我重新安装了更高版本的cuda和pytorch，你也可以新建个环境尝试一下。
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2024年01月12日 18:18 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [open-mmlab/mmcv] ImportError: DLL load failed while importing _ext: 找不到指定的模块。 (#1347) | 你好，我也遇到了这个问题，请问你现在解决了吗 请问你现在解决了嘛 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

请问下你解决这个问题安装的cuda和python版本是多少？我现在是torch1.8.0+cu11.3，一直没找到解决办法。

**Comment by macaulishxcoo** [comment]
> 非常感谢你的建议，我会尝试更新到更高版本的cuda和pytorch，Thanks！！
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "open-mmlab/mmcv" ***@***.***&gt;; 发送时间:&nbsp;2024年1月13日(星期六) 下午3:24 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [open-mmlab/mmcv] ImportError: DLL load failed while importing _ext: 找不到指定的模块。 (#1347) 你好，我解决了，我重新安装了更高版本的cuda和pytorch，你也可以新建个环境尝试一下。
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***&gt; | | 日期 | 2024年01月12日 18:18 | | 收件人 | ***@***.***&gt; | | 抄送至 | ***@***.***&gt;***@***.***&gt; | | 主题 | Re: [open-mmlab/mmcv] ImportError: DLL load failed while importing _ext: 找不到指定的模块。 (#1347) | 你好，我也遇到了这个问题，请问你现在解决了吗 请问你现在解决了嘛 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt; — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.*

请问更新到更高的版本后，bug解决了吗？
