### ISSUE TITLE
Bug when checking if number of GPUs is different during resume

### ISSUE THREAD

**Issue by collinmccarthy** [open-mmlab/mmcv#1359]
**Describe the Issue**
I run training jobs in Slurm, and when they get pre-empted and automatically resume the number of iterations changes. The value in the checkpoint file is correct, and I've traced the issue to [here](https://github.com/open-mmlab/mmcv/blob/4bab29241a6b10a538ac3f9916ff58803377f36b/mmcv/runner/base_runner.py#L377) (shown below):

```python
if 'config' in checkpoint['meta']:
        config = mmcv.Config.fromstring(
            checkpoint['meta']['config'], file_format='.py')
        previous_gpu_ids = config.get('gpu_ids', None)
        if previous_gpu_ids and len(previous_gpu_ids) > 0 and len(
                previous_gpu_ids) != self.world_size:
            self._iter = int(self._iter * len(previous_gpu_ids) /
                             self.world_size)
            self.logger.info('the iteration number is changed due to '
                             'change of GPU number')
```

Specifically here:

```python
if previous_gpu_ids and len(previous_gpu_ids) > 0 and len(
        previous_gpu_ids) != self.world_size:
    self._iter = int(self._iter * len(previous_gpu_ids) /
                     self.world_size)
```

My value for `previous_gpu_ids` is `range(0, 1)` which has a length of 1, and the current world size is 2, so the iteration count gets incorrectly halved. My guess is `gpu_ids` was recently changed to be a range instead of a list, or it uses both, in different situations. The original fix is from #844.

**Reproduction**

1. What command, code, or script did you run?

I'm running experiments using [XCiT semantic segmentation](https://github.com/facebookresearch/xcit/tree/master/semantic_segmentation), using the latest version of `mmcv-full` and `mmsegmentation`, as shown below. The issue should be easily reproducible in a multi-GPU environment that produces a `range` object for GPU ids. I'm using Slurm with 2 GPUs on a 4-GPU machine for each run, and resuming the checkpoint from the exact machine it was saved on with the exact same parameters (it's just requeued). 

2. Did you make any modifications on the code? Did you understand what you have modified?

Only config files, and yes.

**Environment**

1. Please run `python -c "from mmcv.utils import collect_env; print(collect_env())"` to collect necessary environment information and paste it here.

```console
{'sys.platform': 'linux', 'Python': '3.8.12 | packaged by conda-forge | (default, Sep 16 2021, 02:08:29) [GCC 9.4.0]', 'CUDA available': True, 'GPU 0,1': 'NVIDIA Tesla V100-DGXS-32GB', 'CUDA_HOME': '/usr/local/cuda-11.1', 'NVCC': 'Build cuda_11.1.TC455_06.29190527_0', 'GCC': 'gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0', 'PyTorch': '1.9.0', 'PyTorch compiling details': 'PyTorch built with:\n  - GCC 7.3\n  - C++ Version: 201402\n  - Intel(R) oneAPI Math Kernel Library Version 2021.3-Product Build 20210617 for Intel(R) 64 architecture applications\n  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)\n  - OpenMP 201511 (a.k.a. OpenMP 4.5)\n  - NNPACK is enabled\n  - CPU capability usage: AVX2\n  - CUDA Runtime 11.1\n  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37\n  - CuDNN 8.0.5\n  - Magma 2.5.2\n  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, \n', 'TorchVision': '0.10.0', 'OpenCV': '4.4.0', 'MMCV': '1.3.13', 'MMCV Compiler': 'GCC 7.3', 'MMCV CUDA Compiler': '11.1'}
```

**Bug fix**

Not sure what you want to do, in terms of checking for an object of type range or turning it into a list then checking the length (that probably makes sense). I don't have time for a PR right now (crunch time, sorry).

Thanks!
-Collin

**Comment by collinmccarthy** [comment]
Oh, right, I forgot `list(range(0, 1))` is just `[0]`. So then I'm not exactly sure where this went wrong. Is `range(0, 1)` supposed to represent GPUs 0 and 1? That's what I originally thought but I'm not sure what the intention is.

**Comment by collinmccarthy** [comment]
In case it helps, here's the log from the first epoch, and the start of when it resumes. At least to me, it looks like `range(0, 1)` is supposed to mean GPUs (0, 1) but that only has a length of 1.

[20210921_201242_e1.log](https://github.com/open-mmlab/mmcv/files/7212425/20210921_201242_e1.log)
[20210921_211552_resume.log](https://github.com/open-mmlab/mmcv/files/7212426/20210921_211552_resume.log)

**Comment by zhouzaida** [comment]
> Oh, right, I forgot `list(range(0, 1))` is just `[0]`. So then I'm not exactly sure where this went wrong. Is `range(0, 1)` supposed to represent GPUs 0 and 1? That's what I originally thought but I'm not sure what the intention is.

hi @collinmccarthy , `gpu_ids = range(0, 1)` means one GPU

**Comment by Junjun2016** [comment]
https://github.com/open-mmlab/mmcv/pull/1360

**Comment by zhouzaida** [comment]
The using runner of mmseg is `IterBasedRunner`, which doesn't modify the `self._iter` status.
https://github.com/open-mmlab/mmcv/blob/b92ea0b5df9cfa4222fec704890bd6c8901fe6b8/mmcv/runner/iter_based_runner.py#L139-L176

**Comment by zhouzaida** [comment]
By the way, the gpu_ids is incorrect before the PR (https://github.com/open-mmlab/mmsegmentation/pull/866)

**Comment by collinmccarthy** [comment]
Thank you both, this makes more sense. When I ran into this issue I was using the `EpochBasedRunner` so for my particular case #866 should solve it. That hasn't been released yet so I'll pull from master. Thanks!
