### ISSUE TITLE
Is there any way to init the conv.weight and conv.bias with different init method?

### ISSUE THREAD

**Issue by HarborYuan** [open-mmlab/mmcv#1366]
Hi,

Thanks for your work on mmcv.

I am trying to init my model with init_cfg, but I found it is hard to init conv2d.weight and conv2d.bias with different method. Is there any way to achieve this without write a custom init_weights()?

At the same time, it is also hard to only init a specific module(I achieve this by letting init_cfg to init the non-exist conv3d and  override with a name, it is kind of werid). Can I only specify a name to init a specific module?

Thanks.

**Comment by MeowZheng** [comment]
Many thanks for you raising these questions. Based on the current implementation in MMCV, rewriting is the best practice for both of your questions, but we take these issues seriously and will work to address these concerns.
