### ISSUE TITLE
mmcv.Config.fromfile not auto reload

### ISSUE THREAD

**Issue by alenweiru** [open-mmlab/mmcv#137]

**Comment by alenweiru** [comment]
I use `mmcv.Config.fromfile` to load my config python file via jupyter notebook .And I found that when I modify config python file (`comment dict(type='Normalize', **img_norm_cfg),`) ,`mmcv.Config.fromfile` return object not match as the config python file . 
![image](https://user-images.githubusercontent.com/21155566/66023202-09a5fd00-e523-11e9-8587-33af0aab86e1.png)

**Comment by hellock** [comment]
You need to restart the kernel.
