### ISSUE TITLE
ImportError: cannot import name 'MultiScaleDeformableAttention' from 'mmcv.cnn.bricks.transformer'

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [open-mmlab/mmcv#1399]
Thanks for reporting the unexpected results and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmcv.readthedocs.io/en/latest/trouble_shooting.html) but cannot get the expected help.
3. The unexpected results still exist in the latest version.

**Describe the Issue**
```
/home/zuppif/integration-object-detection-icevision/.venv/lib/python3.9/site-packages/mmcv/cnn/bricks/transformer.py:28: UserWarning: Fail to import ``MultiScaleDeformableAttention`` from ``mmcv.ops.multi_scale_deform_attn``, You should install ``mmcv-full`` if you need this module. 
  warnings.warn('Fail to import ``MultiScaleDeformableAttention`` from '
/home/zuppif/integration-object-detection-icevision/.venv/lib/python3.9/site-packages/mmdet/models/utils/transformer.py:26: UserWarning: `MultiScaleDeformableAttention` in MMCV has been moved to `mmcv.ops.multi_scale_deform_attn`, please update your MMCV
  warnings.warn(
Traceback (most recent call last):
  File "/home/zuppif/integration-object-detection-icevision/.venv/lib/python3.9/site-packages/mmdet/models/utils/transformer.py", line 23, in <module>
    from mmcv.ops.multi_scale_deform_attn import MultiScaleDeformableAttention
  File "/home/zuppif/integration-object-detection-icevision/.venv/lib/python3.9/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .ball_query import ball_query
  File "/home/zuppif/integration-object-detection-icevision/.venv/lib/python3.9/site-packages/mmcv/ops/ball_query.py", line 7, in <module>
    ext_module = ext_loader.load_ext('_ext', ['ball_query_forward'])
  File "/home/zuppif/integration-object-detection-icevision/.venv/lib/python3.9/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/zuppif/miniconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/zuppif/integration-object-detection-icevision/.venv/lib/python3.9/site-packages/mmcv/_ext.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor6deviceEv

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zuppif/integration-object-detection-icevision/notebook.py", line 7, in <module>
    from icevision import ObjectDetectionRecord, Parser, ClassMap, BBox, ImgSize
  File "/home/zuppif/integration-object-detection-icevision/.venv/lib/python3.9/site-packages/icevision/__init__.py", line 7, in <module>
    from icevision import models
  File "/home/zuppif/integration-object-detection-icevision/.venv/lib/python3.9/site-packages/icevision/models/__init__.py", line 15, in <module>
    from icevision.models import mmdet
  File "/home/zuppif/integration-object-detection-icevision/.venv/lib/python3.9/site-packages/icevision/models/mmdet/__init__.py", line 1, in <module>
    from icevision.models.mmdet import common
  File "/home/zuppif/integration-object-detection-icevision/.venv/lib/python3.9/site-packages/icevision/models/mmdet/common/__init__.py", line 3, in <module>
    from icevision.models.mmdet.common import bbox
  File "/home/zuppif/integration-object-detection-icevision/.venv/lib/python3.9/site-packages/icevision/models/mmdet/common/bbox/__init__.py", line 1, in <module>
    from icevision.models.mmdet.common.bbox.dataloaders import *
  File "/home/zuppif/integration-object-detection-icevision/.venv/lib/python3.9/site-packages/icevision/models/mmdet/common/bbox/dataloaders.py", line 10, in <module>
    from icevision.models.mmdet.common.utils import convert_background_from_zero_to_last
  File "/home/zuppif/integration-object-detection-icevision/.venv/lib/python3.9/site-packages/icevision/models/mmdet/common/utils.py", line 11, in <module>
    from mmdet.models import build_detector
  File "/home/zuppif/integration-object-detection-icevision/.venv/lib/python3.9/site-packages/mmdet/models/__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/home/zuppif/integration-object-detection-icevision/.venv/lib/python3.9/site-packages/mmdet/models/backbones/__init__.py", line 2, in <module>
    from .csp_darknet import CSPDarknet
  File "/home/zuppif/integration-object-detection-icevision/.venv/lib/python3.9/site-packages/mmdet/models/backbones/csp_darknet.py", line 11, in <module>
    from ..utils import CSPLayer
  File "/home/zuppif/integration-object-detection-icevision/.venv/lib/python3.9/site-packages/mmdet/models/utils/__init__.py", line 16, in <module>
    from .transformer import (DetrTransformerDecoder, DetrTransformerDecoderLayer,
  File "/home/zuppif/integration-object-detection-icevision/.venv/lib/python3.9/site-packages/mmdet/models/utils/transformer.py", line 29, in <module>
    from mmcv.cnn.bricks.transformer import MultiScaleDeformableAttention
ImportError: cannot import name 'MultiScaleDeformableAttention' from 'mmcv.cnn.bricks.transformer' (/home/zuppif/integration-object-detection-icevision/.venv/lib/python3.9/site-packages/mmcv/cnn/bricks/transformer.py)
```

**Reproduction**

Install mmcv-full using `mim` or 

```
pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu102/torch1.9.1/index.html
```

then try to use `vfnet`

**Environment**

1. Please run `python -c "from mmcv.utils import collect_env; print(collect_env())"` to collect necessary environment information \
It results in an error
```
 python -c "from mmcv.utils import collect_env; print(collect_env())"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/zuppif/integration-object-detection-icevision/.venv/lib/python3.9/site-packages/mmcv/utils/env.py", line 87, in collect_env
    from mmcv.ops import get_compiler_version, get_compiling_cuda_version
  File "/home/zuppif/integration-object-detection-icevision/.venv/lib/python3.9/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .ball_query import ball_query
  File "/home/zuppif/integration-object-detection-icevision/.venv/lib/python3.9/site-packages/mmcv/ops/ball_query.py", line 7, in <module>
    ext_module = ext_loader.load_ext('_ext', ['ball_query_forward'])
  File "/home/zuppif/integration-object-detection-icevision/.venv/lib/python3.9/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/zuppif/miniconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/zuppif/integration-object-detection-icevision/.venv/lib/python3.9/site-packages/mmcv/_ext.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor6deviceEv
```

**Comment by zhouzaida** [comment]
hi, @FrancescoSaverioZuppichini , in the latest version (v1.3.15), we provide pre-compiled packages for the Python 3.9 environment.
You can install the latest mmcv-full with the following command.
```bash
pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu102/torch1.9.0/index.html
```

**Comment by FrancescoSaverioZuppichini** [comment]
Thank you very much, I'll check this out

**Comment by DwightFoster** [comment]
Hello I am getting the same error. I used pip install mmcv-full==1.3.16 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.9.0/index.html, but it has not changed anything. The full error is 
`/opt/conda/lib/python3.7/site-packages/mmdet/models/utils/transformer.py:27: UserWarning: `MultiScaleDeformableAttention` in MMCV has been moved to `mmcv.ops.multi_scale_deform_attn`, please update your MMCV
  '`MultiScaleDeformableAttention` in MMCV has been moved to '
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/opt/conda/lib/python3.7/site-packages/mmdet/models/utils/transformer.py in <module>
     22 try:
---> 23     from mmcv.ops.multi_scale_deform_attn import MultiScaleDeformableAttention
     24 

/opt/conda/lib/python3.7/site-packages/mmcv/ops/__init__.py in <module>
      1 # Copyright (c) OpenMMLab. All rights reserved.
----> 2 from .assign_score_withk import assign_score_withk
      3 from .ball_query import ball_query

/opt/conda/lib/python3.7/site-packages/mmcv/ops/assign_score_withk.py in <module>
      5 ext_module = ext_loader.load_ext(
----> 6     '_ext', ['assign_score_withk_forward', 'assign_score_withk_backward'])
      7 

/opt/conda/lib/python3.7/site-packages/mmcv/utils/ext_loader.py in load_ext(name, funcs)
     12     def load_ext(name, funcs):
---> 13         ext = importlib.import_module('mmcv.' + name)
     14         for fun in funcs:

/opt/conda/lib/python3.7/importlib/__init__.py in import_module(name, package)
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 

ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-28-41321e113aac> in <module>
----> 1 from mmdet.models import build_detector
      2 from config import get_config
      3 from mmcv import Config, DictAction
      4 
      5 args = parse_args()

/opt/conda/lib/python3.7/site-packages/mmdet/models/__init__.py in <module>
      1 # Copyright (c) OpenMMLab. All rights reserved.
----> 2 from .backbones import *  # noqa: F401,F403
      3 from .builder import (BACKBONES, DETECTORS, HEADS, LOSSES, NECKS,
      4                       ROI_EXTRACTORS, SHARED_HEADS, build_backbone,
      5                       build_detector, build_head, build_loss, build_neck,

/opt/conda/lib/python3.7/site-packages/mmdet/models/backbones/__init__.py in <module>
      1 # Copyright (c) OpenMMLab. All rights reserved.
----> 2 from .csp_darknet import CSPDarknet
      3 from .darknet import Darknet
      4 from .detectors_resnet import DetectoRS_ResNet
      5 from .detectors_resnext import DetectoRS_ResNeXt

/opt/conda/lib/python3.7/site-packages/mmdet/models/backbones/csp_darknet.py in <module>
      9 
     10 from ..builder import BACKBONES
---> 11 from ..utils import CSPLayer
     12 
     13 

/opt/conda/lib/python3.7/site-packages/mmdet/models/utils/__init__.py in <module>
     14 from .res_layer import ResLayer, SimplifiedBasicBlock
     15 from .se_layer import SELayer
---> 16 from .transformer import (DetrTransformerDecoder, DetrTransformerDecoderLayer,
     17                           DynamicConv, PatchEmbed, Transformer, nchw_to_nlc,
     18                           nlc_to_nchw)

/opt/conda/lib/python3.7/site-packages/mmdet/models/utils/transformer.py in <module>
     27         '`MultiScaleDeformableAttention` in MMCV has been moved to '
     28         '`mmcv.ops.multi_scale_deform_attn`, please update your MMCV')
---> 29     from mmcv.cnn.bricks.transformer import MultiScaleDeformableAttention
     30 
     31 

ImportError: cannot import name 'MultiScaleDeformableAttention' from 'mmcv.cnn.bricks.transformer' (/opt/conda/lib/python3.7/site-packages/mmcv/cnn/bricks/transformer.py)`
I cannot seem to figure out why this error keeps coming back. The correct version is installed I checked it. Can anyone help?

**Comment by deepwilson** [comment]
Same issue. Looking forward to a solution!

**Comment by tabmoo** [comment]
Me too!

**Comment by amine0110** [comment]
Same thing here!

**Comment by zhouzaida** [comment]
Hi, what is your mmcv version?

**Comment by amine0110** [comment]
@zhouzaida it is 1.5 the same as mmcv-full

I checked if the paths and files are put in the right places, and everything is put without any problem!

And when I tried to do the import without the try statement, I got this:

ImportError: DLL load failed: The specified module could not be found.

**Comment by Matesanz** [comment]
The problem is that `ImportError` in [this line](https://github.dev/open-mmlab/mmcv/blob/7e6f4624954d62e6900c3927c7608785cb4a593f/mmcv/cnn/bricks/transformer.py#L32) in is **silently catching another exception rather than the "install mmcv-full" one.**

if you try the line that is raising the Error:

```python
from mmcv.ops.multi_scale_deform_attn import MultiScaleDeformableAttention
>>> ImportError: .../lib/python3.9/site-packages/mmcv/_ext.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor4add_ERKS0_RKN3c106ScalarE
```

:question: May it be related to the python version?
:question: May it be related to the related pytorch version?

:point_right: [Related question](https://stackoverflow.com/questions/67117097/c-cpython-38-x86-64-linux-gnu-so-undefined-symbol-zn6caffe28typemeta21-typem) in Stackoverflow

**Comment by zhaiqx** [comment]
> Hi, what is your mmcv version?

Same question. 

I test the mmcv==1.6.0, cu113, pytorch=1.9.0, and the same question when using the CPU version.

**Comment by ganesh3** [comment]
same question when I create a docker container with the below commands
RUN pip install mmcv-full==1.3.7 -f https://download.openmmlab.com/mmcv/dist/cu101/torch1.8.0/index.html -U
RUN pip install mmdet==2.13.0 -U
RUN pip install mmsegmentation==0.17.0 -U

**Comment by howardchina** [comment]
same question, why alway the same question?

terminal:
`python3 -m pip list | grep mmcv-full
mmcv-full                     1.7.0`

error:
"/home/data/programs/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/c
nn/bricks/transformer.py:33: UserWarning: Fail to import ``MultiScaleDeformableA
ttention`` from ``mmcv.ops.multi_scale_deform_attn``, You should install ``mmcv-
full`` if you need this module."

**Comment by AlistairMcCutcheon** [comment]
I am running pytorch 1.8 and cuda 11.1 in a docker container. 

I had the issue when running:
`RUN pip install openmim
RUN mim install mmcv-full`

However this version of mmcv-full fixed the issue:
`RUN pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.8.0/mmcv_full-1.7.1-cp39-cp39-manylinux1_x86_64.whl`

**Comment by anamazingclown** [comment]
I also had the issue when running my code. 

environment: 
`{torch：1.9.0
torchvision：0.10.0
mmcv-full==1.4.7
mmdet==2.20.0
GPU 0,1: NVIDIA GeForce RTX 4090,
CUDA Version: 12.1}
`
The way I installed mmcv-full on the anaconda virtual environment on the far server is:`pip install mmcv_full-1.4.7-cp37-cp37m-manylinux1_x86_64.whl`

**Comment by 18780165950** [comment]
Me too, does anyone solve this problem？

**Comment by Teassassin** [comment]
> Me too, does anyone solve this problem？

I've tried many ways and it can only be solved by installing official whl...
So, make sure your pytorch and cuda version is on the pre-built list.

https://mmcv.readthedocs.io/en/2.x/get_started/installation.html
![Image](https://github.com/user-attachments/assets/de1e495a-b12e-4edf-a585-e62a3f51be68)
