### ISSUE TITLE
Please support validation workflow for `IterBasedRunner`

### ISSUE THREAD

**Issue by jshilong** [open-mmlab/mmcv#1432]
Please refer to https://github.com/open-mmlab/mmdetection/issues/6357

I saw from the previous issues about putting val in the workflow section. 
```
workflow = [('train', 1), ('val', 1)]
```
But it seems like it only works for EpochBasedRunner. How do I do it with IterBasedRunner?

**Comment by zhouzaida** [comment]
Repeated with #1163

**Comment by Kegard** [comment]
Hello, I have use ` workflow = [('train', 1), ('val', 1)]` with IterBaseRunner but not work. I want to know the bug have been fixed? or how to use `EvalHook` to validate my datasets. Thank you for your reply.
