### ISSUE TITLE
`#warning` is not a portable/standard preprocessor and it produces a `C1021: invalid preprocessor command 'warning'` error when building with MSVC.

### ISSUE THREAD

**Issue by ZwwWayne** [open-mmlab/mmcv#1435]
`#warning` is not a portable/standard preprocessor and it produces a `C1021: invalid preprocessor command 'warning'` error when building with MSVC.

_Originally posted by @HolyWu in https://github.com/open-mmlab/mmcv/pull/1381#discussion_r735788810_

**Comment by zhouzaida** [comment]
We can refer to https://github.com/pytorch/pytorch/pull/20484 to use a portable way of the warning clause

**Comment by ZwwWayne** [comment]
Resolved in #1510
