### ISSUE TITLE
Can I use Adam optimizer together with FixedLrUpdaterHook?

### ISSUE THREAD

**Issue by goolhanrry** [open-mmlab/mmcv#144]
Hi! I'd like to use `mmcv.runner` in my project to do the babysitting during training. I want to use an Adam optimizer and warmup strategy, can I use a FixedLrUpdaterHook in `mmcv.runner` together with the Adam optimizer directly? It seems that FixedLrUpdaterHook will set the lr to the original one every epoch.

**Comment by liangyuandg** [comment]
I also get this question. How do I use adam optimizer within the mmcv framework?
