### ISSUE TITLE
About the value of `cur_im2col_step` in `mmcv/ops/deform_conv.py`

### ISSUE THREAD

**Issue by liqikai9** [open-mmlab/mmcv#1440]
Hi, thanks for your implementation of the `deform_conv` ops, which is a convenient API to use. But when I was trying to reproduce the similar DeformConv layer in [PoseWarper](https://github.com/facebookresearch/PoseWarper), I am confused about the value of the argument `im2col_step`. 

Here is the default value of the `im2col_step` in [PoseWarper](https://github.com/facebookresearch/PoseWarper): 

https://github.com/facebookresearch/PoseWarper/blob/43b1aa373d945abaf9e9a1f70953cc7411796a1a/lib/deform_conv/functions/deform_conv.py#L21

While in mmcv, the definition is:

https://github.com/open-mmlab/mmcv/blob/f9be3bc3336f00138b876de002477864810c5b29/mmcv/ops/deform_conv.py#L60

Which is used here:

https://github.com/open-mmlab/mmcv/blob/f9be3bc3336f00138b876de002477864810c5b29/mmcv/ops/deform_conv.py#L89-L91

My confusion is that, **what if my batch size is larger than 32, but can not be divided by 32**, e.g., **80** in PoseWarper (because it needs to contact five frames for each sample, so if the batch size is set to 16, the actual input size to the forward function of DeformConv will be 80), how can the forward be run normally? 

It seems that we can not assign the value of `im2col_step`  in the forward function of `DeformConv2d`:

https://github.com/open-mmlab/mmcv/blob/f9be3bc3336f00138b876de002477864810c5b29/mmcv/ops/deform_conv.py#L295-L296

So I was wondering how to deal with this situation. I am looking forward to your help.

**Comment by zhouzaida** [comment]
Hi, we can add a new argument `im2col_step` to `DeformConv2d`.

**Comment by liqikai9** [comment]
I have another question that, **what is the function of this value `im2col_step`**?  It seems that when I trained the model with **smaller** `im2col_step` value, it will get slightly **better** results.

**Comment by zhouzaida** [comment]
> I have another question that, **what is the function of this value `im2col_step`**? It seems that when I trained the model with **smaller** `im2col_step` value, it will get slightly **better** results.

The value should only affect the speed of the operator rather than performance.

**Comment by zhouzaida** [comment]
closed by # 1459

**Comment by liebeslied** [comment]
Hi,
I'm running into the error `batch size must be divisible by im2col_step`. My batch size IS divisible by `im2col_step`, but during the last training iteration, when the number of samples remaining is smaller than the batch size, there is a batch that isn't divisible by the `im2col_step`.

I'm using a batch size of 96 and the final batch has 34 samples (so not divisible by 32).

However, if I didn't run into this problem using a batch size of 16 -- the final batches then had size 2 and no error was thrown.

Is there a correct way to preserve the speed of training using `im2col_step` but also use a larger batch size (like 96 in my case) that leaves a remainder not divisible by 32? (Does this make sense?)

Thanks!

**Comment by YXB-NKU** [comment]
> Hi, I'm running into the error `batch size must be divisible by im2col_step`. My batch size IS divisible by `im2col_step`, but during the last training iteration, when the number of samples remaining is smaller than the batch size, there is a batch that isn't divisible by the `im2col_step`.
> 
> I'm using a batch size of 96 and the final batch has 34 samples (so not divisible by 32).
> 
> However, if I didn't run into this problem using a batch size of 16 -- the final batches then had size 2 and no error was thrown.
> 
> Is there a correct way to preserve the speed of training using `im2col_step` but also use a larger batch size (like 96 in my case) that leaves a remainder not divisible by 32? (Does this make sense?)
> 
> Thanks!

I have the same question , my batch size is 256, and it seems no problem in the training stage, but get error message in test stage

**Comment by YXB-NKU** [comment]
![image](https://github.com/open-mmlab/mmcv/assets/69071430/0bb779da-f413-4fbf-a15e-7bb76b66f815)
