### ISSUE TITLE
Generalize NumClassCheckHook to more mmcv libraries

### ISSUE THREAD

**Issue by elopezz** [open-mmlab/mmcv#1453]
**Describe the feature**
The `NumClassCheckHook` from mmdet library https://github.com/open-mmlab/mmdetection/blob/374d4c0bed3e3c01e2988213b54310500479e3df/mmdet/datasets/utils.py#L116 could be generalized for using it in other similar libraries (mmclassification, mmsegmentation) since this hook is very useful and it shouldn't depend in any mmdet specific implementation.

**Motivation**
It is convenient because it can prevent discrepancies between the dataset defined classes and the model `num_classes` values, this discrepancy can cause future errors that could be prevented using this hook.

**Comment by ZwwWayne** [comment]
This hook is specifically designed for MMDet. If you want to use it in misclassification/mmsegmentation, it is better to write a specific one because the number of channels and classification layers are not unified in those repos.

**Comment by elopezz** [comment]
Thank you for your response! I understand why it's dfficult to generalize it to the other libraries, could be feasible to implement the hook in the mmcls library only for the nets that use the same number of classes as in the dataset CLASSES variable?

I'm thinking about something like the trick used in the mmdet case: https://github.com/open-mmlab/mmdetection/blob/374d4c0bed3e3c01e2988213b54310500479e3df/mmdet/datasets/utils.py#L140-L141

**Comment by ZwwWayne** [comment]
> Thank you for your response! I understand why it's dfficult to generalize it to the other libraries, could be feasible to implement the hook in the mmcls library only for the nets that use the same number of classes as in the dataset CLASSES variable?
> 
> I'm thinking about something like the trick used in the mmdet case: https://github.com/open-mmlab/mmdetection/blob/374d4c0bed3e3c01e2988213b54310500479e3df/mmdet/datasets/utils.py#L140-L141

Yes, you can do that! Involve @mzr1996 to follow up on the progress in MMCls.

**Comment by ZwwWayne** [comment]
Since the issue has been answered. This issue will be closed. Feel free to create a new issue in MMCls if you have any questions when integrating the hook in MMCls
