### ISSUE TITLE
shape check of impad function

### ISSUE THREAD

**Issue by ShijieVVu** [open-mmlab/mmcv#148]
In this [line](https://github.com/open-mmlab/mmcv/blob/8829ff0dfd9b9c9484cbce17f5cecd1128b61723/mmcv/image/transforms/geometry.py#L182):
Instead of `for i in range(len(shape) - 1):
         assert shape[i] >= img.shape[i]`
Should it be
`for i in range(len(shape)):
        assert shape[i] >= img.shape[i]`
to ensure all input shape dimensions equal or less than pad shape?

**Comment by hellock** [comment]
Thanks for your report! Maybe adding `assert shape[-1] == img.shape[-1]` is better?
