### ISSUE TITLE
Plan to support other hardware than GPU

### ISSUE THREAD

**Issue by cissoidx** [open-mmlab/mmcv#1484]
Hello,

Thank you guys for execellent work. Do you have any plan to support other hardwares? Training or inferencing?
Like IPU/TPU ...

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the FAQ documentation but cannot get the expected help.

**Comment by zhouzaida** [comment]
Hi @cissoidx. We have a plan to support TPU, but it is not a high priority at this time. If you are interested, you can create a PR and we will handle it with high priority.

**Comment by cissoidx** [comment]
@zhouzaida Great. I am working for Graphcore, and we are using IPU to train neural network. We have supported tensorflow, pytorch and paddlepaddle to train and inference on our hardware. Our web: https://www.graphcore.ai/

Is it possible to PR support for Graphcore IPU to enrich the MMCV community?

Cheers,
xu

**Comment by zhouzaida** [comment]
Great, that's very good news. Would you like to create a PR to support it?

**Comment by cissoidx** [comment]
We are planning on this. Will keep you updated.

**Comment by zhouzaida** [comment]
Supported by #1882
