### ISSUE TITLE
Code for roi_align_forward and roi_align_backward at mmcv/ops/roi_align module

### ISSUE THREAD

**Issue by La-tale** [open-mmlab/mmcv#1486]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the FAQ documentation but cannot get the expected help.

Hi.
Thanks for sharing your great work!

I try to implement roi_align module in tensorflow, but there is no code for 'roi_align_forward' and 'roi_align_backward'.
Could you share code of 'roi_align_forward' and 'roi_align_backward' if you don't mind it?

Thank you!

**Comment by zhouzaida** [comment]
Hi @La-tale , what does `share code` mean here? The code can be found at https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/csrc/pytorch/roi_align.cpp.

**Comment by La-tale** [comment]
Oh I'm sorry, I don't know there is any cpp code and cuda code for it.

Thanks!!
