### ISSUE TITLE
cannot import name 'DeformConv' from mmcv.ops 

### ISSUE THREAD

**Issue by mandy0409** [open-mmlab/mmcv#1498]
Hello, I am using mmcv-full-1.3.17. 

I have an error that cannot import name 'DeformConv' from 'mmcv.ops'  

Could you help me with this issue?

**Comment by zhouzaida** [comment]
Hi @mandy0409 , `DeformConv2d` should be imported rather than `DeformConv`

https://github.com/open-mmlab/mmcv/blob/add157cc73b05c7be3d9b63505e17dc2288a6d0f/mmcv/ops/__init__.py#L12
