### ISSUE TITLE
[RFC] Support exporting to torchscript

### ISSUE THREAD

**Issue by zhiqwang** [open-mmlab/mmcv#1499]
**Describe the feature**

Add support for exporting the models released on mmlab to `torchscript`.

**Motivation**

1. The training framework currently used by `mmlab` is mainly `PyTorch`, so it would be relatively easy to export the model to `torchscript`.

1. If we can export the models to `torchscript`, it will be easy to deploy it with `libtorch`, we can also use more tools released by the `PyTorch` teams, such as `torchserve`.

1. Seems that `torchscript` is attracting more and more attention in industrial production environment. For example, we can find that some edge inference libraries such as `coreML`, `ncnn`, `TVM`, `TensorRT` and `MNN` have added or are adding support for exporting `torchscript` to their own IR models.

**Related resources**

- https://github.com/Tencent/ncnn/pull/3262
- https://github.com/alibaba/MNN/releases/tag/1.2.0
- http://github.com/NVIDIA/Torch-TensorRT
- https://github.com/apache/tvm/releases/tag/v0.8.0
- https://coremltools.readme.io/docs/pytorch-conversion
- https://github.com/pytorch/serve

**Comment by grimoire** [comment]
Thanks for the advice!
We are doing some technical verification about `torchscript`. And I believe it will be supported in future once we find a good way to integrate it in OpenMMLab.

**Comment by zhiqwang** [comment]
Close due to https://github.com/open-mmlab/mmdeploy/pull/159 , Thanks for this great enhancement!
