### ISSUE TITLE
AttributeError：'ConfigDit' object has no attribute 'nms'

### ISSUE THREAD

**Issue by Crush-yq** [open-mmlab/mmcv#1514]
I have installed many versions of mmcv-full and mmdetection, but I keep getting this error, when I lower the version of mmcv-full, it prompts me that the version is too low, please upgrade the version of mmcv-full, has anyone ever had this problem?
This problem has been bothering me for a long time, if you have a solution, please contact me, thanks!

**Comment by teamwong111** [comment]
Hi, @Crush-yq , thanks for your report. Please provide more details to help us solve the problem.
1. What command, code, or script did you run?

2. Did you make any modifications to the code? Did you understand what you have modified?

3. Please run `python -c "from mmcv.utils import collect_env; print(collect_env())"` to collect necessary environment information and paste it here.
4. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Comment by zhouzaida** [comment]
Hi @Crush-yq , it is a bc-breaking of mmdetection and you can upgrade the mmdetection to the newest version which will fix the error.

**Comment by Crush-yq** [comment]
Thank you very much for your explanation, I tried to update my mmaction2, mmcv-full, mmdetection all to the latest version and found that the problem was solved, thank you again!
