### ISSUE TITLE
The function of latest.pth generated by mmcv

### ISSUE THREAD

**Issue by qgh1223** [open-mmlab/mmcv#152]
What is the function of the latest.pth in mmdetection training generated by mmcv?It only cause trouble when training in colab.I cannot directly set work_dir in google drive path.It will cause os.symlink error.I can only change the source code to solve it.

**Comment by ash11sh** [comment]
you can ask this issue in mmdetection repo instead of here

**Comment by hellock** [comment]
It is the symlink to the latest checkpoint. It seems that colab does not support `os.symlink` and you can add an argument in the `checkpoint_cfg` field in config files, like `checkpoint_cfg=dict(create_symlink=False)`.
