### ISSUE TITLE
Face detection

### ISSUE THREAD

**Issue by dreamflasher** [open-mmlab/mmcv#1523]
**Describe the feature**
I'd love to do face detection with mmcv.

**Motivation**
Currently we use https://github.com/deepinsight/insightface/, but we already use other mmcv packages, so it would be quite awesome if you add face detection to your toolset. We know it's too much to ask, and you are probably already aware that there's demand for it. Nevertheless, maybe in the future someone might consider it.

**Comment by ZwwWayne** [comment]
Please create an issue in MMDet and PRs are welcomed.
