### ISSUE TITLE
weights_to_cpu() does not take None val into consideration

### ISSUE THREAD

**Issue by HongweiXie** [open-mmlab/mmcv#154]
In mmcv/runner/checkpoint.py line 192
def weights_to_cpu(state_dict):
    """Copy a model state_dict to cpu.

    Args:
        state_dict (OrderedDict): Model weights on GPU.

    Returns:
        OrderedDict: Model weights on GPU.
    """
    state_dict_cpu = OrderedDict()
    for key, val in state_dict.items():
        state_dict_cpu[key] = val.cpu()
    return state_dict_cpu

If val is None, this will raise an error

**Comment by hellock** [comment]
Thanks for your report. Could you tell in which case the state dict item will be None?
