### ISSUE TITLE
Resume function for the build process.

### ISSUE THREAD

**Issue by DingYuan0118** [open-mmlab/mmcv#1554]
**Describe the feature**
As we can see, build the mmcv-full locally will take ten to dozens of ten minutes. Most of the time was spent on the compilation for the `.cu` file and `.cpp` file. When the build failed, we must fix some config and run the build process from scratch, so it will waste a lot of time. I wander if we can save the successful built file and restart from the failed one, this will save plenty of time.

**Comment by zhouzaida** [comment]
Sorry for the late reply. What I have observed is that the compiled ops are skipped, but just to avoid unknown problems, we recommend that you delete the build and recompile.
