### ISSUE TITLE
NVIDIA GeForce RTX 3090 with CUDA capability sm_86 is not compatible with the current PyTorch installation

### ISSUE THREAD

**Issue by WindFantasy98** [open-mmlab/mmcv#1558]
some errors occur when I install mmcv-full, the full error are as follows:

  NVIDIA GeForce RTX 3090 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
  The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70 sm_75.
  If you want to use the NVIDIA GeForce RTX 3090 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

and my environment is :
ubuntu
RTX 3090
CUDA 10.1 (nvcc)

how to solve this problem?

**Comment by zhouzaida** [comment]
What is your PyTorch version and how do you install it?

**Comment by WindFantasy98** [comment]
> What is your PyTorch version and how do you install it?

I have tried torch 1.6+cu101 and torch 1.11.0.dev20211204+cu102 which all not work.

**Comment by zhouzaida** [comment]
According to the error you reported, you can use the following commands to install the correct PyTorch and mmcv-full.
```bash
conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch
pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.10.0/index.html
```

**Comment by zhouzaida** [comment]
Hi @WindFantasy98, is there any progress?

**Comment by RiikkaYang** [comment]
I had the same problem and had solved by taking@zhouzaida 's advice. Thanks a lot!

**Comment by xiang949876499** [comment]
@zhouzaida Can you help me solve this problem 

![Image](https://github.com/user-attachments/assets/ec28f713-996a-42c8-8821-4c5e629cc9bb)

![Image](https://github.com/user-attachments/assets/5a9e6bc5-c478-426e-bc98-3de1d0cf4db2)

![Image](https://github.com/user-attachments/assets/526bf4c5-3970-4a2b-aa5d-ab7de217a007)
