### ISSUE TITLE
Does mmcv support adjust_hue(), or some functions to change images' hue, similar to 'adjust_contrast' in mmcv.image.photometric?

### ISSUE THREAD

**Issue by shiyegao** [open-mmlab/mmcv#1568]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the FAQ documentation but cannot get the expected help.

**Comment by zhouzaida** [comment]
Hi @shiyegao, we did not provide the function, and if you are interested in it you can create a PR to support it.

https://pytorch.org/vision/main/_modules/torchvision/transforms/functional.html#adjust_hue

Of course, if you have no free time to do it, we will support it in the future.
