### ISSUE TITLE
fatal error: THC/THCDeviceUtils.cuh: No such file or directory    #include <THC/THCDeviceUtils.cuh>

### ISSUE THREAD

**Issue by jinfagang** [open-mmlab/mmcv#1582]
Since upcoming torch version will remove deprecated headers, does there any timeline to support this?

https://github.com/pytorch/pytorch/pull/65472

all these includes moved into ATen.

**Comment by grimoire** [comment]
Thanks for the notification. We will add it to the TODO list.

**Comment by zhouzaida** [comment]
Please @AllentDan have a look.

**Comment by zhouzaida** [comment]
Hi @jinfagang , thanks for your report. Could you provide the version of your PyTorch because I can successfully compile the mmcv-full with torch1.10.1.

**Comment by jinfagang** [comment]
@zhouzaida I forgot which version i tested, seems nightly version

**Comment by zhouzaida** [comment]
Got it. I will test it in the nightly version.

**Comment by zhouzaida** [comment]
I have reproduced a similar error that THC/THC.h can not be found in pre PyTorch1.11.0 so I create a PR to resolve the error.

**Comment by jinfagang** [comment]
@zhouzaida that would be nice. so that pytorch1.11 users won't have pain install mmcv on their decent machines.

**Comment by achaiah** [comment]
I can confirm that compilation fails with Pytorch 1.11.0. Is there any workaround for installing mmcv or are we out of luck?

**Comment by achaiah** [comment]
@zhouzaida It's the same error as above regarding THC header files. Your pull request  #1653 fixes it.

**Comment by zhouzaida** [comment]
> 

Got it.
