### ISSUE TITLE
How to build TensorRT plugins without using the TensorRT .tar file

### ISSUE THREAD

**Issue by BTVinh0409** [open-mmlab/mmcv#1583]
I have tried to build Mmcv with TensorRT plugins in Deepstream 6.0 (TensorRT version 8.0.1 installed). Can I build Mmcv with TensorRT plugins without using the TensorRT .tar file?

**Comment by zhouzaida** [comment]
Please @AllentDan have a look.

**Comment by AllentDan** [comment]
See [official installation](https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#installing)
