### ISSUE TITLE
print function does not work in hook

### ISSUE THREAD

**Issue by yanlongbinluck** [open-mmlab/mmcv#1584]
Hi, I encountered a strange thing. when I used ```print``` function in ```after_train_iter``` as follow, I found that the ```print``` can not be executed in training.  The mmcv version is 0.2.10
Why？
```
from torch.nn.utils import clip_grad
from .hook import Hook

class OptimizerHook(Hook):

    def __init__(self, grad_clip=None):
        self.grad_clip = grad_clip

    def clip_grads(self, params):
        clip_grad.clip_grad_norm_(
            filter(lambda p: p.requires_grad, params), **self.grad_clip)

    def after_train_iter(self, runner):

        print('backward processing')

        runner.optimizer.zero_grad()
        runner.outputs['loss'].backward()
        if self.grad_clip is not None:
            self.clip_grads(runner.model.parameters())
        runner.optimizer.step()
```

**Comment by zhouzaida** [comment]
Did you install mmcv with developing mode `pip install -e .`? Also, our latest version is 1.4.0, and 0.2 is a very early version. Could you tell us why still use 0.2?

**Comment by yanlongbinluck** [comment]
Thanks for your prompt reply.
I install mmcv by ```pip install mmcv==0.2.10```, and I edited the code under the installation path.
I also test in mmcv 1.3.8, it is ok.
The reason for using the 0.2 version is that I am more familiar with this version.
I still really want to know why the ```print``` function does not work there. Is it related to [this?](https://github.com/open-mmlab/mmcv/pull/1123)

**Comment by zhouzaida** [comment]
> Thanks for your prompt reply. I install mmcv by `pip install mmcv==0.2.10`, and I edited the code under the installation path. I also test in mmcv 1.3.8, it is ok. The reason for using the 0.2 version is that I am more familiar with this version. I still really want to know why the `print` function does not work there. Is it related to [this?](https://github.com/open-mmlab/mmcv/pull/1123)

It is not related to https://github.com/open-mmlab/mmcv/pull/1123. In fact, if you edited the code under the installation path, it should work. Maybe you can use the latest mmcv to enjoy power features.

**Comment by yanlongbinluck** [comment]
Thanks. I have soved it.
