### ISSUE TITLE
How to set DataContainer.data?

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmcv#1589]
Hi, dear authors!
Sorry to bother you. 
I want to set the `DataContainer(tensor([xxx, xxx]))` by `DataContainer.data = xxx`
like this:
```
A = DataContainer(tenso_1) # input by mmcv
A.data = tensor_2
```
but an Error came out:
```
AttributeError: can't set attribute
```
Could you tell me how do I solve it? (I want use the tensor_2 to instead of tensor_1)
Thank you!

**Comment by zhongqiu1245** [comment]
Code:
```
from mmcv.parallel import DataContainer as DC
import torch
tensor_1 = torch.tensor([3, 6, 9, 12, 15])
DC1 = DC(tensor_1, stack=True)
DC1.data = torch.tensor([30, 60, 90, 120, 150])
print(DC1.data)
```
Error:
```
Traceback (most recent call last):
  File "/media/gpuservice/DATA/Processing/Ubuntu/core/mmlab/mmdetection/my_tools/exp.py", line 63, in <module>
    DC1.data = torch.tensor([30, 60, 90, 120, 150])
AttributeError: can't set attribute
```

**Comment by zhouzaida** [comment]
Hi, the data is decorated by `@property` and it does not implement the `data.setter` so data can not be modified.
https://github.com/open-mmlab/mmcv/blob/e4b5348ebf407f0886bc11caa7ca74d2fbf693ac/mmcv/parallel/data_container.py#L56-L58
Why not create a new DataContainer object?

**Comment by zhongqiu1245** [comment]
> Hi, the data is decorated by `@property` and it does not implement the `data.setter` so data can not be modified.
> 
> https://github.com/open-mmlab/mmcv/blob/e4b5348ebf407f0886bc11caa7ca74d2fbf693ac/mmcv/parallel/data_container.py#L56-L58
> 
> Why not create a new DataContainer object?

great idea！thank you@

**Comment by cht619** [comment]
> > Hi, the data is decorated by `@property` and it does not implement the `data.setter` so data can not be modified.
> > https://github.com/open-mmlab/mmcv/blob/e4b5348ebf407f0886bc11caa7ca74d2fbf693ac/mmcv/parallel/data_container.py#L56-L58
> > 
> > Why not create a new DataContainer object?
> 
> great idea！thank you@

how to create a new DataContainer?
