### ISSUE TITLE
An error happen in mmcv compilation

### ISSUE THREAD

**Issue by EkAugust** [open-mmlab/mmcv#1593]
When I download mmcv source code and compile it, the following error happens.

> Obtaining file:///home/TangChiaHsin/code/det_TCH/mmdet_basic/mmcv
> Requirement already satisfied: addict in /home/lab517/anaconda3/envs/mmdet_basic_tjx/lib/python3.7/site-packages (from mmcv-full==1.4.1) (2.4.0)
> Requirement already satisfied: numpy in /home/lab517/anaconda3/envs/mmdet_basic_tjx/lib/python3.7/site-packages (from mmcv-full==1.4.1) (1.21.2)
> Requirement already satisfied: packaging in /home/lab517/anaconda3/envs/mmdet_basic_tjx/lib/python3.7/site-packages (from mmcv-full==1.4.1) (21.3)
> Requirement already satisfied: Pillow in /home/lab517/anaconda3/envs/mmdet_basic_tjx/lib/python3.7/site-packages (from mmcv-full==1.4.1) (8.4.0)
> Requirement already satisfied: pyyaml in /home/lab517/anaconda3/envs/mmdet_basic_tjx/lib/python3.7/site-packages (from mmcv-full==1.4.1) (6.0)
> Requirement already satisfied: yapf in /home/lab517/anaconda3/envs/mmdet_basic_tjx/lib/python3.7/site-packages (from mmcv-full==1.4.1) (0.31.0)
> Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /home/lab517/anaconda3/envs/mmdet_basic_tjx/lib/python3.7/site-packages (from packaging->mmcv-full==1.4.1) (3.0.6)
> Installing collected packages: mmcv-full
>   Running setup.py develop for mmcv-full
>     ERROR: Command errored out with exit status 1:
>      command: /home/lab517/anaconda3/envs/mmdet_basic_tjx/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/TangChiaHsin/code/det_TCH/mmdet_basic/mmcv/setup.py'"'"'; __file__='"'"'/home/TangChiaHsin/code/det_TCH/mmdet_basic/mmcv/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
>          cwd: /home/TangChiaHsin/code/det_TCH/mmdet_basic/mmcv/
>     Complete output (15 lines):
>     running develop
>     running egg_info
>     writing mmcv_full.egg-info/PKG-INFO
>     writing dependency_links to mmcv_full.egg-info/dependency_links.txt
>     writing requirements to mmcv_full.egg-info/requires.txt
>     writing top-level names to mmcv_full.egg-info/top_level.txt
>     reading manifest file 'mmcv_full.egg-info/SOURCES.txt'
>     reading manifest template 'MANIFEST.in'
>     adding license file 'LICENSE'
>     adding license file 'LICENSES.md'
>     writing manifest file 'mmcv_full.egg-info/SOURCES.txt'
>     running build_ext
>     /home/lab517/anaconda3/envs/mmdet_basic_tjx/lib/python3.7/site-packages/torch/utils/cpp_extension.py:381: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
>       warnings.warn(msg.format('we could not find ninja.'))
>     error: [Errno 2] No such file or directory: ':/usr/local/cuda-11.3:/usr/local/cuda-11.3:/usr/local/cuda-11.3/bin/nvcc': ':/usr/local/cuda-11.3:/usr/local/cuda-11.3:/usr/local/cuda-11.3/bin/nvcc'
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: /home/lab517/anaconda3/envs/mmdet_basic_tjx/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/TangChiaHsin/code/det_TCH/mmdet_basic/mmcv/setup.py'"'"'; __file__='"'"'/home/TangChiaHsin/code/det_TCH/mmdet_basic/mmcv/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

**Comment by zhouzaida** [comment]
`error: [Errno 2] No such file or directory: ':/usr/local/cuda-11.3:/usr/local/cuda-11.3:/usr/local/cuda-11.3/bin/nvcc': ':/usr/local/cuda-11.3:/usr/local/cuda-11.3:/usr/local/cuda-11.3/bin/nvcc'`
Hi @EkAugust , the config of your nvcc is not correct. Please check it again.

**Comment by EkAugust** [comment]
> `error: [Errno 2] No such file or directory: ':/usr/local/cuda-11.3:/usr/local/cuda-11.3:/usr/local/cuda-11.3/bin/nvcc': ':/usr/local/cuda-11.3:/usr/local/cuda-11.3:/usr/local/cuda-11.3/bin/nvcc'`
> Hi @EkAugust , the config of your nvcc is not correct. Please check it again.

Thanks for your reply.
I find the $PATH error. I delete the CUDA env path export and the error disappear.
I have exported CUDA env path manually before I compile mmcv. It seems that mmcv setup.py file will do it again.
