### ISSUE TITLE
ImportError: DLL load failed while importing _ext: The specified procedure could not be found.

### ISSUE THREAD

**Issue by gitgitgithut** [open-mmlab/mmcv#1594]
Hi there, I recently installed mmcv-full 1.4.1 and mmdet 2.19.1 using conda and openmim on my windows 10 device, and encountered an import error when running the following line:
`from mmdet.apis import init_detector, inference_detector, show_result_pyplot`
The error messages I got were:

![image](https://user-images.githubusercontent.com/11464880/146483861-0185a7af-1e45-4d9f-bbc7-f56e95ad1551.png)

I double checked the versions of my cudatoolkit, torch, mmcv-full and mmdet, and everything seems fine to me. I have pytorch==1.10.0, cudatoolkit==11.3.1, mmcv-full==1.4.1 and mmdet==2.19.1. 

I tried to reinstall mmcv-full to check I got the build version correctly, here's the result:
![image](https://user-images.githubusercontent.com/11464880/146485010-511e70ef-28d4-4353-b1e4-6ceb6f11004a.png)

Yet the same error messages were printed. I suspect it is still an compatibility issue between mmcv-full and mmdet, but i think I got the installation steps correct. Would you please help me with this issue? Thank you. 

The following are all the packages I have installed in my venv:
![image](https://user-images.githubusercontent.com/11464880/146484095-e7a1ac40-8fb3-4728-8cca-037e6b73c612.png)
![image](https://user-images.githubusercontent.com/11464880/146484116-2420f309-e20b-48e6-bc3d-5fda9107b4ea.png)
![image](https://user-images.githubusercontent.com/11464880/146484169-abd0a244-d851-4044-8ed2-11d9f9470947.png)
![image](https://user-images.githubusercontent.com/11464880/146484182-dec908ac-05d2-401f-9430-285fce41cf32.png)

**Comment by zhouzaida** [comment]
Hi, did you install mmcv (not mmcv-full) before? 

Note: Do not install both versions in the same environment, otherwise you may encounter errors like ModuleNotFound.

**Comment by gitgitgithut** [comment]
> Hi, did you install mmcv (not mmcv-full) before?
> 
> Note: Do not install both versions in the same environment, otherwise you may encounter errors like ModuleNotFound.

No, I have re-created my venv and I am certain that only mmcv-full is installed.

**Comment by del-zhenwu** [comment]
> > Hi, did you install mmcv (not mmcv-full) before?
> > Note: Do not install both versions in the same environment, otherwise you may encounter errors like ModuleNotFound.
> 
> No, I have re-created my venv and I am certain that only mmcv-full is installed.

I have uploaded the zip file for `mmdet2.19.1-mmcv1.4.1-torch1.10.0-py38`，would you give a try with installing the `whl file`?
[mmdet-2.19.1-py3-none-any.whl.zip](https://github.com/open-mmlab/mmcv/files/7742523/mmdet-2.19.1-py3-none-any.whl.zip)

**Comment by del-zhenwu** [comment]
@gitgitgithut This package has been proved OK in my env.
![image](https://user-images.githubusercontent.com/56623710/146711241-4fc0bf00-7ff2-478a-8df5-3a8df4b7131f.png)

**Comment by gitgitgithut** [comment]
> @gitgitgithut This package has been proved OK in my env. ![image](https://user-images.githubusercontent.com/56623710/146711241-4fc0bf00-7ff2-478a-8df5-3a8df4b7131f.png)

Hi there, I re-installed my venv using the .whl file you provided me, and the problem persists.
Here are my installation steps:
1. create a new conda venv with python==3.8.12
2. use pip to install mmdet from the wheel you provided me:
`pip install mmdet-2.19.1-py3-none-any.whl` 
3. use conda to install pytorch and cudatoolkits with:
`conda install pytorch==1.10.0 torchvision torchaudio cudatoolkit=11.3 -c pytorch`
4. use pip to install opencv-python-headless and openmim with:
`pip install opencv-python-headless openmim`
5. use openmim to install mmcv-full:
`mim install mmcv-full`

Here's the output of running the same code:
![image](https://user-images.githubusercontent.com/11464880/146736648-cdfb2b81-b840-425c-a016-8599d97aea51.png)

The following is the installed packages' info:
![image](https://user-images.githubusercontent.com/11464880/146737005-89224894-a541-4c1f-9471-38c3392bdd28.png)
![image](https://user-images.githubusercontent.com/11464880/146737040-437011c5-2fb9-4f60-abbb-4ef56e3b6738.png)

**Comment by gitgitgithut** [comment]
I just found out there are also some issues with mmcv:
![image](https://user-images.githubusercontent.com/11464880/146737814-72704408-54c7-4eae-89eb-1dbb340cc866.png)

**Comment by zhouzaida** [comment]
Hi @gitgitgithut , we have updated the pre-built packages of 1.4.1. Please have a try.

**Comment by gitgitgithut** [comment]
Hi @zhouzaida @del-zhenwu, I have reinstalled my venv with the updated mmcv-full 1.4.2, the issue is now resolved:
![image](https://user-images.githubusercontent.com/11464880/147529499-ec99732c-942a-4ede-9a3d-4cb43396c667.png)
Really appreciate your efforts, Thank you!

**Comment by HRADPICKUP** [comment]
That helps much!!

**Comment by duduzai2019** [comment]
I have reinstalled my venv with the updated mmcv-full 1.4.2, the issue is now resolved


> Hi @zhouzaida @del-zhenwu, I have reinstalled my venv with the updated mmcv-full 1.4.2, the issue is now resolved: ![image](https://user-images.githubusercontent.com/11464880/147529499-ec99732c-942a-4ede-9a3d-4cb43396c667.png) Really appreciate your efforts, Thank you!

hi, How can installI  mmcv-full 1.4.2 ??
Thanks!

**Comment by gitgitgithut** [comment]
Hi @duduzai2019, as the official [mmcv documentation](https://mmcv.readthedocs.io/en/latest/get_started/installation.html) stated, you can use pip to install a specific version of mmcv-full with `pip install mmcv-full=={mmcv_version} -f https://download.openmmlab.com/mmcv/dist/{cu_version}/{torch_version}/index.html`.
![image](https://user-images.githubusercontent.com/11464880/185358857-e9199a4c-e80a-462f-a419-798e54173f98.png)

**Comment by duduzai2019** [comment]
> 嗨，@duduzai2019，正如官方[mmcv文档](https://mmcv.readthedocs.io/en/latest/get_started/installation.html)所述，您可以使用pip安装特定版本的mmcv-full。`pip install mmcv-full=={mmcv_version} -f https://download.openmmlab.com/mmcv/dist/{cu_version}/{torch_version}/index.html` ![图像](https://user-images.githubusercontent.com/11464880/185358857-e9199a4c-e80a-462f-a419-798e54173f98.png)

Thank you for your answer, It has been replaced by mvcc 1.4.2 , but train.py is still an old proble
![image](https://user-images.githubusercontent.com/96464964/185367921-400d7a47-72b9-4d59-aa16-ed2f486ec3a1.png)
![image](https://user-images.githubusercontent.com/96464964/185368049-94c10c91-628e-4d78-896d-885bec02c077.png)

**Comment by aldazhu** [comment]
# hi
Encountered the same error in mmcv 2.0.0rc4 when attempting to install it using "pip install mmcv". However, I was able to resolve the issue by building mmcv from the source code。
gpu : quadro M4000
cuda: 11.6
CUDA Capability: 5.2
windows10
 The usage of 'build' can be referred to in this link：https://mmcv.readthedocs.io/en/latest/get_started/build.htmlUDA Capability: 5.2
windows10
 The usage of 'build' can be referred to in this link：https://mmcv.readthedocs.io/en/latest/get_started/build.html

**Comment by lsewcx** [comment]
已解决
原因可能使用pip安装
解决方法改用mim安装就成功了

**Comment by cybbbbbbb** [comment]
hi @gitgitgithut. I have the same problem as you, and it has been bothering me for three days. But I finally solved it now.

**Comment by vigneshwar1565** [comment]
Hi @cybbbbbbb , I'm facing the same issue.
I have installed mmcv - 2.0.0
when I do python demo/demo_skeleton.py demo.mp4 short_serve_out.mp4 --config slowonly_r50_8xb16-u48-240e_ntu60-xsub-keypoint,py --checkpoint slowonly_r50_8xb16-u48-240e_ntu60-xsub-keypoint_20220815-38db104b.pth --label-map tools/data/skeleton/label_map_ntu60.txt
Im getting ImportError: DLL load failed while importing _ext: The specified procedure could not be found.

**Comment by vigneshwar1565** [comment]
> Hi [@cybbbbbbb](https://github.com/cybbbbbbb) , I'm facing the same issue. I have installed mmcv - 2.0.0 when I do python demo/demo_skeleton.py demo.mp4 short_serve_out.mp4 --config slowonly_r50_8xb16-u48-240e_ntu60-xsub-keypoint,py --checkpoint slowonly_r50_8xb16-u48-240e_ntu60-xsub-keypoint_20220815-38db104b.pth --label-map tools/data/skeleton/label_map_ntu60.txt Im getting ImportError: DLL load failed while importing _ext: The specified procedure could not be found.

I was able to fix it by downgrading my pytorch to 2.0.0
pip install torch==2.0.0 torchvision==0.15.1 torchaudio==2.0.1 --index-url https://download.pytorch.org/whl/cu118
