### ISSUE TITLE
HSigmoid default parameter not aligned with Offical Pytorch

### ISSUE THREAD

**Issue by Bo396543018** [open-mmlab/mmcv#1604]
When I convert model to align mmdet's style, I found the default parameter(bias=1.0, divisor=2.0, min_value=0.0, max_value=1.0) for HSigmoid implemented in mmcv  is not aligned with pytorch, which may cause some inconsistency.
Align the default setting may avoid this problem.

**Comment by teamwong111** [comment]
Hi @Bo396543018 , thank you for your advice. Are you willing to create a PR to fix it?
