### ISSUE TITLE
image rescale_size function

### ISSUE THREAD

**Issue by jacqueline-weng** [open-mmlab/mmcv#1614]
I found an implementation of image rescaling probably inappropriate while resizing image to scale that has different width and height.

mmcv/image/geometric.py
line 204-208
![1E4E3BB7-C1D5-48AF-8A03-3E28BF593B7C](https://user-images.githubusercontent.com/62649623/147376706-f6daf2fa-1d5a-494c-abdf-c3f2fed37827.png)
To preserve the width-height ratio, the scale for edge should be calculated correspondingly.
For example, if I wish to rescale an image with shape (1388, 1024) to (480, 640), with the current code it would give a result image of (640, 472) instead of (480, 354). The longest edge of old scale may not be the longest edge in new scale.

I suggest it could change to
![image](https://user-images.githubusercontent.com/62649623/147376928-c881cc04-a080-4f19-a77b-0cb8f1bd47a1.png)

**Comment by zhouzaida** [comment]
The aim of the `rescale_size` is to rescale the image as large as possible within the scale.

https://github.com/open-mmlab/mmcv/blob/e1d6ea8c8706a8515782a026bde8e845930640da/mmcv/image/geometric.py#L230-L233

**Comment by jacqueline-weng** [comment]
> The aim of the `rescale_size` is to rescale the image as large as possible within the scale.
> 
> https://github.com/open-mmlab/mmcv/blob/e1d6ea8c8706a8515782a026bde8e845930640da/mmcv/image/geometric.py#L230-L233

I got what you attempt to do but it causes trouble frequently when dealing with a batch of images. It may not be very reasonable to have different output scales with a uniform input.

**Comment by ZwwWayne** [comment]
The function of imrescale is different from imresize.
imrescale is usually used in mmdetection to rescale the image to a scale retio, which is a convention in object detection. imresize can resize/rescale the image to the exact shape. 
Therefore, if you want to rescale an image with shape (1388, 1024) to (480, 640), you should use imresize to exactly resize the image shape from (1388, 1024) to (480, 640).

**Comment by Charlyo** [comment]
@ZwwWayne it seems we are missing a method to be able to resize them image whilst maintining the input aspect ratio of such. Then padding could be added to ensure the output images stay consistent in the batch.

**Comment by imyhxy** [comment]
It's better to have a `Resize` and a `Rescale` class.
