### ISSUE TITLE
mmcv 1.14.2 windows pre-built package doesnt exist for cuda11.3, torch1.10.0, python3.9

### ISSUE THREAD

**Issue by fcakyon** [open-mmlab/mmcv#1615]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmcv.readthedocs.io/en/latest/trouble_shooting.html) but cannot get the expected help.
3. The unexpected results still exist in the latest version.

**Describe the Issue**
mmcv 1.14.2 windows pre-built package doesnt exist for cuda11.3, torch1.10.0, python3.9: https://download.openmmlab.com/mmcv/dist/cu113/torch1.10.0/index.html

`Everything is fine with mmcv 1.14.1`

**Reproduction**

1. What command, code, or script did you run?

```bash
conda install pytorch=1.10.0 torchvision=0.11.1 cudatoolkit=11.3 -c pytorch
```

```bash
pip install mmcv-full==1.4.2 -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.10.0/index.html
```

2. Did you make any modifications on the code? Did you understand what you have modified?

No

**Environment**

windows10, python3.9 (miniconda), cudatoolkit11.3, rtx3060,

**Comment by zhouzaida** [comment]
Hi @fcakyon , thanks for your feedback. We will provide the pre-built packages for cu113 in the next two days and you can temporarily install the 1.4.1 now.

**Comment by fcakyon** [comment]
@zhouzaida thanks a lot for the feedback!

**Comment by zhouzaida** [comment]
Hi, we have uploaded the pre-built packages for cu113.
