### ISSUE TITLE
dist.reduce throws RuntimeError: Tensors must be CUDA and dense

### ISSUE THREAD

**Issue by adizhol** [open-mmlab/mmcv#1618]
Hi,

I'm trying to use MMDistributedDataParallel on a single node with multiple GPUS.
When the text logger hook is called, the output_device in `_get_max_memory` is 'None' [mmcv/runner/hooks/logger/text.py:110], causing mem_mb to be on the cpu, and dist.reduce() in line 116 to throw a `RuntimeError ("Tensors must be CUDA and dense")`.

I wrap my model with MMDistributedDataParallel like this:
`MMDistributedDataParallel(model.cuda(), find_unused_parameters=True)`

Where should output_device be set? According to pytorch documentation, it should be None when using DDP.

> For multi-device modules and CPU modules,
                   ``device_ids`` must be ``None``.

Environment:
mmcv-full 1.4.2 (reproduced also in 1.2.0)
pytorch 1.1.10
CUDA 11.3
devices are 2 RTX 3080s

Thanks

**Comment by adizhol** [comment]
update:
After checking the MMDetection project, I saw you set device_ids to torch.cuda.get_current_device(), and this also solved the problem (although I'm not sure which gpu memory is being printed).

Not sure if to close this issue...

**Comment by zhouzaida** [comment]
Hi @adizhol , thanks for your report. 
I checked the API of [torch.cuda.max_memory_allocated](https://pytorch.org/docs/stable/generated/torch.cuda.max_memory_allocated.html#torch.cuda.max_memory_allocated) and it seems like that it  will return statistic for the current device given by `current_device()` when the `_get_max_memory` is `None`.
Could you provide some steps to reproduce the error which will be helpful for me to figure out the error why it happened.
