### ISSUE TITLE
Questions on optimizer registering

### ISSUE THREAD

**Issue by DianCh** [open-mmlab/mmcv#1624]
Hi! I'm trying to understand the code and how Pytorch optimizers are integrated is a bit unclear to me. Specifically, are the existing optimizers the native ones from Pytorch? Where in the code are those added to `OPTIMIZERS` registry (I didn't find relevant code under `mmcv/runner/optimizer/`)?

Thank you!

**Comment by zhouzaida** [comment]
Hi, details can be found at `mmcv/runner/optimizer/builder.py`.
https://github.com/open-mmlab/mmcv/blob/e1d6ea8c8706a8515782a026bde8e845930640da/mmcv/runner/optimizer/builder.py#L13-L26

**Comment by DianCh** [comment]
Thank you!
