### ISSUE TITLE
`initialize_buckets` must NOT be called during autograd execution.

### ISSUE THREAD

**Issue by tigert1998** [open-mmlab/mmcv#1631]
Thanks for reporting the unexpected results and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmcv.readthedocs.io/en/latest/trouble_shooting.html) but cannot get the expected help.
3. The unexpected results still exist in the latest version.

**Describe the Issue**
A clear and concise description of what the bug is, including what results are expected and what the real results you got.

**Reproduction**

1. What command, code, or script did you run?

```bash
A placeholder for the command.
```

2. Did you make any modifications on the code? Did you understand what you have modified?

**Environment**

1. Please run `python -c "from mmcv.utils import collect_env; print(collect_env())"` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error traceback here.

```none
A placeholder for traceback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

```
-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/data/data5/v-xiaohutang/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/v-xiaohutang/madness/train.py", line 50, in _single_process_train
    train(model, work_dir, lr, lr_updater_hook,
  File "/home/v-xiaohutang/madness/train.py", line 104, in train
    runner.run(
  File "/data/data5/v-xiaohutang/anaconda3/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/data/data5/v-xiaohutang/anaconda3/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/data/data5/v-xiaohutang/anaconda3/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 29, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "/data/data5/v-xiaohutang/anaconda3/lib/python3.9/site-packages/mmcv/parallel/distributed.py", line 42, in train_step
    and self.reducer._rebuild_buckets()):
RuntimeError: `initialize_buckets` must NOT be called during autograd execution.
```

I am using pytorch 1.10.1 and mmcv 1.4.1. It seems that MMDistributedDataParallel breaks.

**Comment by zhouzaida** [comment]
Thanks for your report. We will check it.

**Comment by zhouzaida** [comment]
Hi @tigert1998 , I can not reproduce the error with pytorch1.10.1 and mmcv 1.4.1. Could you provide some steps to reproduce the error?

**Comment by tigert1998** [comment]
Sorry I have already gave up using mmcv in my project and have used the native apis instead.

**Comment by huang-hz** [comment]
> Hi @tigert1998 , I can not reproduce the error with pytorch1.10.1 and mmcv 1.4.1. Could you provide some steps to reproduce the error?

I have found the same problem when i set the find_unused_parameters from True to False.
