### ISSUE TITLE
How to modify nms?

### ISSUE THREAD

**Issue by missyoudaisy** [open-mmlab/mmcv#1635]
I want to add a fumula in nms algorithm, but when I refer to nms.py,  i find that it uses "extmodule.nms()", so where can i find the source code of nms ?

**Comment by missyoudaisy** [comment]
I want to add a fumula in nms algorithm, but when I refer to nms.py,  i find that it uses "extmodule.nms()", so where can i find the source code of nms ?

**Comment by teamwong111** [comment]
The MMCV `nms` is written in CPP or CUDA. 
CPP version is [here](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/csrc/pytorch/cpu/nms.cpp). 
CUDA version is [here](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/csrc/pytorch/cuda/nms_cuda.cu) and [here](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/csrc/common/cuda/nms_cuda_kernel.cuh)

**Comment by missyoudaisy** [comment]
> The MMCV `nms` is written in CPP or CUDA. CPP version is [here](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/csrc/pytorch/cpu/nms.cpp). CUDA version is [here](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/csrc/pytorch/cuda/nms_cuda.cu) and [here](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/csrc/common/cuda/nms_cuda_kernel.cuh)

ok, thx , i will have a try~

**Comment by missyoudaisy** [comment]
@teamwong111  sorry to disturb you. After the modification, do i need to recompile the mmcv?

**Comment by teamwong111** [comment]
Yes, you can recompile mmcv according to [this doc](https://mmcv.readthedocs.io/en/latest/get_started/build.html).

**Comment by missyoudaisy** [comment]
> Yes, you can recompile mmcv according to [this doc](https://mmcv.readthedocs.io/en/latest/get_started/build.html).

thank u so much~
