### ISSUE TITLE
_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _Z30pyramid_deformable_im2col_cudaN2at6TensorES0_iiiiiiiiiiiiiffiiS0_

### ISSUE THREAD

**Issue by crazysboy** [open-mmlab/mmcv#1636]
mmcv 作者你好，我在你代码上添加了一种新的pyramid_deformable_im2col卷积结构，mmcv显示安装成功，测试时报出_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: 30pyramid_deformable_im2col_cudaN2at6TensorES0_iiiiiiiiiiiiiffiiS0_错误，请问怎么解决，不太明白为啥显示没有定义。

**Comment by zhouzaida** [comment]
请问有绑定么 https://github.com/open-mmlab/mmcv/blob/d30e37d4d57425843bbff484e7e7a1e41230381f/mmcv/ops/csrc/pytorch/pybind.cpp#L366

**Comment by crazysboy** [comment]
m.def("pyramid_deform_conv_forward", &pyramid_deform_conv_forward, "pyramid_deform_conv_forward",
        py::arg("input"), py::arg("weight"), py::arg("offset"),
        py::arg("output"), py::arg("columns"), py::arg("ones"), py::arg("kW"),
        py::arg("kH"), py::arg("dW"), py::arg("dH"), py::arg("padH"),
        py::arg("padW"), py::arg("dilationW"), py::arg("dilationH"),py::arg("scaleW"), py::arg("scaleH"),
        py::arg("group"), py::arg("deformable_group"), py::arg("im2col_step")); 我绑定了是这个名字，不对吗

**Comment by zhouzaida** [comment]
你好，可以对照 https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/csrc/README.md 检查一下，也可以提交 PR 我们帮忙检查一下

**Comment by crazysboy** [comment]
好的

**Comment by zhouzaida** [comment]
你好，问题解决了么

**Comment by crazysboy** [comment]
你好我已经上传到PR了详见add pyramid_deform_conv to mmcv.op #1647

**Comment by zhouzaida** [comment]
好的，我们会检查一下

**Comment by zhouzaida** [comment]
问题已解决
