### ISSUE TITLE
ImportError: DLL load failed: 找不到指定的程序。

### ISSUE THREAD

**Issue by wantaoliu** [open-mmlab/mmcv#1644]
> Traceback (most recent call last):
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "D:\DetectionFrame\20211224mmdetection\mmdet\apis\__init__.py", line 1, in <module>
>     from .inference import (async_inference_detector, inference_detector,
>   File "D:\DetectionFrame\20211224mmdetection\mmdet\apis\inference.py", line 11, in <module>
>     from mmdet.datasets import replace_ImageToTensor
>   File "D:\DetectionFrame\20211224mmdetection\mmdet\datasets\__init__.py", line 2, in <module>
>     from .cityscapes import CityscapesDataset
>   File "D:\DetectionFrame\20211224mmdetection\mmdet\datasets\cityscapes.py", line 16, in <module>
>     from .coco import CocoDataset
>   File "D:\DetectionFrame\20211224mmdetection\mmdet\datasets\coco.py", line 16, in <module>
>     from .custom import CustomDataset
>   File "D:\DetectionFrame\20211224mmdetection\mmdet\datasets\custom.py", line 13, in <module>
>     from .pipelines import Compose
>   File "D:\DetectionFrame\20211224mmdetection\mmdet\datasets\pipelines\__init__.py", line 9, in <module>
>     from .loading import (LoadAnnotations, LoadImageFromFile, LoadImageFromWebcam,
>   File "D:\DetectionFrame\20211224mmdetection\mmdet\datasets\pipelines\loading.py", line 8, in <module>
>     from tools.utilRS import readTif
>   File "D:\DetectionFrame\20211224mmdetection\tools\utilRS.py", line 3, in <module>
>     from osgeo import gdal, ogr
>   File "C:\Users\dell\anaconda3\envs\open-mmlab\lib\site-packages\osgeo\__init__.py", line 21, in <module>
>     _gdal = swig_import_helper()
>   File "C:\Users\dell\anaconda3\envs\open-mmlab\lib\site-packages\osgeo\__init__.py", line 17, in swig_import_helper
>     _mod = imp.load_module('_gdal', fp, pathname, description)
>   File "C:\Users\dell\anaconda3\envs\open-mmlab\lib\imp.py", line 242, in load_module
>     return load_dynamic(name, filename, file)
>   File "C:\Users\dell\anaconda3\envs\open-mmlab\lib\imp.py", line 342, in load_dynamic
>     return _load(spec)
> ImportError: DLL load failed: 找不到指定的程序。
> python-BaseException
> 
> Process finished with exit code 1

I import gdal package,but it is not load the package about gdal,Could you tell me how to solve the problem.

**Comment by zhouzaida** [comment]
Hi, you can report the issue at [mmdetection](https://github.com/open-mmlab/mmdetection/issues)
