### ISSUE TITLE
install mmcv error

### ISSUE THREAD

**Issue by chenggangdu** [open-mmlab/mmcv#165]
compilation terminated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for mmcv
  Running setup.py clean for mmcv
Failed to build mmcv
Installing collected packages: mmcv
    Running setup.py install for mmcv ... error
......
 compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/duchenggang/anaconda3/envs/mmdetection/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/duchenggang/pip-install-n8w_cvv4/mmcv/setup.py'"'"'; __file__='"'"'/home/duchenggang/pip-install-n8w_cvv4/mmcv/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /home/duchenggang/pip-record-c70xg8yw/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

Does anyone know how to solve this problem?

**Comment by linerhome** [comment]
也许你可以用 sudo加命令试试安装 mmcv 

还可以试试环境变量export

**Comment by chenggangdu** [comment]
@linerhome 我用的服务器是公共的，没有权限使用sudo加命令，请问export环境变量是干什么用？
我觉得是这一句出了问题：‘./mmcv/video/optflow_warp/flow_warp.cpp:75:1: fatal error: error writing to /tmp/ccbzacB7.s: No space left on device’，然后我百度到说我的tmp的空间不足，接下来就不知道怎么弄了

**Comment by chenggangdu** [comment]
@linerhome 谢谢你，安装成功了，原因是系统的tmp目录的空间不足，需要在用户目录下新建tmp目录，然后将用户的临时文件存放目录改成新建的tmp目录，例如用户名为 aaa，
新建tmp目录：mkdir /home/aaa/tmp
更改临时文件存放目录：export TMPDIR=/home/aaa/tmp
然后再按照步骤安装即可安装成功

**Comment by daizhenyu** [comment]
c:\users\win10\anaconda3\envs\mytorch\lib\site-packages\torch\utils\cpp_extension.py:270: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
    warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
  building 'mmcv._flow_warp_ext' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for mmcv
  Running setup.py clean for mmcv
Failed to build mmcv
Installing collected packages: mmcv
    Running setup.py install for mmcv ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\win10\anaconda3\envs\mytorch\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\win10\\AppData\\Local\\Temp\\pip-install-wtk7hy79\\mmcv\\setup.py'"'"'; __file__='"'"'C:\\Users\\win10\\AppData\\Local\\Temp\\pip-install-wtk7hy79\\mmcv\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\win10\AppData\Local\Temp\pip-record-s579xap3\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\win10\anaconda3\envs\mytorch\Include\mmcv'
         cwd: C:\Users\win10\AppData\Local\Temp\pip-install-wtk7hy79\mmcv\

What should i do? Please help me
