### ISSUE TITLE
Pretrained models (.pth) don't have ['meta']['epoch'] and ['meta']['iter']

### ISSUE THREAD

**Issue by bladrome** [open-mmlab/mmcv#1671]
**Describe the Issue**
```
/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 363, in resume
    self._epoch = checkpoint['meta']['epoch']
KeyError: 'epoch'
```
**Reproduction**
```
python tools/train.py \
    configs/any_config.conf  \
    --resume-from somepth
```
Finetune pretrained model.

**Bug fix**
https://github.com/open-mmlab/mmcv/blob/86ed509a8bc783cdd0617efeba257375d5aa6658/mmcv/runner/base_runner.py#L363-L364

The above codes ought to be checked

**Comment by zhouzaida** [comment]
Yet, you can refer to https://github.com/open-mmlab/mmdetection/blob/ff9bc39913cb3ff5dde79d3933add7dc2561bab7/configs/retinanet/retinanet_r101_caffe_fpn_1x_coco.py#L6 to load the pretrained models

**Comment by bladrome** [comment]
Yes, but not all model has `init_cfg` , such as:

https://github.com/open-mmlab/mmpose/blob/0376d51efdd93b3c8f3338211130753fed808bb9/mmpose/models/detectors/top_down.py#L24

**Comment by zhouzaida** [comment]
https://github.com/open-mmlab/mmpose/blob/0376d51efdd93b3c8f3338211130753fed808bb9/mmpose/models/detectors/top_down.py#L32
It has a paramter `pretrained`.

**Comment by bladrome** [comment]
@zhouzaida Thanks for your kindness help.
