### ISSUE TITLE
why mmcv.cvt2frames rotate the frames?

### ISSUE THREAD

**Issue by kinredon** [open-mmlab/mmcv#1672]
I am using `mmcv.cvt2frames` to convert the video to frames, but the converted frames are rotated.

The video likes this:
![image](https://user-images.githubusercontent.com/39270545/149653916-07d987d5-3b94-4f21-8ac2-3a16acb34bea.png)
but the generated frames like this:
![image](https://user-images.githubusercontent.com/39270545/149653930-6cc5e8e0-54ef-4578-92d9-161b7bd06633.png)
Obviously, it is rotated by 90 degrees, why did this happen?

The code is shown below:
```
import mmcv

video_path = './b4542860-40cc6d5a.mov'
v = mmcv.VideoReader(video_path)
print(len(v))

v.cvt2frames("./bdd_100k_frames_test")

```
Anyone can give me some suggestions? Thanks!

**Comment by HAOCHENYE** [comment]
Hi, can you supply the converted video? I cannot reproduce the rotated frames with local .mov  video and the same code.

**Comment by kinredon** [comment]
@HAOCHENYE Thanks for your reply, I solved this problem. The reason is the .mov video file has some meta information (e.g. rotate). If I view the video using a player (MacOs quick player or VLC), the player will recognize the meta information and automatically handle it. Unfortunately, OpenCV or many video processing libraries usually just ignore meta information and only read the pure video data. This makes the problem happen. 

I provide a solution below:
  
1) First we can use `ffpmeg` to convert .mov to .mp4 `ffmpeg -i source.mov dest.mp4`

2) Then use the video process lib to extract the frames.

**Comment by HAOCHENYE** [comment]
Thanks for your feedback. Could you please supply your .mov video file, maybe we can fix this bug.

**Comment by kinredon** [comment]
@HAOCHENYE I uploaded the .mov video file [here](https://drive.google.com/file/d/1DuEEflFR22EzF0fNUkd1QiiIkbDrNJzl/view?usp=sharing), if the bug has been fixed, please let me know, thanks a lot.

**Comment by HAOCHENYE** [comment]
Your video can be converted correctly in my device(Ubuntu16.04 opencv 4.5.5.65), what's your opencv version?  It seems this error is caused by opencv version.

**Comment by kinredon** [comment]
I use OpenCV 4.2.0.34 in macOS. And I tested the video on ubuntu and using OpenCV 4.5.5.62, the results are correct.

**Comment by HAOCHENYE** [comment]
@kinredon OpenCV 4.2.0.34 in macOS will get wrong video width and heigh. I've test Opencv4.5.x in macOS will convert .mov video correctly

**Comment by kinredon** [comment]
Thanks for your reply!
