### ISSUE TITLE
can not pip install mmcv

### ISSUE THREAD

**Issue by zhaojingru408** [open-mmlab/mmcv#168]
![1](https://user-images.githubusercontent.com/56055695/71825236-6262d400-30d6-11ea-94c5-53ecd511df21.png)
![2](https://user-images.githubusercontent.com/56055695/71825244-67278800-30d6-11ea-94b4-f582f850719c.png)

wish for help

**Comment by hellock** [comment]
Could you show the outputs of `pip list`?

**Comment by zhaojingru408** [comment]
I have solved the problem，thank you. this's because of gcc's version.

**Comment by swagglian** [comment]
> 我已经解决了问题，谢谢。这是因为gcc
I also meet the error.and can you tell me how do you solve the problem
