### ISSUE TITLE
mmcv nms exported onnx inference error

### ISSUE THREAD

**Issue by jinfagang** [open-mmlab/mmcv#1689]
```
onnxruntime/capi/onnxruntime_inference_collection.py", line 192, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running ReduceMax node. Name:'ReduceMax_382' Status Message: /Users/runner/work/1/s/onnxruntime/core/providers/cpu/reduction/reduction_ops.cc:747 void onnxruntime::ValidateKeepDims(const onnxruntime::TensorShape &, int64_t) keepdims was false. Can't reduce on dim with value of 0 if 'keepdims' is false. Invalid output shape would be produced. input_shape:{0,4}
```

this error caused by:

```
 nms_cfg_ = nms_cfg.copy()
    class_agnostic = nms_cfg_.pop('class_agnostic', class_agnostic)
    if class_agnostic:
        boxes_for_nms = boxes
    else:
        max_coordinate = boxes.max()
        offsets = idxs.to(boxes) * (max_coordinate + torch.tensor(1).to(boxes))
        boxes_for_nms = boxes + offsets[:, None]
```

which boxes might be empty.

this might happen when:

- image don't have any object, and after score thresh, the boxes send to NMS is empty;
- users using random input tensor input, the NMS failed to run since no boxes input.

I want solution on:

- how to avoid this?
- how to make mmcv nms op handle this?

**Comment by AllentDan** [comment]
Hi, @jinfagang. All deployment related codes will be deprecated in the future and deployment would be supported in [mmdeploy](https://github.com/open-mmlab/mmdeploy)

**Comment by grimoire** [comment]
You can pad some dummy boxes with zero scores after NMS to avoid errors on reduction ops.
And if you want to fix it in mmcv, you can update the symbolic in https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/nms.py.

Again, we have start a new project [MMDeploy](https://github.com/open-mmlab/mmdeploy) with more repos and engines support. Any advices and PRs are welcome.

**Comment by jinfagang** [comment]
@grimoire Am deploy some customized models, not standard mmdet model. I just want export it to onnx, and bake the nms operation into model.

this step can handled very well in torchvision.ops.batched_nms, but in mmcv's nms op got some unexpected behavior.

this error isn't happend after nms, it's before nms.  And is not problem of symbolic maybe, it's some judgement code in mmcv breaks.

Anyway, this **only happened if user want export nms op and for some certain model**, normal detection model should works fine since they still can get boxes with a higher score threshold.
