### ISSUE TITLE
Save best according to validation loss

### ISSUE THREAD

**Issue by makifozkanoglu** [open-mmlab/mmcv#1701]
Is there anyway to save weights based on the best validation loss instead of evaluation metrics
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the FAQ documentation but cannot get the expected help.

**Comment by zhouzaida** [comment]
Hi @makifozkanoglu , you can use the [EvalHook](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/evaluation.py#L33) by setting `save_best = 'loss'`. In addition, you need to ensure the `test_fn` will return the loss.

**Comment by makifozkanoglu** [comment]
Hi

How do i feed custom test_fn, is it possible change from config files instead of implementing custom eval function

**Comment by makifozkanoglu** [comment]
On the others my expectation is saving the best weight according to both validation metric and validation loss not one of them. Is it possible?

**Comment by zhouzaida** [comment]
> On the others my expectation is saving the best weight according to both validation metric and validation loss not one of them. Is it possible?

It is not possible, because metric and loss are not necessarily optimal at the same epoch or iteration.

**Comment by zhouzaida** [comment]
> Hi
> 
> How do i feed custom test_fn, is it possible change from config files instead of implementing custom eval function

Which repo do you use?

**Comment by makifozkanoglu** [comment]
> > On the others my expectation is saving the best weight according to both validation metric and validation loss not one of them. Is it possible?
> 
> It is not possible, because metric and loss are not necessarily optimal at the same epoch or iteration.

I think it should depend on user decision, are you welcome for that contribution

**Comment by makifozkanoglu** [comment]
> > Hi
> > How do i feed custom test_fn, is it possible change from config files instead of implementing custom eval function
> 
> Which repo do you use?

More clearly, do we have to create our own evaluation hook inherited from base evalhook? Is this the single way?

**Comment by makifozkanoglu** [comment]
My repository is based on https://github.com/microsoft/SoftTeacher

**Comment by zhouzaida** [comment]
> > > Hi
> > > How do i feed custom test_fn, is it possible change from config files instead of implementing custom eval function
> > 
> > 
> > Which repo do you use?
> 
> More clearly, do we have to create our own evaluation hook inherited from base evalhook? Is this the single way?

Yet, you need to inherit from base evalhook and you can refer to https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/evaluation/eval_hooks.py.
