### ISSUE TITLE
Config object to .py file

### ISSUE THREAD

**Issue by dnth** [open-mmlab/mmcv#1722]
**Checklist**

1. I have searched related issues but cannot get the expected help. Yes
2. I have read the FAQ documentation but cannot get the expected help. Yes

How do I export a Config object to a .py file?

**Comment by teamwong111** [comment]
Hi, you can export a Config object to .py file using `dump` function. More details can be found at https://github.com/open-mmlab/mmcv/blob/master/mmcv/utils/config.py#L537 and https://github.com/open-mmlab/mmcv/blob/master/tests/test_utils/test_config.py#L30.

**Comment by dnth** [comment]
I tried with the dump function but encountered the following error

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [38], in <module>
----> 1 model.cfg.dump()

File ~/anaconda3/envs/icevision-contrib/lib/python3.8/site-packages/mmcv/utils/config.py:536, in Config.dump(self, file)
    534 def dump(self, file=None):
    535     cfg_dict = super(Config, self).__getattribute__('_cfg_dict').to_dict()
--> 536     if self.filename.endswith('.py'):
    537         if file is None:
    538             return self.pretty_text

AttributeError: 'PosixPath' object has no attribute 'endswith'
```

**Comment by teamwong111** [comment]
`endswith` is a str object function. `filename` parameter in Config should be a str.

**Comment by teamwong111** [comment]
It is a bug, we will fix it ASAP.

**Comment by dnth** [comment]
Thanks!

**Comment by jmercat** [comment]
I'm having a similar bug that the given fix will not solve:
In my case I wanted to do a deep copy of a config so I did:
```
copy_config = mmcv.Config(copy.deepcopy(config))
copy_config.dump("test.py")
```
It would be the same thing with any initialization of config from a dict....

In that case, filename is not defined and the dump function throws an error. I don't think checking the extension of the filename that the config is loaded from makes sense... why would dump ever need to know from which file it was loaded, it only needs to know to which type of file it is writing...

I propose changing line 539 of config.py
from:
```
if self.filename.endswith('.py'):
```
to:
```
if file and file.endswith('.py'):
```

**Comment by Mollylulu** [comment]
there are np.ndarray params in my config.py, directly calling `dump` causes yapf error, could you provide an appropriate solution to handle such a case <i.e., save this config.py> ? thanks!
