### ISSUE TITLE
mmcv-full with torch 1.x.2 version

### ISSUE THREAD

**Issue by ilankap** [open-mmlab/mmcv#1727]
I've noticed that the only supported torch version according to the documentation are 1.x.0 and that 1.x.1 are supposed to work with the correlating versions.

I wanted to check if its possible to use torch 1.10.2 with the 1.10.0 installation or must I change my torch version to 1.10.0/1.10.1?

**Comment by zhouzaida** [comment]
Hi, you can have a try in torch1.10.2 and we will test it tomorrow.

**Comment by teamwong111** [comment]
I have tested it. It's no problem.
