### ISSUE TITLE
get error 'Default process group has not been initialized' when running mmaction2's demo tutorial 

### ISSUE THREAD

**Issue by poem2018** [open-mmlab/mmcv#1728]
Hi, when I run the '**Train a new recognizer**' part in mmaction2's demo tutorial (link: [https://github.com/open-mmlab/mmaction2/blob/master/demo/mmaction2_tutorial.ipynb](url)
It stopped at 10 epoch,  and I got an error: `RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.` ,
I wonder what might cause this problem, and how can I fix this problem? 

I use the PyTorch 1.10.0+cu113, Cuda 11.2 (I use the remote GPU platform which initially installed PyTorch itself)

![image](https://user-images.githubusercontent.com/40330318/154407983-1e0c99e8-1ce6-4b5a-b615-9937c6fd7622.png)
![image](https://user-images.githubusercontent.com/40330318/154408220-540d8490-423c-4186-9202-430c4576b532.png)

**Comment by poem2018** [comment]
some other package version
![image](https://user-images.githubusercontent.com/40330318/154408866-6d0dbd2b-b49b-4ded-a9eb-aaf6ddcd3cfc.png)

**Comment by teamwong111** [comment]
Hi, it seems a bug in mmaction2. [dist.barrier()](https://github.com/open-mmlab/mmaction2/blob/master/mmaction/apis/train.py#L206) should work only when `distributed=True`. You can open an issue in mmaction2 to seek help.

**Comment by poem2018** [comment]
> Hi, it seems a bug in mmaction2. [dist.barrier()](https://github.com/open-mmlab/mmaction2/blob/master/mmaction/apis/train.py#L206) should work only when `distributed=True`. You can open an issue in mmaction2 to seek help.

thanks, I will open an issue in that git.

**Comment by zhouzaida** [comment]
The error will be resolved by https://github.com/open-mmlab/mmaction2/pull/1459
