### ISSUE TITLE
install error on mac os

### ISSUE THREAD

**Issue by vernonsong** [open-mmlab/mmcv#1729]
在m1 mac环境下使用CC=clang CXX=clang++ CFLAGS='-stdlib=libc++' MMCV_WITH_OPS=1 pip install -e .进行安装，遇到如下错误

    
ERROR: Command errored out with exit status 1:
     command: /Users/vernon/miniforge3/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/vernon/Downloads/mmcv-master/setup.py'"'"'; __file__='"'"'/Users/vernon/Downloads/mmcv-master/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /Users/vernon/Downloads/mmcv-master/
    Complete output (90 lines):
    Compiling mmcv._ext without CUDA
    running develop
    running egg_info
    creating mmcv_full.egg-info
    writing mmcv_full.egg-info/PKG-INFO
    writing dependency_links to mmcv_full.egg-info/dependency_links.txt
    writing requirements to mmcv_full.egg-info/requires.txt
    writing top-level names to mmcv_full.egg-info/top_level.txt
    writing manifest file 'mmcv_full.egg-info/SOURCES.txt'
    reading manifest file 'mmcv_full.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    adding license file 'LICENSE'
    adding license file 'LICENSES.md'
    writing manifest file 'mmcv_full.egg-info/SOURCES.txt'
    running build_ext
    building 'mmcv._ext' extension
    creating /Users/vernon/Downloads/mmcv-master/build
    creating /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9
    creating /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/mmcv
    creating /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/mmcv/ops
    creating /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/mmcv/ops/csrc
    creating /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/mmcv/ops/csrc/pytorch
    creating /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/mmcv/ops/csrc/pytorch/cpu
    Emitting ninja build file /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/build.ninja...
    Compiling objects...
    Using envvar MAX_JOBS (4) as the number of workers...
    1.10.2
    creating build/lib.macosx-11.0-arm64-3.9
    creating build/lib.macosx-11.0-arm64-3.9/mmcv
    clang++ -bundle -undefined dynamic_lookup -Wl,-rpath,/Users/vernon/miniforge3/lib -L/Users/vernon/miniforge3/lib -Wl,-rpath,/Users/vernon/miniforge3/lib -L/Users/vernon/miniforge3/lib -stdlib=libc++ -arch arm64 /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/active_rotated_filter.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/assign_score_withk.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/ball_query.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/bbox_overlaps.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/border_align.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/box_iou_rotated.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/carafe.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/carafe_naive.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/contour_expand.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/convex_iou.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/corner_pool.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/correlation.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/cpu/active_rotated_filter.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/cpu/box_iou_rotated.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/cpu/deform_conv.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/cpu/modulated_deform_conv.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/cpu/nms.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/cpu/nms_rotated.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/cpu/pixel_group.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/cpu/points_in_boxes.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/cpu/psamask.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/cpu/roi_align.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/cpu/roi_align_rotated.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/cpu/voxelization.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/deform_conv.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/deform_roi_pool.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/focal_loss.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/furthest_point_sample.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/fused_bias_leakyrelu.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/gather_points.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/group_points.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/info.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/iou3d.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/knn.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/masked_conv2d.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/min_area_polygons.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/modulated_deform_conv.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/ms_deform_attn.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/nms.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/nms_rotated.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/pixel_group.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/points_in_boxes.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/points_in_polygons.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/psamask.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/pybind.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/riroi_align_rotated.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/roi_align.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/roi_align_rotated.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/roi_pool.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/roiaware_pool3d.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/roipoint_pool3d.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/rotated_feature_align.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/scatter_points.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/sync_bn.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/three_interpolate.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/three_nn.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/tin_shift.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/upfirdn2d.o /Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/voxelization.o -L/Users/vernon/miniforge3/lib/python3.9/site-packages/torch/lib -lc10 -ltorch -ltorch_cpu -ltorch_python -o build/lib.macosx-11.0-arm64-3.9/mmcv/_ext.cpython-39-darwin.so
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/active_rotated_filter.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/assign_score_withk.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/ball_query.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/bbox_overlaps.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/border_align.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/box_iou_rotated.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/carafe.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/carafe_naive.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/contour_expand.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/convex_iou.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/corner_pool.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/correlation.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/cpu/active_rotated_filter.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/cpu/box_iou_rotated.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/cpu/deform_conv.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/cpu/modulated_deform_conv.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/cpu/nms.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/cpu/nms_rotated.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/cpu/pixel_group.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/cpu/points_in_boxes.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/cpu/psamask.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/cpu/roi_align.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/cpu/roi_align_rotated.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/cpu/voxelization.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/deform_conv.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/deform_roi_pool.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/focal_loss.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/furthest_point_sample.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/fused_bias_leakyrelu.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/gather_points.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/group_points.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/info.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/iou3d.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/knn.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/masked_conv2d.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/min_area_polygons.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/modulated_deform_conv.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/ms_deform_attn.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/nms.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/nms_rotated.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/pixel_group.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/points_in_boxes.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/points_in_polygons.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/psamask.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/pybind.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/riroi_align_rotated.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/roi_align.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/roi_align_rotated.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/roi_pool.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/roiaware_pool3d.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/roipoint_pool3d.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/rotated_feature_align.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/scatter_points.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/sync_bn.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/three_interpolate.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/three_nn.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/tin_shift.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/upfirdn2d.o'
    clang: error: no such file or directory: '/Users/vernon/Downloads/mmcv-master/build/temp.macosx-11.0-arm64-3.9/./mmcv/ops/csrc/pytorch/voxelization.o'
    error: command '/usr/bin/clang++' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/vernon/miniforge3/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/vernon/Downloads/mmcv-master/setup.py'"'"'; __file__='"'"'/Users/vernon/Downloads/mmcv-master/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

**Comment by zhouzaida** [comment]
Hi @VernonSong , thanks for your report. We will try to reproduce the error.
