### ISSUE TITLE
undefined symbol: _ZNK2at6Tensor7is_cudaEv

### ISSUE THREAD

**Issue by haofanwang** [open-mmlab/mmcv#1734]
How to reproduce:
`from mmseg.models import build_segmentor`

Error message: 
`/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor7is_cudaEv`

Environment preparation:
```
conda install pytorch==1.10.0 torchvisio cudatoolkit=11.3 -c pytorch -c conda-forge
pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.10.0/index.html
pip install mmsegmentation
```

It seems that there exists version conflict between mmcv and pytorch. If I install pytorch==1.8.0 and mmcv-full (cu111/torch1.8.0), the command above goes well. By the way, my CUDA Version: 11.0.

**Comment by zhouzaida** [comment]
Hi, thanks for your report. I am sorry that I can not reproduce the error. It works well in my environment which is the same as you provided.

**Comment by garyhsu29** [comment]
Same error while running the tutorial on colab :(

**Comment by zhouzaida** [comment]
> 

Could you provide the full log?

**Comment by garyhsu29** [comment]
Hi @zhouzaida : 
Thanks for the reply.
I fount out that in the colab tutorial:

```
# Install PyTorch
!conda install pytorch=1.10.0 torchvision cudatoolkit=11.1 -c pytorch
# Install MMCV
!pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu101/torch1.6/index.html
```

The cuda and pytorch version doesn't match, after I update the installation link to
`
!pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.10/index.html
`
it works perfectly!

Thanks for your awesome work!
