### ISSUE TITLE
How to compile from the source code to the specified version

### ISSUE THREAD

**Issue by PhDCJojo** [open-mmlab/mmcv#1740]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the FAQ documentation but cannot get the expected help.

**Comment by zhouzaida** [comment]
Hi, you can checkout out to a specified version with `git checkout` like `git checkout v1.4.3`.

**Comment by PhDCJojo** [comment]
> Hi, you can checkout out to a specified version with `git checkout` like `git checkout v1.4.3`.

Thank you for your help. But I'm not familiar with the git operation.  Could you please provide me with a more detailed process? like, Inputting the following commands in the terminal.
(1) git clone https://github.com/open-mmlab/mmcv.git
(2) cd mmcv
(3) git init
(4) git checkout v1.4.3.
Best wishes.

**Comment by zhouzaida** [comment]
(1) git clone https://github.com/open-mmlab/mmcv.git
(2) cd mmcv
(3) git checkout v1.4.3
(4) steps to compile mmcv or mmcv-full. https://mmcv.readthedocs.io/en/latest/get_started/build.html
