### ISSUE TITLE
instalation of mmcv dependencies overrides current instalation of opencv

### ISSUE THREAD

**Issue by Lunatik00** [open-mmlab/mmcv#1749]
The issue is that when a version of opencv is already installed, if it is not specifically opencv-python, the requisites install it, opencv can be opencv, opencv, contrib and their headless version, so, there is a problem with the requirements when using pip install or mim install (it happens with both).

This problem is not limited to mmcv but it also happens in other version, in fact, if you install mmcv-full, mmdet and mmocr you will end up with 2 opencv versions (mmcv-full installs opencv and mmocr installs opencv-headless), this is a problem because when multiple versions are installed there can be different errors due to mismatched versions and because i need to compile opencv for other reasons

the solution should be simple, just fix the requirements to take this into account

Edit: i am just reinstalling mmocr with the no cache option to recompile, it installs both opencv and opencv-headless i get that the non headless version could be necessary, but the headless is the same with a few features removed, and the contrib version has all the regular version has plus extra features.

**Comment by zhouzaida** [comment]
Hi @Lunatik00 , thanks for your report. In fact, if `opencv` has been installed in your environment, mmcv should skip the installation of opencv again.
https://github.com/open-mmlab/mmcv/blob/a0127e1712cd58b22736d20ed4e5531e1d277f5e/setup.py#L119-L131

**Comment by KostadinovShalon** [comment]
Hi,  I faced the same issue. It seems that the problem is coming from mmengine. I had to build mmengine from source to avoid that building mmcv overrides my opencv installation.

**Comment by matanPercepto** [comment]
Hi , I am facing now the same problem when installing mmcv 1.7.0 in docker- I already have opencv-contrib-python installed, but it still install opencv-python, and it creates clashes when trying to call them. any solution that doesn't require building mmcv from source?

**Comment by bhack** [comment]
Can we reopen this? As it is still a problem.

**Comment by Erotemic** [comment]
I agree this is still a problem. I would also like to point out issues and PRs I made awhile back that works to resolve the issue, but they haven't gotten attention in awhile:

#### Issue
https://github.com/open-mmlab/mmengine/issues/1196

#### PRs

https://github.com/open-mmlab/mmcv/pull/2775
https://github.com/open-mmlab/mmengine/pull/1195
