### ISSUE TITLE
“utils/spconv/spconv/geometry.h”: No such file or directory

### ISSUE THREAD

**Issue by lzed2399** [open-mmlab/mmcv#1752]
I use this command to install mmcv-full
`pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu102/torch1.9.0/index.html`
and find this problem
` ./mmcv/ops/csrc/pytorch/cpu\sparse_indice.cpp(16): fatal error C1083: 无法打开包括文件: “utils/spconv/spconv/geometry.h”: No such file or directory`
` error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2`
When I install in win10 and Linux both meet this problem.
Thanks for replying!

**Comment by yangrisheng** [comment]
libboost-filesystem-dev
libboost-dev

try to install those wheel to fix .

**Comment by yangrisheng** [comment]
> I use this command to install mmcv-full `pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu102/torch1.9.0/index.html` and find this problem ` ./mmcv/ops/csrc/pytorch/cpu\sparse_indice.cpp(16): fatal error C1083: 无法打开包括文件: “utils/spconv/spconv/geometry.h”: No such file or directory` ` error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2` When I install in win10 and Linux both meet this problem. Thanks for replying!

libboost-filesystem-dev
libboost-dev

try to install those wheel to fix.

**Comment by lzed2399** [comment]
> libboost-filesystem-dev libboost-dev
> 
> try to install those wheel to fix.

win10 seems cannot install above wheels, how can I solve this problem?
In fact, I used to install successfully mmcv-full and use a long time. because of version not match, I have to install a new mmcv version, than I meet this problem

**Comment by yangrisheng** [comment]
> > libboost-filesystem-dev libboost-dev
> > try to install those wheel to fix.
> 
> win10 seems cannot install above wheels, how can I solve this problem? In fact, I used to install successfully mmcv-full and use a long time. because of version not match, I have to install a new mmcv version, than I meet this problem

error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX86\\x64\\cl.exe' failed with exit status
it seems this error is about vc++ version.I think it is beacause your vs version is too old.

**Comment by lzed2399** [comment]
I have install successfully just now,  use the original command and not change anything.
its so strange and even not need to compile, just takes a few seconds

**Comment by zhouzaida** [comment]
Hi, thanks for your report. What version of mmcv-full did you install?

**Comment by ParlamLiao** [comment]
still having this problem. And using win10 system. need help...

**Comment by abhineet123** [comment]
This seems to be caused by the new version 1.4.6 of mmcv so using an older version should fix it. This worked for me: 
`pip install mmcv-full==1.3.9 -f https://download.openmmlab.com/mmcv/dist/cu102/torch1.9.0/index.html`
Something a bit newer like 1.4.2 should work too.

**Comment by opteroncx** [comment]
MacOS 12.2.1, same problem

**Comment by wangruohui** [comment]
Me on macOS too. 
I think the solution should be adding correcponding header files (spconv related ones for 3D detection) in MENIFEST.in, so that they can be included in the sdist package published to pypi. 

Currently a workaround is to install MMCV from source, which is a git clone instead of a direct `pip install`.

**Comment by teamwong111** [comment]
Can we publish binary distribution to PyPI to avoid `MENIFEST.in` trouble?
