### ISSUE TITLE
The Registryclass cannot instantiate Paddle BatchNorm2d

### ISSUE THREAD

**Issue by zgq91** [open-mmlab/mmcv#1771]
import paddle.nn as nn
from mmcv.utils import Registry

NORM_LAYERS = Registry('norm layer')
NORM_LAYERS.register_module('BN2d', module=nn.BatchNorm2d)

error:

AttributeError: module 'paddle.nn' has no attribute 'BatchNorm2d'

**Comment by teamwong111** [comment]
nn.BatchNorm2d --> nn.BatchNorm2D
