### ISSUE TITLE
can not pip install mmcv/mmcv-full

### ISSUE THREAD

**Issue by LiuJiaji1999** [open-mmlab/mmcv#1779]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the FAQ documentation but cannot get the expected help.3. 

 ubuntu环境下 cuda11.1+pytorch1.10
error:WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fbc2d7ea590&gt;: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /compute/redist/mmcv/

**Comment by HAOCHENYE** [comment]
It seems that your pip connection error, can you download other packages via pip?  Maybe you can try to close your proxy.

**Comment by LiuJiaji1999** [comment]
pip can install other packages, I changed all the mirror sources and the same error was prompted

**Comment by imabackstabber** [comment]
@LiuJiaji1999 Can you show the command you use?so that we can assure whether it's due to Network problem or not.

**Comment by LiuJiaji1999** [comment]
![IMG_7538](https://user-images.githubusercontent.com/52843642/157379966-70e9015b-7d97-406f-87bc-856899e1e0d2.jpeg)

**Comment by LiuJiaji1999** [comment]
I have used  pip install mmcv.  pip install mmcv-full.    pip install mmcv -i 所有镜像源 ![IMG_7539](https://user-images.githubusercontent.com/52843642/157380288-0f3c97aa-47ef-4be5-88b9-c383778334f5.png)

**Comment by imabackstabber** [comment]
the corresponding command
```bash
pip install mmcv-full==1.3.9 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.10.0/index.html
```
works fine on my ubuntu,maybe reset your proxy?

**Comment by LiuJiaji1999** [comment]
The current practice is using the server of the enterprise. How can I view and reset the proxy?

**Comment by zhouzaida** [comment]
Sorry for the late reply. Could you try to `ping baidu.com`?
