### ISSUE TITLE
install mmcv-full  error  ：error: command 'g++' failed with exit status 1

### ISSUE THREAD

**Issue by clin-fu** [open-mmlab/mmcv#1782]
The following error message is displayed when mMCV-Full is installed  ：
  g++: error: /tmp/pip-install-n45b0a7u/mmcv-full_cdba712495754c0f9365268e02cb6d80/build/temp.linux-x86_64-3.7/./mmcv/ops/csrc/pytorch/cuda/box_iou_rotated_cuda.o: No such file or directory
      g++: error: /tmp/pip-install-n45b0a7u/mmcv-full_cdba712495754c0f9365268e02cb6d80/build/temp.linux-x86_64-3.7/./mmcv/ops/csrc/pytorch/cuda/cudabind.o: No such file or directory
      error: command 'g++' failed with exit status 1

and my cuda version = 10.1
             pytorch version=1.7.0

**Comment by imabackstabber** [comment]
looks like compiler,i.e. g++ hasn't find .o file ,probably due to the unsuccessful build of mmcv code,which only offers cuda file to be built to make .o file.Maybe check if [build of mmcv](https://mmcv.readthedocs.io/en/latest/get_started/build.html) is successful?

**Comment by clin-fu** [comment]
> looks like compiler,i.e. g++ hasn't find .o file ,probably due to the unsuccessful build of mmcv code,which only offers cuda file to be built to make .o file.Maybe check if [build of mmcv](https://mmcv.readthedocs.io/en/latest/get_started/build.html) is successful?


I can easily install MMCV, but the above error occurs when I install MMCV-Full.I have tried this command 'pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu101/torch1.7.0/index.html'  many times on different Versions of PyTorch, including changing the environment, and the above error still exists.

**Comment by clin-fu** [comment]
I can easily install MMCV, but the above error occurs when I install MMCV-Full.I have tried this command 'pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu101/torch1.7.0/index.html' many times on different Versions of PyTorch, including changing the environment, and the above error still exists.

**Comment by clin-fu** [comment]
A more detailed error message is attached：


error: command 'g++' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/fuchenlin/anaconda3/envs/mmr/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-d6_17zib/mmcv-full_8b3355c8540b4491af08e3c6a524afb2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-d6_17zib/mmcv-full_8b3355c8540b4491af08e3c6a524afb2/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-c_qre251/install-record.txt --single-version-externally-managed --compile --install-headers /home/fuchenlin/anaconda3/envs/mmr/include/python3.7m/mmcv-full Check the logs for full command output.

**Comment by imabackstabber** [comment]
looks like your error message is chunked,but i got a similiar closed issue here for reference,you can resort to:[g++ error #1371](https://github.com/open-mmlab/mmcv/issues/1371),maybe this can help

**Comment by HaronCHou** [comment]
https://blog.csdn.net/fq9200/article/details/125362088

**解决这个问题：要将编译选项里面的use_ninja给禁用掉，就可以成功编译出.o文件了**

![image](https://github.com/open-mmlab/mmcv/assets/22512646/f790556b-41bf-4598-9925-f5c0fc41915c)
