### ISSUE TITLE
pip install mmcv-full fail

### ISSUE THREAD

**Issue by makaaay** [open-mmlab/mmcv#1785]
Hello,

i met the compile error in mac cpu situation when i do "pip install mmcv-full"
[errorLog.txt](https://github.com/open-mmlab/mmcv/files/8213326/errorLog.txt)
it looks like something miss in "maxpooling.h"

what should I do to fix this compile error?

**Comment by imabackstabber** [comment]
Maybe try [git clone and build the code](https://mmcv.readthedocs.io/en/latest/get_started/build.html)?

**Comment by makaaay** [comment]
> Maybe try [git clone and build the code](https://mmcv.readthedocs.io/en/latest/get_started/build.html)?

Thanks for your reply.

1. i try to build the source code in torch1.7+cuda10.1 ，but it also has the compile error, build fail.

this is the error log:
[errorLog.txt](https://github.com/open-mmlab/mmcv/files/8215025/errorLog.txt)

**Comment by zhouzaida** [comment]
Hi, thanks for your report. Could you try to install `mmcv-full` with pre-built packages by `pip install mmcv-full -f -f https://download.openmmlab.com/mmcv/dist/cu101/torch1.7.0/index.html`.

**Comment by styler00dollar** [comment]
Can confirm that `pip install mmcv-full` does not work currently. I use the TensorRT docker image from Nvidia `(nvcr.io/nvidia/tensorrt:21.12-py3)` and it was working a while back. Now it always just crashes my build.
![image](https://user-images.githubusercontent.com/51405565/158025028-59ca6f83-a633-4ac9-b543-90d22ca3d989.png)
I tried to download v1.4.6 and manually run pip install there, and it works. The pip package needs to be fixed.

Workaround install:
```
ENV MMCV_WITH_OPS=1
RUN wget https://github.com/open-mmlab/mmcv/archive/refs/tags/v1.4.6.zip && 7z x v1.4.6.zip && cd mmcv-1.4.6 && MMCV_WITH_OPS=1 pip install -e .
```

**Comment by Agito555** [comment]
> Hi, thanks for your report. Could you try to install `mmcv-full` with pre-built packages by `pip install mmcv-full -f -f https://download.openmmlab.com/mmcv/dist/cu101/torch1.7.0/index.html`.

Hello,I have met the question mentioned in the link https://github.com/open-mmlab/mmcv/issues/1318, and i have tried to follow the instructions in the link,but failed.  I notice that the instruction advises us to download the software Visual Studio 2019, but it can not be downloaded now. And the cuda11.0 is not compatiable with the newest Visual Studio2022. I wonder whether it is the problem and how can i do to fix the problem?

**Comment by imabackstabber** [comment]
> > Hi, thanks for your report. Could you try to install `mmcv-full` with pre-built packages by `pip install mmcv-full -f -f https://download.openmmlab.com/mmcv/dist/cu101/torch1.7.0/index.html`.
> 
> Hello,I have met the question mentioned in the link #1318, and i have tried to follow the instructions in the link,but failed. I notice that the instruction advises us to download the software Visual Studio 2019, but it can not be downloaded now. And the cuda11.0 is not compatiable with the newest Visual Studio2022. I wonder whether it is the problem and how can i do to fix the problem?

I read the issue you mentioned,now mmcv support downloading pre-built package for windows,I'm not sure if you tried the proper way to download pre-built package.Looks like you have cuda11.0 installed,so maybe try 
```
pip install mmcv-full=={mmcv_version} -f https://download.openmmlab.com/mmcv/dist/cu110/torch1.7.0/index.html
```
