### ISSUE TITLE
Cannot install in Windows 10

### ISSUE THREAD

**Issue by nishavarghese15** [open-mmlab/mmcv#1787]
![image](https://user-images.githubusercontent.com/93310210/157439307-08d671b8-0796-452f-9030-bd4ed18c83f5.png)
 

Torch = 1.9.0
cuda = 10.2

Error came while installing in windows. Is there any solution?
Thanks in advance.

**Comment by imabackstabber** [comment]
could you post the full log?

**Comment by nishavarghese15** [comment]
[mmcv_install.txt](https://github.com/open-mmlab/mmcv/files/8215589/mmcv_install.txt)

Thanks for the reply. The .txt file has some lines missing.

ERROR: Failed building wheel for mmcv-full in line 7785

Thanks

**Comment by imabackstabber** [comment]
i search keyword 'Error' in your txt,and i found this:
```
fatal error C1083: Cannot open include file: 'utils/spconv/spconv/maxpool.h': No such file or directory
```
which implies there's some file missing.If you're using pip to install mmcv-full,[previous issue](https://github.com/open-mmlab/mmcv/issues/1785) suggests same fault could happen.
Maybe resorting to [git clone and build the code](https://mmcv.readthedocs.io/en/latest/get_started/build.html) will help.

**Comment by nishavarghese15** [comment]
Okay. Thanks. I will check.

**Comment by zhouzaida** [comment]
Thanks for your report. Could you try to install mmcv-full with `pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu102/torch1.9.0/index.html`?

**Comment by nishavarghese15** [comment]
Thanks for the reply. I used the above line itself to install mmcv-full. But got error. Now I am trying with the git clone option. 

Thanks.

**Comment by HAOCHENYE** [comment]
Does this pr https://github.com/open-mmlab/mmcv/pull/1766 fix the error?

**Comment by nishavarghese15** [comment]
I followed the instructions in https://mmcv.readthedocs.io/en/latest/get_started/build.html

mmcv-full got installed but without cuda. 'No CUDA runtime is found'. But cuda (C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2) is available in the specified folder in the computer.

(mmcv) C:\Users\nish1\mmcv>python setup.py develop
No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2'
Compiling mmcv._ext without CUDA
running develop
running egg_info
writing mmcv_full.egg-info\PKG-INFO
writing dependency_links to mmcv_full.egg-info\dependency_links.txt
writing requirements to mmcv_full.egg-info\requires.txt
writing top-level names to mmcv_full.egg-info\top_level.txt
reading manifest file 'mmcv_full.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: manifest_maker: MANIFEST.in, line 6: path 'mmcv/ops/csrc/' cannot end with '/'

adding license file 'LICENSE'
adding license file 'LICENSES.md'
writing manifest file 'mmcv_full.egg-info\SOURCES.txt'
running build_ext
building 'mmcv._ext' extension
Emitting ninja build file C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\build.ninja...
Compiling objects...
Using envvar MAX_JOBS (8) as the number of workers...
ninja: no work to do.
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\nish1\miniconda3\envs\mmcv\lib\site-packages\torch\lib /LIBPATH:C:\Users\nish1\miniconda3\envs\mmcv\libs /LIBPATH:C:\Users\nish1\miniconda3\envs\mmcv\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x64" c10.lib torch.lib torch_cpu.lib torch_python.lib /EXPORT:PyInit__ext C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\active_rotated_filter.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\assign_score_withk.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\ball_query.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\bbox_overlaps.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\border_align.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\box_iou_rotated.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\carafe.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\carafe_naive.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\contour_expand.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\convex_iou.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\corner_pool.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\correlation.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\deform_conv.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\deform_roi_pool.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\focal_loss.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\furthest_point_sample.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\fused_bias_leakyrelu.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\fused_spconv_ops.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\gather_points.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\group_points.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\info.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\iou3d.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\knn.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\masked_conv2d.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\min_area_polygons.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\modulated_deform_conv.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\ms_deform_attn.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\nms.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\nms_rotated.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\pixel_group.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\points_in_boxes.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\points_in_polygons.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\psamask.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\pybind.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\riroi_align_rotated.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\roiaware_pool3d.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\roipoint_pool3d.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\roi_align.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\roi_align_rotated.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\roi_pool.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\rotated_feature_align.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\scatter_points.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\sparse_pool_ops.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\spconv_ops.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\sync_bn.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\three_interpolate.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\three_nn.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\tin_shift.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\upfirdn2d.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\voxelization.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch/cpu\active_rotated_filter.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch/cpu\box_iou_rotated.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch/cpu\deform_conv.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch/cpu\modulated_deform_conv.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch/cpu\nms.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch/cpu\nms_rotated.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch/cpu\pixel_group.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch/cpu\points_in_boxes.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch/cpu\psamask.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch/cpu\roi_align.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch/cpu\roi_align_rotated.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch/cpu\sparse_indice.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch/cpu\sparse_maxpool.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch/cpu\sparse_reordering.obj C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch/cpu\voxelization.obj /OUT:build\lib.win-amd64-3.7\mmcv\_ext.cp37-win_amd64.pyd /IMPLIB:C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\_ext.cp37-win_amd64.lib
   Creating library C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\_ext.cp37-win_amd64.lib and object C:\Users\nish1\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/ops/csrc/pytorch\_ext.cp37-win_amd64.exp
Generating code
Finished generating code
copying build\lib.win-amd64-3.7\mmcv\_ext.cp37-win_amd64.pyd -> mmcv
Creating c:\users\nish1\miniconda3\envs\mmcv\lib\site-packages\mmcv-full.egg-link (link to .)
mmcv-full 1.4.6 is already the active version in easy-install.pth

Installed c:\users\nish1\mmcv
Processing dependencies for mmcv-full==1.4.6
Searching for regex==2022.3.2
Best match: regex 2022.3.2
Adding regex 2022.3.2 to easy-install.pth file

Using c:\users\nish1\miniconda3\envs\mmcv\lib\site-packages
Searching for yapf==0.32.0
Best match: yapf 0.32.0
Adding yapf 0.32.0 to easy-install.pth file
Installing yapf-script.py script to C:\Users\nish1\miniconda3\envs\mmcv\Scripts
Installing yapf.exe script to C:\Users\nish1\miniconda3\envs\mmcv\Scripts
Installing yapf-diff-script.py script to C:\Users\nish1\miniconda3\envs\mmcv\Scripts
Installing yapf-diff.exe script to C:\Users\nish1\miniconda3\envs\mmcv\Scripts

Using c:\users\nish1\miniconda3\envs\mmcv\lib\site-packages
Searching for PyYAML==6.0
Best match: PyYAML 6.0
Adding PyYAML 6.0 to easy-install.pth file

Using c:\users\nish1\miniconda3\envs\mmcv\lib\site-packages
Searching for Pillow==8.4.0
Best match: Pillow 8.4.0
Adding Pillow 8.4.0 to easy-install.pth file

Using c:\users\nish1\miniconda3\envs\mmcv\lib\site-packages
Searching for packaging==21.3
Best match: packaging 21.3
Adding packaging 21.3 to easy-install.pth file

Using c:\users\nish1\miniconda3\envs\mmcv\lib\site-packages
Searching for numpy==1.21.5
Best match: numpy 1.21.5
Adding numpy 1.21.5 to easy-install.pth file
Installing f2py-script.py script to C:\Users\nish1\miniconda3\envs\mmcv\Scripts
Installing f2py.exe script to C:\Users\nish1\miniconda3\envs\mmcv\Scripts

Using c:\users\nish1\miniconda3\envs\mmcv\lib\site-packages
Searching for addict==2.4.0
Best match: addict 2.4.0
Adding addict 2.4.0 to easy-install.pth file

Using c:\users\nish1\miniconda3\envs\mmcv\lib\site-packages
Searching for pyparsing==3.0.7
Best match: pyparsing 3.0.7
Adding pyparsing 3.0.7 to easy-install.pth file

Using c:\users\nish1\miniconda3\envs\mmcv\lib\site-packages
Finished processing dependencies for mmcv-full==1.4.6

![image](https://user-images.githubusercontent.com/93310210/157603981-d961860e-dadd-4df1-90e0-19f5e386de59.png)
Is there any compatibility issue between torch version and cuda version?

Thanks

**Comment by nishavarghese15** [comment]
Hi all,

'CUDA runtime is not found' error got fixed by installing
pip install torch==1.9.0+cu102 torchvision==0.10.0+cu102 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html

Thank you all for the support.
