### ISSUE TITLE
Little mistake in TextLoggerHook

### ISSUE THREAD

**Issue by rydenisbak** [open-mmlab/mmcv#179]
Can you change this line
https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/logger/text.py#L90
to
```python
mode = runner.mode
```
?

**Comment by hellock** [comment]
This is a dirty hack. Sometimes we do not have evaluation epochs but use hooks to perform the evaluation. We want the mode to be `val` in this case.

**Comment by rydenisbak** [comment]
Ok, thank you
