### ISSUE TITLE
安装完import mmcv时出现: AttributeError: 'Version' object has no attribute 'release'

### ISSUE THREAD

**Issue by luqiang6q** [open-mmlab/mmcv#1793]
安装mmcv-full结束后，执行import mmcv会出现以下问题：
    assert version.release, f'failed to parse version {version_str}'
AttributeError: 'Version' object has no attribute 'release

安装方法：
预编译、直接编译等安装方法都试过了，都不行

**Comment by luqiang6q** [comment]
cuda10.1,pytorch1.8.1

**Comment by luqiang6q** [comment]
试了1.3.17以上的版本，都会出现上述错误。不过安装1.3.17后，import mmcv不会出现上述错误，但from mmcv.runner import load_checkpoint时仍会出现该错误

**Comment by luqiang6q** [comment]
求解。。。

**Comment by zhouzaida** [comment]
可以更新一下 packaging 的版本，pip install -U packaging
