### ISSUE TITLE
[ERROR] ModuleNotFoundError

### ISSUE THREAD

**Issue by BeyondYourself** [open-mmlab/mmcv#1805]
![d0878c9ed5e8ea4081ca507670e343f](https://user-images.githubusercontent.com/12640462/158346638-c5963798-7ad0-43b9-8086-c3e47d09b08a.png)

platfform:windows cpu
mmcv version :1.4.6

**Comment by zhouzaida** [comment]
Hi, could you provide the output of `pip list`?

**Comment by BeyondYourself** [comment]
![image](https://user-images.githubusercontent.com/12640462/158507905-1564b6fe-7aaa-411a-969b-5962ca22e4e3.png)

like this

**Comment by zhouzaida** [comment]
Hi, you need to install mmcv-full rather than mmcv if you want to use ops.

**Comment by zhouzaida** [comment]
![image](https://user-images.githubusercontent.com/58739961/158616756-e75004b9-85b2-4263-92c2-118761cfa1ab.png)

**Comment by BeyondYourself** [comment]
thx, I have resolved the error
