### ISSUE TITLE
How to disable logging during init_weights()

### ISSUE THREAD

**Issue by LukeForeverYoung** [open-mmlab/mmcv#1808]
**Checklist**

1. I have searched related issues but cannot get the expected help. yes
2. I have read the FAQ documentation but cannot get the expected help. yes

I notice that when call init_weight(), the mmcv logger will print a lot of lines such as ```Initialized by user-defined `init_weights` in SwinTransformer```
Is it possible to prevent logger to print these information, but keep the others.

**Comment by zhouzaida** [comment]
Hi @LukeForeverYoung , this is useful information for users debugging. If you really want to disable the lo, maybe you need to modify the code https://github.com/open-mmlab/mmcv/blob/e319369068c8fe813086ecddf1070ac510860592/mmcv/runner/base_module.py#L118

**Comment by zhouzaida** [comment]
Thanks for your suggestions. Please @jshilong have a look.

**Comment by lvdehuaiying** [comment]
> > Hi @LukeForeverYoung , this is useful information for users debugging. If you really want to disable the lo, maybe you need to modify the code
> > https://github.com/open-mmlab/mmcv/blob/e319369068c8fe813086ecddf1070ac510860592/mmcv/runner/base_module.py#L118
> 
> Thank you for your suggestions, and I agree that the outputs are useful. But these logs take up too many lines, making it difficult to view the rest of the outputs. Maybe it is great to incorporate a flag in the config to decide if the init_weights function will print logs for debugging and avoid modifying the source code.

MMCV's logger have different information importance levels, that is DEBUG, INFO, WARNING, ERROR, CRITICAL, from low to high. Find the outputting logger' name, (in your log info, such as 'mmdet'), then using:
`mmcv.utils.get_logger('mmdet')`
`logger.setLevel('WARNING')`
or set higher level.
