### ISSUE TITLE
关于旋转矩形iou计算代码中的问题

### ISSUE THREAD

**Issue by JinYue2015** [open-mmlab/mmcv#1832]
https://github.com/open-mmlab/mmcv/blob/5b5d0c15bcba1c60215823bee1ba6c7808be6bc2/mmcv/ops/csrc/common/box_iou_rotated_utils.hpp#L56

在函数get_rotated_vertices中的坐标点旋转计算代码，和注释中的计算公式不匹配(顺时针和逆时针的都对不上)
![image](https://user-images.githubusercontent.com/12403827/159906813-7dbdbd43-9a5f-4be2-a2af-aa0bd88cecf0.png)

顺时针：
![image](https://user-images.githubusercontent.com/12403827/159907126-d82ef126-e7ba-49fe-a937-9100144a2a19.png)
逆时针：
![image](https://user-images.githubusercontent.com/12403827/159907299-26cd05e5-370b-4664-824d-1e1c559c5358.png)

我自己推出来，x轴朝右，y轴朝上，逆时针方向旋转才能与代码匹配。
请问这段代码有问题嘛，还是坐标系定义哪里有改动？

**Comment by JinYue2015** [comment]
some problem of function ‘get_rotated_vertices’ in file [mmcv/mmcv/ops/csrc/common/box_iou_rotated_utils.hpp](https://github.com/open-mmlab/mmcv/blob/5b5d0c15bcba1c60215823bee1ba6c7808be6bc2/mmcv/ops/csrc/common/box_iou_rotated_utils.hpp#L56)

I check the code and comment in document. find code can't match the algrithm in doc whether in mode cw or ccw.
 
![image](https://user-images.githubusercontent.com/12403827/159914676-715104b7-286c-4ac4-97dc-e84077dbbbcb.png)
![image](https://user-images.githubusercontent.com/12403827/159914707-60c5ae62-740e-466b-a833-b8f9a3e691d1.png)

**Comment by zhouzaida** [comment]
Please @zytx121 have a look.

**Comment by JinYue2015** [comment]
> The code in `box_iou_rotated_utils.hpp` has been simplified. Maybe this code can help you understand ![image](https://user-images.githubusercontent.com/10410257/159940372-2829b8a8-fb1a-4cab-9eed-bb7781eef956.png)

Please check the symbol before cos and sin in the code of calculating pts[0]and pts[1].（简化我知道的，关键是PA、PB的计算。sin cos前面的符号对不上啊。代码里面pts[0]是PB，pts[1]是PA？）
https://github.com/open-mmlab/mmcv/blob/5b5d0c15bcba1c60215823bee1ba6c7808be6bc2/mmcv/ops/csrc/common/box_iou_rotated_utils.hpp#L66

And please tell me which coordinate system and which rotation directtion for calc.

**Comment by zytx121** [comment]
The most basic case shown in the formula is that the rotation center is at the origin and the point to be rotated is in the fourth quadrant. In this code, the rotation center is in the center of the box, and the points to be rotated are not only in the fourth quadrant. Although the rotation matrix is the same, the rotation formula for the points in each quadrant is different and cannot be directly applied mechanically.

The coordinate system and rotation direction have been clearly explained in the docstring. 
- The x-axis is towards the right and the y-axis is towards the down. 
- The default rotation direction is clockwise.
