### ISSUE TITLE
Abort ONNX Custom Ops in mmcv

### ISSUE THREAD

**Issue by DDGRCF** [open-mmlab/mmcv#1835]
**Checklist**
when I see mmcv source code, I have a question abort that when I convert a custom ops like NMS, how it can know where custom NMS come from, I can't see the register code of custom onnx ops in mmcv.

**Comment by AllentDan** [comment]
You can check [this](https://github.com/open-mmlab/mmcv/blob/1a2f174ffedefda2015be78571d89f8d84c31f54/mmcv/ops/nms.py#L35) out. We use the symbolic method of pytorch to register a custom op. As for how symbolic works, maybe you can refer to [pytorch](https://pytorch.org/docs/master/onnx.html?highlight=symbolic#torch.onnx.register_custom_op_symbolic).

**Comment by DDGRCF** [comment]
> You can check [this](https://github.com/open-mmlab/mmcv/blob/1a2f174ffedefda2015be78571d89f8d84c31f54/mmcv/ops/nms.py#L35) out. We use the symbolic method of pytorch to register a custom op. As for how symbolic works, maybe you can refer to [pytorch](https://pytorch.org/docs/master/onnx.html?highlight=symbolic#torch.onnx.register_custom_op_symbolic).

thanks for your answer

**Comment by zgplvyou** [comment]
> You can check [this](https://github.com/open-mmlab/mmcv/blob/1a2f174ffedefda2015be78571d89f8d84c31f54/mmcv/ops/nms.py#L35) out. We use the symbolic method of pytorch to register a custom op. As for how symbolic works, maybe you can refer to [pytorch](https://pytorch.org/docs/master/onnx.html?highlight=symbolic#torch.onnx.register_custom_op_symbolic).

@AllentDan I try to use the symbolic method of pytorch to register a custom op, however,  my function return more than one output,  it doesn`t work, here is my code.

def func1(a, b):
    c = torch.add(a, b)
    d = torch.sub(c, a)
    return [c,d]

class NMSop(torch.autograd.Function):

    @staticmethod
    def forward(ctx, a, thr):
        return func1(a, thr)

    @staticmethod
    def backward(ctx, bb):
        return b

    @staticmethod
    def symbolic(g, a, thr):
        thre = g.op("Constant", value_t=torch.tensor([thr]))
        x =  g.op('Aten::NMS', a, thre)
        return  g.op('Add', x, thre)

and after torch.onnx.export, there are not Aten::NMS node. so, do u know how to solve it?
