### ISSUE TITLE
I cannot compiler mmcv on windows with 3090

### ISSUE THREAD

**Issue by bzfather** [open-mmlab/mmcv#1839]
CUDA=11.4 GPU=RTX3090 Windows
I tried both pre-built packages and build manually. They didn't work neither.
I have tried many versions of cudatoolkit and pytorch.
The direct problem is when I check environment it showed that" MMCV compiler is not available"
When I built it manually according to the document, it was stuck in 'python setup.py build_ext', showing "Command '['ninja', '-v',]' returned non-zero exit status 1"

**Comment by zhouzaida** [comment]
Hi @bzfather , thanks for your report. Could you provide the full compilation or installation log?

**Comment by bzfather** [comment]
@zhouzaida Do you mean the log shown in terminal? I wonder if there is a log file about the detail of compilation.

**Comment by zhouzaida** [comment]
You can redirect the log in terminal to `log.txt`.
