### ISSUE TITLE
Cuda 11.2 support!

### ISSUE THREAD

**Issue by rohansig** [open-mmlab/mmcv#1841]
Hi,

I was installing mmcv on collab and found that collab uses cuda 11.2 but I dont see support for this cuda version.

**Comment by zhouzaida** [comment]
Hi, thanks for your report. You can install the cudatoolkit=10.2 with conda.

```bash
conda install pytorch==1.9.0 torchvision==0.10.0 cudatoolkit=10.2 -c pytorch
pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu102/torch1.9/index.html
```

**Comment by rohansig** [comment]
Following is the error executing above commmands:

Collecting package metadata (current_repodata.json): done
Solving environment: - WARNING conda.core.solve:_add_specs(649): pinned spec cudatoolkit=11.1 conflicts with explicit specs.  Overriding pinned specfailed with initial frozen solve. Retrying with flexible solve.
Solving environment: \ WARNING conda.core.solve:_add_specs(649): pinned spec cudatoolkit=11.1 conflicts with explicit specs.  Overriding pinned specfailed with repodata from current_repodata.json, will retry with next repodata source.

ResolvePackageNotFound: 
  - conda==4.9.2

**Comment by zhouzaida** [comment]
Does it seem like you had installed cudatoolkit?
