### ISSUE TITLE
Speed up Registry initialization

### ISSUE THREAD

**Issue by astahlman** [open-mmlab/mmcv#1843]
Python imports that trigger many calls to `Registry.__init__()` are slow.

**Motivation**

`Registry.__init__` calls `infer_scope()`:

https://github.com/open-mmlab/mmcv/blob/c46deb0576edaff5cd5a7d384c617478c7a73a70/mmcv/utils/registry.py#L93

...which in turn calls `inspect.stack()`.

https://github.com/open-mmlab/mmcv/blob/c46deb0576edaff5cd5a7d384c617478c7a73a70/mmcv/utils/registry.py#L142-L144

`inspect.stack()` is slow because it requires repeated filesystem access as it loads source files for each stack frame from disk (see https://stackoverflow.com/a/42636264/895769 for more information). This causes importing a module that instantiates multiple registries to be slow.

**Related resources**
If there is an official code release or third-party implementations, please also provide the information here, which would be very helpful.

**Additional context**
If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.

**Comment by imabackstabber** [comment]
since here is a pr #1844  solving this issue,I'm closing it.Thanks for your work.
