### ISSUE TITLE
Loading weights from TorchVision will stop working

### ISSUE THREAD

**Issue by datumbox** [open-mmlab/mmcv#1848]
Hi OpenMMLab team, Thanks for your awesome work on MMCV.

The current implementation of `get_torchvision_models()` is trying to access the `model_urls` variable that existed in some backbone implementations of TorchVision. TorchVision considers this variable non-public (because it's [not included](https://github.com/pytorch/vision/blob/release/0.12/torchvision/models/optical_flow/raft.py#L16) in the `__all__`) and non-standard (because it's [not available](https://github.com/pytorch/vision/blob/release/0.12/torchvision/models/optical_flow/raft.py#L23) in all models) and thus plans to remove it on the next version. We are currently moving on a new API that will allow us to support multiple pretrained weights for every model variant (read more [here](https://pytorch.org/blog/introducing-torchvision-new-multi-weight-support-api/)). This change has recently landed at TorchVision on https://github.com/pytorch/vision/pull/5618.

To avoid breakages, we recommend to [update](https://github.com/open-mmlab/mmcv/blob/fb486b96fd9932637a16f23a5dc60904c12bea7d/mmcv/runner/checkpoint.py#L108-L117) your code. A few options include to:
1. Access the URLs from the [new public locations](https://github.com/pytorch/vision/blob/main/torchvision/models/optical_flow/raft.py#L525)
2. Move the the `model_urls` maps on your side
3. Something else, happy to work with you to figure it out

We intentionally released this change several months before the next release to give time to iron out issues like that. Let me know your thoughts on how we should go about it. Thanks!

**Comment by zhouzaida** [comment]
@datumbox, thank you for your reminders and suggestions, we will modify the code accordingly.

**Comment by datumbox** [comment]
@zhouzaida Thanks a lot for the reply.

We have a dedicated issue for feedback about the new API at https://github.com/pytorch/vision/issues/5088; if you find any issues we would love to know and act upon it. Also let me know if there is anything we can do on our side to help.

**Comment by HAOCHENYE** [comment]
@datumbox Hi， will these features be released in torchvison 0.13.0? We try to handle these changes by checking the version of torchvision.

**Comment by datumbox** [comment]
@HAOCHENYE yes that's correct. Starting from 0.13, TorchVision will adopt the new API. The plan is for the old one to remain available for 2 versions (planned for removal on 0.15) but it will emit a warning if used. Let me know if you have any feedback or need more info. Thanks!

**Comment by zhouzaida** [comment]
Hi @datumbox , thanks for your awesome work on torchvision. We are trying to handle these changes and we want to know when will the new version v0.13 be released?

**Comment by datumbox** [comment]
@zhouzaida Apologies for the delay getting back to you. I was OOO. 

We don't have a fixed date yet but we expect it to be around end of June or beginning of July.

**Comment by zhouzaida** [comment]
> @zhouzaida Apologies for the delay getting back to you. I was OOO.
> 
> We don't have a fixed date yet but we expect it to be around end of June or beginning of July.

Got it. Thanks for your reply.
