### ISSUE TITLE
Use Hierarchy Registry to build modules from different OpenMMLab frameworks

### ISSUE THREAD

**Issue by hyz-xmaster** [open-mmlab/mmcv#1853]
Hi, I learnt that I can build modules from more than one OpenMMLab toolboxes based on the [Hierarchy Registry](https://github.com/open-mmlab/mmcv/blob/master/docs/en/understand_mmcv/registry.md#hierarchy-registry) mechanism. I appreciate that you guys provide an example for this. But I still didn't figure out how I can use this Hierarchy Registry because of some ambiguity in this example. 

> In MMDetection we define NetA:

Does this mean that I can define  the NetA model anywhere in MMDetection? 
After defining the NetA, do I need to rebuild and reinstall mmdet?

> 2.Build from parent registry.
The shared MODELS registry in MMCV is the parent registry for all downstream codebases (root registry):

I am a bit confused about how MMCV knows that I have defined a NetA model in MMDetection?
To use the mmdet.NetA, do I need to import mmdet.models in mmcv? 

In general, it would be highly appreciated if you could give a detailed example for the Hierarchy Registry usage, especially a step-by-step one.

Thanks.

**Comment by zhouzaida** [comment]
Hi @hyz-xmaster , thanks for your report. The [link](https://mmdetection.readthedocs.io/en/latest/tutorials/customize_models.html) would be helpful.

**Comment by hyz-xmaster** [comment]
> Hi @hyz-xmaster , thanks for your report. The [link](https://mmdetection.readthedocs.io/en/latest/tutorials/customize_models.html) would be helpful.

Hi, thanks for your reply. But this answer doesn't solve my aforementioned problems. I still don't know how to use the Hierarchy Registry to build a new model from different OpenMMLab frameworks. Actually, I even didn't run that [example](https://github.com/open-mmlab/mmcv/blob/master/docs/en/understand_mmcv/registry.md#hierarchy-registry) successfully. Hope you can provide a feasible example with scripts.

**Comment by HAOCHENYE** [comment]
Hi @hyz-xmaster. The `NetA`  The registration process for `NetA` occurs during the `import` phase. The registration process for `NetA` happens at the `import` stage, so wherever `NetA` is defined, you can simply import the `netA.py` and then get the corresponding `class` in the Registry via the `get` method. 


You can get class `NetA` by following steps

1. Define `NetA` in `net_a.py`

`net_a.py`:

```python
from mmdet.models.builder import MODELS


@MODELS.register_module
class NetA:
    pass
```

2. import net_a.py and get create a instance by `MODELS.build`

`sample.py`
```python
from mmdet.models.builder import MODELS
import net_a  #import NetA module


net_a = MODELS.build('NetA')
```

BTW, 

> I even didn't run that [example](https://github.com/open-mmlab/mmcv/blob/master/docs/en/understand_mmcv/registry.md#hierarchy-registry) successfully. Hope you can provide a feasible example with scripts.

It could be helpful if you can supply the error information raised by the tutorial code.

**Comment by hyz-xmaster** [comment]
Hi @HAOCHENYE , thanks for your example. My main problem is how to use a mmdet module in mmcls or use a mmcls module in mmdet. I understand your example and I have figured out the reason why I didn't run the [example](https://github.com/open-mmlab/mmcv/blob/master/docs/en/understand_mmcv/registry.md#hierarchy-registry) successfully. 

The main problem in the following [code](https://github.com/open-mmlab/mmcv/blob/master/docs/en/understand_mmcv/registry.md#hierarchy-registry) snippet: 
```python
from mmdet.models import MODELS
net_a = MODELS.build(cfg=dict(type='NetA'))
net_b = MODELS.build(cfg=dict(type='mmcls.NetB'))
```
is that it misses one `import` line:

`import mmcls.models` or other similar `import mmcls.xxx` statements. 

This line allows the code in mmdet to know `NetB` defined in mmcls. Otherwise, this piece of code won't know where `NetB` is defined.

This problem has already been pointed out [here](https://github.com/open-mmlab/mmcv/blob/master/docs/en/understand_mmcv/registry.md#a-simple-example):

> The registry mechanism will be triggered only when the file where the module is located is imported.
So you need to import that file somewhere. More details can be found at https://github.com/open-mmlab/mmdetection/issues/5974.

**Comment by xjq1042523740** [comment]
> Hi @hyz-xmaster , thanks for your report. The [link](https://mmdetection.readthedocs.io/en/latest/tutorials/customize_models.html) would be helpful.
Hello, this link is invalid, can you send it again?

**Comment by hitbuyi** [comment]
I have the same issue,  examples in doucment of  mmcv v1.4.1 don't run sucessfully
