### ISSUE TITLE
When I use the Tensorrt -DCNV2 plugin, cudaScaleRunner.cpp (119) - Cuda Error in execute: 700 (an illegal memory access was encountered) appears, how to solve it?

### ISSUE THREAD

**Issue by scuizhibin** [open-mmlab/mmcv#1856]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the FAQ documentation but cannot get the expected help.

**Comment by grimoire** [comment]
Please provide the model and test data to reproduce this error.
Note that TensorRT support in MMCV would be deprecated in the future. Please try ops in https://github.com/open-mmlab/mmdeploy.

**Comment by scuizhibin** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/mmcv"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月5日(星期二) 上午8:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-mmlab/mmcv] When I use the Tensorrt -DCNV2 plugin, cudaScaleRunner.cpp (119) - Cuda Error in execute: 700 (an illegal memory access was encountered) appears, how to solve it? (Issue #1856)





 
Please provide the model and test data to reproduce this error.
 Note that TensorRT support in MMCV would be deprecated in the future. Please try ops in https://github.com/open-mmlab/mmdeploy.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

kaixin_d2cny.onnx (183.73M, 2022年05月06日 09:29 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=20393766de58b6958a919b5a1365004e5e5a0104030650534b0906540d480602565d1a045351074c540c550407550151535806003574320a07504f0f5b3a565305574e485a0b5c196604&code=f97f5e2a

**Comment by scuizhibin** [comment]
I used qq mailbox to send to you, I used the DCNV2 code of mmcv and the code of https://github.com/lesliejackson/TensorRT-DCNv2-Plugin, both have the same problem, you can also try it. Tnesorrt 7.2.1 graphics card is RTX3060, driver is 470.103.01.

**Comment by grimoire** [comment]
Please try the one in  https://github.com/open-mmlab/mmdeploy.

**Comment by scuizhibin** [comment]
我加速的是fcos3d，deploy里面没有。


---Original---
From: ***@***.***&gt;
Date: Wed, Apr 6, 2022 10:27 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [open-mmlab/mmcv] When I use the Tensorrt -DCNV2 plugin, cudaScaleRunner.cpp (119) - Cuda Error in execute: 700 (an illegal memory access was encountered) appears, how to solve it? (Issue #1856)




 
Please try the one in  https://github.com/open-mmlab/mmdeploy.
 
&mdash;

**Comment by grimoire** [comment]
You can build the plugin and load it with: ` ctypes.CDLL(lib_path)`, they are basically the same.

**Comment by scuizhibin** [comment]
翻译
OK,&nbsp;but&nbsp;I&nbsp;am&nbsp;using&nbsp;tensorrt&nbsp;c++&nbsp;and&nbsp;need&nbsp;to&nbsp;register&nbsp;the&nbsp;plugin,&nbsp;and&nbsp;can't&nbsp;use&nbsp;cpython.dll.


---Original---
From: ***@***.***&gt;
Date: Fri, Apr 8, 2022 16:30 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [open-mmlab/mmcv] When I use the Tensorrt -DCNV2 plugin,cudaScaleRunner.cpp (119) - Cuda Error in execute: 700 (an illegal memoryaccess was encountered) appears, how to solve it? (Issue #1856)




 
You can build the plugin and load it with:  ctypes.CDLL(lib_path), they are basically the same.
 
&mdash;

**Comment by grimoire** [comment]
That would be much easier, just link the lib into your program.
