### ISSUE TITLE
solution for Integrating  several api

### ISSUE THREAD

**Issue by kcs6568** [open-mmlab/mmcv#1857]
Hi, I'm using mmdetection and mmsegmentation api.

Is there any way to use these two APIs together?
I want to use mmdetection's detector and mmsegmentation's segmentor in one process for my research. For example, I want to use faster rcnn and fcn with resnet50 as a backbone for training.

For this, there is a simple way to integrate the mmsegmentation module inside mmdetection, but it seems to cost a lot of time.

Is there any more effective way other than these methods?

Thank you in advance.

**Comment by imabackstabber** [comment]
> I want to use mmdetection's detector and mmsegmentation's segmentor in one process for my research. For example, I want to use faster rcnn and fcn with resnet50 as a backbone for training.

I'm a little confused. Does this means you want to jointly train faster rcnn and fcn with **the same resnet50 backbone** or just train two models respectively?

**Comment by kcs6568** [comment]
Sorry for the confusion.

As you said, I want to learn through the same resnet backbone.

I want to train to use only the head module for both networks and share the resnet50 backbone.
For example, I learn faster rcnn and fcn based on a shared resnet50 backbone.
Training for detection and segmentation is done in the head for each task.
(rpn for faster rcnn, fcn head for fcn)

I found a document in the mmdetection api that describes a task similar to the one I want.

https://github.com/open-mmlab/mmdetection/blob/master/docs/en/tutorials/how_to.md

This document describes how to directly call the network of mmclassification for the backbone network in mmdetection.

As such, I am curious about how to call and use mmdetection module and mmsegmentation module at the same time.

**Comment by imabackstabber** [comment]
> Sorry for the confusion.
> 
> As you said, I want to learn through the same resnet backbone.
> 
> I want to train to use only the head module for both networks and share the resnet50 backbone. For example, I learn faster rcnn and fcn based on a shared resnet50 backbone. Training for detection and segmentation is done in the head for each task. (rpn for faster rcnn, fcn head for fcn)
> 
> I found a document in the mmdetection api that describes a task similar to the one I want.
> 
> https://github.com/open-mmlab/mmdetection/blob/master/docs/en/tutorials/how_to.md
> 
> This document describes how to directly call the network of mmclassification for the backbone network in mmdetection.
> 
> As such, I am curious about how to call and use mmdetection module and mmsegmentation module at the same time.

I read the docs mentioned above, maybe you can use ``custom_imports`` to do it.Just like add a backbone from mmcls,you can add a seg head from mmseg.
Here is an example:
```
custom_imports = dict(imports=['mmcls.models'], allow_failed_imports=False) # import backbone from mmcls
custom_imports = dict(imports=['mmcls.models'], allow_failed_imports=False) # import seg head from mmseg
model = dict(
    backbone=dict(
        _delete_=True, # Delete the backbone field in _base_
        type='mmcls.backbone', # Using backbone from mmcls
        ...), 
    neck=dict(...),
    roi_head = dict(...), # define faster rcnn rpn head
    seg_head = dict(
        _delete_=True
        type='FPNHead',
        ...)
)
```

**Comment by kcs6568** [comment]
Great! I'll try this!!

Thank you for your help!
