### ISSUE TITLE
Is there a way to save a Config instance to a file?

### ISSUE THREAD

**Issue by hovnatan** [open-mmlab/mmcv#1861]
I create a `Config` class instance in Python code, by making changes to a base config. Is there a way to save it to a file that can be loaded afterwards with `Config.from_file()`?

**Comment by HAOCHENYE** [comment]
@hovnatan Hi, we can dump the config file by `config.dump('my_config.py')` and load it by `Config.from_file('my_config.py')`

**Comment by hovnatan** [comment]
Thanks!
