### ISSUE TITLE
Is the runner.optimizer sometimes a dict?

### ISSUE THREAD

**Issue by teamwong111** [open-mmlab/mmcv#1895]
I'm not sure about that. But I see some inconsistencies in [LrUpdaterHook](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/lr_updater.py#L59) and [OptimizerHook](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/optimizer.py#L53)

**Comment by zhouzaida** [comment]
The `OptimizerHook` only works when `runner.optimizer` is an Optimizer object rather than dict. Examples about how to use multiple optimizers can be found at https://github.com/open-mmlab/mmgeneration/blob/0892df54932f927e415dad282dbb0fe6409271ce/mmgen/models/gans/basic_conditional_gan.py#L238

**Comment by teamwong111** [comment]
Ok, I got it.
