### ISSUE TITLE
Enabling HIP 

### ISSUE THREAD

**Issue by zstreet87** [open-mmlab/mmcv#1898]
Thanks for reporting the unexpected results and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help. Yes
2. I have read the [FAQ documentation](https://mmcv.readthedocs.io/en/latest/trouble_shooting.html) but cannot get the expected help. Yes
3. The unexpected results still exist in the latest version. Check

**Describe the Issue**
Trying to compile MMCV with the docker image below, I am running into 'cuda_runtime_api.h' file not found within the 'spconv_utils.h' file.  This file's path is ./mmcv/ops/csrc/pytorch/spconv_utils.h and this path is not included in the setup.py.  Therefore, this file is not hipified once MMCV is JIT compiled at installation and hence the error.  Including this path in the setup.py fixed this issue but gave other errors.  This is probably from ROCm and hipify_torch updates as I saw a installation of MMCV-full has already been successful in older versions. 

**Reproduction**

1. What command, code, or script did you run?

```bash
MMCV_WITH_OPS=1 pip install -e .
```

2. Did you make any modifications on the code? Did you understand what you have modified?
No code change is necessary.  Just run in the specified docker container.

**Environment**
```bash
docker pull rocm/pytorch:rocm5.0_ubuntu18.04_py3.7_pytorch_1.10.0
```
1. Please run `python -c "from mmcv.utils import collect_env; print(collect_env())"` to collect necessary environment information and paste it here.
/bin/sh: 1: /opt/rocm/bin/nvcc: not found
{'sys.platform': 'linux', 'Python': '3.7.11 (default, Jul 27 2021, 14:32:16) [GCC 7.5.0]', 'CUDA available': True, 'GPU 0,1,2,3,4,5,6,7': '', 'CUDA_HOME': '/opt/rocm', 'NVCC': 'Not Available', 'GCC': 'gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0', 'PyTorch': '1.10.0a0+git089849b', 'PyTorch compiling details': 'PyTorch built with:\n  - GCC 7.5\n  - C++ Version: 201402\n  - Intel(R) oneAPI Math Kernel Library Version 2022.0-Product Build 20211112 for Intel(R) 64 architecture applications\n  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)\n  - OpenMP 201511 (a.k.a. OpenMP 4.5)\n  - LAPACK is enabled (usually provided by MKL)\n  - NNPACK is enabled\n  - CPU capability usage: AVX512\n  - HIP Runtime 50013.60.1\n  - MIOpen 2.15.0\n  -
Magma 2.5.4\n  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CXX_COMPILER=/opt/cache/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=OFF, USE_CUDNN=OFF, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, \n', 'TorchVision': '0.11.0a0+fa347eb', 'OpenCV': '4.5.5', 'MMCV': '1.5.0', 'MMCV Compiler': 'n/a', 'MMCV CUDA Compiler': 'n/a'}

3. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)
    Just use this docker image rocm/pytorch:rocm5.0_ubuntu18.04_py3.7_pytorch_1.10.0

**Error traceback**
If applicable, paste the error traceback here.

```
 FAILED: /home/zstreet/ROCm/mmcv/build/temp.linux-x86_64-3.7/home/zstreet/ROCm/mmcv/mmcv/ops/csrc/pytorch/hip/sparse_reordering.o
    /opt/rocm/bin/hipcc  -DMMCV_WITH_HIP -DMMCV_WITH_CUDA -I/home/zstreet/ROCm/mmcv/mmcv/ops/csrc/common -I/home/zstreet/ROCm/mmcv/mmcv/ops/csrc/common/cuda -I/opt/conda/lib/python3.7/site-packages/torch/include -I/opt/conda/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/lib/python3.7/site-packages/torch/include/TH -I/opt/conda/lib/python3.7/site-packages/torch/include/THC -I/opt/conda/lib/python3.7/site-packages/torch/include/THH -I/opt/rocm/include -I/opt/rocm/miopen/include -I/opt/conda/include/python3.7m -c -c /home/zstreet/ROCm/mmcv/mmcv/ops/csrc/pytorch/hip/sparse_reordering.hip -o /home/zstreet/ROCm/mmcv/build/temp.linux-x86_64-3.7/home/zstreet/ROCm/mmcv/mmcv/ops/csrc/pytorch/hip/sparse_reordering.o -fPIC -D__HIP_PLATFORM_HCC__=1 -DCUDA_HAS_FP16=1 -D__HIP_NO_HALF_OPERATORS__=1 -D__HIP_NO_HALF_CONVERSIONS__=1 -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=1 --amdgpu-target=gfx900 --amdgpu-target=gfx906 --amdgpu-target=gfx908 --amdgpu-target=gfx90a --amdgpu-target=gfx1030 -fno-gpu-rdc
    In file included from /home/zstreet/ROCm/mmcv/mmcv/ops/csrc/pytorch/hip/sparse_reordering.hip:29:
    In file included from /home/zstreet/ROCm/mmcv/mmcv/ops/csrc/pytorch/hip/../spconv_utils.h:17:
    /opt/conda/lib/python3.7/site-packages/torch/include/ATen/cuda/CUDAContext.h:5:10: fatal error: 'cuda_runtime_api.h' file not found
    #include <cuda_runtime_api.h>
             ^~~~~~~~~~~~~~~~~~~~
    1 error generated when compiling for gfx1030.

```

**Bug fix**
There are several easy solutions for this particular error.  However, my attempts to resolve this issue has lead me down deep rabbit holes that seem to break more things so I am hoping to receive some guidance here.

For example, once the HIP folders are generated via hipify_torch, I can manually change the setup.py file to point to those generated folders and MMCV-full builds without any errors.  However, I get an undefined symbols error if I try to check the installation and this appears to be from not pointing to the .cu files to begin with.

The trivial fix is to use #ifdef guards to include the correct hip file but I end up with ambiguous definitions.

Another attempt still was to just add the pytorch path to the glob in the setup.py and this does indeed generate a correct hipified spconv_utils_hip.h file.  However other errors arise, unfortunately.

Any help parsing through this would be greatly appreciated!

**Comment by grimoire** [comment]
The `CUDAExtension` would hipify the cuda code so we can compile it on Rocm device. It will read the include and sources and replace some code from cuda to hip.

https://github.com/pytorch/pytorch/blob/3e10fe323165a94fed66b1487902e8d394ce3be1/torch/utils/cpp_extension.py#L1010

It seems the `hipify` does not known the heads there, add it in to the includes might fix the error.

**Comment by grimoire** [comment]
It seems that the hipify does not know there is a head file inside `ops/pytorch`, have you tried to add the include_directory in setup?

**Comment by zstreet87** [comment]
Got it working and I will file a PR tomorrow.  Thank you for your attention :)
