### ISSUE TITLE
Error: pip install -e .

### ISSUE THREAD

**Issue by ssli23** [open-mmlab/mmcv#1901]
ERROR: Command errored out with exit status 1:
     command: /home/kb535/anaconda3/envs/mmdetection/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/kb535/lss/codes/objection/mmcv/setup.py'"'"'; __file__='"'"'/home/kb535/lss/codes/objection/mmcv/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ygtoecmu
         cwd: /home/kb535/lss/codes/objection/mmcv/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/kb535/lss/codes/objection/mmcv/setup.py", line 12, in <module>
        if torch.__version__ == 'parrots':
    AttributeError: module 'torch' has no attribute '__version__'
    ----------------------------------------
WARNING: Discarding file:///home/kb535/lss/codes/objection/mmcv. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

ububtu:20.04
pytorch:1.8.0
cuda:11.1
torchvision:0.8.1
gcc:7.5.0
g++:7.5.0
3090

**Comment by zhouzaida** [comment]
Hi @ssli23 , what is your mmcv version?

**Comment by ssli23** [comment]
> Hi @ssli23 , what is your mmcv version?

mmcv ：1.3.9

**Comment by zhouzaida** [comment]
What command did you use to install mmcv?

**Comment by ssli23** [comment]
pip install mmcv-full=={1.3.9} -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.8.0/index.html

**Comment by zhouzaida** [comment]
> File "/home/kb535/lss/codes/objection/mmcv/setup.py", line 12, in
> if torch.version == 'parrots':
> AttributeError: module 'torch' has no attribute 'version'

Did you modify the setup.py in mmcv? I found it was not consistent with https://github.com/open-mmlab/mmcv/blob/v1.3.9/setup.py#L10

**Comment by HAOCHENYE** [comment]
HI @ssli23 , Does your mmdetection version match with https://mmdetection.readthedocs.io/en/v2.21.0/get_started.html

**Comment by ssli23** [comment]
> mmcv ：1.3.9



> HI @ssli23 , Does your mmdetection version match with https://mmdetection.readthedocs.io/en/v2.21.0/get_started.html

mmcv ：1.3.9
Is this version available?

**Comment by HAOCHENYE** [comment]
@ssli23 1.3.9 is available, but it seems this error is not caused by mmcv 1.3.9.  Do you build mmcv from source?(/home/kb535/lss/codes/objection/mmcv/setup.py) Maybe you can `cd` to this directory and `git checkout  v1.3.9` to ensure mmcv source code is unchangde.

**Comment by HAOCHENYE** [comment]
Besides, will reinstall mmcv worked(uninstall mmcv or mmcv-full first). Just install mmcv by pip install mmcv-full==1.3.9 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.8.0/index.html
