### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 0: invalid continuation byte

### ISSUE THREAD

**Issue by creater-zq** [open-mmlab/mmcv#1903]
在windows11上面，我使用`pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.11.0/index.html`安装了`mmcv-full 1.5.0`。
之后使用[测试脚本](https://github.com/open-mmlab/mmcv/blob/master/.dev_scripts/check_installation.py)测试是否安装成功，出现了如下错误:
```bash
C:\Users\ZhangQu\.conda\envs\mmlab\python.exe D:/masterResearch/envtest/check_mmcv.py
Start checking the installation of mmcv-full ...
CPU ops were compiled successfully.
CUDA ops were compiled successfully.
mmcv-full has been installed successfully.

Traceback (most recent call last):
  File "D:\masterResearch\envtest\check_mmcv.py", line 40, in <module>
    env_info_dict = collect_env()
  File "C:\Users\ZhangQu\.conda\envs\mmlab\lib\site-packages\mmcv\utils\env.py", line 91, in collect_env
    env_info['MSVC'] = cc.decode(encoding).partition('\n')[0].strip()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 0: invalid continuation byte

Process finished with exit code 1
```

**Comment by zhouzaida** [comment]
感谢你的反馈，这是 collect_env 中的一个编码问题，我们会尽快修复。另外，安装应该是没问题的，可正常使用

**Comment by creater-zq** [comment]
好的，谢谢


| |
张取
|
|
***@***.***
|
On 4/22/2022 10:17，Zaida ***@***.***> wrote：

感谢你的反馈，这是 collect_env 中的一个编码问题，我们会尽快修复。另外，安装应该是没问题的，可正常使用

**Comment by SuTanTank** [comment]
@creater-zq 请帮忙一下执行下面的命令，这将帮助我们定位问题：

```
import sys, os, locale
locale.getdefaultlocale()
sys.stdout.fileno()
os.device_encoding(sys.stdout.fileno())
```

**Comment by creater-zq** [comment]
| |
张取
|
|
***@***.***
|
On 4/22/2022 12:36，Tan ***@***.***> wrote：

@creater-zq 请帮忙一下执行下面的命令，这将帮助我们定位问题：

import sys, os, locale

locale.getdefaultlocale()

sys.stdout.fileno()

os.device_encoding(sys.stdout.fileno())

**Comment by creater-zq** [comment]
我在pycharm和anaconda的终端里面测试结果不一样




| |
张取
|
|
***@***.***
|
On 4/22/2022 12:36，Tan ***@***.***> wrote：

@creater-zq 请帮忙一下执行下面的命令，这将帮助我们定位问题：

import sys, os, locale

locale.getdefaultlocale()

sys.stdout.fileno()

os.device_encoding(sys.stdout.fileno())

**Comment by creater-zq** [comment]
> @creater-zq 请帮忙一下执行下面的命令，这将帮助我们定位问题：
> 
> ```
> import sys, os, locale
> locale.getdefaultlocale()
> sys.stdout.fileno()
> os.device_encoding(sys.stdout.fileno())
> ```

我在pycharm里面和anaconda的终端执行结果不一样？
![image](https://user-images.githubusercontent.com/59300179/164605111-f7ffff55-c061-4815-826e-2d5a9ad89069.png)

**Comment by SuTanTank** [comment]
```
sys.getdefaultencoding()
```

**Comment by creater-zq** [comment]
> ```
> sys.getdefaultencoding()
> ```
我是windows下测试的：
![image](https://user-images.githubusercontent.com/59300179/164616718-fd128368-aed4-4fbd-b900-78d5f760743b.png)

**Comment by creater-zq** [comment]
> ```
import sys, os, locale

print(locale.getdefaultlocale())
print(sys.stdout.fileno())
print(os.device_encoding(sys.stdout.fileno()))
print(sys.getdefaultencoding())
> ```
我在Ubuntu20.04测试结果：
```bash
('zh_CN', 'UTF-8')
1
UTF-8
utf-8
```

**Comment by zhouzaida** [comment]
@creater-zq 请帮忙测试一下 https://github.com/open-mmlab/mmcv/pull/1905 是否可以解决该问题，只用修改本地环境对应的代码即可，谢谢

**Comment by creater-zq** [comment]
> @creater-zq 请帮忙测试一下 #1905 是否可以解决该问题，只用修改本地环境对应的代码即可，谢谢

* 正常工作，谢谢
![image](https://user-images.githubusercontent.com/59300179/164873670-e2aa1f2f-3369-4a04-b99b-247f92f06e57.png)

**Comment by YixingHuang** [comment]
> 

这个应该是PyCharm的问题，我电脑上也是pycharm里os.device_encoding(sys.stdout.fileno())得到的结果为None导致的这个bug
