### ISSUE TITLE
Mmseg test training iteration is time-consuming.

### ISSUE THREAD

**Issue by xiabo123** [open-mmlab/mmcv#1909]
![image](https://user-images.githubusercontent.com/40659418/164954000-6c084e81-4e05-4e39-82b6-823f937930b8.png)

According to the test log, is time a time-consuming iteration?

Is the corresponding code the execution time of the function train in the file 'mmcv\runner\iter_based_runner.py'?

**Comment by zhouzaida** [comment]
Hi @xiabo123 , the time consumption is not quite normal. Could you provide more environmental information?

**Comment by xiabo123** [comment]
Hi @zhouzaida ,
Test command：python3 tools/train.py configs/deeplabv3/deeplabv3_r50-d8_512x1024_40k_cityscapes.py
mmcv_full: 1.3.16
What I want to know is whether the time field in the output log is what I said?
![image](https://user-images.githubusercontent.com/40659418/164959506-e7ac249b-09bb-4596-8996-a8aa845e6737.png)

**Comment by xiabo123** [comment]
Hi @zhouzaida ,
The code is as follows
![image](https://user-images.githubusercontent.com/40659418/164959669-08325585-ba2f-4a18-a836-3e71d2c4bb71.png)

**Comment by xiabo123** [comment]
Hi @zhouzaida ,
The code is as follows
![image](https://user-images.githubusercontent.com/40659418/164959711-8a1a9e3c-7e48-440b-9478-8d81b22916d0.png)

**Comment by zhouzaida** [comment]
The time field contains consumption to load data and iterate a batch of data.

**Comment by zhouzaida** [comment]
The time field contains consumption to load data and iterate a batch of data.

**Comment by xiabo123** [comment]
@zhouzaida Excuse me again，The operation of the following code takes time. Is it an iterative training?
![image](https://user-images.githubusercontent.com/40659418/164960905-ea22b1b9-27d4-48b0-b9d6-784a57cf558e.png)

**Comment by zhouzaida** [comment]
Yet

**Comment by xiabo123** [comment]
@zhouzaida 
Thank you very much for your answer.
