### ISSUE TITLE
About time.sleep(2) in EpochBasedRunner

### ISSUE THREAD

**Issue by JihwanEom** [open-mmlab/mmcv#1912]
Hi,

I wonder there is any progress to replace this line: https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/epoch_based_runner.py#L46 - time.sleep(2) in EpochBasedRunner.

Like #1640, I agree with this method is not elegant and should be improved to prevent possible deadlock by epoch transition.

Could you explain why time.sleep(2) is need to prevent deadlock and I want to know whether there is any update for replace this code or more safe method to prevent deadlock.

Thank you.
Jihwan

**Comment by JihwanEom** [comment]
@zhouzaida  Any update?

**Comment by zhouzaida** [comment]
Sorry for the late reply. We were trying to reproduce the deadlock but failed. The reason why we added `time.sleep(2)` is to escape the deadlock we met before.

**Comment by JihwanEom** [comment]
Okay, thank you for your kind sharing. Please let me know if deadlock is reproduced or there is anything that I can help.

**Comment by zhouzaida** [comment]
> Okay, thank you for your kind sharing. Please let me know if deadlock is reproduced or there is anything that I can help.

OK, thanks for your feedback.
