### ISSUE TITLE
MLFlow Logger override epoch methods

### ISSUE THREAD

**Issue by dimimal** [open-mmlab/mmcv#1928]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the FAQ documentation but cannot get the expected help.

I am using a customised MLflowLogger class to export my mmdetection model training performance to mlflow. 
However, when I override the log() method, this method is called on every iteration. When I tried to override the `after_train_epoch()` and `after_val_epoch()`, I noticed that the log() method is bypassed and when train/val_epoch methods are called I get only the validation losses, without the validation map performance benchmarks. 

I am using the workflow = [(train, 1), (val, 1)] during the training. 
Does anyone know why do we get this behavior?
Also, is it possible to retrieve all the performance metrics somehow (val/bbox_map, val/segm_map ) and per class if possible??  

Thanks

**Comment by zhouzaida** [comment]
Hi, if log() was called on each iteration, please check the value of the interval.
https://github.com/open-mmlab/mmcv/blob/9f5a03dc2ca3731b2c1b18f90f826fcb9eb51ccf/mmcv/runner/hooks/logger/mlflow.py#L39

In addition, could your provide the snippets of your `after_train_epoch` and `after_val_epoch`?
