### ISSUE TITLE
NameError: name 'file_client_args' is not defined

### ISSUE THREAD

**Issue by lijinrun** [open-mmlab/mmcv#1929]
![image](https://user-images.githubusercontent.com/49092533/166097100-ea1b2134-697c-4b24-8b54-7939c5f71640.png)
How to solve this error，

**Comment by zhouzaida** [comment]
It seems like your config missed the file_client_args field. You can open an issue in mmtracking.

**Comment by lijinrun** [comment]
> It seems like your config missed the file_client_args field. You can open an issue in mmtracking (https://github.com/open-mmlab/mmtracking/issues).

Thank you very much.
