### ISSUE TITLE
error when install mmcv-full==1.2.7

### ISSUE THREAD

**Issue by Zztrans** [open-mmlab/mmcv#1930]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the FAQ documentation but cannot get the expected help.

when I install env on colab,
`pip install mmcv-full==1.2.7`

Several days ago, it is ok installed. But today I found it error.

The error message is

`Building wheels for collected packages: mmcv-full 
  Building wheel for mmcv-full (setup.py) ... error
  ERROR: Failed building wheel for mmcv-full
  Running setup.py clean for mmcv-full
Failed to build mmcv-full`

And I also find some advice say use 

`pip install mmcv=... f {https://download.openmmlab.com/mmcv/dist/cu.../torch.../index.html} `

But I can't find version about mmcv-full==1.2.7 . Almost >=1.3.1.

Is the version 1.2.7 not supported?

**Comment by zhouzaida** [comment]
What are your cuda and torch versions?

**Comment by Zztrans** [comment]
> What are your cuda and torch versions?

1.11.0+cu113.

**Comment by zhouzaida** [comment]
MMCV supports pre-built packages for cuda11.3 and torch1.11.0 since mmcv v1.4.7.

You can click the [URL](https://download.openmmlab.com/mmcv/dist/cu113/torch1.11/index.html) to see the supported versions.

**Comment by Zztrans** [comment]
> 



> MMCV supports pre-built packages for cuda11.3 and torch1.11.0 since mmcv v1.4.7.
> 
> You can click the [URL](https://download.openmmlab.com/mmcv/dist/cu113/torch1.11/index.html) to see the supported versions.

Somewhere may I find version 1.2.7?

**Comment by zhouzaida** [comment]
You can find version 1.2.7 at https://download.openmmlab.com/mmcv/dist/cu102/torch1.7.0/index.html or lower torch version.

**Comment by Zztrans** [comment]
Thanks a lot!

Maybe I should do some version-compatible work.
