### ISSUE TITLE
(use DCN)AttributeError: 'Version' object has no attribute 'release'

### ISSUE THREAD

**Issue by Zizzzzzzz** [open-mmlab/mmcv#1934]
when i import DCN:from mmcv.ops import DeformConv2dPack as DCN

```

> `Traceback (most recent call last):
>   File "main.py", line 11, in <module>
>     from model.model import create_model, load_model, save_model
>   File "/data/users/CHDHPC/2020224031/code/CenterTrack-DanceTrack/src/lib/model/model.py", line 10, in <module>
>     from .networks.dla import DLASeg
>   File "/data/users/CHDHPC/2020224031/code/CenterTrack-DanceTrack/src/lib/model/networks/dla.py", line 17, in <module>
>     from mmcv.ops import DeformConv2dPack as DCN
>   File "/data/users/CHDHPC/2020224031/anaconda3/envs/SiamMOT/lib/python3.6/site-packages/mmcv/__init__.py", line 4, in <module>
>     from .fileio import *
>   File "/data/users/CHDHPC/2020224031/anaconda3/envs/SiamMOT/lib/python3.6/site-packages/mmcv/fileio/__init__.py", line 2, in <module>
>     from .file_client import BaseStorageBackend, FileClient
>   File "/data/users/CHDHPC/2020224031/anaconda3/envs/SiamMOT/lib/python3.6/site-packages/mmcv/fileio/file_client.py", line 15, in <module>
>     from mmcv.utils.misc import has_method
>   File "/data/users/CHDHPC/2020224031/anaconda3/envs/SiamMOT/lib/python3.6/site-packages/mmcv/utils/__init__.py", line 40, in <module>
>     from .hub import load_url
>   File "/data/users/CHDHPC/2020224031/anaconda3/envs/SiamMOT/lib/python3.6/site-packages/mmcv/utils/hub.py", line 9, in <module>
>     if TORCH_VERSION != 'parrots' and digit_version(TORCH_VERSION) < digit_version(
>   File "/data/users/CHDHPC/2020224031/anaconda3/envs/SiamMOT/lib/python3.6/site-packages/mmcv/utils/version_utils.py", line 24, in digit_version
>     assert version.release, f'failed to parse version {version_str}'
> AttributeError: 'Version' object has no attribute 'release'`

```

my environment is cuda11.3,pytorch1.10.0,mmcv1.4.5
can someone help me?

**Comment by zhouzaida** [comment]
Hi, please upgrade your setuptools by `pip install -U setuptools`

More details at https://github.com/open-mmlab/mmcv/issues/1230

**Comment by Zizzzzzzz** [comment]
Thanks! But there is an another problem @zhouzaida 

> `Traceback (most recent call last):
>   File "main.py", line 11, in <module>
>     from model.model import create_model, load_model, save_model
>   File "/data/users/CHDHPC/2020224031/code/CenterTrack-DanceTrack/src/lib/model/model.py", line 10, in <module>
>     from .networks.dla import DLASeg
>   File "/data/users/CHDHPC/2020224031/code/CenterTrack-DanceTrack/src/lib/model/networks/dla.py", line 17, in <module>
>     from mmcv.ops import DeformConv2dPack as DCN
>   File "/data/users/CHDHPC/2020224031/anaconda3/envs/SiamMOT/lib/python3.6/site-packages/mmcv/__init__.py", line 4, in <module>
>     from .fileio import *
>   File "/data/users/CHDHPC/2020224031/anaconda3/envs/SiamMOT/lib/python3.6/site-packages/mmcv/fileio/__init__.py", line 2, in <module>
>     from .file_client import BaseStorageBackend, FileClient
>   File "/data/users/CHDHPC/2020224031/anaconda3/envs/SiamMOT/lib/python3.6/site-packages/mmcv/fileio/file_client.py", line 15, in <module>
>     from mmcv.utils.misc import has_method
>   File "/data/users/CHDHPC/2020224031/anaconda3/envs/SiamMOT/lib/python3.6/site-packages/mmcv/utils/__init__.py", line 39, in <module>
>     from .env import collect_env
>   File "/data/users/CHDHPC/2020224031/anaconda3/envs/SiamMOT/lib/python3.6/site-packages/mmcv/utils/env.py", line 9, in <module>
>     import cv2
>   File "/data/users/CHDHPC/2020224031/anaconda3/envs/SiamMOT/lib/python3.6/site-packages/cv2/__init__.py", line 5, in <module>
>     from .cv2 import *
> ImportError: dlopen: cannot load any more object with static TLS`

**Comment by zhouzaida** [comment]
Could you provide the output of `pip list`?

**Comment by zhouzaida** [comment]
https://github.com/pytorch/pytorch/issues/2575
https://github.com/scikit-learn/scikit-learn/issues/14485
