### ISSUE TITLE
How to check a checkpoint file for a specific config

### ISSUE THREAD

**Issue by ahmadmustafaanis** [open-mmlab/mmcv#1943]
**Checklist**

1. I have searched related issues but cannot get the expected help. 
YES
2. I have read the FAQ documentation but cannot get the expected help.
YES

-------

Let's say I want to use a different config i.e `vipnas_res50_coco_wholebody_256x192` or `hrnet_w32_halpe_256x192` How can I find the pre-trained model pth file URL for these configs? 
Thanks.

**Comment by teamwong111** [comment]
`vipnas_res50_coco_wholebody_256x192` is [here](https://github.com/open-mmlab/mmpose/blob/master/configs/wholebody/2d_kpt_sview_rgb_img/topdown_heatmap/coco-wholebody/vipnas_coco-wholebody.md). `hrnet_w32_halpe_256x192` seems no checkpoint. You can open an issue in mmpose to ask more details.
