### ISSUE TITLE
poly lr update hook

### ISSUE THREAD

**Issue by liuheng92** [open-mmlab/mmcv#1956]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the FAQ documentation but cannot get the expected help.

my training config

```
optimizer = dict(type='SGD', lr=0.063, momentum=0.9, weight_decay=1e-4)
optimizer_config = dict(grad_clip=None)
# learning policy
lr_config = dict(policy='poly', power=0.9, min_lr=1e-7, by_epoch=True)
```

lr gets 2e-5 when model finished the last epoch, why? lr should be 1e-7, right?

**Comment by zhouzaida** [comment]
Hi @liuheng92 , you can find the detail about poly at https://github.com/open-mmlab/mmcv/blob/a3b4640be8485afc5c04174616d01251f48b5716/mmcv/runner/hooks/lr_updater.py#L226

And you can visualize the lr using the script (https://github.com/open-mmlab/mmcv/blob/master/.dev_scripts/visualize_lr.py). Usage can be found at https://github.com/open-mmlab/mmcv/pull/1667
