### ISSUE TITLE
where to find the source code of nms_rotated

### ISSUE THREAD

**Issue by VCBE123** [open-mmlab/mmcv#1957]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the FAQ documentation but cannot get the expected help.

**Comment by VCBE123** [comment]
finaly i reach [there](https://github.com/facebookresearch/detectron2/tree/main/detectron2/layers/csrc/), [nms_rotate](https://github.com/facebookresearch/detectron2/tree/main/detectron2/layers/csrc/nms_rotate). Thanks anyway

**Comment by teamwong111** [comment]
[python interface](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/nms.py), [c++ interface](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/csrc/pytorch/nms_rotated.cpp), [c++ op](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/csrc/pytorch/cpu/nms_rotated.cpp), [cuda op](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/csrc/pytorch/cuda/nms_rotated_cuda.cu), [cuda kernel](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/csrc/common/cuda/nms_rotated_cuda.cuh)
