### ISSUE TITLE
How to gracefully kill a running?

### ISSUE THREAD

**Issue by makecent** [open-mmlab/mmcv#1961]
Sometimes we need to kill a training/testing for some reasons. Currently I use the short-cut `Ctrl + C` to stop a running `mmlab` process. 

However, sometimes I have to further use `nvidia-smi` and `kill` to release the GPU memory manually. Even worse, I found that sometimes the CPU memory were not released; And I cannot found the relavant process id so I have to restart the server to release the CPU memory.

Is there a graceful way to stop a running `mmlab` process and clear the occupied GPU and CPU memory?

**Comment by teamwong111** [comment]
Can `ps -ef` help you find the process id?

**Comment by makecent** [comment]
> Can `ps -ef` help you find the process id?

Thanks for the reply. I'd like to have a try once my current training are finished.
