### ISSUE TITLE
When I run my own trained dataset model, an error occurs（pycharm）

### ISSUE THREAD

**Issue by icehumana** [open-mmlab/mmcv#1963]
![1YBIUVIY9XEKLRFBZ_SS3A](https://user-images.githubusercontent.com/97574209/168576957-89efd33d-bdb7-4cef-8094-aa4a52c9200a.png)
![GRJ25I)L05 I`PW2JW@_~TD](https://user-images.githubusercontent.com/97574209/168577068-81e1dcdc-a37e-4452-83f8-d453b80350b9.png)
![DNU(M1P(}2N8}ZY71_H 88C](https://user-images.githubusercontent.com/97574209/168577240-6f7f37ef-1273-4a1e-9a78-d47533ff95c9.png)
I tried almost all the available mmcv versions and these versions are all this bug

**Comment by zhouzaida** [comment]
Hi, you can open an issue at https://github.com/open-mmlab/mmclassification/issues.
