### ISSUE TITLE
AssertionError: active_rotated_filter_forward miss in module _ext

### ISSUE THREAD

**Issue by 2292301049** [open-mmlab/mmcv#2022]
安装好mmdection和mmcv后，从mmcv库中导出SAConv模块，运行时报错AssertionError: active_rotated_filter_forward miss in module _ext

**Comment by zhouzaida** [comment]
请问你的 mmcv 是哪个版本

**Comment by 2292301049** [comment]
torch1.70+cuda110,mmcv3.5

**Comment by HerTenSu** [comment]
我把mmcv降级之后就没有这个问题了
mmcv1.4.0

**Comment by 2292301049** [comment]
我用的1.3.5，已经不能再降了



---Original---
From: ***@***.***&gt;
Date: Mon, May 30, 2022 20:52 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [open-mmlab/mmcv] AssertionError: active_rotated_filter_forwardmiss in module _ext (Issue #2022)




 
我把mmcv降级之后就没有这个问题了
 mmcv1.4.0

**Comment by 2292301049** [comment]
好的，非常感谢，换成1.5.0版本的解决了



---Original---
From: "Zaida ***@***.***&gt;
Date: Mon, May 30, 2022 22:41 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [open-mmlab/mmcv] AssertionError: active_rotated_filter_forward miss in module _ext (Issue #2022)




 
1.3.5 还没有这个算子

**Comment by 2292301049** [comment]
torch1.7.0+cuda110,mmcv3.5



---Original---
From: "Zaida ***@***.***&gt;
Date: Sun, May 29, 2022 00:31 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [open-mmlab/mmcv] AssertionError: active_rotated_filter_forward miss in module _ext (Issue #2022)




 
请问你的 mmcv 是哪个版本
