### ISSUE TITLE
ERROR: Package 'mdformat' requires a different Python: 3.6.12 not in '<4.0,>=3.7'

### ISSUE THREAD

**Issue by zcyKTH** [open-mmlab/mmcv#2028]
The version of python noted in README is 3.6+. However, lint `mdformat` should be configured based on python in '<4.0,>=3.7'.

**Comment by zhouzaida** [comment]
Thanks for your feedback. mdformat requires python>=3.7 so we will downgrade the version of mdformat to support python3.6.
