### ISSUE TITLE
Versions after v1.4.6 can not be compiled on ROCM. 

### ISSUE THREAD

**Issue by xiabo123** [open-mmlab/mmcv#2035]
The following error occurs in the newly added file in v1.4.6.
It seems that the transcoding of the newly added file is incorrect.
![image](https://user-images.githubusercontent.com/40659418/171312603-4f50cd85-249a-460f-8c8d-b3e148232eb1.png)

**Comment by imabackstabber** [comment]
This may be related to #1949 , so may @teamwong111 and @grimoire can help.

**Comment by zhouzaida** [comment]
resolved by https://github.com/open-mmlab/mmcv/pull/1918
