### ISSUE TITLE
Installation - RuntimeError: Detected CUDA version mismatch

### ISSUE THREAD

**Issue by connor-john** [open-mmlab/mmcv#2038]
Any idea why this is happening suddenly for me?

```
conda create -n mmlab python=3.7
conda activate mmlab
```
```
conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch
```
```py
import torch
print(torch.version.cuda)
```
```
11.3
```
```
pip install mmcv-full==1.4.0 -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.11/index.html
```
```
   raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
    RuntimeError:
    The detected CUDA version (10.1) mismatches the version that was used to compile
    PyTorch (11.3). Please make sure to use the same CUDA versions.
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/connor/anaconda3/envs/mmlab/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qxe55gjg/mmcv-full_795d7f6e5c3d4443bcae582b5dbece2a/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qxe55gjg/mmcv-full_795d7f6e5c3d4443bcae582b5dbece2a/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-qp1gw908/install-record.txt --single-version-externally-managed --compile --install-headers /home/connor/anaconda3/envs/mmlab/include/python3.7m/mmcv-full Check the logs for full command output.
```

My nvcc --version is 10.1, but this issue never used to happen before

system: Ubuntu 18.04 LTS

Any help appreciated, thank you

**Comment by HAOCHENYE** [comment]
Hi~ thanks for your feedback,  the installation of `mmcv-full` will compile cuda-ops with your local nvcc.  It could be better to make your nvcc version consistent with your PyTorch and mmcv cuda version.

It could be better if you can provide the hardware environment (GPU) and **complete error logs**. These will help us to  locate the problem more accurately.

**Comment by connor-john** [comment]
Thanks @HAOCHENYE, I'll attempt with a lower PyTorch version,

I'll close the issue and follow up if I have any issues again, 

Thanks again.

**Comment by rlleshi** [comment]
@HAOCHENYE I currently have `mmcv-full` 1.4.5 running with torch 1.10.0 (cu113) on a 10.1 CUDA driver (as well as similar variations on a couple of other environments).

However, the latest installs of mmcv will throw an error if there is a version mismatch (e.g. 10.1 vs 11.3)

Why is this the case so long as my setup is still working as is the case with my old environments? Wouldn't it be better to leave it to the user's discretion and give a warning for the version mismatch instead of throwing an error?
