### ISSUE TITLE
ModuleNotFoundError: No module named 'mmcv._ext'

### ISSUE THREAD

**Issue by liyiwei979621500** [open-mmlab/mmcv#204]
I clone the repo and run pip install.

When I run test_image.py, this error shows up.

https://github.com/open-mmlab/mmcv/blob/120c6a64daefe97d451cbea4eae15af0ade50a17/mmcv/video/optflow.py#L4

**Comment by xjock** [comment]
Just cd ..

**Comment by DuinoDu** [comment]
Any update?

**Comment by DuinoDu** [comment]
Build mmcv with `MMCV_WITH_OPS=1` may help.

**Comment by lui-shex** [comment]
what you mean Build mmcv with MMCV_WITH_OPS=1 ?

**Comment by lui-shex** [comment]
what you mean MMCV_WITH_OPS=1?  I can't run MMCV_WITH_OPS=1 pip install -e .

**Comment by NikZak** [comment]
<b>Workaround</b>:
pip uninstall mmcv mmcv-full
git clone https://github.com/open-mmlab/mmcv.git
cd mmcv
MMCV_WITH_OPS=1 pip install -e .

**Comment by sailfish009** [comment]
> Workaround:
> pip uninstall mmcv mmcv-full
> git clone https://github.com/open-mmlab/mmcv.git
> cd mmcv
> MMCV_WITH_OPS=1 pip install -e .

Thanks! works for me.

**Comment by guofuxin** [comment]
> what you mean MMCV_WITH_OPS=1? I can't run MMCV_WITH_OPS=1 pip install -e .

I also can't run it.Are  you  deal  with  it?

**Comment by guofuxin** [comment]
> MMCV_WITH_OPS=1 pip install -e
 
I can't  run  MMCV_WITH_OPS=1 pip install -e,
the  terminal is "  -e option requires 1 argument"，
can  you   help  me  ? thank  you   very   much

**Comment by NikZak** [comment]
You should not forget the dot at the end ".". Which just means installing from current directory.
It is not
MMCV_WITH_OPS=1 pip install -e
It is
MMCV_WITH_OPS=1 pip install -e .

**Comment by liuligang123** [comment]
I run the MMCV_WITH_OPS=1 pip install -e . and then solve the problem
just wait when running setup.py develop for mmcv-full

**Comment by Never-up** [comment]
> I run the MMCV_WITH_OPS=1 pip install -e . and then solve the problem
> just wait when running setup.py develop for mmcv-full

请问你解决了吗，我也遇到了

**Comment by VoldemortGin** [comment]
> I run the MMCV_WITH_OPS=1 pip install -e . and then solve the problem

That didn't work for me. And my mmcv version is 1.1.3. Still, I got `ModuleNotFoundError: No module named 'mmcv._ext'` Error when I tried to run a demo.

Any solution? My log is as below:
```bash
python demo/image_demo.py demo/demo.jpg configs/mask_rcnn/mask_rcnn_x101_64x4d_fpn_1x_coco.py 

checkpoints/mask_rcnn_x101_64x4d_fpn_1x_coco_20200201-9352eb0d.pth 
Traceback (most recent call last):
  File "demo/image_demo.py", line 3, in <module>
    from mmdet.apis import inference_detector, init_detector, show_result_pyplot
  File "/home/linhan/workspace/mmcv/mmdetection/mmdet/apis/__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/home/linhan/workspace/mmcv/mmdetection/mmdet/apis/inference.py", line 7, in <module>
    from mmcv.ops import RoIAlign, RoIPool
  File "/home/linhan/anaconda3/lib/python3.7/site-packages/mmcv-1.1.3-py3.7-linux-x86_64.egg/mmcv/ops/__init__.py", line 1, in <module>
    from .bbox import bbox_overlaps
  File "/home/linhan/anaconda3/lib/python3.7/site-packages/mmcv-1.1.3-py3.7-linux-x86_64.egg/mmcv/ops/bbox.py", line 3, in <module>
    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
  File "/home/linhan/anaconda3/lib/python3.7/site-packages/mmcv-1.1.3-py3.7-linux-x86_64.egg/mmcv/utils/ext_loader.py", line 11, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/linhan/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'
```
Thank you in advance.

**Comment by neomukul** [comment]
@VoldemortGin are you able to resolve this issue, I am also having the same issue.
if i Install mmcv-full it is not working as mmcv-1.2 version is not compatible with mmdet and if i install mmcv-1.1.3 it throws error "ModuleNotFoundError: No module named 'mmcv._ext'"?

**Comment by surendrallam** [comment]
> Workaround:
> pip uninstall mmcv mmcv-full
> git clone https://github.com/open-mmlab/mmcv.git
> cd mmcv
> MMCV_WITH_OPS=1 pip install -e .

This worked for me... Thanks a ton @NikZak

**Comment by korhun** [comment]
For windows, this worked for me:

pip uninstall mmcv
pip uninstall mmcv-full
git clone https://github.com/open-mmlab/mmcv.git
cd mmcv
set MMCV_WITH_OPS=1
pip install -e .

**Comment by surendrallam** [comment]
This will work in RISC-V, I installed it on SiFive Unleashed board, it worked for me.

pip uninstall mmcv
pip uninstall mmcv-full
git clone https://github.com/open-mmlab/mmcv.git
cd mmcv
set MMCV_WITH_OPS=1
pip install -e .

Thanks and Regards,
Surendra Allam,
Senior Software Engineer,
Exaleap Semiconductors,
Bangalore, India.

Sent from my iPhone

On 03-Feb-2021, at 7:52 PM, Koray Orhun <notifications@github.com> wrote:

﻿

For windows, this worked for me:

pip uninstall mmcv
pip uninstall mmcv-full
git clone https://github.com/open-mmlab/mmcv.git
cd mmcv
set MMCV_WITH_OPS=1
pip install -e .

**Comment by SamMohel** [comment]
> > I run the MMCV_WITH_OPS=1 pip install -e . and then solve the problem
> 
> That didn't work for me. And my mmcv version is 1.1.3. Still, I got `ModuleNotFoundError: No module named 'mmcv._ext'` Error when I tried to run a demo.
> 
> Any solution? My log is as below:
> 
> ```shell
> python demo/image_demo.py demo/demo.jpg configs/mask_rcnn/mask_rcnn_x101_64x4d_fpn_1x_coco.py 
> 
> checkpoints/mask_rcnn_x101_64x4d_fpn_1x_coco_20200201-9352eb0d.pth 
> Traceback (most recent call last):
>   File "demo/image_demo.py", line 3, in <module>
>     from mmdet.apis import inference_detector, init_detector, show_result_pyplot
>   File "/home/linhan/workspace/mmcv/mmdetection/mmdet/apis/__init__.py", line 1, in <module>
>     from .inference import (async_inference_detector, inference_detector,
>   File "/home/linhan/workspace/mmcv/mmdetection/mmdet/apis/inference.py", line 7, in <module>
>     from mmcv.ops import RoIAlign, RoIPool
>   File "/home/linhan/anaconda3/lib/python3.7/site-packages/mmcv-1.1.3-py3.7-linux-x86_64.egg/mmcv/ops/__init__.py", line 1, in <module>
>     from .bbox import bbox_overlaps
>   File "/home/linhan/anaconda3/lib/python3.7/site-packages/mmcv-1.1.3-py3.7-linux-x86_64.egg/mmcv/ops/bbox.py", line 3, in <module>
>     ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
>   File "/home/linhan/anaconda3/lib/python3.7/site-packages/mmcv-1.1.3-py3.7-linux-x86_64.egg/mmcv/utils/ext_loader.py", line 11, in load_ext
>     ext = importlib.import_module('mmcv.' + name)
>   File "/home/linhan/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
> ModuleNotFoundError: No module named 'mmcv._ext'
> ```
> 
> Thank you in advance.

did you solve it ?

**Comment by TheFebrin** [comment]
For people still struggling with this error: `ModuleNotFoundError: No module named 'mmcv._ext'`

1. It's important that pytorch - cuda - mmcv are compatible  
2. Therefore first you should check your cuda version `nvidia-smi`
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.102.04   Driver Version: 450.102.04   CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
```

For example mine is `11.0`

3. Then download correct pytorch:
```
pip install torch==1.8.0+cu111 torchvision==0.9.0+cu111 torchaudio==0.8.0 -f https://download.pytorch.org/whl/torch_stable.html
```
This is Pytorch 1.8.0 with cuda 11.1.

4. Install correct mmcv as they mention in their [README](https://github.com/open-mmlab/mmdetection/blob/master/docs/get_started.md)
```
pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.8.0/index.html
```
`/cu111/torch1.8.0/` see how cuda and torch versions are matching

5. It should work 😃  
```
Python 3.7.5 (default, Feb 23 2021, 13:22:40) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from mmcv.ops import get_compiling_cuda_version, get_compiler_version
>>> print(get_compiling_cuda_version())
11.1
>>> print(get_compiler_version())
GCC 7.3
>>> 
```

PS Here's our [project](https://github.com/TheFebrin/Deep-Learning-Project-Instance-Segmentation) where we used `mmdet`

**Comment by THEBEST-cloud** [comment]
> > what you mean MMCV_WITH_OPS=1? I can't run MMCV_WITH_OPS=1 pip install -e .
> 
> I also can't run it.Are you deal wi

> > I run the MMCV_WITH_OPS=1 pip install -e . and then solve the problem
> > just wait when running setup.py develop for mmcv-full
> 
> 请问你解决了吗，我也遇到了

请问怎么解决的啊 MMCV_WITH_OPS=1 pip install -e .这个命令执行报错 'MMCV_WITH_OPS' 不是内部或外部命令，也不是可运行的程序

**Comment by XuhuiJiang** [comment]
> For windows, this worked for me:
> 
> pip uninstall mmcv
> pip uninstall mmcv-full
> git clone https://github.com/open-mmlab/mmcv.git
> cd mmcv
> set MMCV_WITH_OPS=1
> pip install -e .

this is the accuracy

**Comment by jankrans** [comment]
> > For windows, this worked for me:
> > pip uninstall mmcv
> > pip uninstall mmcv-full
> > git clone https://github.com/open-mmlab/mmcv.git
> > cd mmcv
> > set MMCV_WITH_OPS=1
> > pip install -e .

Still getting the error mentioned in the title when trying this on windows conda environment.
cudatoolkit=11.3.1
mmcv=1.4.5
mmdet=2.21.0
python=3.7.11
torchvision=0.11.3

Would also rather have the mmdet-full. Been struggling for a long time with all these versions. Someone with a working windows version that could provide quick explanation?

**Comment by Lucifer60** [comment]
> 

I am really appreciate that after stuggling one day on  "No module named 'mmcv._ext'" problem that after

**Comment by Lucifer60** [comment]
I am really appreciate that after stuggling one day on "No module named 'mmcv._ext'" problem that after uninstall mmcv-full and uninstall mmcv .I can't pip install -e. So I use your method "pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.8.0/index.html" And it work well now.

**Comment by EgShes** [comment]
For me helped

1. Install right version of torch for your cuda. Get command from [here](https://pytorch.org/get-started/previous-versions/)
`pip install torch==2.0.0 torchvision==0.15.1 torchaudio==2.0.1 --index-url https://download.pytorch.org/whl/cu118`
2. Install right mmcv for your torch. Get command from [here](https://mmcv.readthedocs.io/en/latest/get_started/installation.html#install-with-pip)
`pip install mmcv==2.0.1 -f https://download.openmmlab.com/mmcv/dist/cu118/torch2.0/index.html`

**Comment by rhelck** [comment]
Have the same issue, the approaches listed here do not work for me

This is the only thing preventing me from using your model, could you guys either simplify the installation process or provide more reliable instructions for installing the model?

I don't mean to come across as impatient, but I was excited to use your model after seeing your object detection benchmark results, and this issue looks like its been around for a while

**Comment by hutIngk** [comment]
> Workaround: pip uninstall mmcv mmcv-full git clone https://github.com/open-mmlab/mmcv.git cd mmcv MMCV_WITH_OPS=1 pip install -e .

sry, i have tried your method, but it is seems to work failed in Windows，it reports MMCV_WITH_OPS is not a inner or out command, so are u guys who said to slove this problem all work on linux or other else ?

**Comment by yhbcode000** [comment]
My solution, I have no idea what the side effect is, but it works fine.

<img width="945" height="472" alt="Image" src="https://github.com/user-attachments/assets/fb25b7ea-7f89-439a-9dd1-4bb581862cb7" />
