### ISSUE TITLE
Can the default InstanceNormalization replacement with MMCVInstanceNormalization be made optional?

### ISSUE THREAD

**Issue by serser** [open-mmlab/mmcv#2043]
I'm with `mmcv-full==1.3.16`, trying to export trt engine with mmcv's exporter but failed with,

```
[06/07/2022-00:28:05] [TRT] [E] 3: getPluginCreator could not find plugin: MMCVInstanceNormalization version: 1
Traceback (most recent call last):
  File "tools/deployment/onnx2tensorrt.py", line 145, in <module>
    workspace_size=args.workspace_size)
  File "tools/deployment/onnx2tensorrt.py", line 47, in onnx2tensorrt
    max_workspace_size=max_workspace_size)
  File "/path/to/my/conda_env/open-mmlab/lib/python3.7/site-packages/mmcv/tensorrt/tensorrt_utils.py", line 63, in onnx2trt
    raise RuntimeError(f'parse onnx failed:\n{error_msgs}')
RuntimeError: parse onnx failed:
In node 6 (importFallbackPluginImporter): UNSUPPORTED_NODE: Assertion failed: creator && "Plugin not found, are the plugin name, version, and namespace correct?"
```

My onnx can be successfully exported by native trtexec. It seems TensorRT 7.2+ readily supports this operation. I have to otherwise register MMCVInstanceNormalization plugin somehow. Could you also show me show to do the latter?

**Comment by serser** [comment]
Figured out that `mmcv==1.3.16` can be compiled with `TensorRT 7.2.3.4`, so that `MMCVInstanceNormalization` plugin can be supported. But higher TensorRT 8+ produces errors. 
```
TENSORRT_DIR=/path/to/TensorRT-7.2.3.4 MMCV_WITH_OPS=1 MMCV_WITH_TRT=1 pip install -e .
```

**Comment by serser** [comment]
This however generated an engine that can't be deserialized due to tag mismatch. Confirmed to have same version of TensorRT.

```
[TensorRT] ERROR: coreReadArchive.cpp (32) - Serialization Error in verifyHeader: 0 (Magic tag does not match)
[TensorRT] ERROR: INVALID_STATE: std::exception
[TensorRT] ERROR: INVALID_CONFIG: Deserialize the cuda engine failed.
```

> Figured out that `mmcv==1.3.16` can be compiled with `TensorRT 7.2.3.4`,
> 
> ```
> TENSORRT_DIR=/path/to/TensorRT-7.2.3.4 MMCV_WITH_OPS=1 MMCV_WITH_TRT=1 pip install -e .
> ```
> 
> so that `MMCVInstanceNormalization` plugin can be supported. But higher TensorRT 8+ produces compilation errors.

**Comment by grimoire** [comment]
> This however generated an engine that can't be deserialized due to tag mismatch. Confirmed to have same version of TensorRT.

As far as I know, the tag is used to distinguish different TensorRT versions. Could you check the environment again? You can use `ldd` on the related libraries to see which TensorRT are they linked to.

**Comment by serser** [comment]
Tried out MMDeploy, it seems that torch 1.7 is not supported [here](https://github.com/open-mmlab/mmdeploy/blob/2a0fcb6e71ff1ec937079e1e7f577eb500123a20/mmdeploy/pytorch/ops/instance_norm.py#L6).

**Comment by serser** [comment]
> > This however generated an engine that can't be deserialized due to tag mismatch. Confirmed to have same version of TensorRT.
> 
> As far as I know, the tag is used to distinguish different TensorRT versions. Could you check the environment again? You can use `ldd` on the related libraries to see which TensorRT are they linked to.

Aye. I was using the version compiled w/ the above mentioned flags to convert engines (`mmcv.tensorrt.onnx2trt`) and loaded it with `mmcv.tensorrt.TRTWraper`, all along with TensorRT-7.2.3.4 python package. I am puzzled to find the version mismatch though.
