### ISSUE TITLE
How to get the middle layer output of a model for use in downstream models？

### ISSUE THREAD

**Issue by wangych6** [open-mmlab/mmcv#2049]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the FAQ documentation but cannot get the expected help.

For example, in the TSN model, I want to get the output (embedding representation) before the classification head of the model, how should I do it?

**Comment by HAOCHENYE** [comment]
Hi~ Suggest using [register_forward_hook](https://pytorch.org/docs/stable/generated/torch.nn.Module.html?highlight=register_forward_hook#torch.nn.Module.register_forward_hook) to register callback functions, and then get the result from target module. 

For example:

```python
class MyNet(nn.Module):
    def __init__(self):
        super(MyNet, self).__init__()
        self.conv1 = nn.Conv2d(1, 1, 1)
        self.conv2 = nn.Conv2d(1, 1, 1)

    def forward(self, inputs):
        return self.conv1(self.conv2(inputs))


results = dict()


def get_conv1_result(module, inputs, outputs):
    results['conv1'] = outputs


net = MyNet()
net.conv1.register_forward_hook(get_conv1_result)
net(torch.randn(1, 1, 1, 1))
print(results['conv1'])
```

**Comment by wangych6** [comment]
Thanks a lot, this solved my problem perfectly@ @HAOCHENYE
