### ISSUE TITLE
KeyError: 'data_time' in TextLoggerHook

### ISSUE THREAD

**Issue by andreasHan** [open-mmlab/mmcv#2055]
Hello，i.ve fonud a problem at the latest version at TextLoggerHook，when print the log。

![image](https://user-images.githubusercontent.com/38367299/173506594-30eceb94-1b96-4f1c-8a94-14c5910f5f05.png)

It appears that when doing evaluation， the log buffer will be cleared, and because the priority of evaluation hook is higher than  IterTimerHook and TextLoggerHook, so the ‘time’ info is saved in log buffer but the 'data_time' is cleared.

![image](https://user-images.githubusercontent.com/38367299/173506385-6291feae-b702-46e3-ad64-ff0908f5f7da.png)

![image](https://user-images.githubusercontent.com/38367299/173506160-2e153f9b-adb0-456a-aaff-1b0a9a7d925d.png)

Thanks a lot! :）

**Comment by zhouzaida** [comment]
Hi, thanks for your report. Please refer to https://github.com/open-mmlab/mmdetection/blob/ca11860f4f3c3ca2ce8340e2686eeaec05b29111/mmdet/apis/train.py#L232.
