### ISSUE TITLE
ModuleNotFoundError: No module named 'mmcv._ext'

### ISSUE THREAD

**Issue by tricksterANDthug** [open-mmlab/mmcv#2059]
ModuleNotFoundError: No module named 'mmcv._ext'
why?

**Comment by RuijieZhu94** [comment]
I have the same question. Any solutions?

**Comment by MK0820** [comment]
**OS**: Mac OS
**torch**: 1.9.1
**torchvision**: 0.10.1
**torchaudio**: 0.9.1
**mmcv-full**: 1.7.0

```bash
  File "/myenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'
```
The same question.

**Comment by garychan22** [comment]
I have the same question. Any solutions?

**Comment by sgraine** [comment]
I have the same problem! Any updates?

**Comment by jacksteussie** [comment]
still no solution?

**Comment by sinopec** [comment]
I have the same problem! Any updates?

**Comment by SamuelMarks** [comment]
Same issue, any updates?
