### ISSUE TITLE
cannot import name 'IS_MLU_AVAILABLE' from 'mmcv.utils'

### ISSUE THREAD

**Issue by liuyx599** [open-mmlab/mmcv#2064]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the FAQ documentation but cannot get the expected help.

Hello, I get an error when I try to run the following statement

`from mmcv.runner import load_checkpoint`

The error info is:
```python
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/tmp/ipykernel_215/2518613678.py in <module>
----> 1 from mmcv.runner import load_checkpoint

/opt/conda/lib/python3.8/site-packages/mmcv/runner/__init__.py in <module>
      1 # Copyright (c) OpenMMLab. All rights reserved.
----> 2 from .base_module import BaseModule, ModuleDict, ModuleList, Sequential
      3 from .base_runner import BaseRunner
      4 from .builder import RUNNERS, build_runner
      5 from .checkpoint import (CheckpointLoader, _load_checkpoint,

/opt/conda/lib/python3.8/site-packages/mmcv/runner/base_module.py in <module>
      9 import torch.nn as nn
     10 
---> 11 from mmcv.runner.dist_utils import master_only
     12 from mmcv.utils.logging import get_logger, logger_initialized, print_log
     13 

/opt/conda/lib/python3.8/site-packages/mmcv/runner/dist_utils.py in <module>
     14                           _unflatten_dense_tensors)
     15 
---> 16 from mmcv.utils import IS_MLU_AVAILABLE
     17 
     18 

ImportError: cannot import name 'IS_MLU_AVAILABLE' from 'mmcv.utils' (/opt/conda/lib/python3.8/site-packages/mmcv/utils/__init__.py)
```

my env list:
```
mmcv                      1.5.3                    pypi_0    pypi
mmcv-full                 1.5.3                    pypi_0    pypi
pytorch                   1.11.0          py3.8_cuda11.3_cudnn8.2.0_0 
````

i can find the attribute `IS_MLU_AVAILABLE` in /opt/conda/lib/python3.8/site-packages/mmcv/utils/__init__.py
![image](https://user-images.githubusercontent.com/75027570/174520122-9f7a8e6a-c4ab-4ecd-807c-c0b792df9d12.png)

**Comment by liuyx599** [comment]
Thank you very much, after I uninstalled and reinstalled everything seems to be bug free!

**Comment by hoseinCode** [comment]
hi what do i should uninstall and reinstall for fixing this error?

**Comment by LittleFay2** [comment]
> hi what do i should uninstall and reinstall for fixing this error?

I have the same problem.

**Comment by LittleFay2** [comment]
> hi what do i should uninstall and reinstall for fixing this error?

I reinstall mmcv, and the problem is resolved.
`pip install mmcv==2.0.0rc4 -f https://download.openmmlab.com/mmcv/dist/cu117/torch1.13/index.html`

**Comment by StellarOdys2ey** [comment]
have you solved the problem now?
