### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by leetesua** [open-mmlab/mmcv#2068]
hello fellows, when I run:

**pip install mmcv-full==1.4 -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.11.0/index.html**

I got a long long red error, and at the end, it says:

**ERROR: Command errored out with exit status 1: /home/lidexuan/anaconda3/envs/open-mmlab/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7bf7beha/mmcv-full_6aadf3cb45714e1f90c19497209299d3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7bf7beha/mmcv-full_6aadf3cb45714e1f90c19497209299d3/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-k9w9iyws/install-record.txt --single-version-externally-managed --compile --install-headers /home/lidexuan/anaconda3/envs/open-mmlab/include/python3.10/mmcv-full Check the logs for full command output.**

any idea?

**Comment by zhouzaida** [comment]
Hi @leetesua , Since 1.4.7, mmcv-full provided pre-built packages for cu113-torch1.11.0 so specifing `mmcv-full==1.4` can not obtain pre-built packages. You can use `pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.11.0/index.html` to install the latest packages.
