### ISSUE TITLE
How to save mmcv module with torch.jit.trace or torch.jit.script?

### ISSUE THREAD

**Issue by bigmindapp** [open-mmlab/mmcv#2072]
I want to convert some model to Coreml. But it seems it should be run torch.jit.trace or torch.jit.script first.
It will always be failed and stoped at ModulatedDeformConv2dFunction which contained in mmcv.
Does MMCV support Torch Script?
Thanks

**Comment by grimoire** [comment]
Custom autograd.Function can not be serialize in torchscript (yes, they can be trace/script, but you can't save it to a file).
You need a custom extension to support the module you want [like this](https://pytorch.org/tutorials/advanced/torch_script_custom_ops.html).
