### ISSUE TITLE
How to use mmcv data augmentation methods in other mm repos eg. mmdet mmrotate ?

### ISSUE THREAD

**Issue by marson666** [open-mmlab/mmcv#2076]
I'm trying to use mmcv data augmentation methods in mmrotate, but it occurs an error, how to use  them in other mm repos ?
Error:
KeyError: "DOTADataset: 'ColorJitter is not in the pipeline registry'"

train_pipeline in config file:
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='RResize', img_scale=(1024, 1024)),
    dict(
        type='ColorJitter',
        brightness=0.5,    # 亮度变化范围（0.5 ~ 1.5)
        contrast=0.5,      # 对比度变化范围（0.5 ~ 1.5)
        saturation=0.5,    # 饱和度变化范围（0.5 ~ 1.5)
        # 色相变换应用较少，目前 MMClassification 暂不支持 Hue 的增强
    ),
    dict(
        type='RRandomFlip',
        flip_ratio=[0.25, 0.25, 0.25],
        direction=['horizontal', 'vertical', 'diagonal'],
        version=angle_version),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
]

**Comment by zhouzaida** [comment]
Hi @marson666 , ColorJitter should be a class defined in mmcls and mmdet can not use the transform from mmcls because they don't have the same parent registry.
