### ISSUE TITLE
Support for DeepSpeed

### ISSUE THREAD

**Issue by slyviacassell** [open-mmlab/mmcv#2077]
**Describe the feature**
Does the mmcv have the interfaces to integrate the deepspeed?

**Comment by zhouzaida** [comment]
Hi @slyviacassell , mmcv have not integrated the `deepspeed` temporarily but we may support it in the future.

**Comment by slyviacassell** [comment]
Hi, @zhouzaida , thanks. I am waiting for it. Closed.

**Comment by weitunglin** [comment]
Hi, is there any timeline for supporting deepspeed or other similar library can be shared?
