### ISSUE TITLE
mmcv from source installation issue 

### ISSUE THREAD

**Issue by khaledmohamed00** [open-mmlab/mmcv#2078]
when i try to install mmcv from source i get this error : 
**environment** 
ubuntu 22.04
Python 3.7.13  [GCC 7.5.0]
pytorch 1.10.1
cuda 11.1

the version of mmcv does not matter 

when i run this command `MMCV_WITH_OPS=1 pip install -e .`

i get this error 

> Obtaining file:///home/adtrain/mmcv
Requirement already satisfied: addict in /home/adtrain/anaconda3/envs/bevfusion_env/lib/python3.7/site-packages (from mmcv-full==1.4.0) (2.4.0)
Requirement already satisfied: numpy in /home/adtrain/anaconda3/envs/bevfusion_env/lib/python3.7/site-packages (from mmcv-full==1.4.0) (1.21.5)
Requirement already satisfied: packaging in /home/adtrain/anaconda3/envs/bevfusion_env/lib/python3.7/site-packages (from mmcv-full==1.4.0) (21.3)
Requirement already satisfied: Pillow in /home/adtrain/anaconda3/envs/bevfusion_env/lib/python3.7/site-packages (from mmcv-full==1.4.0) (9.0.1)
Requirement already satisfied: pyyaml in /home/adtrain/anaconda3/envs/bevfusion_env/lib/python3.7/site-packages (from mmcv-full==1.4.0) (6.0)
Requirement already satisfied: yapf in /home/adtrain/anaconda3/envs/bevfusion_env/lib/python3.7/site-packages (from mmcv-full==1.4.0) (0.32.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /home/adtrain/anaconda3/envs/bevfusion_env/lib/python3.7/site-packages (from packaging->mmcv-full==1.4.0) (3.0.9)
Installing collected packages: mmcv-full
  Attempting uninstall: mmcv-full
    Found existing installation: mmcv-full 1.3.8
    Uninstalling mmcv-full-1.3.8:
      Successfully uninstalled mmcv-full-1.3.8
  Running setup.py develop for mmcv-full
    ERROR: Command errored out with exit status 1:
     command: /home/adtrain/anaconda3/envs/bevfusion_env/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/adtrain/mmcv/setup.py'"'"'; __file__='"'"'/home/adtrain/mmcv/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/adtrain/mmcv/
    Complete output (24 lines):
    running develop
    running egg_info
    writing mmcv_full.egg-info/PKG-INFO
    writing dependency_links to mmcv_full.egg-info/dependency_links.txt
    writing requirements to mmcv_full.egg-info/requires.txt
    writing top-level names to mmcv_full.egg-info/top_level.txt
    reading manifest file 'mmcv_full.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    adding license file 'LICENSE'
    adding license file 'LICENSES.md'
    writing manifest file 'mmcv_full.egg-info/SOURCES.txt'
    running build_ext
    building 'mmcv._ext' extension
    gcc -pthread -B /home/adtrain/anaconda3/envs/bevfusion_env/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DMMCV_WITH_CUDA -I/home/adtrain/mmcv/mmcv/ops/csrc/common -I/home/adtrain/mmcv/mmcv/ops/csrc/common/cuda -I/home/adtrain/anaconda3/envs/bevfusion_env/lib/python3.7/site-packages/torch/include -I/home/adtrain/anaconda3/envs/bevfusion_env/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/adtrain/anaconda3/envs/bevfusion_env/lib/python3.7/site-packages/torch/include/TH -I/home/adtrain/anaconda3/envs/bevfusion_env/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-11.1/include -I/home/adtrain/anaconda3/envs/bevfusion_env/include/python3.7m -c ./mmcv/ops/csrc/pytorch/assign_score_withk.cpp -o build/temp.linux-x86_64-3.7/./mmcv/ops/csrc/pytorch/assign_score_withk.o -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0
    gcc: error trying to exec 'cc1plus': execvp: No such file or directory
    /home/adtrain/anaconda3/envs/bevfusion_env/lib/python3.7/site-packages/setuptools/installer.py:30: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
      SetuptoolsDeprecationWarning,
    /home/adtrain/anaconda3/envs/bevfusion_env/lib/python3.7/site-packages/setuptools/command/easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      EasyInstallDeprecationWarning,
    /home/adtrain/anaconda3/envs/bevfusion_env/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      setuptools.SetuptoolsDeprecationWarning,
    /home/adtrain/anaconda3/envs/bevfusion_env/lib/python3.7/site-packages/torch/utils/cpp_extension.py:381: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
      warnings.warn(msg.format('we could not find ninja.'))
    error: command '/usr/local/cuda-11.1/bin/gcc' failed with exit code 1
    ----------------------------------------
  Rolling back uninstall of mmcv-full
  Moving to /home/adtrain/anaconda3/envs/bevfusion_env/lib/python3.7/site-packages/mmcv/
   from /home/adtrain/anaconda3/envs/bevfusion_env/lib/python3.7/site-packages/~mcv
  Moving to /home/adtrain/anaconda3/envs/bevfusion_env/lib/python3.7/site-packages/mmcv_full-1.3.8.dist-info/
   from /home/adtrain/anaconda3/envs/bevfusion_env/lib/python3.7/site-packages/~mcv_full-1.3.8.dist-info
ERROR: Command errored out with exit status 1: /home/adtrain/anaconda3/envs/bevfusion_env/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/adtrain/mmcv/setup.py'"'"'; __file__='"'"'/home/adtrain/mmcv/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

**Comment by zhouzaida** [comment]
Hi, the error `gcc: error trying to exec 'cc1plus': execvp: No such file or directory` seems like the gcc did not work as expected. Maybe you need to check gcc whether works first.

**Comment by khaledmohamed00** [comment]
could you please elaborate more @zhouzaida

**Comment by zhouzaida** [comment]
Maybe [this link](https://stackoverflow.com/questions/11912878/gcc-error-gcc-error-trying-to-exec-cc1-execvp-no-such-file-or-directory) will be helpful.

**Comment by khaledmohamed00** [comment]
Thanks @zhouzaida  for your help  and sorry for the late reply. 
what worked for me : i installed pytorch 1.7 instead of 1.10.1 and manged to install mmcv , what i find weird is that i have installed mmcv on the same machine with pytorch 1.10.1 in different conda  environment with no problem .

**Comment by zhouzaida** [comment]
It is a little weird.

**Comment by arjuntheprogrammer** [comment]
Try to run these commands:
`conda install gcc_linux-64 -y`
`conda install gxx_linux-64 -y`

**Comment by laukaho** [comment]
Probably because it cannot find `cc1plus`

**Verify if `cc1plus` exists by `sudo find /usr/ -name cc1plus`**
Expected output
```
/usr/lib/gcc/x86_64-linux-gnu/11/cc1plus
```
Then,
```
export PATH=/usr/lib/gcc/x86_64-linux-gnu/11/:$PATH
```
Try to reinstall mmcv

**If `cc1plus` not exists, reinstall**
```
sudo apt update
sudo apt install --reinstall build-essential g++
```
