### ISSUE TITLE
mmcv installation error

### ISSUE THREAD

**Issue by shu-ds** [open-mmlab/mmcv#2079]
Thanks for reporting the unexpected results and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmcv.readthedocs.io/en/latest/trouble_shooting.html) but cannot get the expected help.
3. The unexpected results still exist in the latest version.

**The installation failed following the instructions. The error was ModuleNotFoundError: No module named 'click'. If 'click' installed, it failed with ModuleNotFoundError: No module named 'tabulate'
**

**Reproduction**

1. What command, code, or script did you run?

```
conda create --name openmmlab python=3.8 -y
conda activate openmmlab
conda install pytorch torchvision -c pytorch
pip install -U openmim
mim install mmcv-full
```
Error appeared at line `mim install mmcv-full`

2. Did you make any modifications on the code? Did you understand what you have modified?

no applicable

**Comment by zhouzaida** [comment]
Hi @shu-ds , please uninstall openmim first and install it again.

**Comment by skyqwe123** [comment]
@zhouzaida 你好，请问使用如下方式安装
pip install openmim
mim install mmcv-full
mmcv-full安装过程中一直显示 
Building wheel for mmcv-full (setup.py) ... 
是什么问题？

**Comment by zhouzaida** [comment]
@skyqwe123 这说明没有找到预编译包，你可以提供 torch 和 cuda 的版本么

**Comment by shu-ds** [comment]
> Hi @shu-ds , please uninstall openmim first and install it again.
> 
> ```shell
> pip uninstall openmim
> pip install openmim
> mim install mmcv-full
> ```

hi @zhouzaida many thanks for your reply. This did not work for me.

The issue is solved for me by using 
pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/{cu_version}/{torch_version}/index.html

**Comment by skyqwe123** [comment]
> @skyqwe123 这说明没有找到预编译包，你可以提供 torch 和 cuda 的版本么

torch1.7.1 cuda11.5，问题解决了

pip uninstall openmim
pip install openmim
mim install mmcv-full
这个好像不是那么的有效，还是需要自己去对应torch与cuda的版本

**Comment by zhouzaida** [comment]
@skyqwe123 应该是不用的，你方便提供 mim install mmcv-full 的输出日志么
