### ISSUE TITLE
The error about pretty_text

### ISSUE THREAD

**Issue by DeepDetector** [open-mmlab/mmcv#2080]
**Checklist**
1. I have searched related issues but cannot get the expected help.
2. I have read the FAQ documentation but cannot get the expected help.

1. i pip install mmcv_full-1.5.3-cp38-cp38-manylinux1_x86_64.whl.
2. i run chenck check_installation.py and get:

Start checking the installation of mmcv-full ...
CPU ops were compiled successfully.
CUDA ops were compiled successfully.
mmcv-full has been installed successfully.
Environment information:
sys.platform: linux
Python: 3.8.12 (default, Oct 12 2021, 13:49:34) [GCC 7.5.0]
CUDA available: True
GPU 0,1,2,3: Tesla V100-DGXS-32GB
CUDA_HOME: :/usr/local/cuda-10.0
GCC: gcc (Ubuntu 6.5.0-2ubuntu1~18.04) 6.5.0 20181026
PyTorch: 1.8.0+cu111
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

TorchVision: 0.9.0+cu111
OpenCV: 4.4.0
MMCV: 1.5.3
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.1

5. but when i run

`from mmcv import Config`
`cfg = Config.fromfile('redet_re50_refpn_1x_dota_ms_rr_le90.py')`
`print(cfg.pretty_text)`

i get:
Traceback (most recent call last):
  File "config.py", line 7, in <module>
    cfg.pretty_text
  File "/home/cv2019/anaconda3/envs/mmcv_rotate/lib/python3.8/site-packages/mmcv/utils/config.py", line 519, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/home/cv2019/anaconda3/envs/mmcv_rotate/lib/python3.8/site-packages/mmcv/utils/config.py", line 50, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'pretty_text'

Thank you for your great work, but i have work on this issue for days.

**Comment by HAOCHENYE** [comment]
Hi~ thanks for your feedback. `pretty_text` is the property of `Config`. From the error message, it seems that config can't find the `pretty_text` property, so it tries to find the key in `_cfg_dict` and finally raise this error. Could you provide the complete error message? and check your `mmcv.Config` truly has the pretty_text property.

**Comment by HAOCHENYE** [comment]
> 
Could you load the `cfg` from file and dump it into python format with the simplest code? such as:
```python
from mmcv import Config
cfg = Config.fromfile('configs/redet/redet_re50_refpn_1x_dota_ms_rr_le90.py')
cfg.dump('test.py')
```
I'm not sure if there is something else wrong in train.py and caused this error.

Would you mind providing us with the code that reproduces the error, and It could be helpful to locate the problem?

**Comment by HAOCHENYE** [comment]
Suggest directly installing pre-built mmcv by the commands list here.
https://github.com/open-mmlab/mmcv
![image](https://user-images.githubusercontent.com/57566630/176394294-3e40cfe5-cdc7-4331-b079-8a93e8409a90.png)

**Comment by DeepDetector** [comment]
> Suggest directly installing pre-built mmcv by the commands list here. https://github.com/open-mmlab/mmcv ![image](https://user-images.githubusercontent.com/57566630/176394294-3e40cfe5-cdc7-4331-b079-8a93e8409a90.png) Hope the pre-built package can solve your problem, expected your reply.

Yeah, I download whl from https://download.openmmlab.com/mmcv/dist/cu111/torch1.8.0/index.html

**Comment by HAOCHENYE** [comment]
> > Suggest directly installing pre-built mmcv by the commands list here. https://github.com/open-mmlab/mmcv ![image](https://user-images.githubusercontent.com/57566630/176394294-3e40cfe5-cdc7-4331-b079-8a93e8409a90.png) Hope the pre-built package can solve your problem, expected your reply.
> 
> Yeah, I download whl from https://download.openmmlab.com/mmcv/dist/cu111/torch1.8.0/index.html. But it doesn't work.

How about just install mmcv-full by 
`pip install mmcv-full==1.5.3 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.8.0/index.html`

**Comment by DeepDetector** [comment]
> > > Suggest directly installing pre-built mmcv by the commands list here. https://github.com/open-mmlab/mmcv ![image](https://user-images.githubusercontent.com/57566630/176394294-3e40cfe5-cdc7-4331-b079-8a93e8409a90.png) Hope the pre-built package can solve your problem, expected your reply.
> > 
> > 
> > Yeah, I download whl from https://download.openmmlab.com/mmcv/dist/cu111/torch1.8.0/index.html. But it doesn't work.
> 
> How about just install mmcv-full by `pip install mmcv-full==1.5.3 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.8.0/index.html`

Thank you! The issue has been solved. I clone the conda environment from another server that successfully installed mmcv-full.
The error is due to some incompatible packages.

**Comment by SohanLalYadav2304** [comment]
@DeepDetector How did you solve this, could you elaborate please?

**Comment by startgalaxy** [comment]
> > > > Suggest directly installing pre-built mmcv by the commands list here. https://github.com/open-mmlab/mmcv ![image](https://user-images.githubusercontent.com/57566630/176394294-3e40cfe5-cdc7-4331-b079-8a93e8409a90.png) Hope the pre-built package can solve your problem, expected your reply.
> > > 
> > > 
> > > Yeah, I download whl from https://download.openmmlab.com/mmcv/dist/cu111/torch1.8.0/index.html. But it doesn't work.
> > 
> > 
> > How about just install mmcv-full by `pip install mmcv-full==1.5.3 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.8.0/index.html`
> 
> Thank you! The issue has been solved. I clone the conda environment from another server that successfully installed mmcv-full. The error is due to some incompatible packages.

Hello! I have the same question with you,but I don't know which package is mismatched.I followed the code given on the official website for verification, which shows that mmcv and mmdet are installed successfully, but the following errors occur during operation.Can you give me some advice? Thanks
![1704878349852](https://github.com/open-mmlab/mmcv/assets/87422186/106e0399-aaec-46fe-9a6b-1792ff84fdf8)

**Comment by zhouzaida** [comment]
Hi @startgalaxy , what is your mmcv version?

**Comment by ShunLu91** [comment]
I have tried mmcv-full-1.3.17 and mmcv-full-1.7.2, and both of them encountered this problem. 
Finally, I found that it was caused by the wrong version of other supporting packages. For me, as I used the Python=3.6 with a **tomli** having a very previous version, making the **yapf** being an old version. After reinstalling the tomli==1.2.3 and yapf==0.32.0, I successfully installed mmcv-full-1.3.17.

**Comment by wuyunxin2001** [comment]
> > > > 建议通过这里的命令列表直接安装预构建的 mmcv。 ![image](https://user-images.githubusercontent.com/57566630/176394294-3e40cfe5-cdc7-4331-b079-8a93e8409a90.png) https://github.com/open-mmlab/mmcv 希望预构建的软件包可以解决您的问题，期待您的回复。
> > > 
> > > 
> > > 是的，我从 https://download.openmmlab.com/mmcv/dist/cu111/torch1.8.0/index.html 下载 whl。但它不起作用。
> > 
> > 
> > 直接安装 mmcv-full 怎么样`pip install mmcv-full==1.5.3 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.8.0/index.html`
> 
> 谢谢！问题已解决。我从另一台成功安装了 mmcv-full 的服务器克隆了 conda 环境。该错误是由于某些不兼容的软件包造成的。

您好，怎样解决的呢，可以说一下嘛

**Comment by wuyunxin2001** [comment]
@DeepDetector
