### ISSUE TITLE
What's the difference between roi_align in mmcv and torchvision

### ISSUE THREAD

**Issue by htx-DeepLearning** [open-mmlab/mmcv#2081]
I check outputs of roi_align in both mmcv and torchvision, but they are not same. Are there any documents explaining the difference?

**Comment by HAOCHENYE** [comment]
Hi, thanks for your feedback, could provide the simplest code to reproduce this issue?

**Comment by htx-DeepLearning** [comment]
> Hi, thanks for your feedback, could provide the simplest code to reproduce this issue?

Thanks for your reply. Sry, I made a mistake.
