### ISSUE TITLE
Is there any error in the forward function of class PointsSampler?

### ISSUE THREAD

**Issue by zhangtingyu11** [open-mmlab/mmcv#2082]
In the circumstance that the fps_sample_range is not equal to -1,the point_xyz and features index should be [last_fps_end_index:fps_sample_range+last_fps_end_index]?
For example,if there are 3000 points in total,and self.fps_sample_range_list is [1000,1000,1000].For the first time in the loop,sample_points_xyz and sample_features will choose the first 1000 points.And the last_fps_end_index will be added to 1000.For the second time in the loop,sample_points_xyz and sample_features will choose 1000\~1000 points, but I think the chosen index should be 1000\~2000(last_fps_end_index\~fps_sample_range+last_fps_end_index).
Am I thinking wrong or the code is wrong?Hope to get reply.

**Comment by HAOCHENYE** [comment]
Should `fps_sample_range_list` be `[1000, 1000, 1000]` ? I think its value should be Increasing.

**Comment by zhangtingyu11** [comment]
> Should `fps_sample_range_list` be `[1000, 1000, 1000]` ? I think its value should be increasing.

**Comment by zhangtingyu11** [comment]
> Should `fps_sample_range_list` be `[1000, 1000, 1000]` ? I think its value should be increasing.
If the fps_sample_range_list is [1000,2000,3000].The first time in the loop,it will choose points with index in 0～1000,and last_fps_end_index will be 1000.The second time in the loop,it will choose points with index in 1000～2000,and the last_fps_end_index will be 3000(1000+2000).The third time in the loop,it will choose points with index in 3000～3000.Thus the points with index 2000～3000 are not chosen.Is this right？

**Comment by HAOCHENYE** [comment]
> > Should `fps_sample_range_list` be `[1000, 1000, 1000]` ? I think its value should be increasing.
> > If the fps_sample_range_list is [1000,2000,3000].The first time in the loop,it will choose points with index in 0～1000,and last_fps_end_index will be 1000.The second time in the loop,it will choose points with index in 1000～2000,and the last_fps_end_index will be 3000(1000+2000).The third time in the loop,it will choose points with index in 3000～3000.Thus the points with index 2000～3000 are not chosen.Is this right？

You are right, it seems there is some logic error of the current `PointsSampler`, but we did not find it since the downstream repo only use the default value of `fps_sample_range_list`. 
Thanks for your feedback, would mind creating a PR to fix this error?

**Comment by zhangtingyu11** [comment]
> > > Should `fps_sample_range_list` be `[1000, 1000, 1000]` ? I think its value should be increasing.
> > > If the fps_sample_range_list is [1000,2000,3000].The first time in the loop,it will choose points with index in 0～1000,and last_fps_end_index will be 1000.The second time in the loop,it will choose points with index in 1000～2000,and the last_fps_end_index will be 3000(1000+2000).The third time in the loop,it will choose points with index in 3000～3000.Thus the points with index 2000～3000 are not chosen.Is this right？
> 
> You are right, it seems there is some logic error of the current `PointsSampler`, but we did not find it since the downstream repo only use the default value of `fps_sample_range_list=-1`. I think the general logic should be to loop the `points_xyz` with index: `0-1000`, `1000-2000`, `2000-3000`.
> 
> Thanks for your feedback, would mind creating a PR to fix this error?

OK，I have committed PR.
