### ISSUE TITLE
nan or wrong loss by simultaneous use of GradientCumulativeOptimizerHook and resume

### ISSUE THREAD

**Issue by shinya7y** [open-mmlab/mmcv#2083]
**Describe the Issue**

The following codes cause nan or wrong loss.

https://github.com/open-mmlab/mmcv/blob/d71d067da19d71d79e7b4d7ae967891c7bb00c05/mmcv/runner/hooks/optimizer.py#L150-L154

https://github.com/open-mmlab/mmcv/blob/d71d067da19d71d79e7b4d7ae967891c7bb00c05/mmcv/runner/hooks/optimizer.py#L162-L167

**Bug case 1**

Condition:
`self.cumulative_iters = 2`
`runner.max_iters = 10000`
`runner.iter = 3000` (resume from 3k iteration)

`residual_iters = 7000`
`self.divisible_iters = 7000`
`self.remainder_iters = 0`

`loss_factor = 0` and loss becomes nan at 7k iteration.

A comment in MMSelfSup points out this bug case. https://github.com/open-mmlab/mmselfsup/blob/a7dbc55eb09dc494eac8a2091f86cd7c4aae3cd5/mmselfsup/core/hooks/optimizer_hook.py#L74-L76

**Bug case 2**

Condition:
`self.cumulative_iters = 2`
`runner.max_iters = 10001`
`runner.iter = 3000` (resume from 3k iteration)

`residual_iters = 7001`
`self.divisible_iters = 7000`
`self.remainder_iters = 1`

Wrong `loss_factor = 1` and `loss` after 7k iteration.
This bug case silently causes wrong results.

**Bug fix**

```python
if runner.iter < runner.max_iters - self.remainder_iters:
    loss_factor = self.cumulative_iters
else:
    loss_factor = self.remainder_iters
```

**Comment by HAOCHENYE** [comment]
Thanks for your feedback, this is actually a bug. Would you mind creating a PR to fix this？
