### ISSUE TITLE
Get stuck when import mmcv before import torch

### ISSUE THREAD

**Issue by Bruce-Si** [open-mmlab/mmcv#2086]
Thank you for your code. I have installed mmcv-full successfully, but I got stuck when I `import mmcv` before `import torch`. That's confusing, can you tell why? Thank you. 
The environment is: 
```
Ubuntu: 18.04
python: 3.7.13
cuda: 10.2
mmcv-full==1.4.8,
torch==1.9.0
```
I installed mmcv through: `pip install mmcv-full==1.4.8 -f https://download.openmmlab.com/mmcv/dist/cu102/torch1.9.0/index.html`

**Comment by Bruce-Si** [comment]
> What will happen if import torch before mmcv? Does it work well?

No, the code just get stuck, not moving forward and nothing output.

**Comment by Bruce-Si** [comment]
I tried different version of pytorch and python and cuda and mmcv, all get stuck if import torch before mmcv

**Comment by HAOCHENYE** [comment]
How about use mmcv version >= 1.5.0?, We optimizer the import speed in #1844.

**Comment by Bruce-Si** [comment]
> How about use mmcv version >= 1.5.0?, We optimizer the import speed in #1844.

I have tried `mmcv==1.5.3`, it does't work...

**Comment by Bruce-Si** [comment]
Now I have reversed the order of `import torch` and `import mmcv` all the code involved. It's a big project but at least work...
