### ISSUE TITLE
The input type of data in `mmcv.parallel.DataContainer`

### ISSUE THREAD

**Issue by liqikai9** [open-mmlab/mmcv#2091]
In this line https://github.com/open-mmlab/mmcv/blob/master/mmcv/parallel/data_container.py#L40, it says that the input type of data must be `torch.Tensor` or `np.ndarray`.
But I have found an example in mmdet that input a dict: https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/pipelines/formatting.py#L344
Could you explain is their any type constraint of `mmcv.parallel.DataContainer`? 
Thanks~

**Comment by HAOCHENYE** [comment]
https://github.com/open-mmlab/mmcv/blob/9fffcbc9cdc79736b866d17d0243f4eef7b7cadf/mmcv/parallel/data_container.py#L87 constrains the type of data. However, if data is a `dict` and `size` or `dim` method is not called,  just like https://github.com/open-mmlab/mmcv/blob/9fffcbc9cdc79736b866d17d0243f4eef7b7cadf/mmcv/parallel/collate.py#L70, it will also not raise an error. But I think this behavior is dangerous.
