### ISSUE TITLE
Not find GPU.

### ISSUE THREAD

**Issue by AndrewWangCH** [open-mmlab/mmcv#2099]
Hi,  I get a error.
 File "....\lib\site-packages\mmcv\ops\nms.py", line 28, in forward
    inds = ext_module.nms(
RuntimeError: nms_impl: implementation for device cuda:0 not found.

My mmcv-full is 1.5.3, but print(torch.cuda.is_available()) is true.

And My computer install Visual Studio 2022, I do not install othre mmcv-full( < 1.5.3, them must have VS2017orVS2019).
So I want to why.

Regards!

**Comment by zhouzaida** [comment]
H @AndrewWangCH , it seems like mmcv-full was not installed successfully. Could you provide your torch and cuda versions?

**Comment by AndrewWangCH** [comment]
![1](https://user-images.githubusercontent.com/59794732/177293261-3afa6fad-297a-4733-91f7-3a3e38f8e094.png)
![2](https://user-images.githubusercontent.com/59794732/177293271-efb37761-3bba-4fa0-995e-34bd9f62fad9.png)

I install mmcv-full 1.5.3 successfully, but I not installed successfully(example 1.5.0,1.4.8).

**Comment by AndrewWangCH** [comment]
hi @zhouzaida, this error occurs while running mmrotate demo.

**Comment by zhouzaida** [comment]
What command did you use to install mmcv-full?

**Comment by AndrewWangCH** [comment]
I use pip, 
I not install cudatoolkit11.3(conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch), 
now I plan to install again refer to https://zhuanlan.zhihu.com/p/434491590.

**Comment by zhouzaida** [comment]
You can install mmcv-full via openmim.

```bash
pip install -U openmim
mim install mmcv-full
```

**Comment by AndrewWangCH** [comment]
![3](https://user-images.githubusercontent.com/59794732/177470540-3d821b49-50f7-43e0-92b2-91fb5c0f2967.png)
![4](https://user-images.githubusercontent.com/59794732/177470548-c2f2ace3-25b7-4d5e-ab1c-f7be64aef23e.png)
![5](https://user-images.githubusercontent.com/59794732/177470761-b195621d-f2c4-40bc-a715-7a8c4800593c.png)
![6](https://user-images.githubusercontent.com/59794732/177470772-ecf7a899-9b9a-470f-8705-d0f77af1a7eb.png)
I use your said method, but not slove this problem.

**Comment by zhouzaida** [comment]
Could you provide the full log of the above command?

**Comment by AndrewWangCH** [comment]
![Screenshot 2022-07-14 191100](https://user-images.githubusercontent.com/59794732/179132854-39ca397f-9b3f-420e-b416-e86fc0e6df4b.png)

**Comment by zhouzaida** [comment]
Could you try to add an option `--no-cache-dir`?

```bash
mim uninstall mmcv-full
mim install mmcv-full --no-cache-dir
```

**Comment by AndrewWangCH** [comment]
I have successfully used the mmcv， I think my network lead to install other vision mmcv.
My method is install mmcv in othre PC, and copy to my PC.
Finally, thank you for your guidance!
