### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by mvm95** [open-mmlab/mmcv#2101]
Hi, 
I was studying the module and I was trying to implement a STGNN like described in https://mmaction2.readthedocs.io/en/latest/_modules/mmaction/models/backbones/stgcn.html

I am still not so very familiar with python, which I work whit since a month, so maybe this issue could be more technical. Do have any suggestion to how to solve the problem? 

Here below I' ll write the interested code part.
Thanks to everyone, even for the patience.

import torch.nn as nn
import torch
from mmcv.cnn import constant_init, kaiming_init, normal_init
from mmcv.runner import load_checkpoint
from mmcv.utils import _BatchNorm
**from ..utils import get_root_logger
from ..builder import BACKBONES
from ..skeleton_gcn.utils import Graph**

  Input In [7] in <cell line: 1>
    from ..utils import get_root_logger
ImportError: attempted relative import with no known parent package

**Comment by HAOCHENYE** [comment]
Hi,  What is your directory structure? If you are using relative import, you should ensure that each module has `__init__` files. **from ..utils import xxx**, **from ..build import xxx** belongs to relative import. Does your `utils` and its sub directory have `__init__.py`?
