### ISSUE TITLE
Getting Error: Failed building wheel for mmcv-full

### ISSUE THREAD

**Issue by balandongiv** [open-mmlab/mmcv#2102]
I tried to install `mmcv-full` on a system with `Windows 10`.

The system comes with `cuda 11.3` and `pytorch 11.1` . The `pytorch` is installed under `conda` environment with the syntaxt `conda install -n test pytorch==1.11.0 torchvision torchaudio -c pytorch`

The following line was used to install the `mmcv-full`
`pip install mmcv-full==1.5.3 -f https://download.openmmlab.com/mmcv/dist/cu113/torch11.1/index.html`

However, in the middle of the installation, the compiler return

```
 copying mmcv\ops\csrc\tensorrt\plugins\trt_roi_align_kernel.cu -> build\lib.win-amd64-3.8\mmcv\ops\csrc\tensorrt\
plugins
  copying mmcv\ops\csrc\tensorrt\plugins\trt_scatternd.cpp -> build\lib.win-amd64-3.8\mmcv\ops\csrc\tensorrt\plugins
  copying mmcv\ops\csrc\tensorrt\plugins\trt_scatternd_kernel.cu -> build\lib.win-amd64-3.8\mmcv\ops\csrc\tensorrt\
plugins
  running build_ext
  C:\Users\rpb\anaconda3\envs\test\lib\site-packages\torch\utils\cpp_extension.py:322: UserWarning: Error checking 
compiler version for cl: [WinError 2] The system cannot find the file specified
    warnings.warn(f'Error checking compiler version for {compiler}: {error}')
  building 'mmcv._ext' extension
  creating build\temp.win-amd64-3.8
  creating build\temp.win-amd64-3.8\Release
  creating build\temp.win-amd64-3.8\Release\mmcv
  creating build\temp.win-amd64-3.8\Release\mmcv\ops
  creating build\temp.win-amd64-3.8\Release\mmcv\ops\csrc
  creating build\temp.win-amd64-3.8\Release\mmcv\ops\csrc\pytorch
  creating build\temp.win-amd64-3.8\Release\mmcv\ops\csrc\pytorch\cpu
  creating build\temp.win-amd64-3.8\Release\mmcv\ops\csrc\pytorch\cuda
  "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\bin\HostX86\x64\cl.exe"
 /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DMMCV_WITH_CUDA -IC:\Users\rpb\AppData\Local\Temp\pip-install-ho03yw5v\mmcv-f
ull_30122287b7064130b2983914081f85d6\mmcv\ops\csrc\common -IC:\Users\rpb\AppData\Local\Temp\pip-install-ho03yw5v\mm
cv-full_30122287b7064130b2983914081f85d6\mmcv\ops\csrc\common\cuda -IC:\Users\rpb\anaconda3\envs\test\lib\site-pack
ages\torch\include -IC:\Users\rpb\anaconda3\envs\test\lib\site-packages\torch\include\torch\csrc\api\include -IC:\U
sers\rpb\anaconda3\envs\test\lib\site-packages\torch\include\TH -IC:\Users\rpb\anaconda3\envs\test\lib\site-package
s\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include" -IC:\Users\rpb\anaconda3\e
nvs\test\include -IC:\Users\rpb\anaconda3\envs\test\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\
BuildTools\VC\Tools\MSVC\14.32.31326\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTo
ols\VC\Tools\MSVC\14.32.31326\include" /EHsc /Tp./mmcv/ops/csrc/pytorch/cpu\active_rotated_filter.cpp /Fobuild\temp
.win-amd64-3.8\Release\./mmcv/ops/csrc/pytorch/cpu\active_rotated_filter.obj /MD /wd4819 /wd4251 /wd4244 /wd4267 /w
d4275 /wd4018 /wd4190 /EHsc -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 
  active_rotated_filter.cpp
  C:\Users\rpb\anaconda3\envs\test\lib\site-packages\torch\include\c10/core/Allocator.h(3): fatal error C1083: Cann
ot open include file: 'stddef.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.32.31326\
\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
  ----------------------------------------
  ERROR: Failed building wheel for mmcv-full
```

For context, the `c++` development has been install as shown in the figure.

<img width="880" alt="Snap 2022-07-06 at 08 14 01" src="https://user-images.githubusercontent.com/22090092/177437014-f882fc07-6211-4c0f-87e8-7d5489307b39.png">

**Comment by HAOCHENYE** [comment]
Hi, we suggest installing mmcv-full from the pre-built package:
`pip install mmcv-full==1.5.3 -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.11.0/index.html`

**Comment by HAOCHENYE** [comment]
Hi, what's your Cuda version of PyTorch (result of `torch.version.cuda`)?

**Comment by zhouzaida** [comment]
Hi, the command should be `pip install mmcv-full==1.5.3 -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.11/index.html`

**Comment by zhouzaida** [comment]
You can install mmcv-full via openmim.

```bash
pip install -U openmim
mim install mmcv-full
```

**Comment by balandongiv** [comment]
Thanks for the insight. The `openmim` approach is elegant.

**Comment by balandongiv** [comment]
Hi @zhouzaida , I am re-opening this issue.

I now try to install `mmcv-full` on Ubuntu `20.04`. The specs is as follow

1. CUDA 11.7
2. Torch 1.12.0

I tried using the `mim` approach

```
pip install -U openmim
mim install mmcv-full

```

However, the installer return a RuntimeError
```

    RuntimeError:
    The detected CUDA version (11.7) mismatches the version that was used to compile
    PyTorch (10.2). Please make sure to use the same CUDA versions.

```

Similarly, using the precompile version, also return the same `RuntimeError`

```
    RuntimeError:
    The detected CUDA version (11.7) mismatches the version that was used to compile
    PyTorch (10.2). Please make sure to use the same CUDA versions.

```

`
pip install mmcv-full==1.5.3 -f https://download.openmmlab.com/mmcv/dist/cu117/torch1.12/index.html`


The full spec:

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_May__3_18:49:52_PDT_2022
Cuda compilation tools, release 11.7, V11.7.64
Build cuda_11.7.r11.7/compiler.31294372_0
```

and
`
 torch-1.12.0 torchaudio-0.12.0 torchvision-0.13.0`


Is it mean I need to downgrade the `CUDA` version.

Appreciate for any advice.

**Comment by zhouzaida** [comment]
Could you provide the output of `import torch;print(torch.version.cuda)`?

**Comment by balandongiv** [comment]
Thanks for responding @zhouzaida,really appreciate. I downgrade the cuda to `11.6` and using pytorch `11.6` instead.

**Comment by umer-khalil745** [comment]
> You can install mmcv-full via openmim.
> 
> ```shell
> pip install -U openmim
> mim install mmcv-full
> ```

I am trying to install mmcv-full using openmim but getting an error
         File "C:\Users\Specialist\AppData\Local\conda\conda\envs\openmmlab\lib\site-packages\torch\utils\cpp_extension.py", line 1909, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mmcv-full
  Running setup.py clean for mmcv-full
Failed to build mmcv-full
ERROR: Could not build wheels for mmcv-full, which is required to install pyproject.toml-based projects

can you please help me with this? Thanks.

**Comment by lanhuiling01** [comment]
> > You can install mmcv-full via openmim.您可以通过 openmim 安装 mmcv-full。
> > ```shell
> > pip install -U openmim
> > mim install mmcv-full
> > ```
> 
> I am trying to install mmcv-full using openmim but getting an error我正在尝试使用openmim安装mmcv-full，但出现错误 File "C:\Users\Specialist\AppData\Local\conda\conda\envs\openmmlab\lib\site-packages\torch\utils\cpp_extension.py", line 1909, in _run_ninja_build文件“C：\Users\Specialist\AppData\Local\conda\conda\envs\openmmlab\lib\site-packages\torch\utils\cpp_extension.py”，第 1909 行，_run_ninja_build raise RuntimeError(message) from e从 e 引发 RuntimeError（message） RuntimeError: Error compiling objects for extensionRuntimeError：编译扩展对象时出错 [end of output] [输出结束]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.注意：此错误源自子进程，可能不是 pip 的问题。 ERROR: Failed building wheel for mmcv-full错误：mmcv-full 的构建轮失败 Running setup.py clean for mmcv-full运行 mmcv-full 的 setup.py clean Failed to build mmcv-full无法构建 mmcv-full ERROR: Could not build wheels for mmcv-full, which is required to install pyproject.toml-based projects错误：无法为 mmcv-full 构建轮子，这是安装基于 pyproject.toml 的项目所必需的
> 
> can you please help me with this? Thanks.你能帮我解决这个问题吗？谢谢。

I had the same problem, could I ask if you solved it?

**Comment by zhouzaida** [comment]
> > > You can install mmcv-full via openmim.您可以通过 openmim 安装 mmcv-full。
> > > ```shell
> > > pip install -U openmim
> > > mim install mmcv-full
> > > ```
> > 
> > 
> > I am trying to install mmcv-full using openmim but getting an error我正在尝试使用openmim安装mmcv-full，但出现错误 File "C:\Users\Specialist\AppData\Local\conda\conda\envs\openmmlab\lib\site-packages\torch\utils\cpp_extension.py", line 1909, in _run_ninja_build文件“C：\Users\Specialist\AppData\Local\conda\conda\envs\openmmlab\lib\site-packages\torch\utils\cpp_extension.py”，第 1909 行，_run_ninja_build raise RuntimeError(message) from e从 e 引发 RuntimeError（message） RuntimeError: Error compiling objects for extensionRuntimeError：编译扩展对象时出错 [end of output] [输出结束]
> > note: This error originates from a subprocess, and is likely not a problem with pip.注意：此错误源自子进程，可能不是 pip 的问题。 ERROR: Failed building wheel for mmcv-full错误：mmcv-full 的构建轮失败 Running setup.py clean for mmcv-full运行 mmcv-full 的 setup.py clean Failed to build mmcv-full无法构建 mmcv-full ERROR: Could not build wheels for mmcv-full, which is required to install pyproject.toml-based projects错误：无法为 mmcv-full 构建轮子，这是安装基于 pyproject.toml 的项目所必需的
> > can you please help me with this? Thanks.你能帮我解决这个问题吗？谢谢。
> 
> I had the same problem, could I ask if you solved it?

Hi, what are your pytorch and cuda versions?

**Comment by karayakar** [comment]
I tried pytorch 12.4, 11.8 , cuda 11.8 , 12.1, 12.4
it fails. Not working.
