### ISSUE TITLE
tensorrt plugin install wrong

### ISSUE THREAD

**Issue by Winnie202** [open-mmlab/mmcv#2112]
Here is my relevant configuration：
mmcv-full                     1.5.3
mmedit                        0.15.0  
tensorrt                      8.2.1.8
torch                         1.8.1
torchvision                   0.9.1

But I am getting the following error
![2022-07-13 11-02-51屏幕截图](https://user-images.githubusercontent.com/86768013/178643669-c8066b60-9afa-4064-b8d6-7a036c673283.png)

please help me to solve this problem

**Comment by HAOCHENYE** [comment]
Hi~ Have you followed the steps in https://mmcv.readthedocs.io/en/latest/deployment/tensorrt_plugin.html?highlight=trt? It seems that you've not TensorRT correctly

**Comment by Winnie202** [comment]
> Hi~ Have you followed the steps in https://mmcv.readthedocs.io/en/latest/deployment/tensorrt_plugin.html?highlight=trt? It seems that you've not TensorRT correctly

I installed tensorRT and mmcv-full first, and then followed the command：
git clone https://github.com/open-mmlab/mmcv.git
export TENSORRT_DIR=`pwd`/TensorRT-7.2.1.6
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$TENSORRT_DIR/lib
MMCV_WITH_OPS=1 MMCV_WITH_TRT=1 pip install -e .

![image](https://user-images.githubusercontent.com/86768013/178969847-5fe5c1a8-788e-4797-8fba-3fb084581614.png)

![image](https://user-images.githubusercontent.com/86768013/178969620-2c49957c-5b54-4278-825e-52639ba52fdb.png)

**Comment by HAOCHENYE** [comment]
Hi， It seems you are using tensorRT 8.10. How about trying TensorRT-7.2.1.6 and following the steps in docs.
![image](https://user-images.githubusercontent.com/57566630/179195022-62160d1e-e955-481e-892f-9b9424c6c1f8.png)

**Comment by Winnie202** [comment]
> 您好，看来您使用的是 tensorRT 8.10。如何尝试 TensorRT-7.2.1.6 并按照文档中的步骤操作。 ![图片](https://user-images.githubusercontent.com/57566630/179195022-62160d1e-e955-481e-892f-9b9424c6c1f8.png)

Yes, I installed tensorRT8.2.1.8, but I changed the version number in the command during the actual operation. The reason is that the version is different and the mmcv plugin cannot be installed?

**Comment by grimoire** [comment]
Yes, TensorRT plugins in MMCV do not support TensorRT8+, please try the plugin in [MMDeploy](https://github.com/open-mmlab/mmdeploy).
