### ISSUE TITLE
MMCV CUDA Compiler: Not Available

### ISSUE THREAD

**Issue by The-Storm19** [open-mmlab/mmcv#2117]
I am trying to train an object detection algorithm, and am running into issues with the mmcv-full library. I have run this model before with no issues, but now I am having issues. Running the program yields this prompt:
![Screenshot 2022-07-14 135430](https://user-images.githubusercontent.com/51663415/179073695-559cd51b-6b5a-46a6-bbaf-cffe7d751250.png)
This contains all my version data for torch, cuda, etc. Moreover, I've properly installed mmcv-full, and have even tried installing it with the `MMCV_WITH_OPS=1` and `FORCE_CUDA=1` commands, but the programs still returns `MMCV CUDA Compiler: not available`. The program will run fine for one epoch, and then when saving the epoch to checkpoint, it fails with this error:
![Screenshot 2022-07-14 135350](https://user-images.githubusercontent.com/51663415/179074302-30fd0f06-7287-49bb-b4aa-902379667411.png)
Any help in fixing this would be greatly appreciated.

**Comment by zhouzaida** [comment]
Hi, could you provide the log of installing mmcv-full?

**Comment by The-Storm19** [comment]
![image](https://user-images.githubusercontent.com/51663415/179254463-960cf801-4acc-4925-aaaf-26e979b0a911.png)
Is this what you're looking for?

**Comment by The-Storm19** [comment]
Got it. I reinstalled mmcv-full with MIM instead of PIP and that seemed to work.
