### ISSUE TITLE
AttributeError: partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' (most likely due to a circular import)

### ISSUE THREAD

**Issue by dingjingzhen** [open-mmlab/mmcv#2134]
When I finish installing mmcv,

pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu116/torch1.12.0/index.html

 I get an error:
![260b5180-53e2-4701-87ce-acfc26d8a7fe](https://user-images.githubusercontent.com/21244263/179916469-84dd2861-5201-42e1-a3f7-953497a15e49.png)

**Comment by HAOCHENYE** [comment]
Hi, it seems an error raised by opencv. Can you execute `python -c 'import cv2'` successfully? If not, you can try to reinstall your opencv.
