### ISSUE TITLE
MMCV==1.6.0 is used but incompatible

### ISSUE THREAD

**Issue by eregen** [open-mmlab/mmcv#2136]
Thanks for reporting the unexpected results and we appreciate it a lot.

**Describe the Issue**
I'm trying to run a script that uses mmcv-full as a dependancy. My environment has CUDA 10.1 and Torch 1.6.0 installed. I installed MMCV-full using

```pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index/html```

which installed version 1.6.0
I then installed mmseg using pip. But when I try to run a script for training a refinement network I an incompatibility error. 

```python -c 'from mmseg.apis import inference_segmentor, init_segmentor'```
Why is there an incompatibility with the mmcv-full version the home website installed?

**Environment**

{'sys.platform': 'linux', 'Python': '3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:21) [GCC 9.4.0]', 'CUDA available': True, 'GPU 0': 'Tesla T4', 'CUDA_HOME': '/usr', 'NVCC': 'Cuda compilation tools, release 10.1, V10.1.24', 'GCC': 'gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0', 'PyTorch': '1.6.0', 'PyTorch compiling details': 'PyTorch built with:\n  - GCC 7.3\n  - C++ Version: 201402\n  - Intel(R) oneAPI Math Kernel Library Version 2022.1-Product Build 20220311 for Intel(R) 64 architecture applications\n  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)\n  - OpenMP 201511 (a.k.a. OpenMP 4.5)\n  - NNPACK is enabled\n  - CPU capability usage: AVX2\n  - CUDA Runtime 10.1\n  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37\n  - CuDNN 7.6.3\n  - Magma 2.5.2\n  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, \n', 'TorchVision': '0.7.0', 'OpenCV': '4.6.0', 'MMCV': '1.6.0', 'MMCV Compiler': 'GCC 9.4', 'MMCV CUDA Compiler': '11.6'}

**Error traceback**
If applicable, paste the error traceback here.

Traceback (most recent call last):
  File "tools/train.py", line 12, in <module>
    from mmseg import __version__
  File "/home/ubuntu/BPR/mmseg/__init__.py", line 27, in <module>
    f'MMCV=={mmcv.__version__} is used but incompatible. ' \
AssertionError: MMCV==1.6.0 is used but incompatible. Please install mmcv>=[1, 1, 4], <=[1, 2, 0].
Traceback (most recent call last):
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/ubuntu/.conda/envs/open-mmlab/bin/python', '-u', 'tools/train.py', '--local_rank=0', 'configs/bpr/hrnet18s_128.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

**Comment by zhouzaida** [comment]
Hi, you can upgrade your mmseg version or downgrade your mmcv version to 1.2.0

**Comment by zhouzaida** [comment]
Fixed by https://github.com/open-mmlab/mmsegmentation/pull/1764
