### ISSUE TITLE
AttributeError: type object 'MultiScaleDeformableAttention' has no attribute 'ms_deform_attn_forward'

### ISSUE THREAD

**Issue by chuyi192** [open-mmlab/mmcv#2138]
**Checklist**
![image](https://user-images.githubusercontent.com/64272072/180151192-f1d832d0-58ec-4157-821a-97db749250b1.png)

![image](https://user-images.githubusercontent.com/64272072/180152087-62b94750-6b7b-402b-9a27-d7be16512a63.png)

I have this problem when running the code and don't know how to fix it

**Comment by chuyi192** [comment]
> **Checklist** ![image](https://user-images.githubusercontent.com/64272072/180151192-f1d832d0-58ec-4157-821a-97db749250b1.png)
> 
> I have this problem when running the code, hope it can help

![image](https://user-images.githubusercontent.com/64272072/180151448-860331e9-a8be-41d9-b996-1b654c35c5ca.png)

**Comment by lalaha1** [comment]
I have the same question. How do you solve it?

**Comment by MrPeterJin** [comment]
Same problem here, do you have solutions?

**Comment by Li-Whasaka** [comment]
Hi，Do you solve the problem？HOW to solve it？  Thank you
