### ISSUE TITLE
Error: AssertionError: MMCV==1.6.1 is used but incompatible. Please install mmcv>=1.3.17, <=1.6.0.

### ISSUE THREAD

**Issue by impulsecorp** [open-mmlab/mmcv#2150]
Since you released the new version yesterday the Google Colab notebook I have been using for the 2 weeks started giving errors.
I tried upgrading using:
pip install -U openmim
mim install mmcv-full
but it still gives this same error, which is listed below.

It fixes the error if I change it to install like this:
import torch
  torch_version, cuda_version = torch.__version__.split('+')
  !pip install mmcv-full==1.6.0 -f [https://download.openmmlab.com/mmcv/dist/{cuda_version}/torch{torch_version}/index.html](https://download.openmmlab.com/mmcv/dist/%7Bcuda_version%7D/torch%7Btorch_version%7D/index.html)

but I would ideally like to use 1.6.1.  This is the error I get:

AssertionError                            Traceback (most recent call last)

[<ipython-input-7-06628b9dbbcd>](https://localhost:8080/#) in <module>()
     14 from terminaltables import AsciiTable
     15 
---> 16 from mmdet.core import eval_recalls
     17 from mmdet.datasets.api_wrappers import COCO, COCOeval
     18 from mmdet.datasets.builder import DATASETS

[/content/mmdetection/mmdet/__init__.py](https://localhost:8080/#) in <module>()
     24 assert (mmcv_version >= digit_version(mmcv_minimum_version)
     25         and mmcv_version <= digit_version(mmcv_maximum_version)), \
---> 26     f'MMCV=={mmcv.__version__} is used but incompatible. ' \
     27     f'Please install mmcv>={mmcv_minimum_version}, <={mmcv_maximum_version}.'
     28 

AssertionError: MMCV==1.6.1 is used but incompatible. Please install mmcv>=1.3.17, <=1.6.0.

**Comment by HAOCHENYE** [comment]
Hi~. MMDetection has not supported MMCV 1.6.1 now, we will make it compatible ASAP.

**Comment by zhouzaida** [comment]
Fixed by https://github.com/open-mmlab/mmdetection/pull/8440
