### ISSUE TITLE
Maybe a bug about `multi_scale_deform_attn`

### ISSUE THREAD

**Issue by pixeli99** [open-mmlab/mmcv#2159]
Hi,
I got an error when executing this line of code.
https://github.com/open-mmlab/mmcv/blob/4558bfbd5bfc883e81da1b42c67e3611180ae587/mmcv/ops/multi_scale_deform_attn.py#L324

`RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!`

I personally feel that there is a problem with initializing weights. You can see here, the `bias` of **sampling_offsets** may be put on `cpu`?
https://github.com/open-mmlab/mmcv/blob/4558bfbd5bfc883e81da1b42c67e3611180ae587/mmcv/ops/multi_scale_deform_attn.py#L249

The `device` of grid_init is `cpu` on my machine.
```python
thetas = torch.arange(
            self.num_heads,
            dtype=torch.float32) * (2.0 * math.pi / self.num_heads)
grid_init = torch.stack([thetas.cos(), thetas.sin()], -1)
```

**Comment by zhouzaida** [comment]
Calling `model.init_weight()` after `model.to('cuda:0')` will cause this error you mentioned above. Are you willing to create a PR to resolve it?

**Comment by pixeli99** [comment]
OK, but where was the `model.to('cuda:0')` called?

I'm not sure where to fix it

**Comment by zhouzaida** [comment]
Oh, and there's already a PR (#2158) to fix this bug.

**Comment by pixeli99** [comment]
OK, thank you for your reply.😊
