### ISSUE TITLE
The grad sync about MMDistributedDataParallel

### ISSUE THREAD

**Issue by as754770178** [open-mmlab/mmcv#216]
I want to know `MMDistributedDataParallel` how to sync gradients after BP?

**Comment by hellock** [comment]
`MMDistributedDataParallel` only adds support for our data type `DataContainer`, other parts like forward and backward are just the same as the official `DistributedDataParallel`.

**Comment by as754770178** [comment]
#166 
I read the code of Pytorch，it exec `_sync_params` in `forward`. But you reply me that `Gradients will be synchronized after BP.`
I think that the `MMDataParallel` only adds support for our data type `DataContainer`.
But there are many differences between  `MMDistributedDataParallel` and `DistributedDataParallel` in pytorch.

**Comment by as754770178** [comment]
sorry, I find the code in Fp16OptimizerHook
