### ISSUE TITLE
Is there simple ways to do unit test on CUDA code?

### ISSUE THREAD

**Issue by chunibyo-wly** [open-mmlab/mmcv#2161]
Hello, thanks for your work.
I have noticed that there are python unit tests to test kernel functions.
But if I want to do unit test on small functions, are there any convenient methods?
Thanks for your reply.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the FAQ documentation but cannot get the expected help.

**Comment by grimoire** [comment]
AFAIK, there is no such tools to support CUDA kernel unit test directly.
A good practice from [nvidia documentation](https://docs.nvidia.com/cuda/cuda-c-best-practices-guide/index.html#unit-testing)
You can split your kernel into multiple function with both `__host__` and `__device__`. So you can test these function just like normal c++ function.

**Comment by chunibyo-wly** [comment]
Thanks for your reply.
I followed this [repo](https://github.com/havogt/cuda_gtest_plugin) to do unit test.
