### ISSUE TITLE
MMCV DCNv2/ModulatedDeformConv2d ONNX support

### ISSUE THREAD

**Issue by abhiagwl4262** [open-mmlab/mmcv#2169]
I have been able to make the ONNX inference work for a model with mmcv's ModulatedDeformConv2d. I did follow the process mentioned in MMCV documentation from https://mmcv.readthedocs.io/en/latest/deployment/onnxruntime_op.html 

1. Can anyone please explain why we need to build MMCV from source and why can't we directly install MMCV using PIP with ORT support ?
2. In there a way I can remove MMCV dependency from ONNX inference ?
3. Is DCNv2 is only supported for CPU inference with ONNX model? If yes, how one can enable the GPU support?

**Comment by grimoire** [comment]
1. It is hard to make a pre-built version since we do not know the ONNX Runtime version that you are using.
2. No you can't, unless ONNX Runtime supports DCNv2 in the future.
3. Yes. it is recommended to use TensorRT instead of ONNX Runtime if you want to infer with your GPU.

**Comment by abhiagwl4262** [comment]
And I think To enable running through tensorrt, I would have to add plugin to support MMCV's DCNv2.

**Comment by grimoire** [comment]
We have provided plugins for DCNv2 in both [MMDeploy](https://github.com/open-mmlab/mmdeploy/tree/master/csrc/mmdeploy/backend_ops/tensorrt/modulated_deform_conv) and [MMCV](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/csrc/tensorrt/plugins/trt_modulated_deform_conv.cpp)

**Comment by abhiagwl4262** [comment]
For MMCV i did see this link - https://github.com/open-mmlab/mmcv/blob/master/docs/en/deployment/tensorrt_plugin.md/

Which tells me to follow same kind of procedure which I followed with ONNX runtime support of DCN-v2(ModulatedDeformConv2d)

This link says, it supports these plugins with tensorrt7 only. This will not work in Tensorrt8 with MMCV?

Is ModulatedDeformConv2d is supported in MMDeploy with tensorrt8 ?

**Comment by grimoire** [comment]
Plugins in MMDeploy support both 7 and 8.

**Comment by abhiagwl4262** [comment]
I have been following this link to install MMCV with tensorrt for custom plugins. 
`https://github.com/open-mmlab/mmcv/blob/master/docs/en/deployment/tensorrt_plugin.md/`

During installation I didn't see any error but while importing I am facing this - 

```
>>> from mmcv.tensorrt import  TRTWrapper
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/abhishek/TRT/mmcv/mmcv/tensorrt/__init__.py", line 19, in <module>
    from .tensorrt_utils import (TRTWraper, TRTWrapper, load_trt_engine,
  File "/home/ubuntu/abhishek/TRT/mmcv/mmcv/tensorrt/tensorrt_utils.py", line 17, in <module>
    device_id: int = 0) -> trt.ICudaEngine:
AttributeError: type object 'tensorrt.tensorrt.ILogger' has no attribute 'Severity'
```

**Comment by abhiagwl4262** [comment]
> @grimoire, I have been following this link to install MMCV with tensorrt for custom plugins. https://github.com/open-mmlab/mmcv/blob/master/docs/en/deployment/tensorrt_plugin.md/
> 
> JUST ONE change - I am using ubuntu18.04 tar file - TensorRT-7.2.1.6.Ubuntu-18.04.x86_64-gnu.cuda-10.2.cudnn8.0.tar.gz instead of ubuntu16.04 - TensorRT-7.2.1.6.Ubuntu-16.04.x86_64-gnu.cuda-10.2.cudnn8.0.tar.gz
> 
> During installation I didn't see any error but while importing I am facing this -
> 
> ```
> >>> from mmcv.tensorrt import  TRTWrapper
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/ubuntu/abhishek/TRT/mmcv/mmcv/tensorrt/__init__.py", line 19, in <module>
>     from .tensorrt_utils import (TRTWraper, TRTWrapper, load_trt_engine,
>   File "/home/ubuntu/abhishek/TRT/mmcv/mmcv/tensorrt/tensorrt_utils.py", line 17, in <module>
>     device_id: int = 0) -> trt.ICudaEngine:
> AttributeError: type object 'tensorrt.tensorrt.ILogger' has no attribute 'Severity'
> ```

@grimoire I could resolve this by changing 
https://github.com/open-mmlab/mmcv/blob/f527e43c1a1e52e5903410255aea1f71f005a161/mmcv/tensorrt/tensorrt_utils.py#L14 to 
`log_level: trt.Logger.Severity = trt.Logger.ERROR,`

But I am facing this now - 

```
file "/home/ubuntu/abhishek/TRT/mmcv/mmcv/tensorrt/tensorrt_utils.py", line 73, in onnx2trt
    if not parser.parse(onnx_model.SerializeToString()):
IndexError: Attribute not found: axes
```

**Comment by grimoire** [comment]
Please note that ONNX Runtime and TensorRT support has been deprecated in MMCV. Please try MMDeploy if you want to deploy the model.

**Comment by abhiagwl4262** [comment]
@grimoire  To be able to use mmdeploy, I will need to add my model to MMDET, right ? To avoid that I wanna go the MMCV way.

**Comment by grimoire** [comment]
No, you don't need to.

model convert
```python
import torch
from mmcv.ops import ModulatedDeformConv2dPack
from mmdeploy.apis.onnx import export
from mmdeploy.apis.tensorrt import from_onnx
from mmdeploy.backend.tensorrt import save

model = ModulatedDeformConv2dPack(3, 8, 3, 1, 1).cuda()
x = torch.rand(1, 3, 32, 32).cuda()
model_name = 'tmp'

# export onnx
export(
    model,
    x,
    model_name,
    'tensorrt',
    input_names=['input'],
    output_names=['output'],
    opset_version=11)

# create tensorrt engine
engine = from_onnx(
    model_name + '.onnx',
    model_name,
    input_shapes=dict(
        input=dict(min_shape=x.shape, opt_shape=x.shape, max_shape=x.shape)),
    max_workspace_size=1 << 30)

# save engine
save(engine, model_name + '.engine')

```

load and inference by python
```python
import torch
from mmdeploy.backend.tensorrt import TRTWrapper, load

x = torch.rand(1, 3, 32, 32).cuda()
model_name = 'tmp'

engine = load(model_name + '.engine')

# create wrapper
wrapper = TRTWrapper(engine)

with torch.no_grad():
    trt_output = wrapper({'input': x})['output']

```

Note that please do not put model export and inference in the same thread.

**Comment by abhiagwl4262** [comment]
> > @grimoire, I have been following this link to install MMCV with tensorrt for custom plugins. https://github.com/open-mmlab/mmcv/blob/master/docs/en/deployment/tensorrt_plugin.md/
> > JUST ONE change - I am using ubuntu18.04 tar file - TensorRT-7.2.1.6.Ubuntu-18.04.x86_64-gnu.cuda-10.2.cudnn8.0.tar.gz instead of ubuntu16.04 - TensorRT-7.2.1.6.Ubuntu-16.04.x86_64-gnu.cuda-10.2.cudnn8.0.tar.gz
> > During installation I didn't see any error but while importing I am facing this -
> > ```
> > >>> from mmcv.tensorrt import  TRTWrapper
> > Traceback (most recent call last):
> >   File "<stdin>", line 1, in <module>
> >   File "/home/ubuntu/abhishek/TRT/mmcv/mmcv/tensorrt/__init__.py", line 19, in <module>
> >     from .tensorrt_utils import (TRTWraper, TRTWrapper, load_trt_engine,
> >   File "/home/ubuntu/abhishek/TRT/mmcv/mmcv/tensorrt/tensorrt_utils.py", line 17, in <module>
> >     device_id: int = 0) -> trt.ICudaEngine:
> > AttributeError: type object 'tensorrt.tensorrt.ILogger' has no attribute 'Severity'
> > ```
> 
> @grimoire I could resolve this by changing
> 
> https://github.com/open-mmlab/mmcv/blob/f527e43c1a1e52e5903410255aea1f71f005a161/mmcv/tensorrt/tensorrt_utils.py#L14
> 
> to
> `log_level: trt.Logger.Severity = trt.Logger.ERROR,`
> But I am facing this now -
> 
> ```
> file "/home/ubuntu/abhishek/TRT/mmcv/mmcv/tensorrt/tensorrt_utils.py", line 73, in onnx2trt
>     if not parser.parse(onnx_model.SerializeToString()):
> IndexError: Attribute not found: axes
> ```
> 
> I am attaching ONNX model for the reference [here](https://drive.google.com/file/d/1pCz1_uEm2SUqa-p3TYlz8e7wHkOdr1AJ/view?usp=sharing)

@grimoire BTW I could resolve this by choosing opset_version=11 for onnx export, I was using opset_version=13 before.

**Comment by abhiagwl4262** [comment]
> No, you don't need to.
> 
> model convert
> 
> ```python
> import torch
> from mmcv.ops import ModulatedDeformConv2dPack
> from mmdeploy.apis.onnx import export
> from mmdeploy.apis.tensorrt import from_onnx
> from mmdeploy.backend.tensorrt import save
> 
> model = ModulatedDeformConv2dPack(3, 8, 3, 1, 1).cuda()
> x = torch.rand(1, 3, 32, 32).cuda()
> model_name = 'tmp'
> 
> # export onnx
> export(
>     model,
>     x,
>     model_name,
>     'tensorrt',
>     input_names=['input'],
>     output_names=['output'],
>     opset_version=11)
> 
> # create tensorrt engine
> engine = from_onnx(
>     model_name + '.onnx',
>     model_name,
>     input_shapes=dict(
>         input=dict(min_shape=x.shape, opt_shape=x.shape, max_shape=x.shape)),
>     max_workspace_size=1 << 30)
> 
> # save engine
> save(engine, model_name + '.engine')
> ```
> 
> load and inference by python
> 
> ```python
> import torch
> from mmdeploy.backend.tensorrt import TRTWrapper, load
> 
> x = torch.rand(1, 3, 32, 32).cuda()
> model_name = 'tmp'
> 
> engine = load(model_name + '.engine')
> 
> # create wrapper
> wrapper = TRTWrapper(engine)
> 
> with torch.no_grad():
>     trt_output = wrapper({'input': x})['output']
> ```
> 
> Note that please do not put model export and inference in the same thread.

@grimoire Ohh great. Thanks for letting me know that I don't need to add instance segmentation model to mmdet to deploy with mmdeploy. 

I did use https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/get_started.md to seup the environment. 

I am running the ModulatedDeformConv2d as you shared. I am getting the following error :- 

```
2022-08-04 17:34:58,904 - mmdeploy - WARNING - Could not load the library of tensorrt plugins.             Because the file does not exist: 
Traceback (most recent call last):
  File "test_dcnv2.py", line 22, in <module>
    engine = from_onnx(
  File "/home/ubuntu/anaconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/backend/tensorrt/utils.py", line 113, in from_onnx
    raise RuntimeError(f'Failed to parse onnx, {error_msgs}')
RuntimeError: Failed to parse onnx, In node 20 (importFallbackPluginImporter): UNSUPPORTED_NODE: Assertion failed: creator && "Plugin not found, are the plugin name, version, and namespace correct?"
```
It is not detecting Tensorrt plugiuns

**Comment by abhiagwl4262** [comment]
Thanks @grimoire. I could convert my pytorch model to trt successfully.
