### ISSUE TITLE
syncBN 'super' object has no attribute '_specify_ddp_gpu_num'

### ISSUE THREAD

**Issue by 1170801121** [open-mmlab/mmcv#2171]
Hi, I notice that you fixed this bug at https://github.com/open-mmlab/mmcv/pull/1138. But I still encounter this when I run my code. I install pytorch and mmcv-full through 
```
pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html
pip install mmcv-full==1.3.0 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.9.0/index.html
```

The bug is as follows:
```
Traceback (most recent call last):
  File "/cluster/project/vss/lib64/python3.8/site-packages/mmcv/utils/registry.py", line 179, in build_from_cfg
    return obj_cls(**args)
  File "/cluster/home/vss/VSS-CFFM/mmseg/models/decode_heads/cffm_head.py", line 53, in __init__
    self.linear_fuse = ConvModule(
  File "/cluster/project/vss/lib64/python3.8/site-packages/mmcv/cnn/bricks/conv_module.py", line 147, in __init__
    self.norm_name, norm = build_norm_layer(norm_cfg, norm_channels)
  File "/cluster/project/vss/lib64/python3.8/site-packages/mmcv/cnn/bricks/norm.py", line 110, in build_norm_layer
    layer._specify_ddp_gpu_num(1)
  File "/cluster/project/vss/lib64/python3.8/site-packages/mmcv/utils/parrots_wrapper.py", line 87, in _specify_ddp_gpu_num
    super()._specify_ddp_gpu_num(gpu_size)
AttributeError: 'super' object has no attribute '_specify_ddp_gpu_num'
```
My env:
Cuda=11.1.1
pytorch=1.9.0
mmcv=1.3.0

Thank you for help!

**Comment by zhouzaida** [comment]
Could you check whether `torch.nn.SyncBatchNorm` has this method?

**Comment by 1170801121** [comment]
> Could you check whether `torch.nn.SyncBatchNorm` has this method?

I am not sure I understand your question. Can you elaborate more on what do you mean by 'this method'? I just check that I have this:
>>> torch.nn.SyncBatchNorm
<class 'torch.nn.modules.batchnorm.SyncBatchNorm'>

**Comment by zhouzaida** [comment]
Hi, this error had been resolved since v1.3.9 so you can upgrade your mmcv to v1.3.9 or higher with the following command

```bash
pip install mmcv-full==1.3.9 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.9.0/index.html
```

**Comment by 1170801121** [comment]
But my current codebase is from mmseg which has assert clause to check the mmcv version to be from 1.1.4 to 1.3.0 in its __init__.py.  
```
MMCV_MIN = '1.1.4'
MMCV_MAX = '1.3.0'
assert (mmcv_min_version <= mmcv_version <= mmcv_max_version), \
    f'MMCV=={mmcv.__version__} is used but incompatible. ' \
    f'Please install mmcv>={mmcv_min_version}, <={mmcv_max_version}.'
```
Thus if I update mmcv to 1.3.9, I need to remove the version check. Will remove the version assert clause impact the running of the code base?

**Comment by zhouzaida** [comment]
Got it. You also can refer to https://github.com/open-mmlab/mmcv/pull/1138 to fix the error you met.
