### ISSUE TITLE
Potential bug in calc_square_dist()

### ISSUE THREAD

**Issue by chyohoo** [open-mmlab/mmcv#2178]
https://github.com/open-mmlab/mmcv/blob/f527e43c1a1e52e5903410255aea1f71f005a161/mmcv/ops/points_sampler.py#L12
This function could return NaN, since the square dist could be negative in some cases.

for example:
```
a = torch.tensor([[[0.0000, 0.0000, 0.2188, 0.0000, 0.0000]]])
b = torch.tensor([[[0.0000, 0.0000, 0.2189, 0.0000, 0.0000]]])
calc_square_dist(a,b)

```

**Comment by zhouzaida** [comment]
Please @ZCMax have a look.

**Comment by ZCMax** [comment]
I can not produce the `NaN` result using your provided example. It calculates the square dist correctly.

**Comment by chyohoo** [comment]
> I can not reproduce the `NaN` result using your provided example. It calculates the square dist correctly.

this is very strange. I can reproduce neither. But I did encounter NaN while using it.
![image](https://user-images.githubusercontent.com/6997278/183035655-f045ed52-74fe-4ca9-930a-8737ee74998f.png)

**Comment by zhouzaida** [comment]
Hi, what is your mmcv version? I also can not reproduce the `NaN` result.

![image](https://user-images.githubusercontent.com/58739961/183559499-16b12424-a5cf-4d21-b509-f681ab7e891c.png)

**Comment by chyohoo** [comment]
[nan_tensor.zip](https://github.com/open-mmlab/mmcv/files/9297341/nan_tensor.zip)
I save the two tensors in the zip file.
My  mmcv version is 

> MMCV: 1.5.0
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.0

**Comment by Tai-Wang** [comment]
This seems to be caused by a subtle numerical problem. Because there can be negative values around zero in the results of `dist = a_square + b_square - 2 * corr_matrix`, i.e., in `dist`, `nan` can be produced by computing `sqrt(dist)`. A simple workaround is to add an small number `epsilon` to dist when computing its square root. Please @ZCMax have a look at whether this modification has other influence or has any effect on current related models.

**Comment by chyohoo** [comment]
> This seems to be caused by a subtle numerical problem. Because there can be negative values around zero in the results of `dist = a_square + b_square - 2 * corr_matrix`, i.e., in `dist`, `nan` can be produced by computing `sqrt(dist)`. A simple workaround is to add an small number `epsilon` to dist when computing its square root. Please @ZCMax have a look at whether this modification has other influence or has any effect on current related models.

yep. using `torch.cdist` instead not seen `nan` so far

**Comment by ZCMax** [comment]
> 

Great, `torch.dist` would be a better solution for this situation, contributions ( PR) are welcome if you have time after checking the performance influence of this modification.
