### ISSUE TITLE
Sharp Aware Minima implementation

### ISSUE THREAD

**Issue by doem97** [open-mmlab/mmcv#2190]
Dear developers,

I want to adopt SAM (Sharpness-aware minima) from [repo](https://github.com/davda54/sam) or [paper](https://arxiv.org/abs/2010.01412). I found it so difficult to do backward -> optimize -> full-backward -> optimize with mmcv. May I get some help to fit this code into mmcv?

```python
for input, output in data:
  def closure():
    loss = loss_function(output, model(input))
    loss.backward()
    return loss

  loss = loss_function(output, model(input))
  loss.backward()
  optimizer.step(closure)
  optimizer.zero_grad()
```

Many thanks!!!!!!

**Comment by HAOCHENYE** [comment]
Hi, using `OptimizerHook` may not be suitable for this case. You could do this by the following steps:

1.  Regist `SAM` optimizer in `OPTIMIZERS`.
2. Set `optimizer_config=None` when you call `register_training_hooks` to disable `OptimizerHook`.
3. Implement the optimize logic as above in the `model.train_step`.

[MMGeneration](https://github.com/open-mmlab/mmgeneration) optimize the model with the custom logic, you can refer to it.

**Comment by doem97** [comment]
> Hi, using `OptimizerHook` may not be suitable for this case. You could do this by the following steps:
> 
> 1. Regist `SAM` optimizer in `OPTIMIZERS`.
> 2. Set `optimizer_config=None` when you call `register_training_hooks` to disable `OptimizerHook`.
> 3. Implement the optimize logic as above in the `model.train_step`.
> 
> [MMGeneration](https://github.com/open-mmlab/mmgeneration) optimize the model with the custom logic, you can refer to it.

Thanks! It's a good solution. But I think may need to change the runner as it is actually a "two forward run" which is not what the `EpochBasedRunner` do.

**Comment by doem97** [comment]
Hi all, just for reference, I solve by registering three modules: `TwoForwardRunner`, `SAMOptimizer`, `SAMOptimizerHook`. I provide the main modifications here.
1. Register a `TwoForwardRunner` from the base runner with two full-forwards, and add new hook `after_first_forward`
```python
# mmcv.runner.epoch_based_runner
@RUNNERS.register_module()
class TwoForwardRunner(EpochBasedRunner):
    """Replace Runner with two forward SAM."""
    def train(self, ...):
        ...
        for i, data_batch in enumerate(self.data_loader):
            ...
            self.run_iter(data_batch, train_mode=True, **kwargs)
            self.call_hook("after_first_forward") # SAMOptimizer.first_step()
            self.run_iter(data_batch, train_mode=True, **kwargs)
            self.call_hook("after_train_iter") # SAMOptimizer.second_step()
    ...

# mmcv.runner.hooks.hook
class Hook:
    def after_first_forward(self, runner):
        pass
```

2. Register a `SAMOptimizer` that does SAM optimization for any `torch.optim.Optim` optimizer. (thanks to @davda54/[sam](https://github.com/davda54/sam))
```python
# mmcv.runner.optimizer.sam_optimizer
@OPTIMIZERS.register_module()
class SAMOptimizer(torch.optim.Optimizer):
    """Copy from @davda54/sam, include origin optimizer as self.base_optimizer ."""
    def __init__(self, ...):
        self.base_optimizer = torch.optim.OriginOptimizer(...)
    def first_step(self, ...): ...
    def second_step(self, ...): ...
```

3. Implement `SAMOptimizerHook` to trigger two-step optimization:
```python
# mmcv.runner.hooks.optimizer
@HOOKS.register_module()
class SAMOptimizerHook(OptimizerHook):
    """Optimizer Hook implements multi-iters SAM"""
    def after_first_forward(self, runner):
        ...
        runner.outputs["loss"].backward()
        runner.optimizer.first_step(zero_grad=True)

    def after_train_iter(self, runner):
        ...
        runner.outputs["loss"].backward()
        runner.optimizer.second_step(zero_grad=False)
```

4. (FINAL) modify the config:
```python
# config.py
optimizer = dict(type="SAM", ...)
optimizer_config = dict(type="SAMOptimizerHook", ...)
runner = dict(type="SAMRunner", ...)
```
