### ISSUE TITLE
RuntimeError: expected scalar type Half but found Float with three_nn

### ISSUE THREAD

**Issue by DanieeelLiu** [open-mmlab/mmcv#2191]
Hi, I tried to run three_nn operator with Half datatype, but got following unexpected error. It seems that the three_nn_cuda_kernel supports half dataype. (MMCV==1.6.1, torch=1.9).
I set the datatype of unknown, and known to torch.half in test_three_nn.py and run command "pytest test_three_nn.py"

Error message:
target = tensor([[[-1.8369,  3.5605, -0.7866],
         [ 0.7617,  2.9414,  0.2314],
         [-0.6504,  3.6641, -1.0625],
    ...9],
         [-0.5620,  1.4229, -1.2861],
         [-0.5884,  1.3115, -1.2900]]], device='cuda:0', dtype=torch.float16)
source = tensor([[[-1.8369,  3.5605, -0.7866],
         [ 0.7617,  2.9414,  0.2314],
         [-0.6504,  3.6641, -1.0625],
    ...7],
         [-1.3398,  1.9990, -0.3699],
         [-1.3398,  1.9990, -0.3699]]], device='cuda:0', dtype=torch.float16)

    @staticmethod
    def forward(ctx: Any, target: torch.Tensor,
                source: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
        """
        Args:
            target (torch.Tensor): shape (B, N, 3), points set that needs to
                find the nearest neighbors.
            source (torch.Tensor): shape (B, M, 3), points set that is used
                to find the nearest neighbors of points in target set.
    
        Returns:
            torch.Tensor: shape (B, N, 3), L2 distance of each point in target
            set to their corresponding top three nearest neighbors.
        """
        target = target.contiguous()
        source = source.contiguous()
    
        B, N, _ = target.size()
        m = source.size(1)
        dist2 = torch.cuda.FloatTensor(B, N, 3)
        idx = torch.cuda.IntTensor(B, N, 3)
    
>       ext_module.three_nn_forward(target, source, dist2, idx, b=B, n=N, m=m)
E       RuntimeError: expected scalar type Half but found Float

**Comment by grimoire** [comment]
https://github.com/open-mmlab/mmcv/blob/f527e43c1a1e52e5903410255aea1f71f005a161/mmcv/ops/three_nn.py#L37 dist2 here is float tensor.

**Comment by DanieeelLiu** [comment]
Yep. From my point of view, this operator can support half, float and double datatype if we change it to "dist2 = target.new_zeros(target.shape)". I think the problem is that the three_nn_cuda_kernel can support half datatype while the three_nn forward api only supports float by set dist2 to float tensor. So is there any reason that dist2 is only set to float tensor?

**Comment by grimoire** [comment]
Theoretically, it is OK to share dtype between dist2 and other inputs.
You can create a PR and discuss it with the developers of MMDet3d directly.
