### ISSUE TITLE
[Feature Request] 关于self attention的flops计算

### ISSUE THREAD

**Issue by yingkaining** [open-mmlab/mmcv#2192]
**Describe the feature**
什么时候可以支持self attention的flop计算

**Motivation**
A clear and concise description of the motivation of the feature.
Ex1. It is inconvenient when \[....\].
Ex2. There is a recent paper \[....\], which is very helpful for \[....\].
在mmdet诸如detr是不支持flops计算的，这导致在论文中与其他当方法不能够形成对比，这个是一个很大的劣势，d2中就支持SA的flop计算。

**Comment by HAOCHENYE** [comment]
我们是有计划实现一个更加通用的 flops counter 的，如果您有一些好的想法也可以一起讨论，一起来支持这个特性~
