### ISSUE TITLE
MacOS install mmcv failed

### ISSUE THREAD

**Issue by Mactarvish** [open-mmlab/mmcv#2194]
系统信息： MacOS Monterey 12.04
芯片 Apple M2

❯ conda activate open-mmlab
❯ CC=clang CXX=clang++ CFLAGS='-stdlib=libc++' MMCV_WITH_OPS=1 pip install -e .

Obtaining file:///Users/mactarvish/fengyongronglu/mmcv
  Preparing metadata (setup.py) ... done
Requirement already satisfied: addict in /Users/mactarvish/opt/anaconda3/envs/open-mmlab/lib/python3.7/site-packages (from mmcv-full==1.6.1) (2.4.0)
Requirement already satisfied: numpy in /Users/mactarvish/opt/anaconda3/envs/open-mmlab/lib/python3.7/site-packages (from mmcv-full==1.6.1) (1.21.5)
Requirement already satisfied: packaging in /Users/mactarvish/opt/anaconda3/envs/open-mmlab/lib/python3.7/site-packages (from mmcv-full==1.6.1) (21.3)
Requirement already satisfied: Pillow in /Users/mactarvish/opt/anaconda3/envs/open-mmlab/lib/python3.7/site-packages (from mmcv-full==1.6.1) (9.2.0)
Requirement already satisfied: pyyaml in /Users/mactarvish/opt/anaconda3/envs/open-mmlab/lib/python3.7/site-packages (from mmcv-full==1.6.1) (6.0)
Requirement already satisfied: yapf in /Users/mactarvish/opt/anaconda3/envs/open-mmlab/lib/python3.7/site-packages (from mmcv-full==1.6.1) (0.32.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /Users/mactarvish/opt/anaconda3/envs/open-mmlab/lib/python3.7/site-packages (from packaging->mmcv-full==1.6.1) (3.0.9)
Installing collected packages: mmcv-full
  Running setup.py develop for mmcv-full
    error: subprocess-exited-with-error
    
    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> [27 lines of output]
        running develop
        running egg_info
        writing mmcv_full.egg-info/PKG-INFO
        writing dependency_links to mmcv_full.egg-info/dependency_links.txt
        writing requirements to mmcv_full.egg-info/requires.txt
        writing top-level names to mmcv_full.egg-info/top_level.txt
        reading manifest file 'mmcv_full.egg-info/SOURCES.txt'
        reading manifest template 'MANIFEST.in'
        adding license file 'LICENSE'
        adding license file 'LICENSES.md'
        writing manifest file 'mmcv_full.egg-info/SOURCES.txt'
        running build_ext
        building 'mmcv._ext' extension
        clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/mactarvish/opt/anaconda3/envs/open-mmlab/include -arch x86_64 -I/Users/mactarvish/opt/anaconda3/envs/open-mmlab/include -arch x86_64 -stdlib=libc++ -DMMCV_WITH_MPS -I/Users/mactarvish/fengyongronglu/mmcv/mmcv/ops/csrc/common -I/Users/mactarvish/fengyongronglu/mmcv/mmcv/ops/csrc/common/mps -I/Users/mactarvish/opt/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include -I/Users/mactarvish/opt/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/Users/mactarvish/opt/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/TH -I/Users/mactarvish/opt/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/THC -I/Users/mactarvish/opt/anaconda3/envs/open-mmlab/include/python3.7m -c ./mmcv/ops/csrc/common/mps/MPSLibrary.mm -o build/temp.macosx-10.9-x86_64-3.7/./mmcv/ops/csrc/common/mps/MPSLibrary.o -Wall -std=c++17 -framework Metal -framework Foundation -ObjC++ -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_clang\" -DPYBIND11_STDLIB=\"_libcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1002\" -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0
        clang: warning: -framework Metal: 'linker' input unused [-Wunused-command-line-argument]
        clang: warning: -framework Foundation: 'linker' input unused [-Wunused-command-line-argument]
        ./mmcv/ops/csrc/common/mps/MPSLibrary.mm:2:10: fatal error: 'c10/util/CallOnce.h' file not found
        #include <c10/util/CallOnce.h>
                 ^~~~~~~~~~~~~~~~~~~~~
        1 error generated.
        /Users/mactarvish/opt/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/command/easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
          EasyInstallDeprecationWarning,
        /Users/mactarvish/opt/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
          setuptools.SetuptoolsDeprecationWarning,
        /Users/mactarvish/opt/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/cpp_extension.py:411: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
          warnings.warn(msg.format('we could not find ninja.'))
        error: command '/usr/bin/clang' failed with exit code 1
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> [27 lines of output]
    running develop
    running egg_info
    writing mmcv_full.egg-info/PKG-INFO
    writing dependency_links to mmcv_full.egg-info/dependency_links.txt
    writing requirements to mmcv_full.egg-info/requires.txt
    writing top-level names to mmcv_full.egg-info/top_level.txt
    reading manifest file 'mmcv_full.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    adding license file 'LICENSE'
    adding license file 'LICENSES.md'
    writing manifest file 'mmcv_full.egg-info/SOURCES.txt'
    running build_ext
    building 'mmcv._ext' extension
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/mactarvish/opt/anaconda3/envs/open-mmlab/include -arch x86_64 -I/Users/mactarvish/opt/anaconda3/envs/open-mmlab/include -arch x86_64 -stdlib=libc++ -DMMCV_WITH_MPS -I/Users/mactarvish/fengyongronglu/mmcv/mmcv/ops/csrc/common -I/Users/mactarvish/fengyongronglu/mmcv/mmcv/ops/csrc/common/mps -I/Users/mactarvish/opt/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include -I/Users/mactarvish/opt/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/Users/mactarvish/opt/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/TH -I/Users/mactarvish/opt/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/THC -I/Users/mactarvish/opt/anaconda3/envs/open-mmlab/include/python3.7m -c ./mmcv/ops/csrc/common/mps/MPSLibrary.mm -o build/temp.macosx-10.9-x86_64-3.7/./mmcv/ops/csrc/common/mps/MPSLibrary.o -Wall -std=c++17 -framework Metal -framework Foundation -ObjC++ -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_clang\" -DPYBIND11_STDLIB=\"_libcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1002\" -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0
    clang: warning: -framework Metal: 'linker' input unused [-Wunused-command-line-argument]
    clang: warning: -framework Foundation: 'linker' input unused [-Wunused-command-line-argument]
    ./mmcv/ops/csrc/common/mps/MPSLibrary.mm:2:10: fatal error: 'c10/util/CallOnce.h' file not found
    #include <c10/util/CallOnce.h>
             ^~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    /Users/mactarvish/opt/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/command/easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      EasyInstallDeprecationWarning,
    /Users/mactarvish/opt/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      setuptools.SetuptoolsDeprecationWarning,
    /Users/mactarvish/opt/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/cpp_extension.py:411: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
      warnings.warn(msg.format('we could not find ninja.'))
    error: command '/usr/bin/clang' failed with exit code 1
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by ice-tong** [comment]
@Mactarvish If you want to compile mmcv-full with MPS ops, you should install the pytorch-nightly which have `c10/util/CallOnce.h`.  

```shell
conda install pytorch torchvision -c pytorch-nightly
```

And you should make sure you have Xcode installed on your Mac, otherwise you will get an error: `xcrun: error: unable to find utility "metal"`.

Feel free to feedback to us if you have any problems you meet.

**Comment by Mactarvish** [comment]
Thanks so much @ice-tong ,after updated system to 12.5 and reinstalled pytorch-nightly, the problem's been solved.
