### ISSUE TITLE
Does the flops_counter support torch.matmul() and torch.nn.functional.interpolate()?

### ISSUE THREAD

**Issue by wmkai** [open-mmlab/mmcv#2196]
is there some documents for this?

**Comment by HAOCHENYE** [comment]
Sorry for the late reply, the supported layers are listed as follows:
https://github.com/open-mmlab/mmcv/blob/595c2ebeb93c873ab2fc4af67a5b81640b7bc314/mmcv/cnn/utils/flops_counter.py#L557.

Currently,  it does not support calculating the ops you mentioned.

**Comment by wmkai** [comment]
thanks for your reply!
