### ISSUE TITLE
My program always get stuck in dataloader

### ISSUE THREAD

**Issue by MMY1994** [open-mmlab/mmcv#2206]
![code](https://user-images.githubusercontent.com/33061770/185142379-1cc90465-835d-41c7-beb9-c7f6205610a4.png)
![terminal](https://user-images.githubusercontent.com/33061770/185142392-7fe6e9a1-e482-4581-8626-6dc23d493d22.png)

**Comment by HAOCHENYE** [comment]
What's your `num_workers` of `DataLoader`, your can try to make it samller.
