### ISSUE TITLE
Can't import build_from_cfg from mmcv.utils, ImportError

### ISSUE THREAD

**Issue by FranzEricSchneider** [open-mmlab/mmcv#2213]
Thanks for reporting the unexpected results and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help. **Yes, I can't find anything about `build_from_cfg`**
2. I have read the [FAQ documentation](https://mmcv.readthedocs.io/en/latest/trouble_shooting.html) but cannot get the expected help. **Doesn't exist :)**
3. The unexpected results still exist in the latest version. **Yes, appearing on 1.6.1**

**Describe the Issue**
A clear and concise description of what the bug is, including what results are expected and what the real results you got.

When installing `1.6.1` from `pip` I am trying to import `mmcv.utils.build_from_cfg` and it is failing. This came up in an `mmsegmentation` PR I am trying to write: https://github.com/open-mmlab/mmsegmentation/pull/1872

**Reproduction**

1. What command, code, or script did you run?

This is what I'm experiencing, but as seen in that original `mmsegmentation` PR others are not always experiencing this. What can I do to fix my installation? Something seems wrong, because when I look at `mmcv.utils.__init__py` (https://github.com/open-mmlab/mmcv/blob/master/mmcv/utils/__init__.py) I can clearly see that `from .registry import Registry, build_from_cfg` and `__all__ = [ ... 'build_from_cfg' ... ]` should make it importable.

```bash
eric@laptop:~$ pip install mmcv-full==1.6.1 --no-cache-dir
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Defaulting to user installation because normal site-packages is not writeable
Collecting mmcv-full==1.6.1
  Downloading mmcv-full-1.6.1.tar.gz (563 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 563.2/563.2 kB 11.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: addict in ./.local/lib/python3.8/site-packages (from mmcv-full==1.6.1) (2.4.0)
Requirement already satisfied: numpy in ./.local/lib/python3.8/site-packages (from mmcv-full==1.6.1) (1.22.2)
Requirement already satisfied: packaging in /usr/lib/python3/dist-packages (from mmcv-full==1.6.1) (20.3)
Requirement already satisfied: Pillow in ./.local/lib/python3.8/site-packages (from mmcv-full==1.6.1) (8.3.1)
Requirement already satisfied: pyyaml in ./.local/lib/python3.8/site-packages (from mmcv-full==1.6.1) (6.0)
Requirement already satisfied: yapf in ./.local/lib/python3.8/site-packages (from mmcv-full==1.6.1) (0.32.0)
Building wheels for collected packages: mmcv-full
  Building wheel for mmcv-full (setup.py) ... done
  Created wheel for mmcv-full: filename=mmcv_full-1.6.1-py2.py3-none-any.whl size=860366 sha256=3ef6e4dc050eb780f39a8ed6a134a88053ecedda1d5ca616919790b0b804dd3f
  Stored in directory: /tmp/pip-ephem-wheel-cache-6j7k8uqk/wheels/05/48/31/8aacd3b86a76e602057c5c1dd234c8bbf7efcce5bec821ea4c
Successfully built mmcv-full
Installing collected packages: mmcv-full
Successfully installed mmcv-full-1.6.1

eric@laptop:~$ ipy
Python 3.8.10 (default, Jun 22 2022, 20:18:18) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.13.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import mmcv; print(mmcv.__version__); from mmcv.utils import build_from_cfg

1.6.1

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-8865daaf63bb> in <module>
----> 1 import mmcv; print(mmcv.__version__); from mmcv.utils import build_from_cfg

ImportError: cannot import name 'build_from_cfg' from 'mmcv.utils' (/home/eric/.local/lib/python3.8/site-packages/mmcv/utils/__init__.py)
```

2. Did you make any modifications on the code? Did you understand what you have modified?

No modifications.

**Environment**

1. Please run `python -c "from mmcv.utils import collect_env; print(collect_env())"` to collect necessary environment information and paste it here.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'collect_env' from 'mmcv.utils' (/home/eric/.local/lib/python3.8/site-packages/mmcv/utils/__init__.py)
```

2. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

Irrelevant.

**Comment by HAOCHENYE** [comment]
Thanks for your feedback, will buildingmmcv-full from the source solve your problem,?

**Comment by FranzEricSchneider** [comment]
I apologize for the slow reply, `pip install openmim && mim install mmcv-full` did the trick. Thanks!

**Comment by HernandoR** [comment]
how could i solve this problem without using mim?
