### ISSUE TITLE
pip install failed

### ISSUE THREAD

**Issue by NEFUJoeyChen** [open-mmlab/mmcv#2214]
![image](https://user-images.githubusercontent.com/50317721/185521088-f79a613b-3a71-4ec6-afd7-1ebbd04940e2.png)
Building wheel for mmcv-full (setup.py) ... \
This state has lasted for four hours. I think it is abnormal.

**Comment by ice-tong** [comment]
Hi @NEFUJoeyChen , please try to install using the following command:

```
pip install mmcv-full==1.6.0 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.9.0/index.html
```

NOTE in [mmcv doc](https://mmcv.readthedocs.io/en/latest/get_started/installation.html): 

> mmcv-full is only compiled on PyTorch 1.x.0 because the compatibility usually holds between 1.x.0 and 1.x.1. If your PyTorch version is 1.x.1, you can install mmcv-full compiled with PyTorch 1.x.0 and it usually works well. For example, if your PyTorch version is 1.8.1 and CUDA version is 11.1, you can use the following command to install mmcv-full.
