### ISSUE TITLE
Multitask framework utilizes mmseg/mmdet

### ISSUE THREAD

**Issue by jyang68sh** [open-mmlab/mmcv#2227]
Hi is there a plan for multitask framework for mmseg & mmdet?
Thanks!

**Comment by zhouzaida** [comment]
Hi, we currently have no plans to support multi-task learning, but our upcoming open source project will do a good job of supporting the use of modules from multiple projects together.

**Comment by jyang68sh** [comment]
> Hi, we currently have no plans to support multi-task learning, but our upcoming open source project will do a good job of supporting the use of modules from multiple projects together.

@zhouzaida I am glad to hear that. Please note me when the new project comes out. I am a big fan of your framework

**Comment by zhouzaida** [comment]
Hi @jyang68sh , we have released a new project [MMEngine](https://github.com/open-mmlab/mmengine) several days before. If you want to build a unified module from mmseg and mmdet, the [documentation](https://mmengine.readthedocs.io/zh_CN/latest/examples/cross_library.html) will be helpful.
