### ISSUE TITLE
mmcv.imread return None

### ISSUE THREAD

**Issue by zgplvyou** [open-mmlab/mmcv#2239]
When I use mmcv load pictures, some pictures can be load, however, there are some pictures will return None.
There is my code, so simple.
img = mmcv.imread('test_006960.jpg')
print(img)
the img will return None, I'm not sure what`s wrong, I upload the image.
![test_006960](https://user-images.githubusercontent.com/22234278/187407323-5d4b0c69-5e3b-471b-940b-9536243d3a3d.jpg)

mmcv                   1.6.1
mmcv-full              1.6.0

**Comment by ice-tong** [comment]
Hi @zgplvyou，I found that the image you posted is truncated.

```python
In [1]: from PIL import Image

In [2]: fpath = './test.jpg'

In [3]: Image.open(fpath).load()
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Input In [3], in <cell line: 1>()
----> 1 Image.open(fpath).load()

File ~/miniconda3/envs/xxx/lib/python3.8/site-packages/PIL/ImageFile.py:251, in ImageFile.load(self)
    249         break
    250     else:
--> 251         raise OSError(
    252             "image file is truncated "
    253             f"({len(b)} bytes not processed)"
    254         )
    256 b = b + s
    257 n, err_code = decoder.decode(b)

OSError: image file is truncated (6 bytes not processed)

In [4]: with open(fpath, 'rb') as f:
   ...:     f.seek(-2, 2)
   ...:     print(f.read())
   ...: 
b'\xa1c'  # The Trailer bytes of JPG should be `FF D9`.

In [5]:
```

**Comment by zgplvyou** [comment]
> Hi @zgplvyou，I found that the image you posted is truncated.
> 
> ```python
> In [1]: from PIL import Image
> 
> In [2]: fpath = './test.jpg'
> 
> In [3]: Image.open(fpath).load()
> ---------------------------------------------------------------------------
> OSError                                   Traceback (most recent call last)
> Input In [3], in <cell line: 1>()
> ----> 1 Image.open(fpath).load()
> 
> File ~/miniconda3/envs/xxx/lib/python3.8/site-packages/PIL/ImageFile.py:251, in ImageFile.load(self)
>     249         break
>     250     else:
> --> 251         raise OSError(
>     252             "image file is truncated "
>     253             f"({len(b)} bytes not processed)"
>     254         )
>     256 b = b + s
>     257 n, err_code = decoder.decode(b)
> 
> OSError: image file is truncated (6 bytes not processed)
> 
> In [4]: with open(fpath, 'rb') as f:
>    ...:     f.seek(-2, 2)
>    ...:     print(f.read())
>    ...: 
> b'\xa1c'  # The trailer bytes of JPG should be `FF D9`.
> 
> In [5]:
> ```

the os error maybe come from PIL. on the top of ImageFile.py, it defines MAXBLOCK = 65536, when the image pixel is larger than 65535 or some pixel is lack, it will raise the error.

**Comment by ice-tong** [comment]
Hi @zgplvyou, cv2.imread got the same warning:
```python
In [1]: import cv2

In [2]: img_arr = cv2.imread('test.jpg')
Premature end of JPEG file

In [3]:
```

And most important is the trailer bytes of this JPG are not `FF D9`.
```python
In [4]: with open(fpath, 'rb') as f:
   ...:     f.seek(-2, 2)
   ...:     print(f.read())
   ...: 
b'\xa1c'  # The trailer bytes of JPG should be `FF D9`.
```

**Comment by zgplvyou** [comment]
ok,thank u for the answer,  maybe the data have some problem after unpack, i will open it and rewrite to address this error, thank u again.

**Comment by ice-tong** [comment]
I will close this issue, feel free to reopen it if you have any problems else. ^_^
