### ISSUE TITLE
update config values from command line args?

### ISSUE THREAD

**Issue by hiyyg** [open-mmlab/mmcv#225]

**Comment by xvjiarui** [comment]
Hi @hiyyg 
It is now supported in the master branch of MMCV. 
You may refer to [here](https://github.com/open-mmlab/mmdetection/blob/8d7c832a09d6c516df2d6f61e1bbfc39ce46b3f2/tools/train.py#L69-L70) for the example of usage.

**Comment by hiyyg** [comment]
Hi @xvjiarui , I wonder if it supports updating the config fields with `tuple` values from command line args?
