### ISSUE TITLE
Error in installing mmcv-full on Mac M1 Chip

### ISSUE THREAD

**Issue by AlfiHasan007** [open-mmlab/mmcv#2250]
Tried to install by following steps from the link: https://mmdetection.readthedocs.io/en/stable/get_started.html#installation
1. using CPU only step :

errors found in "mim install mmcv-full" step: 
![Screen Shot 2022-09-07 at 12 14 09 PM](https://user-images.githubusercontent.com/113052225/188939336-062afd29-8e80-4d7b-9581-34722d73aaa1.png)

![Screen Shot 2022-09-07 at 12 14 02 PM](https://user-images.githubusercontent.com/113052225/188939346-639071bf-a078-4eaf-a68f-420def36611f.png)

2. Also tried to install using pip.: same error 
3. Tried installing from main build using this command. `CC=clang CXX=clang++ CFLAGS='-stdlib=libc++' MMCV_WITH_OPS=1 pip install -e .` same error!! 
4. Tried to install the basic "mmcv" which worked but later couldn't able to find CUDA when tried.. `mmdetection` 

Somehow, no matter what I do, it's looking for CUDA. 
Can't install CUDA as its a Mac M1 Chip.

any help is much appreciated!

**Comment by zhouzaida** [comment]
Hi @AlfiHasan007 , could you provide the full log of installation?

**Comment by HAOCHENYE** [comment]
Will #2194 solve your problem?

**Comment by WilliamLeeBravo** [comment]
pytorch-nightly did solve this problem!
