### ISSUE TITLE
Convertor1 is not in the converters registry

### ISSUE THREAD

**Issue by ghoshsdeep** [open-mmlab/mmcv#2275]
I am trying to learn mmcv from docs.However I face some issue while implementing the simple example of registry from documentation 
My directory structure can be seen in the screenshots.I was running the file **example_test.py**

![Screenshot from 2022-09-20 19-22-42](https://user-images.githubusercontent.com/112154951/191276759-b0f395fd-02fc-4995-82af-8349fcb03c9a.png)
![Screenshot 
![Screenshot from 2022-09-20 19-23-11](https://user-images.githubusercontent.com/112154951/191276813-a435fff9-0e58-4fbf-b3ab-14bfa6df4687.png)
from 2022-09-20 19-22-58](https://user-images.githubusercontent.com/112154951/191276779-d6dee7ae-ae12-4bcd-8912-b4c8f06e7c4d.png)

![Screenshot from 2022-09-20 19-23-11](https://user-images.githubusercontent.com/112154951/191277435-453dd237-0aa7-41e4-be9e-083bdc465a6e.png)

![Screenshot from 2022-09-20 19-23-34](https://user-images.githubusercontent.com/112154951/191276847-ecc5b381-de9e-4164-b6aa-0d28a4b7a7b7.png)

**Comment by HAOCHENYE** [comment]
Hi~ we should import `convertor1.py` and `convertor2.py`  in `example.py` to trigger the **register process**.

**Comment by ghoshsdeep** [comment]
Thank you so much for thr reply,though convertor1 works but convertor2 still shows an error.
![Screenshot from 2022-09-22 16-39-50](https://user-images.githubusercontent.com/112154951/191731776-78ae68ca-0704-4129-ae87-1705c0d58b26.png)

**Comment by HAOCHENYE** [comment]
> Thank you so much for thr reply,though convertor1 works but convertor2 still shows an error.Isn't it supposed to take a function too? ![Screenshot from 2022-09-22 16-42-36](https://user-images.githubusercontent.com/112154951/191732250-d6f1fc2d-ff32-463b-8dd4-68ea3ac39093.png)
> 
> ![Screenshot from 2022-09-22 16-41-42](https://user-images.githubusercontent.com/112154951/191732054-2ab6c30f-9322-42fe-aecd-a452baf9d246.png)

Hi, what's your `MMCV` version? The latest `MMCV` has supported register function object

**Comment by ghoshsdeep** [comment]
Thank you
