### ISSUE TITLE
masked_conv out_w compute error: file masked_conv.py line 54

### ISSUE THREAD

**Issue by ckirchhoff2021** [open-mmlab/mmcv#2276]
Thanks for reporting the unexpected results and we appreciate it a lot.

*
![image](https://user-images.githubusercontent.com/2441530/191447892-b68f4df1-2269-4306-93b7-41583b9b141d.png)
out_w should be calculated by kernel_w while kernel_h is being used,it's a bug.
The error is at masked_conv.py line 54.

**Comment by zhouzaida** [comment]
Hi, thanks for your report. This issue had been resolved by #2264 for 2.x branch and we will pick it to master branch later.
