### ISSUE TITLE
Any Plan to Support FSDP?

### ISSUE THREAD

**Issue by twmht** [open-mmlab/mmcv#2281]
FSDP(https://pytorch.org/blog/introducing-pytorch-fully-sharded-data-parallel-api/) is great to train large model in multi-gpu environment.

It would be great if mmcv can support that.

Any play to support FSDP in the future?

**Comment by HAOCHENYE** [comment]
Thanks for your suggestions, we recently update our training architecture and realse [`MMEngin`](https://github.com/open-mmlab/mmengine). and `FSDP` has been supported in `MMEngine` ！

We sincerely invite you to experience `MMEngine `:), and your valuable comments will help us to improve `MMEngine`.

**Comment by twmht** [comment]
@HAOCHENYE 

Any idea about https://github.com/open-mmlab/mmdetection/discussions/8881?
