### ISSUE TITLE
Question about evaluation hook.

### ISSUE THREAD

**Issue by HarborYuan** [open-mmlab/mmcv#2286]
Hi, 

Thanks for your work on mmcv.

I am working on my project based on mmcv. However, when I was trying to make the EvalHook work before everything starts, I found I cannot. I checked the source code.

https://github.com/open-mmlab/mmcv/blob/bb7106755ec78561152a4273b27298e9c9b76e86/mmcv/runner/hooks/evaluation.py#L240

https://github.com/open-mmlab/mmcv/blob/bb7106755ec78561152a4273b27298e9c9b76e86/mmcv/runner/hooks/evaluation.py#L283

I found that the current logic works if start = 0 && interval = 1. But what I want is to set start = 0 && interval = 10 (that means I want to eval for 0, 10, 20, 30...). Since I found there is a special circumvention in the before_train_epoch, I guess the design already considered to support my usecase. Is there any idea to do so?

Thanks

**Comment by HarborYuan** [comment]
And by the way,

the textlogger seems not to support the before training evaluation. How about add the following codes to textlogger

```
   def __init__(...):
      ...
      self.has_start = False

   def before_train_epoch(self, runner) -> None:
        if not self.has_start:
            self.has_start = True
            self.after_train_epoch(runner)
        else:
            super().before_train_epoch(runner)
```

**Comment by zhouzaida** [comment]
> Hi,
> 
> Thanks for your work on mmcv.
> 
> I am working on my project based on mmcv. However, when I was trying to make the EvalHook work before everything starts, I found I cannot. I checked the source code.
> 
> https://github.com/open-mmlab/mmcv/blob/bb7106755ec78561152a4273b27298e9c9b76e86/mmcv/runner/hooks/evaluation.py#L240
> 
> https://github.com/open-mmlab/mmcv/blob/bb7106755ec78561152a4273b27298e9c9b76e86/mmcv/runner/hooks/evaluation.py#L283
> 
> I found that the current logic works if start = 0 && interval = 1. But what I want is to set start = 0 && interval = 10 (that means I want to eval for 0, 10, 20, 30...). Since I found there is a special circumvention in the before_train_epoch, I guess the design already considered to support my usecase. Is there any idea to do so?
> 
> Thanks

If setting `start = 0 && interval = 10`, the hook should work well at `0, 10, 20, 30...` epoch. BTW, what was the actual behavior?

**Comment by HarborYuan** [comment]
Hi, @zhouzaida 

Thanks for your help.

Supposing using epoch based runner, based on my understanding, when start = 0 && interval = 10, the before_train_epoch will call after_train_epoch and further call _should_evaluate. But since (0 + 1 - 0) % 10 != 0, _should_evaluate will return False.

And even if interval = 1 and start = 0, which means (0 + 1 - 0) % 1 == 0. The textlogger will not print the result since the textlogger will not try to print at before_train_epoch.
