### ISSUE TITLE
What's the best way to modify a list config from argparse?

### ISSUE THREAD

**Issue by zeyuwang615** [open-mmlab/mmcv#2293]
Hi there!

Suppose I have a mmcv config I want to modify from command line options `--cfg-options`, and that config is structured like this:
```
config=dict(
    key1=[
        dict(...)
        dict(key2=value1)
    ]
)
```
And I want to use something like '--cfg-options config.key1[1].key2=value2' to update `key2=value1` to `key2=value2` How can I do that? 

Thanks a lot!

**Comment by HAOCHENYE** [comment]
Hi! sorry for my late reply,  actually now we do not support modifying elements of a list in the command line, the main reason is that https://github.com/open-mmlab/mmcv/blob/847612dfffbcd917b6c267fe9decd4f8afed676e/mmcv/utils/config.py#L601 cannot parse string like "[]".

Recently we update our training architecture and release a new repo [`MMENgine`](https://github.com/open-mmlab/mmengine). Althought it still does not support modifying a list, but you can open an issue there, and we will put it in our development scheduler.

Of course if you can propose your PR to complete this feature, it couldn't be better!
