### ISSUE TITLE
mmcv-full can not install (use win11、cuda11.6、torch1.8.1)

### ISSUE THREAD

**Issue by zysqlmn020928** [open-mmlab/mmcv#2298]
This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by HAOCHENYE** [comment]
Hi, we have not provided pre-built mmcv-full for torch1.8.1 and cuda 11.6, it seems mmcv-full is built from source, can your provide the full error log by:

```bash
pip install mmcv-full -v
```

or

```bash
pip install -e . -v
```

**Comment by zhouzaida** [comment]
Hi @zysqlmn020928 , you could try to install mmcv-full with `mim` tools.

```bash
pip install openmim
mim install mmcv-full
```

**Comment by shift99999999** [comment]
> 嗨，您可以尝试使用 .`mim`
> 
> ```shell
> pip install openmim
> mim install mmcv-full
> ```

您好，您这个方法可以
