### ISSUE TITLE
ImportError: cannot import name 'Config'

### ISSUE THREAD

**Issue by rinawhale** [open-mmlab/mmcv#23]
Hi,
I met the error when I run the code train.py, and I didn't find the 'Config'.
`from mmcv import Config
ImportError: cannot import name 'Config'`

**Comment by Euphoria16** [comment]
Hello, I met the same problem. Could you please tell me how you solved this problem?

**Comment by Msalehi237** [comment]
I have the same issue. Has anyone solved this?

**Comment by AmingWu** [comment]
@Msalehi237 ,Have you solved this problem?

**Comment by korabelnikov** [comment]
@AmingWu 
Have you solved this problem?

**Comment by PLEX-GR00T** [comment]
i got the same error, can you help me guys?

**Comment by Dandelionym** [comment]
So, how, please?

**Comment by limchr** [comment]
Have you solved this problem?

**Comment by aasharma90** [comment]
You can try replacing
`from mmcv.config import Config`
with
`from mmengine.config import Config`

Or install `mmcv-full` package

**Comment by alaa-shubbak** [comment]
i got similar error 

`ImportError: cannot import name 'Config' from 'mmcv' (/home/shubbak/env_pose/lib/python3.9/site-packages/mmcv/__init__.py)`

when open this file (__init__.py)
there was not such import of config , it contains only this : 

`# Copyright (c) OpenMMLab. All rights reserved.
# flake8: noqa
from .arraymisc import *
from .image import *
from .transforms import *
from .version import *
from .video import *
from .visualization import *

# The following modules are not imported to this level, so mmcv may be used
# without PyTorch.
# - op
# - utils
`

**Comment by Crafterluck** [comment]
This problem still arises! Why is this issue closed?
ImportError: cannot import name 'Config' from 'mmcv' (/home/user/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/__init__.py)

**Comment by kekaipr** [comment]
> This problem still arises! Why is this issue closed? ImportError: cannot import name 'Config' from 'mmcv' (/home/user/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/**init**.py)

Hello,I just solve this problem by use following code:

import mmengine
mmengine.Config.fromfile(....)

after mmcv2.0.0,they seems delete some components in mmcv
let me know if you solve the problem by this method,thanks!

**Comment by Crafterluck** [comment]
Thank you, it was very helpful, basically you have to change every mmcv to mmengine.

**Comment by pyl62112991** [comment]
> Hi, I met the error when I run the code train.py, and I didn't find the 'Config'. `from mmcv import Config ImportError: cannot import name 'Config'`

That  change the version of mmcv can solve the problem. mmcv1.7.1 is ok for me.

**Comment by yingqichao** [comment]
Using a lower version seems to be okay.

**Comment by corgok** [comment]
> > This problem still arises! Why is this issue closed? ImportError: cannot import name 'Config' from 'mmcv' (/home/user/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/**init**.py)
> 
> Hello,I just solve this problem by use following code:
> 
> import mmengine mmengine.Config.fromfile(....)
> 
> after mmcv2.0.0,they seems delete some components in mmcv let me know if you solve the problem by this method,thanks!

or just from mmengine import Config then you can keep the rest the same

**Comment by chetana348** [comment]
Downgrading mmcv to 1.7.0 resolved the issue for me.
