### ISSUE TITLE
How to sample the same number of sample for each dataset in Concatenated Dataset

### ISSUE THREAD

**Issue by thancaocuong** [open-mmlab/mmcv#2301]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the FAQ documentation but cannot get the expected help.
Assuming that I created Concatenate Dataset from 3 datasets A, B, C. At each training iteration, I want to sample the same number of samples from each dataset. So how can I implement it?

**Comment by HAOCHENYE** [comment]
Hi! What repo you are using? Asking this question under the corresponding repo may get a faster and more accurate response.

**Comment by thancaocuong** [comment]
@HAOCHENYE  I'm using mmcv

**Comment by HAOCHENYE** [comment]
> @HAOCHENYE I'm using mmcv

So you mean that you implement a Concatenate Dataset, and want to get the same number of samples that belong to A, B, and C in single batch data? I think it may not be the best way to use `ConcatenateDataset` to implement this, and the simplest solution is to define a  `SampleBalancedDataset`(just like `ClassBalancedDataset` defined here https://github.com/open-mmlab/mmdetection/blob/9d3e162459590eee4cfc891218dfbb5878378842/mmdet/datasets/dataset_wrappers.py#L211). 

`SampleBalancedDataset` should expand smaller dataset  to the largest one(maybe simply oversample), and override `__getitem__` method to  return a tuple which contains data from dataset A, B, and C

**Comment by thancaocuong** [comment]
> > @HAOCHENYE I'm using mmcv
> 
> So you mean that you implement a Concatenate Dataset, and want to get the same number of samples that belong to A, B, and C in single batch data? I think it may not be the best way to use `ConcatenateDataset` to implement this, and the simplest solution is to define a `SampleBalancedDataset`(just like `ClassBalancedDataset` defined here https://github.com/open-mmlab/mmdetection/blob/9d3e162459590eee4cfc891218dfbb5878378842/mmdet/datasets/dataset_wrappers.py#L211).
> 
> `SampleBalancedDataset` should expand smaller dataset to the largest one(maybe simply oversample), and override `__getitem__` method to return a tuple which contains data from dataset A, B, and C

thanks, I'll try it
