### ISSUE TITLE
roi_pool bin_x1,x2,y1,y2 compute question: file roi_pool_cuda_kernel.cuh line 40-43

### ISSUE THREAD

**Issue by momo609** [open-mmlab/mmcv#2303]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the FAQ documentation 
![Uploading roi_pool.PNG…]()
but cannot get the expected help.
Rounding down on the left border and rounding up on the right border will cause the pooling area to overlap, which is inconsistent with the normal segmentation

**Comment by momo609** [comment]
![roi_pool](https://user-images.githubusercontent.com/18210557/192963004-05625334-36d1-4c89-a2fd-c1cf33f74e17.PNG)

**Comment by ZwwWayne** [comment]
We follow the official implementation of RoIPool in Detectron, which is also consistent with Torchvision 
https://github.com/pytorch/vision/blob/4a310f26049371959617921d0eb9b001f4d262c6/torchvision/csrc/ops/cuda/roi_pool_kernel.cu#L43-L74
