### ISSUE TITLE
Question to mmcv_ops_definition

### ISSUE THREAD

**Issue by jayggh** [open-mmlab/mmcv#2308]
In the file mmcv_ ops_ definition.md, lines 293 and 295 are used to explain  the meaning of the deform_conv2d parameter(deformable_groups, im2col_step),which is the same. That can't be understood.

**Comment by grimoire** [comment]
That's a mistake in the docs. `im2col_step` is used to control the step of im2col, which is used to do the convolution. It should only affect the inference time of the op. You can just ignore it.
