### ISSUE TITLE
install open-mmlab in python environment

### ISSUE THREAD

**Issue by alaa-shubbak** [open-mmlab/mmcv#2313]
**Checklist**

1. I have searched related issues but cannot get the expected help.
   yes 
2. I have read the FAQ documentation but cannot get the expected help.
   yes 

I am running my model and installation of mmdetection and open-mmlab on a python environment , as the permission on university system does not allow me to use sudo

I faced this error and issues after installation and run the check script <python mmdet/utils/collect_env.py > 

![error in run pzthon env2](https://user-images.githubusercontent.com/10245810/193413118-a5fc6ec8-5ea0-4541-bbad-76baf3eb26df.jpg)

my script to install the environment is as bellow : 

module purge
source open_env/bin/activate 
pip install --upgrade pip
module load gcc/7.5
module load cudnn/latest
module load nvidia/11.1

pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 -f https://download.pytorch.org/whl/torch_stable.html

pip install mmcv-full==1.6.2 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.10.0/index.html
cd mmdetection

pip install -v -e .

any help please .

**Comment by HAOCHENYE** [comment]
It seems you still using cudatoolkit11,7:
![image](https://user-images.githubusercontent.com/57566630/193415033-d253595e-d510-4b74-bb97-aee61327271e.png)
How about set CUDA_HOME manually?

**Comment by alaa-shubbak** [comment]
how can i do so ? where shall i put this line of 
CUDA_HOME=..etc

**Comment by zhouzaida** [comment]
"undefined symbol" probably happened when the cuda version of building mmcv-full is not the same as runtime cuda version.

You can uninstall mmcv-full first and then re-install it with mim.

```python
pip uninstall mmcv-full -y
pip install -U openmim
mim install mmcv-full
```

**Comment by alaa-shubbak** [comment]
the model and training starts to work , thank you very much.

**Comment by alaa-shubbak** [comment]
i would like to reopen the issue again , just beacuse i noticed that when running my training on 1gpu it is working , while when using (tools/dist_train.sh) it dose not. 

it gave me this error 

`'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
`

**Comment by alaa-shubbak** [comment]
thanks , i figure out my issue now. 
no need to reopen this issue again.
