### ISSUE TITLE
Issues about video2img convertion on GoPro camera videos

### ISSUE THREAD

**Issue by cydiachen** [open-mmlab/mmcv#2314]
Thanks for reporting the unexpected results and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmcv.readthedocs.io/en/latest/trouble_shooting.html) but cannot get the expected help.
3. The unexpected results still exist in the latest version. (not yet)

**Describe the Issue**
I came across an issue which is when I use mmcv's video2img convertor to extract frames from a specific video, the code automatically exit when dealing with video frame id 15. No error or exception are displayed or raised. 

I have tested using ffmpeg to extract frame, which is ok. 
**Reproduction**

1. What command, code, or script did you run?

```python
import mmcv
import os
from tqdm import tqdm

video_path = r"F:\CompanyDataset\car_view\raw_video\NT_G228_K3304.37~K3324.961_上行_行车视角_20220901_3.MP4"
video = mmcv.VideoReader(video_path)
output_path = r"F:\CompanyDataset\car_view\raw_output"
img_prefix = os.path.splitext(os.path.split(video_path)[-1])[0]
mode = 'normal'
delta_sec = 1
fps = int(video.fps)

print(fps)
if not os.path.exists(output_path):
    os.makedirs(output_path)

for idx, frame in enumerate(tqdm(video)):
    if mode == 'skip':
        if idx % (fps * delta_sec) == 0:
            mmcv.imwrite(frame, os.path.join(output_path, img_prefix + "_" + str(idx)+'.jpg'))
    else:
        mmcv.imwrite(frame, os.path.join(output_path, img_prefix + "_" + str(idx) + '.jpg'))
```

2. Did you make any modifications on the code? Did you understand what you have modified?

**Environment**

1. Please run `python -c "from mmcv.utils import collect_env; print(collect_env())"` to collect necessary environment information and paste it here.
2. 
![image](https://user-images.githubusercontent.com/26337720/193537934-9939230f-130a-4bed-b786-df06b4d8ab55.png)

3. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
I have upload the video to baidu disk, feel free to test.
链接：https://pan.baidu.com/s/11rrl8q-H8FTAAd4HGzFGVw?pwd=wrxv 
提取码：wrxv 

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by HAOCHENYE** [comment]
Hi! Sorry for my late reply. It seems a bug of `cv2.VideoCapture`. The relative discussion can be found in:
https://stackoverflow.com/questions/49060054/opencv-videocapture-closes-with-videos-from-gopro
https://answers.opencv.org/question/4120/ffmpeg-crash-with-a-gopro-video/

Here are some solutions to solve this problem :apple::apple::apple::
- Strip the audio of the video, and then the video can be read successfully
   ```bash
   ffmpeg -i 1111.MP4 -c copy -an 2222.MP4
   ```
   The audio of  2222.mp4 will be stripped, and then it can be read by your code. 
- Export the jpg directly by ffmpeg like this:
  ```bash
  fmpeg -i ./1111.MP4 frame%03d.jpg
  ```
- **Highly recommend you create a PR to fix this problem**. The simplest solution is to skip the unreadable frames! We are happy to work with you to fix this issue :grin:!

**Comment by cydiachen** [comment]
> * The audio of  2222.mp4 will be stripped, and then it can be read by your code.

Thanks a lot for the kind help. It seems like closely related with GoPro's unique design of intergates GPS and sensor information in MP4 file. I used the second way (Export the jpg directly by ffmpeg). Thank you for your help.
