### ISSUE TITLE
Meaning of one "iter"

### ISSUE THREAD

**Issue by FabianSchuetze** [open-mmlab/mmcv#2315]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the FAQ documentation but cannot get the expected help.

This is a simple question, but I couldn't find the answer through searching the docs and perusing the code, so I decided to ask it here. 

What is one "iter"? Is it equal to the total batch size across all gpus? If I have a per-gpu batch size of 2 and 4 gpus, would one iter be: `next_iter = cur_iter + 2*4`? That is, does an iter scale with the batch size and number of gpus, or is an iter the number of gradient updates? 

Maybe we could extend the [docs](https://github.com/open-mmlab/mmcv/blob/3dd2a21b45b6303b8202f89de4ebb0f52731e4dd/docs/en/understand_mmcv/runner.md) and specify what an iter means for the `IterBasedRunner`?

**Comment by zhouzaida** [comment]
Hi @FabianSchuetze , one `iter` denotes forward propagation once and backward propagation once.

**Comment by FabianSchuetze** [comment]
Thanks for your explanation, @zhouzaida !
