### ISSUE TITLE
NoneType' object has no attribute 'parent'

### ISSUE THREAD

**Issue by ghoshsdeep** [open-mmlab/mmcv#2319]
Its while implementing the tutorial documentation

![Screenshot from 2022-10-06 19-18-15](https://user-images.githubusercontent.com/112154951/194330425-cfff0893-a0a6-47d9-8a52-7575aeb7953e.png)
Can you help me solve this?

**Comment by zhouzaida** [comment]
Hi @ghoshsdeep , the scope `mmdet` is not found here so adding it when defining MODELS would be helpful.

```python
from mmcv.utils import Registry
from mmcv.cnn import MODELS as MMCV_MODELS
import torch.nn as nn

MODELS = Registry('model', parent=MMCV_MODELS, scope='mmdet')  # manually set scope

@MODELS.register_module()
class NetA(nn.Module):
    def forward(self, x):
        return x


net_a = MODELS.build(cfg=dict(type='mmdet.NetA'))
```
