### ISSUE TITLE
update the lr by iteration in epochbasedrunner

### ISSUE THREAD

**Issue by Jacobew** [open-mmlab/mmcv#2320]
Hi, how can I update the learning rate by iteration but not by epoch when using an epochbasedrunner? 

My other question is: which part of the codes should I modify to substitute epochbasedrunner with iterbasedrunner?

Looking forward for the reply :)

**Comment by Jacobew** [comment]
My codebase is based on mmdetection (old version), and it uses epochbasedrunner.

**Comment by zhouzaida** [comment]
You need to update the config in https://github.com/open-mmlab/mmdetection/blob/9d3e162459590eee4cfc891218dfbb5878378842/configs/_base_/schedules/schedule_1x.py#L11

```python
runner = dict(type='EpochBasedRunner', max_epochs=12)
```

->

```python
runner = dict(type='IterBasedRunner', max_iters=160000)
```

BTW, it is recommended that you open an issue in mmdetection for help and they will give you more specific help.

**Comment by Jacobew** [comment]
Got it, thanks for your reply!
