### ISSUE TITLE
MMCV CUDA Compiler: not available

### ISSUE THREAD

**Issue by aschneid42** [open-mmlab/mmcv#2322]
I have tried to install mmcv==1.5.3 in multiple ways (to eventually run mmrotate) for both CUDA 10.2 and 11.0 (with Kubernetes I can create pods with either CUDA version installed)
   1) mim install mmcv-full==1.5.3  --no-cache-dir -f https://download.openmmlab.com/mmcv/dist/cu102/torch1.7.0/index.html
   2) pip install mmcv-full==1.5.3  --no-cache-dir -f https://download.openmmlab.com/mmcv/dist/cu102/torch1.7.0/index.html
   3) from source by cloning mmcv-full==1.5.3 and using: MMCV_WITH_OPS=1 pip install -e .

In all cases torch is able to see the GPU via: torch.cuda.is_available() -> True

Collecting the env info gives:
Environment information:
------------------------------------------------------------
sys.platform: linux
Python: 3.6.8 (default, Nov 16 2020, 16:55:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
CUDA available: True
GPU 0: GRID V100D-32C
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.2, V10.2.8
GCC: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
PyTorch: 1.7.1
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

TorchVision: 0.8.2
OpenCV: 4.6.0
MMCV: 1.5.3
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: not available
------------------------------------------------------------
The check_installation.py script yields:
python check_installation.py
Start checking the installation of mmcv-full ...
CPU ops were compiled successfully.
Traceback (most recent call last):
  File "check_installation.py", line 37, in <module>
    check_installation()
  File "check_installation.py", line 29, in check_installation
    box_iou_rotated(boxes1, boxes2)
  File "/nas/pods/Adam/mmcv-1.5.3/mmcv/ops/box_iou_rotated.py", line 145, in box_iou_rotated
    bboxes1, bboxes2, ious, mode_flag=mode_flag, aligned=aligned)
RuntimeError: box_iou_rotated_impl: implementation for device cuda:0 not found.

I have looked at many other issue reports on this, and tried all the suggestions I can find.

I am using a Kubernetes pod with GPU attached, but the pod has no access to the outside world, so most of the venv needs to be configured/installed from separate server (with no GPU) connected to the same /nas/ drive. Not sure if this could be an issue...

Any help would be greatly appreciated!

**Comment by zhouzaida** [comment]
Hi @aschneid42 , could you provide the output of the installation?

**Comment by aschneid42** [comment]
1) mim install mmcv-full==1.5.3  --no-cache-dir -f https://download.openmmlab.com/mmcv/dist/cu102/torch1.7.0/index.html
Looking in indexes: https://nexusrepo.mda.ca/repository/pypi-proxy-all/simple
Looking in links: https://download.openmmlab.com/mmcv/dist/cu102/torch1.7.0/index.html, https://download.openmmlab.com/mmcv/dist/cu102/torch1.7.0/index.html
Collecting mmcv-full==1.5.3
  Downloading https://nexusrepo.mda.ca/repository/pypi-proxy-all/packages/mmcv-full/1.5.3/mmcv-full-1.5.3.tar.gz (547 kB)
     |████████████████████████████████| 547 kB 78.2 MB/s
  Preparing metadata (setup.py) ... done
Requirement already satisfied: addict in /nas/pods/PythonEnvs/mm/lib/python3.6/site-packages (from mmcv-full==1.5.3) (2.4.0)
Requirement already satisfied: numpy in /nas/pods/PythonEnvs/mm/lib64/python3.6/site-packages (from mmcv-full==1.5.3) (1.19.5)
Requirement already satisfied: packaging in /nas/pods/PythonEnvs/mm/lib/python3.6/site-packages (from mmcv-full==1.5.3) (21.3)
Requirement already satisfied: Pillow in /nas/pods/PythonEnvs/mm/lib64/python3.6/site-packages (from mmcv-full==1.5.3) (8.4.0)
Requirement already satisfied: pyyaml in /nas/pods/PythonEnvs/mm/lib64/python3.6/site-packages (from mmcv-full==1.5.3) (6.0)
Requirement already satisfied: yapf in /nas/pods/PythonEnvs/mm/lib/python3.6/site-packages (from mmcv-full==1.5.3) (0.32.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /nas/pods/PythonEnvs/mm/lib/python3.6/site-packages (from packaging->mmcv-full==1.5.3) (3.0.9)
Building wheels for collected packages: mmcv-full
  Building wheel for mmcv-full (setup.py) ... done
  Created wheel for mmcv-full: filename=mmcv_full-1.5.3-cp36-cp36m-linux_x86_64.whl size=28866584 sha256=4042347cfd98f88242202b21f6a175157b282114ca43efc30239903c7587d7ff
  Stored in directory: /tmp/pip-ephem-wheel-cache-hu631ada/wheels/7a/1c/07/7137cc5aef50dbe6d984b582018b1c5e61c32179bf748cefb5
Successfully built mmcv-full
Installing collected packages: mmcv-full
Successfully installed mmcv-full-1.5.3

**Comment by zhouzaida** [comment]
Hi, mim will automatically add the `-f https:/xxxx/index.html` so installation mmcv just needs to use the command `mim install mmcv-full`.
