### ISSUE TITLE
Operating on referred variables in configs

### ISSUE THREAD

**Issue by OrcunCanDeniz** [open-mmlab/mmcv#2326]
I am referencing variables from base configs and trying to do basic math on them as below;

``` 
voxel_size_ = {{ _base_.voxel_size }} # sourced from model config
point_cloud_range_ = {{ _base_.point_cloud_range }} # sourced from dataset config

# below this line is problematic
grid_x = (point_cloud_range_[3] - point_cloud_range_[0]) / voxel_size_[0]
grid_y = (point_cloud_range_[4] - point_cloud_range_[1]) / voxel_size_[1]
grid_z = (point_cloud_range_[5] - point_cloud_range_[2]) / voxel_size_[2]
```

The bottom 3 lines are causing the error;
```
Traceback (most recent call last):
  File "/home/orcun/miniconda3/envs/mmlab/lib/python3.7/tempfile.py", line 448, in __del__
    self.close()
  File "/home/orcun/miniconda3/envs/mmlab/lib/python3.7/tempfile.py", line 444, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp8tf7o3j0/tmp8y3ub671.py'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/orcun/miniconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/utils/config.py", line 341, in fromfile
    use_predefined_variables)
  File "/home/orcun/miniconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/utils/config.py", line 208, in _file2dict
    mod = import_module(temp_module_name)
  File "/home/orcun/miniconda3/envs/mmlab/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/tmp9yz_i_sy/tmp7xnddyq1.py", line 15, in <module>
TypeError: unsupported operand type(s) for -: 'str' and 'str'
```
How can I use those two vars from base configs in a way that can let operators on them?

** mmcv version : 1.5.2

**Comment by HAOCHENYE** [comment]
Hi! Sorry for my late reply. The referred variable like {{xxx}} in config can only be used for assignment, not for further operations. The placeholder `{{}}` will only be replaced by the real variable after the current config is loaded. However, the operation like:

```python
grid_x = (point_cloud_range_[3] - point_cloud_range_[0]) / voxel_size_[0]  
```

happened during the import process, and `point_cloud_range_` is still a simple string.

Recently we updated our training architecture and released a new repo [`MMEngine`](https://github.com/open-mmlab/mmengine). **The upgraded Config in `MMEngine` can solve your problem.**.

```python
voxel_size_ =  _base_.voxel_size # sourced from model config
point_cloud_range_ = _base_.point_cloud_range # sourced from dataset config

# below this line is problematic
grid_x = (point_cloud_range_[3] - point_cloud_range_[0]) / voxel_size_[0]
grid_y = (point_cloud_range_[4] - point_cloud_range_[1]) / voxel_size_[1]
grid_z = (point_cloud_range_[5] - point_cloud_range_[2]) / voxel_size_[2]
```

**Comment by SCZwangxiao** [comment]
> Hi! Sorry for my late reply. The variable reference like `{{xxx}}` in config file can only be used for assignment, not for further operations. The placeholder `{{}}` will only be replaced by the real variable after importing the current config file. However, the operation like:
> 
> ```python
> grid_x = (point_cloud_range_[3] - point_cloud_range_[0]) / voxel_size_[0]  
> ```
> 
> happened during the import process, and `point_cloud_range_` is still a simple string.
> 
> Recently we updated our training architecture and released a new repo [`MMEngine`](https://github.com/open-mmlab/mmengine). **The upgraded Config in `MMEngine` can solve your problem.**.
> 
> ```python
> voxel_size_ =  _base_.voxel_size # sourced from model config
> point_cloud_range_ = _base_.point_cloud_range # sourced from dataset config
> 
> # below this line is problematic
> grid_x = (point_cloud_range_[3] - point_cloud_range_[0]) / voxel_size_[0]
> grid_y = (point_cloud_range_[4] - point_cloud_range_[1]) / voxel_size_[1]
> grid_z = (point_cloud_range_[5] - point_cloud_range_[2]) / voxel_size_[2]
> ```

Will this feature in ``MMEngine`` be incorporated in ``mmcv`` later?
