### ISSUE TITLE
AssertionError: batch size must be divisible by im2col_step

### ISSUE THREAD

**Issue by yukaizhou** [open-mmlab/mmcv#2327]
<img width="770" alt="1665453182554(1)" src="https://user-images.githubusercontent.com/38181468/194979509-5610f507-14c6-4d07-a25e-b003f9f98e10.png">

**Comment by zhouzaida** [comment]
Hi @yukaizhou , what is your batch size?

**Comment by yukaizhou** [comment]
感谢你的及时回复。batch-size=64(2gpus*32)。通过打印 inputs.size(0)=192， img2col_step=128.

**Comment by zhouzaida** [comment]
inputs.size(0) 这个值是 batch size，而这个值不能被 img2col_step 整除，所以报错，可以调整两个中的一个使得能够整除即可
