### ISSUE TITLE
[doc] Invalid installation command

### ISSUE THREAD

**Issue by del-zhenwu** [open-mmlab/mmcv#2329]
**Checklist**
In https://mmcv.readthedocs.io/en/dev-2.x/get_started/installation.html and https://mmcv.readthedocs.io/en/2.x/get_started/installation.html
![image](https://user-images.githubusercontent.com/56623710/195071705-5b68cf5e-d6cc-4484-a05e-2f4d8f6116f5.png)

**Comment by del-zhenwu** [comment]
It should be `mmcv==`

**Comment by ice-tong** [comment]
Hi @del-zhenwu , thanks for the kind feedback.

We'll fix this, or if you're interested, a PR that fixes this is welcome. ^_^
