### ISSUE TITLE
port ambiguity in slurm init function

### ISSUE THREAD

**Issue by chenyuwang814** [open-mmlab/mmcv#2330]
https://github.com/open-mmlab/mmcv/blob/e417035f5d473b9f85d15ba01267d48d7f30e71e/mmcv/runner/dist_utils.py#L117
This function may cause ports ambiguity among different processes, which may get stuck while initializing communication.

**Comment by zhouzaida** [comment]
Hi @chenyuwang814 , thanks for your report. I closed this issue because it is repeated with https://github.com/open-mmlab/mmcv/issues/2309.
