### ISSUE TITLE
Legacy Install Failure while Building MMCV

### ISSUE THREAD

**Issue by harshsingh-24** [open-mmlab/mmcv#2333]
**Describe the Issue**
Tried to create a new environment with mmcv-full (1.2.7) but failed with pip install.

**Reproduction**

1. What command, code, or script did you run?

```bash
conda create -n oln python=3.7 -y
conda activate oln
conda install pytorch=1.7.0 torchvision cudatoolkit=11.0 -c pytorch -y
pip install mmcv-full==1.2.7
```

2. Did you make any modifications on the code? Did you understand what you have modified?
No. I haven't modified any of the code. Just followed the above instructions.

**Error traceback**

[log.txt](https://github.com/open-mmlab/mmcv/files/9783057/log.txt)

**Comment by ice-tong** [comment]
Hi @harshsingh-24 , I found a nvcc fatal in the log.txt you posted:

```
nvcc fatal   : Unsupported gpu architecture 'compute_86'
```

What is the output for `nvcc -V`?  I think you should update your CUDA version (not the version in `conda install cudatoolkit`).

A related link maybe help: https://stackoverflow.com/questions/69865825/nvcc-fatal-unsupported-gpu-architecture-compute-86

**Comment by harshsingh-24** [comment]
`nvcc -v` gives the following output - 
```
nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
```

Should I update my CUDA version to 11.0?

**Comment by ice-tong** [comment]
I think you should update your CUDA from 10.1 to 11.2.

https://docs.nvidia.com/cuda/archive/11.2.0/ptx-compiler-api/index.html
