### ISSUE TITLE
Why not add a param in `get_root_logger` to set log_formater

### ISSUE THREAD

**Issue by zhijiejia** [open-mmlab/mmcv#2338]
**Question**

1. Why there no param about log_formater in `get_root_logger`, bacause i usually find the log info too long. If the output information is too long, the output information will occupy two lines, which seems to be very uncomfortable to me, so can you add a parameter to allow users to customize `logging.Formatter` in `mmcv/utils/logging.py`? or can i post a PR for this question.

**Comment by HAOCHENYE** [comment]
Hi! thanks for your feedback. I think it is reasonable to customize the logger format. Recently, we upgrade our logging system in `MMEngine`, which is our next-generation training framework. I think it will be more proper to support customized `Formatter` in 

https://github.com/open-mmlab/mmengine/blob/09a195b24cfff85d2de29f0786bbcc9f0586002c/mmengine/logging/logger.py#L94

**Comment by zhijiejia** [comment]
ok~
