### ISSUE TITLE
Can't install mmcv

### ISSUE THREAD

**Issue by mrsempress** [open-mmlab/mmcv#234]
When I use `pip install -v -e . -i https://pypi.tuna.tsinghua.edu.cn/simple` to install mmdetection, I got 

> Collecting mmcv>=0.3.1
Created temporary directory: /tmp/pip-unpack-6lk1cyqa
  Looking up "https://pypi.tuna.tsinghua.edu.cn/packages/6c/20/b29da975cc3944291d456260a466bd70f2859d0334c2f7eb7be68fe38820/mmcv-0.4.3.tar.gz" in the cache
  Current age based on date: 524
  https://pypi.tuna.tsinghua.edu.cn:443 "GET /packages/6c/20/b29da975cc3944291d456260a466bd70f2859d0334c2f7eb7be68fe38820/mmcv-0.4.3.tar.gz HTTP/1.1" 304 0
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/6c/20/b29da975cc3944291d456260a466bd70f2859d0334c2f7eb7be68fe38820/mmcv-0.4.3.tar.gz (53 kB)
  Added mmcv>=0.3.1 from https://pypi.tuna.tsinghua.edu.cn/packages/6c/20/b29da975cc3944291d456260a466bd70f2859d0334c2f7eb7be68fe38820/mmcv-0.4.3.tar.gz#sha256=42fe41720411de2ef05d4d23254c3e9c03690471cfb62d897faa22a320888938 (from mmdet==1.1.0+a1c3aa4) to build tracker '/tmp/pip-req-tracker-byrs7p6l'
    Running setup.py (path:/tmp/pip-install-6lo_xbx8/mmcv/setup.py) egg_info for package mmcv
    Running command python setup.py egg_info
      WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f6b79bfe150>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /packages/16/45/81b5262c0efc08882bdf183b788e6d28e3d684863990996d8b60967d48da/pytest_runner-5.2-py2.py3-none-any.whl

But the other package install sucessfully.
Then I want to install mmcv independently.
I have tried `pip install mmcv -i https://pypi.tuna.tsinghua.edu.cn/simple`, I got 
> ERROR: Command errored out with exit status 1:
command: /home/xxx/anaconda3/envs/open-mmlab/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-430jan3a/mmcv/setup.py'"'"'; __file__='"'"'/tmp/pip-install-430jan3a/mmcv/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-430jan3a/mmcv/pip-egg-info
         cwd: /tmp/pip-install-430jan3a/mmcv/
Complete output (116 lines):
      WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f98d564a350>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /packages/16/45/81b5262c0efc08882bdf183b788e6d28e3d684863990996d8b60967d48da/pytest_runner-5.2-py2.py3-none-any.whl

I also changed the address: aliyun, douban, etc. But I got the same results
So, I use 
```git clone https://github.com/open-mmlab/mmcv.git
  cd mmcv
  pip install -e  .
```
But I got 

> ERROR: Command errored out with exit status 1:
     command: /home/xxx/anaconda3/envs/open-mmlab/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/huangchenxi/mmcv/setup.py'"'"'; __file__='"'"'/home/xxx/mmcv/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info
         cwd: /home/xxx/mmcv/
    Complete output (118 lines):
    WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f1a56d58ed0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /simple/pytest-runner/

How can I install mmcv successfully?

**Comment by hellock** [comment]
The cause might be your network environment. I tried `pip install mmcv -i https://pypi.tuna.tsinghua.edu.cn/simple` and it works well.

**Comment by iamchinu14** [comment]
Not working brother @hellock
