### ISSUE TITLE
why get_model_complexity_info don't calculate the flops in attention layer?

### ISSUE THREAD

**Issue by buaazeus** [open-mmlab/mmcv#2342]
The function get_model_complexity_info in mmcv/cnn/utils/flops_counter.py will not calculate the flops in attention layer.
Is there anyone can help to explain why?
Is there any other tools that can auto calculate the flops in  attention layer?
Thank you.

**Comment by zhouzaida** [comment]
Hi @buaazeus , the calculation of flops in MMCV follows the ways of  [flops-counter.pytorch](https://github.com/sovrasov/flops-counter.pytorch/tree/master/ptflops) which does not support the attention layers very well. You could try to use [fvcore](https://github.com/facebookresearch/fvcore/blob/main/fvcore/nn/flop_count.py).
