### ISSUE TITLE
RuntimeError: Error compiling objects for extension

### ISSUE THREAD

**Issue by Gracia-tjw** [open-mmlab/mmcv#2355]
When I installed mmcv-full follow the [installation instruction](https://mmcv.readthedocs.io/en/latest/get_started/installation.html) on windows in GPU version, I met the error "RuntimeError: Error compiling objects for extension". And I could not find a solution. Even when  I installed mmcv-full using packaged wheel, I met the error "ImportError: DLL load failed: .....". Did anyone have some sugesstions?

**Comment by ice-tong** [comment]
1. Make sure you have uninstall mmcv and mmcv-full successful.
2. Install mmcv-full via mim
```
pip install -U openmim
mim install mmcv-full
```
3. If it still doesn't install successfully, please post your log.

Feel free to feedback us if you have any problems~ ^_^

**Comment by Gracia-tjw** [comment]
Thank you very much! I have installed it in this way successfully!
