### ISSUE TITLE
[Apple Silicon] Install mmcv2.x no longer requires pytorch-nightly

### ISSUE THREAD

**Issue by xin-li-67** [open-mmlab/mmcv#2360]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the FAQ documentation but cannot get the expected help.

I am learning from the latest `mmcv2.0rc2` by following step by step on the documents. My device is M1 Macbook Pro. I found out that with the latest PyTorch, installing and using mmcv2.x&mmengine no longer requires `pytorch-nightly`. I replicated this process twice on my local devices and found no issues while running different verification demos in mmcls2.x and mmdet3.x on apple silicon. Would the developing team investigate this? Here are the screenshots of my local development environment.

![mmcv1](https://user-images.githubusercontent.com/7219519/198499108-834a2c11-8051-4223-b34b-24a07c5679fd.png)
![mmcv2](https://user-images.githubusercontent.com/7219519/198499120-af7b9014-bfe5-48d9-84ca-1ccd5e705534.png)

**Comment by xin-li-67** [comment]
If this is correct, the notice for using pytorch-nightly on apple silicon can be removed and macos users can do basic development thanks to the support of `torch.distributed`.

**Comment by ice-tong** [comment]
Hi @xin-li-67 , sorry for the late reply~

You are totally right! Since PyTorch 1.13 has been released, we can compile the MPS ops successfully without pytorch-nightly. 

I think the note in the installation document should be updated to:
```
If you are using a mac with an M1 chip, install the PyTorch 1.13+, otherwise you will encounter the problem in [issues#2218](https://github.com/open-mmlab/mmcv/issues/2218).
```

If you are interested, a kind contribution is welcome! ^_^

**Comment by xin-li-67** [comment]
> Hi @xin-li-67 , sorry for the late reply~
> 
> You are totally right! Since PyTorch 1.13 has been released, we can compile the MPS ops successfully without pytorch-nightly.
> 
> I think the note in the installation document should be updated to:
> 
> ```
> If you are using a mac with an M1 chip, install the PyTorch 1.13+, otherwise you will encounter the problem in [issues#2218](https://github.com/open-mmlab/mmcv/issues/2218).
> ```
> 
> If you are interested, a kind contribution is welcome! ^_^

Great! I will start the pr.
