### ISSUE TITLE
This ERROR occurred while installing mmcv2.0.0rc1.

### ISSUE THREAD

**Issue by xudadi001** [open-mmlab/mmcv#2379]
![A2D3I(2Q35_L9GD_ZV{4$02](https://user-images.githubusercontent.com/65487336/199493834-8cfdfd42-a380-47e5-aa20-cc40fc48870e.png)
CUDA11.6 pytorch1.12.1

**Comment by HAOCHENYE** [comment]
Hi, thanks for your feedback, could you provide the full error log? It could help us to locate the problem.

**Comment by xudadi001** [comment]
thank you for your attention 
I upgraded the pytorch version to fix the problem.
