### ISSUE TITLE
How to paste images

### ISSUE THREAD

**Issue by monkeycc** [open-mmlab/mmcv#2386]
2 pictures
```
img1 = mmcv.imread('test1.jpg')
img2 = mmcv.imread('test2.jpg')
```
mmcv
Paste one picture to another

**Comment by ice-tong** [comment]
Hi @monkeycc , we currently have not provided an API that pastes an image to another.

I think you can try assigning an image array slice to another image array value. E.g.

```python
img1[x1:x2, y1:y2] = imge2
```

**Comment by monkeycc** [comment]
感谢你的帮助
