### ISSUE TITLE
Detect the current initialized_logger for PretrainedInit

### ISSUE THREAD

**Issue by tjyuyao** [open-mmlab/mmcv#2392]
I suggest to change the fixed 'mmcv' logger in the following line:

https://github.com/open-mmlab/mmcv/blob/b622fb2e29f44d64a704b91a07b659ef7f6a9397/mmcv/cnn/utils/weight_init.py#L506

into a dynamic detected manner, like in:

https://github.com/open-mmlab/mmcv/blob/b622fb2e29f44d64a704b91a07b659ef7f6a9397/mmcv/runner/base_module.py#L95-L96

such that it can consistently log into the user configured loggers, and information about the weight loading is not missed from it.

Current behavior is like:

![image](https://user-images.githubusercontent.com/17985266/200222855-8242ebbc-732f-4850-bbaf-b5f7a8cad75f.png)

This might not considered as a bug, it is just a suggestion.

**Comment by HAOCHENYE** [comment]
Thanks for your feedback! Actually, we have been troubled for a long time by how to use logger in a sensible way crossing multiple projects. Therefore, we upgrade our logging system in [MMEngine](https://github.com/open-mmlab/mmengine/tree/main/mmengine/logging), which is the next-generation training framework for OpenMMLab projects.  I think the upgraded logging system could meet your needs. 

Consider the logging system in MMCV will be removed in [MMCV 2.x](https://github.com/open-mmlab/mmcv/tree/2.x), we have no plan to add a patch to it.

**Comment by tjyuyao** [comment]
I will look into MMEngine, thank you for your reply and excellent work!
