### ISSUE TITLE
[Feature Request] Registry for `NMS` operations

### ISSUE THREAD

**Issue by nijkah** [open-mmlab/mmcv#2395]
**Describe the feature**
How about creating a registry module for `NMS` operations?

**Motivation**
Most of `MM` modules support a registry for custom modules.
However, `nms` operations does not.
So it is quite difficult to use custom `nms` operations.

It would be better to support the registry for `nms` operations for custom modules.

**Comment by zhouzaida** [comment]
Hi @nijkah , `nms` module is not particularly generic, so it is recommended to define it in your own project. By the way, do you have other needs to add it in mmcv?

**Comment by nijkah** [comment]
Hi @zhouzaida.
We have our own `nms` implementation which is suitable for the specific task. But we found that it is quite cumbersome to support custom `nms` without changing the original logic (mmcv or mmdet).

I understand your suggestion. Thanks 😃
