### ISSUE TITLE
pairwise IoU3d calculation

### ISSUE THREAD

**Issue by zen-d** [open-mmlab/mmcv#2400]
**Describe the feature**

Hi, thanks for this nice toolbox.

Would you please consider adding a pairwise 3D IoU function? That is to say, for the input, we have [N, 7] 3D boxes and another [N, 7] 3D boxes, the output is an N-dimensional vector, representing their IoUs between each pair.

To explain it more, the behavior is extended from 2D boxes here https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/bbox.py#L53 by setting `aligned` to `True`.

**Motivation**
A clear and concise description of the motivation of the feature.
Ex1. It is inconvenient when we only need to output such an N-dimensional vector, but we have to calculate an NxN matrix and then extract its diagonal, based on the current implementation.
Ex2. The above situation can even lead to OOM problems.

**Comment by zhouzaida** [comment]
Hi @zen-d , we have provided this IoU function you mention above at https://github.com/open-mmlab/mmcv/blob/89253699dae6d7d6750631c6657e9f73596c495a/mmcv/ops/iou3d.py#L35
