### ISSUE TITLE
 implementation for device cpu not found

### ISSUE THREAD

**Issue by BelongAl** [open-mmlab/mmcv#2410]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the FAQ documentation but cannot get the expected help.
我想把gpu的模型跑在cpu上，但是显示cpu找不到；请问这个问题如何解决

![image](https://user-images.githubusercontent.com/49713362/201575465-4a516f56-3e31-4d3f-8d46-0425c7f2162d.png)

**Comment by zhouzaida** [comment]
Hi @BelongAl , `riroi_align_roated` has no CPU implementation so you can not put your model on CPU.
