### ISSUE TITLE
Problem when saving checkpoint: ValueError: write to closed file

### ISSUE THREAD

**Issue by implus** [open-mmlab/mmcv#242]
in: [https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/checkpoint.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/checkpoint.py)

we found there may be some problems in these two lines:

```python
    with open(filename, 'wb') as f:
        torch.save(checkpoint, f)
```

Since torch.save() accepts filename as its input, it is suggested to use  
```python 
torch.save(checkpoint, filename)  
```
directly. Otherwise the latest mmdetection may have errors when saving models like:

>  ValueError: write to closed file

**Comment by hellock** [comment]
Which version of pytorch are you using? The signiture of `torch.save` should be `save(obj: object, f: file-like object)`

**Comment by implus** [comment]
I see... Thanks for replying~
