### ISSUE TITLE
陷入循环

### ISSUE THREAD

**Issue by wz1114841863** [open-mmlab/mmcv#2431]
问题描述: 
代码原先在低版本运行时无问题, mmcv 版本更新至1.6.2后运行时进入死循环,
查看issue后发现存在类似情况 [Fix] fix the bug caused by batch element is str #1445, https://github.com/open-mmlab/mmcv/pull/1445/files , 但是已经进行了修改并且已经pr,但是查看1.6.2的mmcv/parrel/collate.py 和这个issue更改之前的一样,然后我个人就照着这个文件差异修改了collate.py,但是进而导致返回的数据中 data['img']为空

**Comment by wz1114841863** [comment]
![image](https://user-images.githubusercontent.com/60866264/202465347-63301766-3ec8-4172-ba81-aebd2d4b3549.png)
将collate.py还原,错误如图所示

**Comment by wz1114841863** [comment]
通过pdb debug 排查,确实如同Issue: https://github.com/open-mmlab/mmcv/issues/1387 所言,是因为我的配置中有 'dataset'这个str来标志使用的图片来源于哪个数据集,导致进入了循环,我单纯的添加了elif isinstance(batch[0], Sequence) and not isinstance(batch[0], str): 来替换 elif isinstance(batch[0], Sequence): 避免其进入死循环, 令我疑问的是既然这个问题已经在之前提过了解决方案为什么后面的版本又还原了回去,是有什么别的原因嘛.

**Comment by zhouzaida** [comment]
你好，这个问题会在 #1445 合入之后解决。

**Comment by wz1114841863** [comment]
好,感谢您的回复.
