### ISSUE TITLE
NeptuneLoggerHook in mmcv 2.x

### ISSUE THREAD

**Issue by fcakyon** [open-mmlab/mmcv#2433]
How can I use NeptuneLoggerHook in this setting:

```
"mmengine>=0.3.1"
"mmcv>=2.0.0rc1,<2.1.0"
"mmdet>=3.0.0rc3,<3.1.0"
"mmyolo>=0.1.3,<0.2.0"
```

**Comment by zhouzaida** [comment]
Hi, Neptune will be supported in MMEngine.

**Comment by fcakyon** [comment]
I don't understand the migration from `mmcv LoggerHooks` to `mmengine VisBackends`. So loggers are now called visualization backends?

Can I upload a model artifact to Neptune or WANDB using these visualization backends or do they only cover visualization-related operations?

**Comment by zhouzaida** [comment]
Many logger hooks in mmcv will be migrated to mmengine and they are called visualization backends in mmengine. 

If we want to add a model artifact, we need to add a new method like `add_artifact` both in [BaseVisBackend](https://github.com/open-mmlab/mmengine/blob/main/mmengine/visualization/vis_backend.py#L59) and [Visualizer](https://github.com/open-mmlab/mmengine/blob/main/mmengine/visualization/visualizer.py#L32). Besides, we also need to customize a new visualization hook to call this method. Examples for this type hook can be found at https://github.com/open-mmlab/mmdetection/blob/dev-3.x/mmdet/engine/hooks/visualization_hook.py.

BTW, [WandBVisBackend](https://github.com/open-mmlab/mmengine/blob/9d5b417f07cc189cd0d5517603f3872537c54af8/mmengine/visualization/vis_backend.py#L324) has been supported and it can be a reference to show how to support a new visualization backend. More details can be found at https://github.com/open-mmlab/mmengine/blob/main/mmengine/visualization/vis_backend.py#L324.

**Comment by fcakyon** [comment]
Thanks a lot for the info 👍
