### ISSUE TITLE
typo in `imcrop` docstring

### ISSUE THREAD

**Issue by hubutui** [open-mmlab/mmcv#2438]
https://github.com/open-mmlab/mmcv/blob/abb600ad8d34c0d1bc88b01c4d2526ebdea1f8dc/mmcv/image/geometric.py#L442-L443

I believe `padding` should be `scaling` here.

**Comment by HAOCHENYE** [comment]
Sorry for my late reply and thanks for your feedback, would mind posting a PR to fix this?
