### ISSUE TITLE
[FR] Albumentations support in MMCV v2 

### ISSUE THREAD

**Issue by Minyus** [open-mmlab/mmcv#2446]
**Describe the feature**
The existing version of MMDet, MMCls, etc. (working with MMCV v1) support Albumentations by Albu class.
In MMCV v2 (v2.0.0rc2), I get `Albu is not in the transform registry` error and it seems Albumentations is not supported yet. 

**Related resources**

https://github.com/open-mmlab/mmdetection/blob/e71b499608e9c3ccd4211e7c815fa20eeedf18a2/mmdet/datasets/pipelines/transforms.py#L1328
https://github.com/open-mmlab/mmclassification/blob/0eb3b61fc5a408b1e9fa3e6dcfb40a7628cd1dcb/mmcls/datasets/pipelines/transforms.py#L1013

**Comment by zhouzaida** [comment]
Hi @Minyus , `Albumentaion` has been supported and you can find it at https://github.com/open-mmlab/mmdetection/blob/79c8295801acedee0cbdbf128a01b9fe162646b0/mmdet/datasets/transforms/transforms.py#L1350.

**Comment by Minyus** [comment]
Hi @zhouzaida ,

Thank you for your reply.
I see. I thought the duplicate code for Albumentations support in MMDet, MMCls, etc. would be moved to MMCV v2.
Regarding the issue that MMSelfSup v1.0.0 does not support Albumentations yet, I may raise an issue at MMSelfSup repo.
