### ISSUE TITLE
Questions about RandomChoiceResize

### ISSUE THREAD

**Issue by xiexinch** [open-mmlab/mmcv#2449]
The argument `scales` of `RandomChoiceResize` accepts `Sequence[Union[int, Tuple]]` as input. But at the init function, it's forced to be a list of tuples.
https://github.com/open-mmlab/mmcv/blob/ac470881477e2604333b2f557644859a10c2101f/mmcv/transforms/processing.py#L1057
https://github.com/open-mmlab/mmcv/blob/ac470881477e2604333b2f557644859a10c2101f/mmcv/transforms/processing.py#L1066
Then the argument `scale` of `Resize` accepts `int` or `tuple` as input.
https://github.com/open-mmlab/mmcv/blob/ac470881477e2604333b2f557644859a10c2101f/mmcv/transforms/processing.py#L133
So can you remove the two assertions at https://github.com/open-mmlab/mmcv/blob/ac470881477e2604333b2f557644859a10c2101f/mmcv/transforms/processing.py#L1066 and
https://github.com/open-mmlab/mmcv/blob/ac470881477e2604333b2f557644859a10c2101f/mmcv/transforms/processing.py#L1082

**Comment by zhouzaida** [comment]
closed by #2450
