### ISSUE TITLE
Cannot re-initialize CUDA in forked subprocess when loading model in seldon-core

### ISSUE THREAD

**Issue by rlleshi** [open-mmlab/mmcv#2465]
I am using a [seldon-core](https://docs.seldon.io/projects/seldon-core/en/latest/python/python_component.html) microservice to serve a fast-rcnn detection model. However, when passing the model to the desired Cuda device with torch `model.to(device)` (at [init_detector](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/apis/inference.py#L55)) the following error is thrown:

`Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method.`

The same error is thrown even for human action recognition models of mmaction2 or pose models of mmpose. I have traced it to the checkpoint loading of the `mmcv.runner` but am not sure how to proceed.

The specific suggestions at [this](https://github.com/pytorch/pytorch/issues/40403) known torch issue do not work in this context.

I am attaching a minimal reproducible example in the below zip file.
[cuda_error.zip](https://github.com/open-mmlab/mmdetection/files/10095314/cuda_error.zip)

The contents are:

`Detection.py` -  minimal seldon python wrapper
`Dockerfile` - the dockerfile for the environment
`download_model.sh` - script to download the detection model
`faster_rcnn_r50_caffe_fpn_mstrain_1x_coco-person.py` - model config file

Steps: 

First, create the image: `nvidia-docker build -f Dockerfile . -t seldontest`
Then run the container: `nvidia-docker run -p 5000:5000 -p 9000:9000 --name seldontest -it seldontest`

I am not sure what the problem is because I've been able to deploy other models with gunicorn (which is what the seldon microservice uses) on a cuda device. But as already mentioned it seems to be related to the checkpoint loading of mmcv.

**Comment by HAOCHENYE** [comment]
Ahhh, I'm not familiar with seldon-core, but I still try to find a workaround in Google, and ..... finally, find this [issue](https://github.com/SeldonIO/seldon-core/issues/4429) you created 🤣 . It seems that the official gave you some suggestions 1 hour ago, how about trying it?

**Comment by rlleshi** [comment]
Did you manage to check the minimal example? I think it has something to do with the way `mmcv` loads a checkpoint.

**Comment by HAOCHENYE** [comment]
Alright, I'll check the minimal example today, and give feedback ASAP!

**Comment by HAOCHENYE** [comment]
![image](https://user-images.githubusercontent.com/57566630/206268157-9f63a61c-30f3-458a-b7cd-e7de67441253.png)
reproduce!

It seems the problem is that `gunicorn` forked a process in [here](https://github.com/benoitc/gunicorn/blob/008d81d0227cbc324f4e0814011e5d3cc4ec47e7/gunicorn/arbiter.py#L567)(maybe). I'm not familiar with `gunicorn`, but I think this error is caused by that the current configuration for `gunicorn` does not create the process correctly to run a GPU model.

**Comment by rlleshi** [comment]
hmm, but I've actually deployed other models using seldon-core (hence gunicorn) on a cuda device.

But otherwise do you think there's nothing wrong with the way a checkpoint is loaded by mmcv.runner [here](https://github.com/open-mmlab/mmcv/blob/37aa6dd04c7440dfa1d28a753a2f10d7c5ad621f/mmcv/runner/checkpoint.py#L552)? I can't see anything wrong with that but thought I'd ask once.

**Comment by HAOCHENYE** [comment]
Ahh. So why do you think this error is caused by [_load_checkpoin](https://github.com/open-mmlab/mmcv/blob/37aa6dd04c7440dfa1d28a753a2f10d7c5ad621f/mmcv/runner/checkpoint.py#L552)

**Comment by rlleshi** [comment]
@HAOCHENYE thanks a lot for your support. The `seldon-core` devs confirmed that it was an issue with how the microservice was handling multiprocessing. Still odd that it was failing for openmmlab models while working for other (torch) models on cuda.

For reference to anyone: migrating to [V2](https://mlserver.readthedocs.io/en/latest/index.html) solved the issue.
