### ISSUE TITLE
Slicing Referred List

### ISSUE THREAD

**Issue by OrcunCanDeniz** [open-mmlab/mmcv#2472]
I have a `base_cfg.py`
```
point_cloud_range = [-30, -40, -5, 90, 40, 3.1]
ego_range = [-1.5, -1.5, 0, 7, 1.5, 3.6]

# Translate from base_link to velodyne
x_offset = -6.22
z_offset = -3.12

ego_range[0::3] = list(map(lambda elem: elem+x_offset, ego_range[0::3]))
ego_range[2::3] = list(map(lambda elem: elem+z_offset, ego_range[2::3]))

point_cloud_range[0::3] = list(map(lambda elem: elem+x_offset, point_cloud_range[0::3]))
point_cloud_range[2::3] = list(map(lambda elem: elem+z_offset, point_cloud_range[2::3]))
```

and `child_cfg.py`
```
base =['base_cfg.py']
point_cloud_range_ = {{ _base_.point_cloud_range }}

...
            test_cfg=dict(pts=dict(pc_range=point_cloud_range_[:2]))
            )
...
```

When child_cfg.py is parsed, then `test_cfg.pts.pc_range = "_p"` but when i use `point_cloud_range_` without slicing its value equals to `point_cloud_range_ = [-36.22, -40, -8.120000000000001, 83.78, 40, -0.020000000000000018]` as computed in the base config, as expected. So, how can I get the first two elements(or any slice) of a referred variable?

*mmcv version 1.5.2

**Comment by HAOCHENYE** [comment]
Hi, sorry for my late reply :crying_cat_face:. the reference of base variable like `{{ _base_.point_cloud_range }}` is a placeholder during parsing the config, and you cannot operate it like the original variable. `MMEngine` provides a more general way to handle this case, you can directly access the base variable by `point_cloud_range_ = _base_.point_cloud_range`, and operate the it as the original variable.

https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#reference-of-the-inherited-file

![image](https://user-images.githubusercontent.com/57566630/206976416-f277abf0-d98f-4f67-994c-e4340f820d91.png)
