### ISSUE TITLE
"ModuleNotFoundError: No module named 'mmcv.cnn.weight_init'"

### ISSUE THREAD

**Issue by qingtongshidai** [open-mmlab/mmcv#2484]
The following error occurs when I run a project  
"ModuleNotFoundError: No module named 'mmcv.cnn.weight_init'"
How can I solve this problem?

**Comment by qingtongshidai** [comment]
> Hi @qingtongshidai , what is your mmcv version?

Thank you very much, I've already solved the problem, but there's  another problem 
"ImportError: cannot import name 'deform_conv_cuda' from partially initialized module 'mmdet.ops.dcn'"
and my mmcv==1.4.2, mmdet==2.26.0, torch==1.8.1, cuda==11.1

**Comment by zhouzaida** [comment]
`ops` in mmdet had been moved to mmcv/ops.

**Comment by qingtongshidai** [comment]
OK, thank you for your answer
