### ISSUE TITLE
How can I use iter_based_runner with distributed training ?  

### ISSUE THREAD

**Issue by linmou** [open-mmlab/mmcv#2491]
When I use iter_based_runner to train a model with DDP, I find that current version seems not support iter_based_runner

Here is the bug report. 

`Traceback (most recent call last):                                                                                                                            
  File "/mnt/bd/music-lqbd32-31t-dxj/mmselfsup_new/tools/train.py", line 224, in <module>                  
    main()                                                                                                                                                    
  File "/mnt/bd/music-lqbd32-31t-dxj/mmselfsup_new/tools/train.py", line 214, in main                                                                         
    train_model(                                                                                                                                              
  File "/mnt/bd/music-lqbd32-31t-dxj/mmselfsup_new/mmselfsup/apis/train.py", line 226, in train_model      
    runner.run(data_loaders, cfg.workflow)                                                                                                                    
  File "/opt/conda/lib/python3.9/site-packages/mmcv/runner/iter_based_runner.py", line 130, in run
    self.call_hook('before_epoch')                                             
  File "/opt/conda/lib/python3.9/site-packages/mmcv/runner/base_runner.py", line 317, in call_hook   
    getattr(hook, fn_name)(self)                                               
  File "/opt/conda/lib/python3.9/site-packages/mmcv/runner/hooks/sampler_seed.py", line 15, in before_epoch
    if hasattr(runner.data_loader.sampler, 'set_epoch'):                       
AttributeError: 'IterBasedRunner' object has no attribute 'data_loader'     `

And I found the following annotation under the definition of class 'DistSamplerSeedHook', saying that 
'When distributed training, it is only useful in conjunction with
    :obj:`EpochBasedRunner`, while :obj:`IterBasedRunner` achieves the same
    purpose with :obj:`IterLoader`.'

 So any ideas about using IterBasedRunner in distributed learning?

**Comment by HAOCHENYE** [comment]
Hi, it seems that this problem is cause by `mmselfsup` using `DistSamplerHook` here:

https://github.com/open-mmlab/mmselfsup/blob/1b098964e0ca9c58c0eb1fb7ba575af4c0d1e6aa/mmselfsup/apis/train.py#L162

You can try to disable it and try again.

BTW, I think you could get a faster and more accurate result by posting this issue in `mmselfsup`

**Comment by linmou** [comment]
Thanks，this issue may be from the bug from mmselfsup
