### ISSUE TITLE
error with new installing

### ISSUE THREAD

**Issue by zeynepiskenderoglu** [open-mmlab/mmcv#2502]
I am getting this error about mmcv
`UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.`
After going to the link and updating the mmcv, when this line in my code works
`from mmdet.apis import inference_detector`
I get this error
`AssertionError: MMCV==2.0.0rc3 is used but incompatible. Please install mmcv>=1.3.17, <=1.8.0.`

How can I get rid of this error, how can I fix it?

**Comment by ice-tong** [comment]
Hi @zeynepiskenderoglu , mmcv 2.x is a part of OpenMMLab 2.0 and corresponding to it is mmdet 3.x~

> UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.

This is just a user warning but not an error, you can ignore it if you don't want to use OpenMMLab 2.0~

**Comment by hsp2454** [comment]
Did you solve it in the end, I have the same problem, I encountered it when running "python tool\train.py", it keeps repeating this error.

**Comment by zeynepiskenderoglu** [comment]
No I couldn't solve it, i still keep getting the warning
