### ISSUE TITLE
install mmcv fail

### ISSUE THREAD

**Issue by happylinhxl** [open-mmlab/mmcv#2505]
hi , I have a problem ：install mmcv fail

The machine environment is
OS ：ubuntu 20.04
GPU： nvidia gpu ，this driver is right

I successfully installed mmcv before, but yesterday I found that it could not run correctly. I guess the python environment may be damaged. Today, I used the same method to create a new python environment. I used the following command to install it,

conda create --name openmmlab-new python=3.8 -y
conda activate openmmlab-new
pip install torch==1.10.0+cu111 torchvision==0.11.0+cu111 torchaudio==0.10.0 -f https://download.pytorch.org/whl/torch_stable.html
pip install -U openmim

Each step above runs correctly
However, when I run the command "mim install mmcv-full", an error occurs

(openmmlab-new) root@xxxxxxxx:/# mim install mmcv-full
/root/miniconda3/envs/openmmlab-new/lib/python3.8/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Segmentation fault (core dumped)

There is no more error information. Please give some suggestions about the reason. Thanks

**Comment by ice-tong** [comment]
Hi @happylinhxl , here are some suggestions that may help you locate the problem:

- Using [`-v` options](https://pip.pypa.io/en/stable/cli/pip/#verbose) for more outputs: `mim install -vvv mmcv-full`
- Check the `torch.cuda.is_available()`, `torch.version.cuda` and `torch.__version__`

Feel free to feed back us if you have any problems! ^_^

**Comment by happylinhxl** [comment]
Hi @ice-tong , The problem occurs in torch, which has nothing to do with mmcv. I have solved it. Thank you for your ideas
