### ISSUE TITLE
importError: cannot import name 'BaseTransform' from 'mmcv'

### ISSUE THREAD

**Issue by Guiyingyi1996** [open-mmlab/mmcv#2506]
when I want init to a Vit model for testing, I encountered the following error:
ImportError: cannot import name 'BaseTransform' from 'mmcv'
It comes from File "~/.conda/envs/mmcv/lib/python3.8/site-packages/mmcls/datasets/transforms/auto_augment.py", line 10, in <module>
    from mmcv import BaseTransform, RandomChoice

The Packages i used are as follows:
Package    Version    Source
---------  ---------  ----------------------------------------------
mmcls      1.0.0rc4   https://github.com/open-mmlab/mmclassification
mmcv-full  1.7.0      https://github.com/open-mmlab/mmcv
mmengine   0.3.2      https://github.com/open-mmlab/mmengine

**Comment by zhouzaida** [comment]
Hi, BaseTransform was added in version 2.0.0rc1. More details at https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md#v200rc1. You can use mim to install it.

```
pip install openmim
mim install "mmcv>=2.0.0rc1"
```
