### ISSUE TITLE
how to get iteration number or epoch number by functions 

### ISSUE THREAD

**Issue by xypu98** [open-mmlab/mmcv#2531]
I want to get the iteration number to figure out the processing percentage of training by functions. So that I can change some parameters according to the training process in the code.
Are there any functions to get iteration number of training process?

 Thanks a lot!

**Comment by HAOCHENYE** [comment]
MMCV lacks the ability to interact across modules, which means that runtime information such as epoch iter is difficult to obtain for modules other than `Runner` and `Hook`. A probable workaround maybe setting `epoch` or `iteration` in Hook for specific model, such as:

```python
class CustomHook(Hook):
    ...
    def after_train_iter(self, runner):
        runner.model.toy_model.iter = runner.iter 
```

Then, you can get iteration in `toy_model` by `iter = self.iter`.

Besides, MMEngine (The next generation training architecture of OpenMMLab) can solve this case perfectly :smile: , the global accessible variable `MessageHub` save the `epoch`, `iteraton`, .etc. runtime information and you can get these anywhere, such as:

```python
iter = MesssageHub.get_current_instance().get_info('iter')
```
