### ISSUE TITLE
Dose the spconv_ops operation only support cuda implementation

### ISSUE THREAD

**Issue by LiuYi-Up** [open-mmlab/mmcv#2533]
Hi, thanks for your great work. 
When I try to add the support of spconv to onnxruntime in mmdeploy, I found that there is only a cuda implementation of this operator (the spconv_ops_cuda.cu) . I want to confirm whether there is a cpp implementation of this operator？

**Comment by HAOCHENYE** [comment]
Thanks for your feedback, currently MMCV has not provided the CPU implementation of spconv_ops
