### ISSUE TITLE
Incorrect results for CPU version of nms_rotated on non-contiguous inputs

### ISSUE THREAD

**Issue by allanzelener** [open-mmlab/mmcv#2542]
**Describe the Issue**
The nms_rotated function will produce incorrect results when given non-contiguous tensor inputs on CPU. E.g., some boxes that should be suppressed are not and vice versa. 

**Reproduction**

1. What command, code, or script did you run?

E.g., assume we generate 3D box regressions and concatenate the topdown 2D XY coordinates. This will generate a non-contiguous tensor of 2D rotated boxes that can trigger this issue.

```python
topdown_boxes = torch.cat((boxes[:2], boxes[3:5], boxes[6:7]))
nms_boxes, nms_inds = nms_rotated(topdown_boxes, scores, 0.5)
```

2. Did you make any modifications on the code? Did you understand what you have modified?
I ran a subset of the nms_rotated code in a different repo. Some modifications were made but I expect the issue here to reproduce in the main branch of mmcv due to the reasons described below. 

**Bug fix**
I've determined that the reason for this issue is that [mmcv omits](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/csrc/pytorch/nms_rotated.cpp#L23-L31) the contiguous call from the original [detectron2 repo's](https://github.com/facebookresearch/detectron2/blob/main/detectron2/layers/csrc/nms_rotated/nms_rotated.h#L28-L37) implementation of this function. This may work for the modified GPU implementation in mmcv because `dets_sorted` may be contiguous result from the sorting operation but the [direct pointer access here](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/csrc/pytorch/cpu/nms_rotated.cpp#L49-L50) for the `dets` tensor likely does not produce the correct result when `dets` is non-contiguous.

Both transferring the input tensors to GPU and adding the contiguous calls as done in the detectron2 resolved the issue for me. The latter would be a simple bug fix but I don't know the motivation for removing the contiguous calls from the original implementation in the first place so I'll leave off on creating a PR for now.

**Comment by HAOCHENYE** [comment]
Thanks for your feedback! You're right, we miss the `contiguous` operation to make sure the data is continuous. Would mind posting a PR to fix this?

**Comment by allanzelener** [comment]
@HAOCHENYE The PR is open and I've signed the CLA. I don't currently have a setup to build the project as distributed for all of the testing right now but hopefully your unit tests cover that? Can you take a look at the PR?
