### ISSUE TITLE
How can I set different grad_clip for different layers

### ISSUE THREAD

**Issue by xtk8532704** [open-mmlab/mmcv#2563]
I'm trying to train a cross-modal network, and the modules need different 'max_norm' of grad_clip. 

Can I modify them in the optimizer's 'custom_keys' in the config to do it? Are there any examples?

**Comment by zhouzaida** [comment]
Hi @xtk8532704 , sorry for our late reply. We were on Chinese New Year last week.

You can inherit from `OptimizerHook` and then override the `clip_grads` method.

https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/optimizer.py#L30
