### ISSUE TITLE
Writing and using a custom StorageBackend?

### ISSUE THREAD

**Issue by Data-drone** [open-mmlab/mmcv#2566]
I am using Databricks and though the FUSE mount for storage is similar to a Hard disk, it doesn't support `symlink` which is causing checkpointing to crash.

I tried to use `petrel` backend since it has s3 type links and I am guessing doesn't use symlink but it asks for a client and there is no documentation on what that client is?

How can I create a custom StorageBackend and disable symlinking? How can I get that class properly registered so that I can specify that in my config file and `file_client_args`?

**Comment by zhouzaida** [comment]
Hi @Data-drone , thanks for your report.

If your storage is similar to the hard disk, you can inherit from `HardDiskBackend` and set the `_allow_symlink` as False.

Define a new Backend and register it to FileClient.

```python
from mmcv.fileio import HardDiskBackend

@FileClient.register_backend('custom')
class CustomBackend(HardDiskBackend):
    _allow_symlink = False
```

Use it in your config
```python
file_client_args = dict(backend='custom')
```
