### ISSUE TITLE
CosineLrUpdaterHook not in mmcv==0.4.4

### ISSUE THREAD

**Issue by zehuichen123** [open-mmlab/mmcv#260]
CosineLrUpdateHook is ok in 0.4.3 but raise `KeyError: 'CosineLrUpdaterHook is not in the hook registry'`in 0.4.4 when I call it in mmdet.

**Comment by hellock** [comment]
It has been renamed to `CosineAnealingLrUpdaterHook` to be consistent with the name in PyTorch.

**Comment by zehuichen123** [comment]
ok, I see. Thx~

**Comment by y78h11b09** [comment]
Hi, I meet the same problem, where did you  rename it "CosineAnealingLrUpdaterHook  "?

**Comment by ShoufaChen** [comment]
Renaming `cosine` in the config file to `CosineAnnealing` works for me.
