### ISSUE TITLE
[Feature] Provide mmcv installation link hosted outside of China

### ISSUE THREAD

**Issue by eantono-pge** [open-mmlab/mmcv#2603]
### What is the feature?

My company blocks access to links hosted in China. It would be very useful to our team to be able to an alternative to pip installation links like `https://download.openmmlab.com/mmcv/dist/cu117/torch1.13/index.html` (see [https://mmcv.readthedocs.io/en/latest/get_started/installation.html#install-with-pip]) that are hosted elsewhere so that we are able to access them.

**Comment by zhouzaida** [comment]
Hi @eantono-pge , I am sorry that we have no plan to host wheels in other places.

**Comment by eantono-pge** [comment]
Ok, thanks for letting me know!
