### ISSUE TITLE
Mmcv installation failed

### ISSUE THREAD

**Issue by lindadamama** [open-mmlab/mmcv#2607]
### 📚 The doc issue

<img width="1183" alt="image" src="https://user-images.githubusercontent.com/48863486/219431367-4e4bb9a7-3105-4897-975f-f6047f32bd0b.png">
<img width="1226" alt="image" src="https://user-images.githubusercontent.com/48863486/219433389-8051fee9-5f35-46df-a743-3b72acaca327.png">
```pthon

pip install mmcv-full==1.3.14

```
I encountered this problem when installing mmcv. I don't know how to solve it

**Comment by zhouzaida** [comment]
Hi @lindadamama , `mmcv-full` pre-built packages were provided since `mmcv>=1.4.0` so you need to build it from source if you need to install `mmcv-full==1.3.14`. Please refer to https://mmcv.readthedocs.io/zh_CN/latest/get_started/build.html#windows-mmcv-full.
