### ISSUE TITLE
[Docs] 

### ISSUE THREAD

**Issue by Fun772283153** [open-mmlab/mmcv#2627]
### 📚 The doc issue

![image](https://user-images.githubusercontent.com/23419799/221849182-98ee7653-0a33-4afe-ab52-1cd37a88276a.png)

I dont know what is the pointsets, why it should be x1, y1,x2,y2,...,x9,y9, could you tell me about what are pointsets and polygons, and can this function be used for caculate giou between two oriented bounding box?

**Comment by Fun772283153** [comment]
can someone explain how to use convex_giou

**Comment by zhouzaida** [comment]
Hi, the pointsets represent the points generated by model prediction and the polygons represent the oriented bounding box (OBB) which are ground truths, which can be denoted as `(x1, y1, x2, y2, x3, y3, x4, y4)`.

**Comment by Fun772283153** [comment]
> 

Thanks a lot.
