### ISSUE TITLE
[Docs] 

### ISSUE THREAD

**Issue by shireen1512** [open-mmlab/mmcv#2633]
### 📚 The doc issue

Hello, 
i have a custom dataset (.jpg images and grayscale .png masks) and i have organized it according to this doc : https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/tutorials/customize_datasets.md#customize-datasets-by-reorganizing-data
i have a very rookie question because i know i don't understand the steps to follow..
if i want to train 'ocrnet' for example:  
`!python tools/train.py configs/ocrnet/ocrnet_hr18_512x1024_160k_cityscapes.py`
what i don't understand is, where should i specify my data? it's not happy because it thinks i want to train on cityscapes : 
FileNotFoundError: CityscapesDataset: [Errno 2] No such file or directory: 'data/cityscapes/leftImg8bit/train'

**Comment by HAOCHENYE** [comment]
Here are two common approaches:

1. Modify the "data_root" in the configuration file to point to your Cityscapes dataset.
2. Alternatively, create a soft link to the Cityscapes dataset in the "data" folder (you should create "data" first) at the root of your project
