### ISSUE TITLE
[Feature] The "dilation" and "group" disappear in the realization of the masked_conv2d op  

### ISSUE THREAD

**Issue by ckirchhoff2021** [open-mmlab/mmcv#2635]
### What is the feature?

Nowadays some tests are token on the op of "masked_conv2d". "dilation" and "group" are passed to the class module, while the parameters don't take effect when i cange the value. It turns out to be the "dilation" and "group" are not used in the kernel. so should we pass the two parameters to the class module, or should we remove these in the inputs?

**Comment by zhouzaida** [comment]
The two parameters are not supported currently.
