### ISSUE TITLE
[Bug]  File "/Users/kyanchen/opt/miniconda3/envs/pytorch/lib/python3.9/site-packages/mmcv/ops/nms.py", line 127, in nms     inds = NMSop.apply(boxes, scores, iou_threshold, offset, score_threshold,   File "/Users/kyanchen/opt/miniconda3/envs/pytorch/lib/python3.9/site-packages/mmcv/ops/nms.py", line 27, in forward     inds = ext_module.nms( RuntimeError: nms_impl: implementation for device mps:0 not found.

### ISSUE THREAD

**Issue by KyanChen** [open-mmlab/mmcv#2639]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmcv/issues) and [Discussions](https://github.com/open-mmlab/mmcv/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmcv).

### Environment

OrderedDict([('sys.platform', 'darwin'), ('Python', '3.9.12 (main, Jun  1 2022, 06:34:44) [Clang 12.0.0 ]'), ('CUDA available', False), ('numpy_random_seed', 2147483648), ('GCC', 'Apple clang version 14.0.0 (clang-1400.0.29.202)'), ('PyTorch', '1.13.1'), ('PyTorch compiling details', 'PyTorch built with:\n  - GCC 4.2\n  - C++ Version: 201402\n  - clang 14.0.0\n  - LAPACK is enabled (usually provided by MKL)\n  - NNPACK is enabled\n  - CPU capability usage: NO AVX\n  - Build settings: BLAS_INFO=accelerate, BUILD_TYPE=Release, CXX_COMPILER=/Applications/Xcode_14.0.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -Wno-deprecated-declarations -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_PYTORCH_METAL_EXPORT -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -DUSE_COREML_DELEGATE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wvla-extension -Wno-range-loop-analysis -Wno-pass-failed -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -Wconstant-conversion -Wno-invalid-partial-specialization -Wno-typedef-redefinition -Wno-unused-private-field -Wno-inconsistent-missing-override -Wno-c++14-extensions -Wno-constexpr-not-const -Wno-missing-braces -Wunused-lambda-capture -Wunused-local-typedef -Qunused-arguments -fcolor-diagnostics -fdiagnostics-color=always -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -DUSE_MPS -fno-objc-arc -Wno-unguarded-availability-new -Wno-unused-private-field -Wno-missing-braces -Wno-c++14-extensions -Wno-constexpr-not-const, LAPACK_INFO=accelerate, TORCH_VERSION=1.13.1, USE_CUDA=OFF, USE_CUDNN=OFF, USE_EIGEN_FOR_BLAS=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=OFF, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=ON, USE_OPENMP=OFF, USE_ROCM=OFF, \n'), ('TorchVision', '0.14.1'), ('OpenCV', '4.6.0'), ('MMEngine', '0.6.0'), ('MMCV', '2.0.0rc4'), ('MMCV Compiler', 'clang 13.1.6'), ('MMCV CUDA Compiler', 'not available')])

### Reproduces the problem - code sample

 File "/Users/kyanchen/opt/miniconda3/envs/pytorch/lib/python3.9/site-packages/mmcv/ops/nms.py", line 127, in nms
    inds = NMSop.apply(boxes, scores, iou_threshold, offset, score_threshold,
  File "/Users/kyanchen/opt/miniconda3/envs/pytorch/lib/python3.9/site-packages/mmcv/ops/nms.py", line 27, in forward
    inds = ext_module.nms(
RuntimeError: nms_impl: implementation for device mps:0 not found.

### Reproduces the problem - command or script

 File "/Users/kyanchen/opt/miniconda3/envs/pytorch/lib/python3.9/site-packages/mmcv/ops/nms.py", line 127, in nms
    inds = NMSop.apply(boxes, scores, iou_threshold, offset, score_threshold,
  File "/Users/kyanchen/opt/miniconda3/envs/pytorch/lib/python3.9/site-packages/mmcv/ops/nms.py", line 27, in forward
    inds = ext_module.nms(
RuntimeError: nms_impl: implementation for device mps:0 not found.

### Reproduces the problem - error message

 File "/Users/kyanchen/opt/miniconda3/envs/pytorch/lib/python3.9/site-packages/mmcv/ops/nms.py", line 127, in nms
    inds = NMSop.apply(boxes, scores, iou_threshold, offset, score_threshold,
  File "/Users/kyanchen/opt/miniconda3/envs/pytorch/lib/python3.9/site-packages/mmcv/ops/nms.py", line 27, in forward
    inds = ext_module.nms(
RuntimeError: nms_impl: implementation for device mps:0 not found.

**Comment by zhouzaida** [comment]
Hi, the NMS op is not supported for MPS currently.

**Comment by volkov-maxim** [comment]
> Hi, the NMS op is not supported for MPS currently.

Hi, @zhouzaida!
Have you planned to implement NMS op for MPS? If yes, then when?
