### ISSUE TITLE
How to install mmcv-full with cuda11.4 and pytorch1.11.0[Docs] 

### ISSUE THREAD

**Issue by YaqinLong** [open-mmlab/mmcv#2650]
### 📚 The doc issue

I want to deploy a algorithm on Jetson Xavier NX, whose cuda is 11.4. In the documentation of how to install mmcv-full, it does not have the cuda11.4 option. So, how to install the mmcv-full with cuda 11.4?
Thank you for your replying.

**Comment by HAOCHENYE** [comment]
Hi, suggest using `openmim` to install `mmcv-full`. 

```shell
pip uninstall mmcv-full -y
pip install -U openmim
mim install mmcv-full
```

If there is no valid pre-built package for the corresponding PyTorch and cudatoolkit, it will fallback to build mmcv from source automatically.

**Comment by zhouzaida** [comment]
Hi @YaqinLong , you can refer to https://mmcv.readthedocs.io/en/latest/get_started/build.html#build-mmcv-full to install it from the source code.
