### ISSUE TITLE
[Bug] `mmcv.cnn.ConvModule` cannot used with `torch.jit.script`

### ISSUE THREAD

**Issue by FabianSchuetze** [open-mmlab/mmcv#2651]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmcv/issues) and [Discussions](https://github.com/open-mmlab/mmcv/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmcv).

### Environment

OrderedDict([('sys.platform', 'linux'), ('Python', '3.8.10 (default, Nov 14 2022, 12:59:47) [GCC 9.4.0]'), ('CUDA available', False), ('numpy_random_seed', 2147483648), ('GCC', 'x86_64-linux-gnu-gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0'), ('PyTorch', '1.13.1+cu117'), ('PyTorch compiling details', 'PyTorch built with:\n  - GCC 9.3\n  - C++ Version: 201402\n  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications\n  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)\n  - OpenMP 201511 (a.k.a. OpenMP 4.5)\n  - LAPACK is enabled (usually provided by MKL)\n  - NNPACK is enabled\n  - CPU capability usage: AVX2\n  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, \n'), ('TorchVision', '0.14.1+cu117'), ('OpenCV', '4.2.0'), ('MMEngine', '0.6.0'), ('MMCV', '2.0.0rc4'), ('MMCV Compiler', 'GCC 9.3'), ('MMCV CUDA Compiler', '11.7')])

### Reproduces the problem - code sample

Thanks for this wonderful repo. It's a pleasure to work with it and read the code. 

I am trying to `torch.jit.scrpit` a network containing the `ConvModule` and receive the following error:

```
RuntimeError: 
Module 'ConvModule' has no attribute 'padding_layer' :
  File "/home/schuetze/.local/lib/python3.8/site-packages/mmcv/cnn/bricks/conv_module.py", line 206
            if layer == 'conv':
                if self.with_explicit_padding:
                    x = self.padding_layer(x)
                        ~~~~~~~~~~~~~~~~~~ <--- HERE
                x = self.conv(x)
            elif layer == 'norm' and norm and self.with_norm:
```

Indeed, self.padding_layer is not defined in every branches of the code.

I thus wonder if `torch.jit.scripting` supported by mmcv? Onnx seems to be supported, but I  am not sure if torch jit is supported. The error prevents me from torch.jit.scripting networks containing the `ConvModule`. 

### Reproduces the problem - command or script

```
 import torch
from mmcv.cnn import ConvModule
module = ConvModule(256, 256, 3, 1, 1) 
torch.jit.script(module)
```

### Reproduces the problem - error message

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-5-a7607b895eb4> in <module>
----> 1 torch.jit.script(module)

~/.local/lib/python3.8/site-packages/torch/jit/_script.py in script(obj, optimize, _frames_up, _rcb, example_inputs)
   1284     if isinstance(obj, torch.nn.Module):
   1285         obj = call_prepare_scriptable_func(obj)
-> 1286         return torch.jit._recursive.create_script_module(
   1287             obj, torch.jit._recursive.infer_methods_to_compile
   1288         )

~/.local/lib/python3.8/site-packages/torch/jit/_recursive.py in create_script_module(nn_module, stubs_fn, share_types, is_tracing)
    474     if not is_tracing:
    475         AttributeTypeIsSupportedChecker().check(nn_module)
--> 476     return create_script_module_impl(nn_module, concrete_type, stubs_fn)
    477 
    478 def create_script_module_impl(nn_module, concrete_type, stubs_fn):

~/.local/lib/python3.8/site-packages/torch/jit/_recursive.py in create_script_module_impl(nn_module, concrete_type, stubs_fn)
    540     # Compile methods if necessary
    541     if concrete_type not in concrete_type_store.methods_compiled:
--> 542         create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
    543 
    544         # Create hooks after methods to ensure no name collisions between hooks and methods.

~/.local/lib/python3.8/site-packages/torch/jit/_recursive.py in create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
    391     property_rcbs = [p.resolution_callback for p in property_stubs]
    392 
--> 393     concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
    394 
    395 def create_hooks_from_stubs(concrete_type, hook_stubs, pre_hook_stubs):

RuntimeError: 
Module 'ConvModule' has no attribute 'padding_layer' :
  File "/home/schuetze/.local/lib/python3.8/site-packages/mmcv/cnn/bricks/conv_module.py", line 206
            if layer == 'conv':
                if self.with_explicit_padding:
                    x = self.padding_layer(x)
                        ~~~~~~~~~~~~~~~~~~ <--- HERE
                x = self.conv(x)
            elif layer == 'norm' and norm and self.with_norm:



```

**Comment by HAOCHENYE** [comment]
Hi, for those modules which do not have a dynamic branch during runtime, we suggest using `torch.jit.trace` to trace it

**Comment by FabianSchuetze** [comment]
Makes a lot of sense - thank you
