### ISSUE TITLE
[Bug] undefined symbol: _ZN3c105ErrorC2ENS_14SourceLocationESs

### ISSUE THREAD

**Issue by uniyushu** [open-mmlab/mmcv#2660]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmcv/issues) and [Discussions](https://github.com/open-mmlab/mmcv/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmcv).

### Environment

(open-mmlab) ubuntu@ml-ubuntu20-04-desktop-v2-6-32gb-25m:/data/Projects/mmclassification$ python -c "from mmcv.utils import collect_env; print(collect_env())"
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/utils/env.py", line 124, in collect_env
    from mmcv.ops import get_compiler_version, get_compiling_cuda_version
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/ops/__init__.py", line 3, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/ops/active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC2ENS_14SourceLocationESs

### Reproduces the problem - code sample

python tools/train.py configs/resnet/resnet18_8xb16_cifar10.py 

### Reproduces the problem - error message
<img width="1133" alt="image" src="https://user-images.githubusercontent.com/20262193/224940579-d0684e5d-5277-4e0f-a7a3-7f86eb9380c8.png">

### Additional information

<img width="1129" alt="image" src="https://user-images.githubusercontent.com/20262193/224939640-75963b68-0596-4656-b9ef-d7835d32837c.png">
<img width="1145" alt="image" src="https://user-images.githubusercontent.com/20262193/224941168-77d9879b-6dc0-4b88-a89b-00433b7fce94.png">
<img width="1142" alt="image" src="https://user-images.githubusercontent.com/20262193/224942283-d2072b6a-c6a2-4987-be82-eec32c30bf61.png">

**Comment by uniyushu** [comment]
git checkout 2.x

**Comment by bryanbocao** [comment]
Same issue here.

**Comment by ZHANG-ZHENPENG** [comment]
Same issue on google colab. 
ImportError: /usr/local/lib/python3.10/dist-packages/mmcv/_ext.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops10zeros_like4callERKNS_6TensorESt8optionalIN3c1010ScalarTypeEES5_INS6_6LayoutEES5_INS6_6DeviceEES5_IbES5_INS6_12MemoryFormatEE

**Comment by bryanbocao** [comment]
In experience, it is mainly due to version problems.

```python3.10``` can be a problem, try 8?

```
NVIDIA® RTX A5000
v11.3 with cuDNN v8.2.0
PyTorch v1.9.1
```
```
mim install mmcv==2.1.0
```
