### ISSUE TITLE
[Bug]  based on:mmcv 2.0.0rc4  mmcv.imcrop  return a error img size

### ISSUE THREAD

**Issue by thfylsty** [open-mmlab/mmcv#2705]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmcv/issues) and [Discussions](https://github.com/open-mmlab/mmcv/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmcv).

### Environment

when 
```python
import mmcv
resized_img = np.ones((360,640,3))
crop = (0, -12, 640, 372)
img = mmcv.imcrop(resized_img, np.array(crop), pad_fill=0)
print(img.shape)
```
the mmcv result is 
`result: (385, 641, 3)`

but the old version use PLT to crop images ,get shape`result: (384, 640, 3)` 
```python
from  PIL import Image
resized_img = np.ones((360,640,3))
crop = (0, -12, 640, 372)
resized_img = Image.fromarray(resized_img,mode="RGB")
img = resized_img.crop(crop)
print(np.array(img).shape)
```
`result: (384, 640, 3)`

it is soooo crazy. My netword cannot get a low loss due to the intrinsics project with a error input size.

### Reproduces the problem - code sample

img = mmcv.imcrop(resized_img, np.array(crop), pad_fill=0)

### Reproduces the problem - command or script

img = mmcv.imcrop(resized_img, np.array(crop), pad_fill=0)

### Reproduces the problem - error message

a giant model loss

**Comment by thfylsty** [comment]
![image](https://user-images.githubusercontent.com/29136517/227956138-917f6dd9-f12a-4ad0-8853-5d1dd14eed14.png)

**Comment by zhouzaida** [comment]
Hi @thfylsty , sorry for my late reply. The definition of bounding boxes in MMCV and PIL is different; the bottom-right coordinate is included in MMCV, while it is not included in PIL. Suppose the box is (0, 0, 10, 10), then the width and height of the bounding box in MMCV would be 11, whereas in PIL, the value would be 10.
