### ISSUE TITLE
[Bug]cuda 11.6 安装 mmcv1.3.4向下兼容不了

### ISSUE THREAD

**Issue by cqray1990** [open-mmlab/mmcv#2714]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmcv/issues) and [Discussions](https://github.com/open-mmlab/mmcv/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmcv).

### Environment

CUDA 11.6 
python3.8
ubantu 18
pytorch 1.13.1

### Reproduces the problem - code sample
用以下命令安装mmcv
pip install mmcv-full==1.3.4 -f https://download.openmmlab.com/mmcv/dist/cu116/torch1.13.1/index.html
mmcv版本我只需要安装1.3.4 d
安装中途出现如下错误：
   compilation terminated.
      error: command '/usr/local/cuda-11.6/bin/nvcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mmcv-full
  Running setup.py clean for mmcv-full
Failed to build mmcv-full
Installing collected packages: mmcv-full

### Reproduces the problem - command or script
用以下命令安装mmcv
pip install mmcv-full==1.3.4 -f https://download.openmmlab.com/mmcv/dist/cu116/torch1.13.1/index.html
mmcv版本我只需要安装1.3.4 d
安装中途出现如下错误：
   compilation terminated.
      error: command '/usr/local/cuda-11.6/bin/nvcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mmcv-full
  Running setup.py clean for mmcv-full
Failed to build mmcv-full
Installing collected packages: mmcv-full

### Reproduces the problem - error message

   compilation terminated.
      error: command '/usr/local/cuda-11.6/bin/nvcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mmcv-full
  Running setup.py clean for mmcv-full
Failed to build mmcv-full
Installing collected packages: mmcv-full

### Additional information
用以下命令安装mmcv
pip install mmcv-full==1.3.4 -f https://download.openmmlab.com/mmcv/dist/cu116/torch1.13.1/index.html
mmcv版本我只需要安装1.3.4 d
安装中途bui出现如下错误：

   compilation terminated.
      error: command '/usr/local/cuda-11.6/bin/nvcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mmcv-full
  Running setup.py clean for mmcv-full
Failed to build mmcv-full
Installing collected packages: mmcv-full

**Comment by zhouzaida** [comment]
MMCV v1.3.4 没有提供 PyTorch1.13-CUDA11.6 的预编译包，需自行源码安装，可参考 https://mmcv.readthedocs.io/zh_CN/latest/get_started/build.html#mmcv-full。
