### ISSUE TITLE
[Bug] compatibility with torch 2.0?

### ISSUE THREAD

**Issue by wqh17101** [open-mmlab/mmcv#2728]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmcv/issues) and [Discussions](https://github.com/open-mmlab/mmcv/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmcv).

### Environment

[root@cvmodel-75789d455f-9g85b lib]# python -c "from mmcv.utils import collect_env; print(collect_env())"
/opt/aaa/python/python-3.9.11/lib/python3.9/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
/bin/sh: /usr/local/cuda/bin/nvcc: Permission denied
/bin/sh: gcc: command not found
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/aaa/python/python-3.9.11/lib/python3.9/site-packages/mmcv/utils/env.py", line 124, in collect_env
    from mmcv.ops import get_compiler_version, get_compiling_cuda_version
  File "/opt/aaa/python/python-3.9.11/lib/python3.9/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "/opt/aaa/python/python-3.9.11/lib/python3.9/site-packages/mmcv/ops/active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "/opt/aaa/python/python-3.9.11/lib/python3.9/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/opt/aaa/python/python-3.9.11/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory

### Reproduces the problem - code sample

python -c "from mmcv.utils import collect_env; print(collect_env())"

### Reproduces the problem - command or script

python -c "from mmcv.utils import collect_env; print(collect_env())"

### Reproduces the problem - error message

ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory

### Additional information

I am using torch 2.0.0 and 
```
[root@cvmodel-75789d455f-9g85b torch]# cd lib
[root@cvmodel-75789d455f-9g85b lib]# ll
total 3202460
-r-x------ 1 manas manas    1289880 Apr  3 10:05 libc10_cuda.so
-r-x------ 1 manas manas     852504 Apr  3 10:05 libc10.so
-r-x------ 1 manas manas      22425 Apr  3 10:05 libcaffe2_nvrtc.so
-r-x------ 1 manas manas  348150584 Apr  3 10:06 libcublasLt.so.11
-r-x------ 1 manas manas  156720544 Apr  3 10:06 libcublas.so.11
-r-x------ 1 manas manas     687321 Apr  3 10:06 libcudart-e409450e.so.11.0
-r-x------ 1 manas manas  113856969 Apr  3 10:06 libcudnn_adv_infer.so.8
-r-x------ 1 manas manas   95519201 Apr  3 10:06 libcudnn_adv_train.so.8
-r-x------ 1 manas manas  458532049 Apr  3 10:06 libcudnn_cnn_infer.so.8
-r-x------ 1 manas manas   74242329 Apr  3 10:06 libcudnn_cnn_train.so.8
-r-x------ 1 manas manas   91406321 Apr  3 10:06 libcudnn_ops_infer.so.8
-r-x------ 1 manas manas   67609937 Apr  3 10:06 libcudnn_ops_train.so.8
-r-x------ 1 manas manas     150200 Apr  3 10:06 libcudnn.so.8
-r-x------ 1 manas manas     168721 Apr  3 10:06 libgomp-a34b3233.so.1
-r-x------ 1 manas manas    9484529 Apr  3 10:05 libnvfuser_codegen.so
-r-x------ 1 manas manas    7079489 Apr  3 10:06 libnvrtc-builtins.so.11.7
-r-x------ 1 manas manas   45791369 Apr  3 10:06 libnvrtc-d833c4f3.so.11.2
-r-x------ 1 manas manas      43681 Apr  3 10:06 libnvToolsExt-847d78f2.so.1
-r-x------ 1 manas manas      44560 Apr  3 10:05 libshm.so
-r-x------ 1 manas manas  514384193 Apr  3 10:05 libtorch_cpu.so
-r-x------ 1 manas manas  214779865 Apr  3 10:06 libtorch_cuda_linalg.so
-r-x------ 1 manas manas 1054681913 Apr  3 10:05 libtorch_cuda.so
-r-x------ 1 manas manas      20825 Apr  3 10:06 libtorch_global_deps.so
-r-x------ 1 manas manas   23565153 Apr  3 10:06 libtorch_python.so
-r-x------ 1 manas manas     166536 Apr  3 10:05 libtorch.so

```
libtorch_cuda.so exsits.

My cuda is 11.7 and mmcv-full is https://download.openmmlab.com/mmcv/dist/cu117/torch1.13.0/mmcv_full-1.7.0-cp39-cp39-manylinux1_x86_64.whl

**Comment by zhouzaida** [comment]
Hi @wqh17101 , we have not provided pre-built mmcv-full for torch2.0.0 so you need to build it from source instead of installing the https://download.openmmlab.com/mmcv/dist/cu117/torch1.13.0/mmcv_full-1.7.0-cp39-cp39-manylinux1_x86_64.whl

**Comment by wqh17101** [comment]
@zhouzaida When will you release pre-built mmcv-full for torch2.0.0? We really need it .

**Comment by maxpain** [comment]
Any updates?

**Comment by wqh17101** [comment]
@maxpain from https://mmcv.readthedocs.io/en/latest/get_started/installation.html
 `pip install mmcv==2.0.0 -f https://download.openmmlab.com/mmcv/dist/cu118/torch2.0/index.html`

**Comment by maxpain** [comment]
> @maxpain from https://mmcv.readthedocs.io/en/latest/get_started/installation.html
> 
>  `pip install mmcv==2.0.0 -f https://download.openmmlab.com/mmcv/dist/cu118/torch2.0/index.html`

It doesn't work with CUDA 12

**Comment by bigmover** [comment]
> pip install mmcv==2.0.0 -f https://download.openmmlab.com/mmcv/dist/cu118/torch2.0/index.html

Hi guys! @maxpain Ever been in this situation?
torch==2.0.0 torchvision==0.15.1 torchaudio==2.0.1 and mmcv==2.0.0 with multiThreading call will freeze the GPU when GPU utilization reaches 100%
