### ISSUE TITLE
您好，想from mmcv import Config，但是会报错

### ISSUE THREAD

**Issue by funwong** [open-mmlab/mmcv#2757]
![屏幕截图 2023-04-12 172010](https://user-images.githubusercontent.com/113315791/231414191-52da7b64-5304-40ec-9ad8-dde718740207.png)
![屏幕截图 2023-04-12 172116](https://user-images.githubusercontent.com/113315791/231414207-15820e0c-6d57-47c8-bf28-1e1dd83b44eb.png)

**Comment by zhouzaida** [comment]
您好，从 MMCV 2.0.0 开始，Config 等一些训练相关的模块会被删除，详情见https://github.com/open-mmlab/mmcv/blob/main/docs/zh_cn/compatibility.md#v200。

如果您是 OpenMMLab 的新用户，强烈推荐您使用 MMEngine 中的 Config (https://github.com/open-mmlab/mmengine)。

- 安装 MMEngine

```bash
pip install openmim
mim install mmengine
```

- 使用 MMEngine 中的 Config

```python
# Config 的使用教程可阅读 https://mmengine.readthedocs.io/zh_CN/latest/advanced_tutorials/config.html
from mmengine.config import Config
```

如果您是 OpenMMLab 的旧用户，仍然希望使用 MMCV 中的 Config，可以降低 MMCV 的版本

- 安装低版本的 MMCV

```bash
pip install openmim
mim install "mmcv-full<2.0.0"
```

- 使用 MMCV 中的 Config

```python
# https://mmcv.readthedocs.io/zh_CN/1.x/
from mmcv import Config
```

**Comment by VLadImirluren** [comment]
> https://github.com/open-mmlab/mmengine)。

你好，config的import问题很好的解决了，但是我的from mmcv import DictAction失败请问有什么解决办法吗？

非常感谢

**Comment by mantou-yyds** [comment]
@VLadImirluren 我也有同样的问题，请问解决了吗？

**Comment by VLadImirluren** [comment]
> @VLadImirluren 我也有同样的问题，请问解决了吗？

直接从mmengine import

**Comment by 1chenchen22** [comment]
你好，我这个项目用到了这几个命令from mmcv.parallel import collate, scatter from mmcv import Config, DictAction
from mmcv.runner import get_dist_info, init_dist现在我已经按照上面说的方法可以成功导入，这几个命令没问题了。
但是from mmcv.parallel import collate, scatter这个出了问题不知道如何解决
我电脑安装了2.1的mmcv，安装成功了，而且因为cuda版本只能安装2.1的mmcv，所以想问问旧版本的from mmcv.parallel import collate, scatter导入的这个命令，要如何在2.1中使用吗，
so I would like to ask how to use the command imported from mmcv.parallel import collate, scatter in mmcv 2.1.

**Comment by xyb1314** [comment]
![image](https://github.com/open-mmlab/mmcv/assets/65058409/71780b03-a2fd-4f2a-8726-f90f0b8e624f)
is it a module called init_dist in runner ? i am so confused

**Comment by tingxueronghua** [comment]
万恶之源，不知道那个大聪明想出来的。。。
