### ISSUE TITLE
Failed to build wheel for mmcv-full

### ISSUE THREAD

**Issue by MABatin** [open-mmlab/mmcv#2759]
Thanks for reporting the unexpected results and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmcv.readthedocs.io/en/latest/trouble_shooting.html) but cannot get the expected help.
3. The unexpected results still exist in the latest version.

**Describe the Issue**
When trying to install mmcv-full==1.4.2 using pip, I get the following error.

**Reproduction**

1. What command, code, or script did you run?

```bash
pip install mmcv-full==1.4.2
```

2. Did you make any modifications on the code? Did you understand what you have modified?
- No modification done

**Environment**

1. Please run `python -c "from mmcv.utils import collect_env; print(collect_env())"` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\] - ```pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio==0.11.0 --extra-index-url https://download.pytorch.org/whl/cu113```

   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)
```      
export PATH=/usr/local/cuda/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
export CUDA_HOME=/usr/local/cuda
```

**Error traceback**
If applicable, paste the error traceback here.

```none
./mmcv/ops/csrc/pytorch/cuda/psamask_cuda.cu:5:10: fatal error: THC/THC.h: No such file or directory
      5 | #include <THC/THC.h>
        |          ^~~~~~~~~~~
  compilation terminated.
  error: command '/usr/local/cuda/bin/nvcc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for mmcv-full
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by zhouzaida** [comment]
Hi @MABatin , you could use the pre-built packages provided by us.

```bash
pip install -U openmim
mim install mmcv-full==1.4.2
```

The error you reported is caused by the upgrade of torch.
