### ISSUE TITLE
ModuleNotFoundError: No module named 'mmcv.parallel'

### ISSUE THREAD

**Issue by Liqq1** [open-mmlab/mmcv#2761]
您好, 我的程序中涉及：
```
from mmcv.parallel import MMDataParallel, MMDistributedDataParallel
```
但出现以下错误：
```
ModuleNotFoundError: No module named 'mmcv.parallel'
```

我的版本为：
```
mmcv                2.0.0rc4
mmengine            0.7.2
mmsegmentation      1.0.0
torch               1.12.1+cu113
torchaudio          0.12.1+cu113
torchvision         0.13.1+cu113
```

**Comment by winnieepooh** [comment]
同样的问题，请问您解决了吗

**Comment by Liqq1** [comment]
> 同样的问题，请问您解决了吗

你好，我暂时“解决”了(因为我还是没找到最新版的mmcv的parallel变为什么了，我降低了版本)；我现在的版本为：
```
torch               1.8.1+cu101
torchaudio          0.8.1
torchvision         0.9.1+cu101

mmcv-full           1.4.0
mmengine            0.7.2
mmsegmentation      0.14.0
```
我的安装命令为：
```
pip install mmcv-full==1.4.0 -f https://download.openmmlab.com/mmcv/dist/cu112/torch1.6.0/index.html
```

```
pip install torch==1.8.1+cu101 torchvision==0.9.1+cu101 torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html
```

引起上述问题的原因见：https://mmcv.readthedocs.io/en/latest/compatibility.html

<img width="799" alt="image" src="https://user-images.githubusercontent.com/54054113/232287899-63d5af84-2575-4102-9435-1350273a454d.png">
<img width="789" alt="image" src="https://user-images.githubusercontent.com/54054113/232287913-20257f10-b2cc-4af7-b7f0-22109eff63b3.png">

**Comment by zhouzaida** [comment]
Hi, the parallel has been removed from MMCV since v2.0.0. More details can be found at https://github.com/open-mmlab/mmcv/blob/main/docs/en/compatibility.md#v200.

**Comment by Liqq1** [comment]
那在v2.0.0中怎么使用parallel包中的相关内容呢？例如， MMDataParallel, MMDistributedDataParallel

**Comment by MartinYYYYan** [comment]
同问，
那在v2.0.0中怎么使用parallel包中的相关内容呢？例如， MMDataParallel, MMDistributedDataParallel

**Comment by T0L0ve** [comment]
+1

**Comment by SimLuo2014** [comment]
+1

**Comment by micklexqg** [comment]
同问，
既然删了，那在v2.0.0中怎么使用parallel呢？

**Comment by zhouzaida** [comment]
Hi, the `MMDistributedDataParallel` in MMCV has been migrated to MMEngine (https://github.com/open-mmlab/mmengine/blob/426a565908e47f791938baa3a876a87de306b436/mmengine/model/wrappers/distributed.py#L16).

If the distributed environment is initialized (see https://mmengine.readthedocs.io/en/latest/common_usage/speed_up_training.html#distributed-training for details about how to launch distributed training), the `MMDistributedDataParallel` will be automatically wrapped for the model.

The logic to wrapper the model is in https://github.com/open-mmlab/mmengine/blob/426a565908e47f791938baa3a876a87de306b436/mmengine/runner/runner.py#L408.

Of course, we can pass the `model_wrapper_cfg` to the `cfg` of `Runner` in MMEngine.

```python
runner = Runner(
    model=ResNet18(),
    work_dir='./work_dir',
    train_dataloader=train_dataloader_cfg,
    optim_wrapper=dict(
        type='AmpOptimWrapper',
        # If you want to use bfloat16, uncomment the following line
        # dtype='bfloat16',  # valid values: ('float16', 'bfloat16', None)
        optimizer=dict(type='SGD', lr=0.001, momentum=0.9)),
    train_cfg=dict(by_epoch=True, max_epochs=3),
    cfg=dict(model_wrapper_cfg=dict(type=MMDistributedDataParallel),
)
runner.train()
```

In addition, we also provide several documentation to help migration. https://mmengine.readthedocs.io/en/latest/migration/runner.html

**Comment by garychan22** [comment]
> mmsegmentation

so where to remove? I have not found an easy way to transfer the code in older version to latest version when the code using

```
from mmcv.parallel import MMDataParallel, DataContainer, collate
model = MMDataParallel(model, device_ids=[0])
```

**Comment by garychan22** [comment]
> Hi, the parallel has been removed from MMCV since v2.0.0. More details can be found at https://github.com/open-mmlab/mmcv/blob/main/docs/en/compatibility.md#v200.

so where to move? I have not found an easy way to transfer the code in older version to latest version when the code using

```
from mmcv.parallel import MMDataParallel, DataContainer, collate
model = MMDataParallel(model, device_ids=[0])
```

**Comment by TMaysGGS** [comment]
> > Hi, the parallel has been removed from MMCV since v2.0.0. More details can be found at https://github.com/open-mmlab/mmcv/blob/main/docs/en/compatibility.md#v200.
> 
> so where to move? I have not found an easy way to transfer the code in older version to latest version when the code using
> 
> ```
> from mmcv.parallel import MMDataParallel, DataContainer, collate
> model = MMDataParallel(model, device_ids=[0])
> ```

I have the same question like this. I searched the repo open-mmlab/mmengine for like "MMDataParallel" and was not able to find a substitute function for mmcv.parallel.MMDataParallel.

**Comment by cr7Alex** [comment]
+1

**Comment by ghazalmatt3r** [comment]
+1

**Comment by kcqniov** [comment]
from mmcv.parallel import MMDataParallel, MMDistributedDataParallel     in older versions
from mmengine.model import MMDataParallel, MMDistributedDataParallel    in new versions

**Comment by aganji2** [comment]
> from mmcv.parallel import MMDataParallel, MMDistributedDataParallel in older versions from mmengine.model import MMDataParallel, MMDistributedDataParallel in new versions

Hi, I used: from mmengine.model import MMDataParallel, MMDistributedDataParallel

it works for MMDistributedDataParallel but for MMDataParallel we have this problem:

from mmengine.model import MMDataParallel, MMDistributedDataParallel
Traceback (most recent call last):
File "", line 1, in
ImportError: cannot import name 'MMDataParallel'

**Comment by henryone0910** [comment]
+1

> > from mmcv.parallel import MMDataParallel, MMDistributedDataParallel in older versions from mmengine.model import MMDataParallel, MMDistributedDataParallel in new versions
> 
> Hi, I used: from mmengine.model import MMDataParallel, MMDistributedDataParallel
> 
> it works for MMDistributedDataParallel but for MMDataParallel we have this problem:
> 
> from mmengine.model import MMDataParallel, MMDistributedDataParallel Traceback (most recent call last): File "", line 1, in ImportError: cannot import name 'MMDataParallel'

**Comment by zhouzaida** [comment]
Hi @aganji2 and @henryone0910 , `MMDataParallel` is not supported in `mmengine`. It is recommended to use `MMDistributedDataParallel` which has better performance.

**Comment by fuzio35** [comment]
开发板上跑mmcv是真的折磨，版本就那几个还得来回对齐

**Comment by aA13142968398** [comment]
> 同样的问题，请问您解决了吗
pip install mmcv==1.4.0 -f https://download.openmmlab.com/mmcv/dist/cu118/torch2.0/index.html -i https://pypi.tuna.tsinghua.edu.cn/simple
这样子，就可以了

**Comment by ops120** [comment]
> pip install mmcv==1.4.0 -f https://download.openmmlab.com/mmcv/dist/cu118/torch2.0/index.html -i https://pypi.tuna.tsinghua.edu.cn/simple

帮到了1年以后的人
