### ISSUE TITLE
from mmcv.runner import load_checkpoint ModuleNotFoundError: No module named 'mmcv.runner'

### ISSUE THREAD

**Issue by HUST20203505** [open-mmlab/mmcv#2762]
Hi,
I met the error when I run the code
from mmcv.runner import load_checkpoint
ModuleNotFoundError: No module named 'mmcv.runner'

**Comment by winnieepooh** [comment]
同样的问题，请问您解决了吗

**Comment by zhc9** [comment]
我也遇到了同样的问题，解决了能告诉我下吗，windows系统，python版本3.9.2，pytorch版本1.9.0，cuda版本1.1.1，torchvision版本0.10.0

**Comment by zeyuanyin** [comment]
same issue

**Comment by zhouzaida** [comment]
Hi, the Runner has been removed from MMCV since v2.0.0. More details can be found at https://github.com/open-mmlab/mmcv/blob/main/docs/en/compatibility.md#v200.

**Comment by AIBUWAN** [comment]
mmcv2.0.0中去掉了mmcv.runner, 可以用`mim install mmcv-full`安装mmcv 1.7.1 版本就可以了

**Comment by jsxyhelu** [comment]
from mmengine.runner import load_checkpoint

**Comment by aspnetcs** [comment]
mim install mmcv-full==1.2 -i https://pypi.douban.com/simple

**Comment by sidiangongyuan** [comment]
> Hi, the Runner has been removed from MMCV since v2.0.0. More details can be found at https://github.com/open-mmlab/mmcv/blob/main/docs/en/compatibility.md#v200.

Have any replace function?

**Comment by aspnetcs** [comment]
就这些吧，你研究公式检测吗？













--




在 2023-09-14 13:32:41，"karl_yk" ***@***.***> 写道：

Hi, the Runner has been removed from MMCV since v2.0.0. More details can be found at https://github.com/open-mmlab/mmcv/blob/main/docs/en/compatibility.md#v200.

Have any replace function?

**Comment by sidiangongyuan** [comment]
我要导入模块
from mmcv.cnn.bricks.registry import (ATTENTION,
                                      TRANSFORMER_LAYER,
                                      TRANSFORMER_LAYER_SEQUENCE)
  但是找到bricks这个模块。

**Comment by aspnetcs** [comment]
我加你微信













--




在 2023-09-14 15:31:56，"karl_yk" ***@***.***> 写道：

我要导入模块
from mmcv.cnn.bricks.registry import (ATTENTION,
TRANSFORMER_LAYER,
TRANSFORMER_LAYER_SEQUENCE)
但是找到bricks这个模块。

**Comment by sidiangongyuan** [comment]
已经解决了，多谢

**Comment by hoseinCode** [comment]
> > Hi, the Runner has been removed from MMCV since v2.0.0. More details can be found at https://github.com/open-mmlab/mmcv/blob/main/docs/en/compatibility.md#v200.
> 
> Have any replace function?

i have same error: no module named 'mmcv.runner'. please introduce me replace function

**Comment by aspnetcs** [comment]
怎么解决的?













--




在 2023-09-15 18:49:45，"karl_yk" ***@***.***> 写道：

已经解决了，多谢

**Comment by sidiangongyuan** [comment]
> > > Hi, the Runner has been removed from MMCV since v2.0.0. More details can be found at https://github.com/open-mmlab/mmcv/blob/main/docs/en/compatibility.md#v200.
> > 
> > 
> > Have any replace function?
> 
> i have same error: no module named 'mmcv.runner'. please introduce me replace function

It has been removed to the mmengine package.  So you can research it.

**Comment by sidiangongyuan** [comment]
> 怎么解决的?
> […](#)
> -- 在 2023-09-15 18:49:45，"karl_yk" ***@***.***> 写道： 已经解决了，多谢 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

我是混合精度相关的，但是在2.x  mmcv这个包已经没有这个了。我直接给删了 没什么影响

**Comment by aspnetcs** [comment]
谢谢













--




在 2023-09-17 10:39:04，"karl_yk" ***@***.***> 写道：

怎么解决的?
…
-- 在 2023-09-15 18:49:45，"karl_yk" @.> 写道： 已经解决了，多谢 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.>

我是混合精度相关的，但是在2.x mmcv这个包已经没有这个了。我直接给删了 没什么影响

**Comment by aspnetcs** [comment]
It has been removed to the mmengine package. So you can research it.
我是混合精度相关的，但是在2.x mmcv这个包已经没有这个了。我直接给删了 没什么影响













--




At 2023-09-15 19:46:10, "seyed hosein alhoseiny" ***@***.***> wrote:

Hi, the Runner has been removed from MMCV since v2.0.0. More details can be found at https://github.com/open-mmlab/mmcv/blob/main/docs/en/compatibility.md#v200.

Have any replace function?

i have same error: no module named 'mmcv.runner'. please introduce me replace function
