### ISSUE TITLE
 'FastRCNN is not in the model registry.

### ISSUE THREAD

**Issue by Wangxunhang** [open-mmlab/mmcv#2763]
KeyError: 'FastRCNN is not in the model registry. Please check whether the value of `FastRCNN` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

**Comment by zhouzaida** [comment]
Hi @Wangxunhang , you can open an issue in [mmdet](https://github.com/open-mmlab/mmdetection/issues).
