### ISSUE TITLE
Error install mmcv with pytorch 1.12 and CUDA 11.4

### ISSUE THREAD

**Issue by dinhthihuyen** [open-mmlab/mmcv#2798]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmcv/issues) and [Discussions](https://github.com/open-mmlab/mmcv/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmcv).

### Environment

I use conda to install mmcv:
CUDA: 11.4
pytorch:     1.12.1 cuda112py37h6a44366_201 conda-forge
mmcv-full: 1.6.0    cuda112py37h628c0f8         conda-forge

### Reproduces the problem - code sample

I use conda to install mmcv:
CUDA: 11.4
pytorch:     1.12.1  cuda112py37h6a44366_201 conda-forge
mmcv-full:  1.6.0    cuda112py37h628c0f8          conda-forge
and got error undefined symbol

### Reproduces the problem - command or script

I use conda to install mmcv:
CUDA: 11.4
pytorch:     1.12.1 cuda112py37h6a44366_201 conda-forge
mmcv-full: 1.6.0    cuda112py37h628c0f8         conda-forge
and got error undefined symbol

### Reproduces the problem - error message

I got error mmcv/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNK3c1010TensorImpl36is_congituous_nondefault_polity_implENX_12MemoryFormatE

**Comment by zhouzaida** [comment]
Hi @dinhthihuyen , because PyTorch does not provide a pre-compiled package for cuda11.4, we do not provide one either, so you can install it from source (https://mmcv.readthedocs.io/en/1.x/get_started/build.html#build-on-linux). Since you may need to install **mmcv1.6.0**, you will need to checkout into that branch.
