### ISSUE TITLE
error install mmcv

### ISSUE THREAD

**Issue by harborsarah** [open-mmlab/mmcv#2804]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmcv/issues) and [Discussions](https://github.com/open-mmlab/mmcv/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmcv).

### Environment

I am running the code on Linux and the Cuda module is already loaded, version 10.2
pip install torch==1.9.0
pip install torchvision==0.10.0
pip install mmcv==1.3.17 -f https://download.openmmlab.com/mmcv/dist/cu102/torch1.9/index.html

### Reproduces the problem - code sample

python check_installation.py

### Reproduces the problem - command or script

when the installation is finished, I run check_installations.py and still give GPU is not supported error
RuntimeError: Not compiled with GPU support

### Reproduces the problem - error message

Since i am running on Linux/Unix, I load cuda with module load cuda/10.2
before i install mmcv-full, i check cuda version with: nvcc --version, and the result is:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89

Since I read your documentation and i also try with this method:
![image](https://github.com/open-mmlab/mmcv/assets/65909204/5ab54fe2-17e6-4021-a92b-3c9e3605dceb)

but afterwards it still cannot run on GPU.
Do you have any idea of how to solve this? I have been stacked here for several days

Thanks a lot for your help

**Comment by zhouzaida** [comment]
Hi, what is the output of `torch.cuda.is_available()`?

**Comment by harborsarah** [comment]
> 

this is True. Cuda is available

**Comment by harborsarah** [comment]
Hi,

I also would like to ask if it is possible to build the package manually on Linux/Unix rather than using pip install? Since i check the document and in this 'Build on Windows' part, the package is built though: 'python setup.py build_ext & python setup.py develop'. I would like to know is this can also be the way building the package on Linux?

I also tried this method but the build_ext is done really fast and i think it is not really working. Because after i install the package and run check_installation,py,  “No module named ‘mmcv._ext’ this error pops up.

**Comment by zhouzaida** [comment]
Hi, mmcv can be installed from source.

```bash
# If you want to install mmcv < 2.0.0
git clone https://github.com/open-mmlab/mmcv.git
cd mmcv
git checkout 1.x
MMCV_WITH_OPS=1 pip install -e . -v
```

**Comment by Natotela** [comment]
> Hi, mmcv can be installed from source.
> 
> ```shell
> # If you want to install mmcv < 2.0.0
> git clone https://github.com/open-mmlab/mmcv.git
> cd mmcv
> git checkout 1.x
> MMCV_WITH_OPS=1 pip install -e . -v
> ```

10Q my redeemer!

**Comment by RubiaCx** [comment]
It works! Thanks a lot~ 
`
python -m pip uninstall mmcv
python -m pip install -r requirements.txt
MMCV_WITH_OPS=1 python -m pip install -e . -v
python .dev_scripts/check_installation.py
`
