### ISSUE TITLE
[Bug] from mmdet.datasets import build_dataset  ImportError: cannot import name 'build_dataset' from 'mmdet.datasets' 

### ISSUE THREAD

**Issue by HLH13297997663** [open-mmlab/mmcv#2861]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmcv/issues) and [Discussions](https://github.com/open-mmlab/mmcv/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmcv).

### Environment

python3.7

### Reproduces the problem - code sample

python -c "from mmdet.datasets import build_dataset"

### Reproduces the problem - command or script

None

### Reproduces the problem - error message

ImportError: cannot import name 'build_dataset' from 'mmdet.datasets' (/home/hlh/.local/lib/python3.7/site-packages/mmdet/datasets/__init__.py)

### Additional information

None

**Comment by zhouzaida** [comment]
What is your mmdet version?
