### ISSUE TITLE
使用mim install mmcv-full报错

### ISSUE THREAD

**Issue by billfjj** [open-mmlab/mmcv#2863]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmcv/issues) and [Discussions](https://github.com/open-mmlab/mmcv/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmcv).

### Environment

pytorch的安装方法：
conda install pytorch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 pytorch-cuda=11.7 -c pytorch -c nvidia

### Reproduces the problem - code sample

(mmrotate) E:\PycharmProjects\mmrotate>mim install mmcv-full  
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Looking in links: https://download.openmmlab.com/mmcv/dist/cu117/torch1.13.0/index.html
Collecting mmcv-full
  Using cached https://download.openmmlab.com/mmcv/dist/cu117/torch1.13.0/mmcv_full-1.7.1-cp38-cp38-win_amd64.whl (14.8 MB)
Collecting addict (from mmcv-full)
  ERROR: HTTP error 403 while getting https://pypi.tuna.tsinghua.edu.cn/packages/6a/00/b08f23b7d7e1e14ce01419a467b583edbb93c6cdb8654e54a9cc579cd61f/addict-2.4.0-py3-none-any.whl#sha256=249bb56bbfd3cdc2a004ea0ff4c2b6ddc84d53bc2194761
636eb314d5cfa5dfc (from https://pypi.tuna.tsinghua.edu.cn/simple/addict/)
ERROR: Could not install requirement addict from https://pypi.tuna.tsinghua.edu.cn/packages/6a/00/b08f23b7d7e1e14ce01419a467b583edbb93c6cdb8654e54a9cc579cd61f/addict-2.4.0-py3-none-any.whl#sha256=249bb56bbfd3cdc2a004ea0ff4c2b6ddc84d
53bc2194761636eb314d5cfa5dfc (from mmcv-full) because of HTTP error 403 Client Error: Forbidden for url: https://pypi.tuna.tsinghua.edu.cn/packages/6a/00/b08f23b7d7e1e14ce01419a467b583edbb93c6cdb8654e54a9cc579cd61f/addict-2.4.0-py3-
none-any.whl for URL https://pypi.tuna.tsinghua.edu.cn/packages/6a/00/b08f23b7d7e1e14ce01419a467b583edbb93c6cdb8654e54a9cc579cd61f/addict-2.4.0-py3-none-any.whl#sha256=249bb56bbfd3cdc2a004ea0ff4c2b6ddc84d53bc2194761636eb314d5cfa5dfc
 (from https://pypi.tuna.tsinghua.edu.cn/simple/addict/)

### Reproduces the problem - command or script

请求被拒绝

### Reproduces the problem - error message

 ERROR: HTTP error 403 while getting https://pypi.tuna.tsinghua.edu.cn/packages/6a/00/b08f23b7d7e1e14ce01419a467b583edbb93c6cdb8654e54a9cc579cd61f/addict-2.4.0-py3-none-any.whl#sha256=249bb56bbfd3cdc2a004ea0ff4c2b6ddc84d53bc2194761
636eb314d5cfa5dfc (from https://pypi.tuna.tsinghua.edu.cn/simple/addict/)
ERROR: Could not install requirement addict from https://pypi.tuna.tsinghua.edu.cn/packages/6a/00/b08f23b7d7e1e14ce01419a467b583edbb93c6cdb8654e54a9cc579cd61f/addict-2.4.0-py3-none-any.whl#sha256=249bb56bbfd3cdc2a004ea0ff4c2b6ddc84d
53bc2194761636eb314d5cfa5dfc (from mmcv-full) because of HTTP error 403 Client Error: Forbidden for url: https://pypi.tuna.tsinghua.edu.cn/packages/6a/00/b08f23b7d7e1e14ce01419a467b583edbb93c6cdb8654e54a9cc579cd61f/addict-2.4.0-py3-
none-any.whl for URL https://pypi.tuna.tsinghua.edu.cn/packages/6a/00/b08f23b7d7e1e14ce01419a467b583edbb93c6cdb8654e54a9cc579cd61f/addict-2.4.0-py3-none-any.whl#sha256=249bb56bbfd3cdc2a004ea0ff4c2b6ddc84d53bc2194761636eb314d5cfa5dfc
 (from https://pypi.tuna.tsinghua.edu.cn/simple/addict/)

**Comment by zhouzaida** [comment]
可以试试把 pypi 清华源换成其他的源

**Comment by billfjj** [comment]
> 可以试试把 pypi 清华源换成其他的源

确实是源的问题，谢谢大佬
