### ISSUE TITLE
Do you know why you don't like to use your library, there are too many versions and too mixed, and the front and back are incompatible, plus other supporting mm series, for anyone to install your library is to find guilt[Feature] 

### ISSUE THREAD

**Issue by wangxiaochun520** [open-mmlab/mmcv#2902]
### What is the feature?

**Do you know why you don't like to use your library, there are too many versions and too mixed, and the front and back are incompatible, plus other supporting mm series, for anyone to install your library is to find guilt**

**Comment by zhouzaida** [comment]
We provide the tool `openmim` which can install any OpenMMLab repos in one line.
