### ISSUE TITLE
Check `None` when merging dict

### ISSUE THREAD

**Issue by JoannaLXY** [open-mmlab/mmcv#292]
In this function, is there any chance that values in `a`  is `None`? Here if `None` means uninitialized, so it may cause an error when merging the two dicts.
Maybe add a checking before merging and skip the `None` values?

https://github.com/open-mmlab/mmcv/blob/7f80a2c6b9c7f994b9420e72b32f84a0283e4e05/mmcv/utils/config.py#L145-L161

Similar problem in function `merge_from_dict`.

**Comment by xvjiarui** [comment]
Hi @JoannaLXY 
If a value is `None` but not a `dict`, then only replacement should happen. Only `dict` could be merged. 
Or could you please provide an example of your use case?

**Comment by JoannaLXY** [comment]
@xvjiarui Thanks for the explanation. In my case, I do not want to replace the original value if a value is `None`. For example, 
```python
#  output_config from args.out
a = dict(out=args.out)
# output_config from cfg file,  e.g. output_config = dict(out='result.json')
b = cfg.get('output_config', {})
c = _merge_a_into_b(a, b)
```
Here, in this case, `a` and `b` are two configs, `a` has a higher priority than `b`, but when `args.out` is not initialized, its default value is None, then I would like to keep the value in `b` if the incoming value is `None`. 
In fact, this may lead to misunderstanding and require clear specification on whether `None` means uninitialized or unset. If we denote `None` as uninitialized, then we should skip `None` value; if we denote `None` as a value that means unset, then replacement should happen.
