### ISSUE TITLE
[Docs] mim install mmcv failed

### ISSUE THREAD

**Issue by MengZhen-Chi** [open-mmlab/mmcv#2920]
### 📚 The doc issue

when I use "mim install mmcv",  I meet the error:
[WARNING:] Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f85d5f93b80>, 'Connection to download.openmmlab.com timed out. (connect timeout=15)')': /mmcv/dist/cu116/torch1.12.0/index.html

**Comment by zhouzaida** [comment]
Hi, could your machine connect to the internet?

**Comment by MengZhen-Chi** [comment]
> Hi, could your machine connect to the internet?

may be the connection has some problems, I have installed the mmcv by building mmcv from source

**Comment by puranjay123** [comment]
I am not able to install mmcv as well even the `pip install mmcv` is not working
![image](https://github.com/open-mmlab/mmcv/assets/55429956/006f1b58-51ed-4858-9bd8-4e35d2c4d430)

**Comment by MengZhen-Chi** [comment]
> I am not able to install mmcv as well even the `pip install mmcv` is not working ![image](https://user-images.githubusercontent.com/55429956/265994882-006f1b58-51ed-4858-9bd8-4e35d2c4d430.png) Opening a new issue for the same

may be you can try "mim install mmcv" after you download mim command
