### ISSUE TITLE
[Docs] 

### ISSUE THREAD

**Issue by chuanchengh** [open-mmlab/mmcv#2961]
### 📚 The doc issue

May I ask how many versions of 'mmcv' need to be downloaded? The prompt for me to download 2.0.0 is that I cannot use 'Config' and 'DictAction', as well as' mmcv. parallel 'and' mmcv. runner '

**Comment by fanqiNO1** [comment]
If you want to use `Config`, `DictAction`, `mmcv.parallel` and `mmcv.runner` in mmcv, you can try to download the version v1.7.1
