### ISSUE TITLE
[Bug]     raise KeyError( KeyError: 'Mymodel is not in the detector registry'

### ISSUE THREAD

**Issue by cqray1990** [open-mmlab/mmcv#2975]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmcv/issues) and [Discussions](https://github.com/open-mmlab/mmcv/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmcv).

### Environment

mmcv 1.4.0
mmdet 2.11
pytorch 1.13.1

### Reproduces the problem - code sample

customer model is not in the detector registry, i define the model as follow,but raise KeyError( KeyError: 'Mymodel is not in the detector registry'

@DETECTORS.register_module()
class mymodel(TwoStageDetector):
        pass

### Reproduces the problem - command or script

customer model is not in the detector registry, i define the model as follow,but raise KeyError( KeyError: 'Mymodel is not in the detector registry'

@DETECTORS.register_module()
class mymodel(TwoStageDetector):
        pass

### Reproduces the problem - error message

customer model is not in the detector registry, i define the model as follow,but raise KeyError( KeyError: 'Mymodel is not in the detector registry'

@DETECTORS.register_module()
class mymodel(TwoStageDetector):
        pass

**Comment by zhouzaida** [comment]
Hi @cqray1990 , you can find the solution at https://github.com/open-mmlab/mmdetection/issues/5974.
