### ISSUE TITLE
[Docs] 我想知道我是4090显卡，因此mmcv只能安装2.0以上,但是发现这样就没有对应的mmdetection安装了

### ISSUE THREAD

**Issue by sjz-hub** [open-mmlab/mmcv#2990]
### 📚 The doc issue

[Docs] 我想知道我是4090显卡，因此mmcv只能安装2.0以上,但是发现这样就没有对应的mmdetection安装了，请问这个是怎么解决呢，是可以安装更低的mmcv还是说可以下载更高版本的mmdetection

**Comment by zhouzaida** [comment]
请问你的 pytorch 和 cuda 是什么版本，你想安装哪个版本的 mmcv？

**Comment by YANG-CY-163** [comment]
Did you solve it? I also encountered a similar problem, my torch and cuda version is 2.0.0+cu118, I want to install mmcv-full 1.6.0 on 4090 but it fails, is there any way to use mmcv-full 1.6.0 on 4090, or do I must use mmcv 2.x version ?

**Comment by MX-S** [comment]
Hi, have you solved it? I have the same problem as you.
