### ISSUE TITLE
[Google COLAB] --- ERROR: Could not build wheels for mmcv-full, which is required to install pyproject.toml-based projects[Bug] 

### ISSUE THREAD

**Issue by Arslan-Mehmood1** [open-mmlab/mmcv#3001]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmcv/issues) and [Discussions](https://github.com/open-mmlab/mmcv/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmcv).

### Environment

**Runtime : Colab T4 GPU Runtime.**

**Python 3.10.12**

**default packages on colab:**
pytorch and cuda version:
import torch
print(torch.version)
**2.1.0+cu118**

**Installing mmcv-full:**
!pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu118/2.1.0/index.html

### Reproduces the problem - code sample

google colab
**Runtime : Colab T4 GPU Runtime.**

!pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu118/2.1.0/index.html

### Reproduces the problem - command or script

!pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu118/2.1.0/index.html

### Reproduces the problem - error message

!pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu118/2.1.0/index.html

### Additional information

Runtime : Colab T4 GPU Runtime.

Python 3.10.12

default packages on colab:
pytorch and cuda version:
import torch
print(torch.version)
2.1.0+cu118

Installing mmcv-full:
!pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu118/2.1.0/index.html

getting error:

Looking in links: https://download.openmmlab.com/mmcv/dist/cu118/2.1.0/index.html
Collecting mmcv-full
Using cached mmcv-full-1.7.1.tar.gz (605 kB)
Preparing metadata (setup.py) ... done
Collecting addict (from mmcv-full)
Using cached addict-2.4.0-py3-none-any.whl (3.8 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from mmcv-full) (1.23.5)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from mmcv-full) (23.2)
Requirement already satisfied: Pillow in /usr/local/lib/python3.10/dist-packages (from mmcv-full) (9.4.0)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.10/dist-packages (from mmcv-full) (6.0.1)
Requirement already satisfied: yapf in /usr/local/lib/python3.10/dist-packages (from mmcv-full) (0.40.2)
Requirement already satisfied: importlib-metadata>=6.6.0 in /usr/local/lib/python3.10/dist-packages (from yapf->mmcv-full) (7.0.0)
Requirement already satisfied: platformdirs>=3.5.1 in /usr/local/lib/python3.10/dist-packages (from yapf->mmcv-full) (4.1.0)
Requirement already satisfied: tomli>=2.0.1 in /usr/local/lib/python3.10/dist-packages (from yapf->mmcv-full) (2.0.1)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.10/dist-packages (from importlib-metadata>=6.6.0->yapf->mmcv-full) (3.17.0)
Building wheels for collected packages: mmcv-full
error: subprocess-exited-with-error

× python setup.py bdist_wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Building wheel for mmcv-full (setup.py) ... error
ERROR: Failed building wheel for mmcv-full
Running setup.py clean for mmcv-full
Failed to build mmcv-full
ERROR: Could not build wheels for mmcv-full, which is required to install pyproject.toml-based projects

To reproduce this error:
simply start a t4 gpu colab runtime and execute the !pip install command I'm using above for mmcv-full

**Comment by lanhuiling01** [comment]
I had the same problem, could I ask if you solved it?

**Comment by zhouzaida** [comment]
Hi, the `torch` string should be added in the link like `pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu118/torch2.1.0/index.html`. You can try it again.

**Comment by davehorner** [comment]
I am able to install the above pip mmcv-full command; is there a way I can use that in place of mmcv which I can not get to work because the gcc version on 22.04. gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04)
```
anaconda3/lib/python3.11/site-packages/torch/include/ATen/ATen.h:4:2: error: #error C++17 or later compatible compiler is required to use ATen.
          4 | #error C++17 or later compatible compiler is required to use ATen.
```
I am running cuda 12.3 via wsl.  Ubuntu 22.04.3 LTS

using https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=WSL-Ubuntu&target_version=2.0&target_type=deb_local

I have tried all sorts of things and no luck.

**Comment by zhouzaida** [comment]
> I am able to install the above pip mmcv-full command; is there a way I can use that in place of mmcv which I can not get to work because the gcc version on 22.04. gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04)
> 
> ```
> anaconda3/lib/python3.11/site-packages/torch/include/ATen/ATen.h:4:2: error: #error C++17 or later compatible compiler is required to use ATen.
>           4 | #error C++17 or later compatible compiler is required to use ATen.
> anaconda3/lib/python3.11/site-packages/torch/utils/cpp_extension.py:424: UserWarning: There are no g++ version bounds defined for CUDA version 12.1
>         warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
> ```
> 
> I am running cuda 12.3 via wsl. Ubuntu 22.04.3 LTS
> 
> using https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=WSL-Ubuntu&target_version=2.0&target_type=deb_local
> 
> I have tried all sorts of things and no luck.
> 
> ```
> pip install mmcv -f https://download.openmmlab.com/mmcv/dist/cu118/torch2.1.0/index.html
> ```
> 
> installs fine and the following does not error out.
> 
> ```
> python -c 'import mmcv; import mmcv.ops'
> ```
> 
> but I think I am having issues because the version specified is not installed.
> 
> ```
> mim install -v -e .
> ```
> 
> ```
> Collecting mmcv<2.1.0,>=2.0.0rc4 (from mmyolo==0.6.0)
>   Using cached mmcv-2.0.1.tar.gz (469 kB)
>   Running command python setup.py egg_info
> ```
> 
> I can provide the full output if that helps. heres the whl install attempt.
> 
> ```
>  pip install mmcv-2.0.0-cp38-cp38-manylinux1_x86_64.whl
> ERROR: mmcv-2.0.0-cp38-cp38-manylinux1_x86_64.whl is not a supported wheel on this platform.
> `
> ```

Could you provide the output of `torch.version.cuda`?

**Comment by davehorner** [comment]
```
>>> import torch
>>> torch.version.cuda
'12.1'
```

**Comment by zhouzaida** [comment]
> pip install mmcv -f https://download.openmmlab.com/mmcv/dist/cu118/torch2.1.0/index.html

You could install mmcv with `pip install mmcv -f https://download.openmmlab.com/mmcv/dist/cu121/torch2.1.0/index.html`

**Comment by davehorner** [comment]
```
pip install mmcv -f https://download.openmmlab.com/mmcv/dist/cu121/torch2.1.0/index.html
```
seems to work.
```
Requirement already satisfied: mmcv in /home/dhorner/anaconda3/lib/python3.11/site-packages (2.1.0)
```

`mim install -v -e .` still tries to compile the dependency.

**Comment by 18780165950** [comment]
@zhouzaida  i 

> > pip install mmcv -f https://download.openmmlab.com/mmcv/dist/cu118/torch2.1.0/index.html
> 
> You could install mmcv with `pip install mmcv -f https://download.openmmlab.com/mmcv/dist/cu121/torch2.1.0/index.html`

After I excute the command, MMCV==2.2.0 is installed to my machine by default， but I get following error:
AssertionError: MMCV==2.2.0 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.1.0，   
how to specify the version of mmcv to install?

**Comment by userwatch** [comment]
Hello @zhouzaida same error, Did you solved? import mmseg
print(mmseg.__version__)  AssertionError: MMCV==2.2.0 is used but incompatible. Please install mmcv>=2.0.0rc4.

**Comment by 18780165950** [comment]
您好，您发的邮件我已收到，我尽快给您回复。

**Comment by userwatch** [comment]
@18780165950 Thank you very much.

**Comment by gracyashhh** [comment]
@zhouzaida Thanks pip install mmcv -f https://download.openmmlab.com/mmcv/dist/cu121/torch2.1.0/index.html works, but my issue with mmcv for my project on colab is 
MMCV==2.2.0 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.2.0. 
can you please help with getting this exact version, every other pip command runs but never ends. Thanks in advance :)

**Comment by 18780165950** [comment]
您好，您发的邮件我已收到，我尽快给您回复。
