### ISSUE TITLE
Error when running pip install: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

### ISSUE THREAD

**Issue by moha23** [open-mmlab/mmcv#302]
**Command I ran:**

pip install --user --proxy=http://proxyserver mmcv==0.4.4

**Error:**

ERROR: Command errored out with exit status 1:
     command: /home/s18002/anaconda3/envs/my_env/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bs9m80ii/mmcv/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bs9m80ii/mmcv/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-bs9m80ii/mmcv/pip-egg-info
         cwd: /tmp/pip-install-bs9m80ii/mmcv/
    Complete output (33 lines):
    WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fe96fca6250>: Failed to establish a new connection: [Errno 113] No route to host')': /simple/numpy/
    WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fe96fca6c90>: Failed to establish a new connection: [Errno 113] No route to host')': /simple/numpy/
    WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fe96fc84f90>: Failed to establish a new connection: [Errno 113] No route to host')': /simple/numpy/
    WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fe96fc8e310>: Failed to establish a new connection: [Errno 113] No route to host')': /simple/numpy/
    WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fe96fc8ec10>: Failed to establish a new connection: [Errno 113] No route to host')': /simple/numpy/
    ERROR: Could not find a version that satisfies the requirement numpy>=1.11.1 (from versions: none)
    ERROR: No matching distribution found for numpy>=1.11.1
    Traceback (most recent call last):
      File "/home/s18002/anaconda3/envs/my_env/lib/python3.7/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/home/s18002/anaconda3/envs/my_env/lib/python3.7/subprocess.py", line 363, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/home/s18002/anaconda3/envs/dense_matching_benchmark/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpaz5otv11', '--quiet', 'numpy>=1.11.1']' returned non-zero exit status 1.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-bs9m80ii/mmcv/setup.py", line 6, in <module>
        dist.Distribution().fetch_build_eggs(['Cython', 'numpy>=1.11.1'])
      File "/home/s18002/anaconda3/envs/my_env/lib/python3.7/site-packages/setuptools/dist.py", line 698, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/s18002/anaconda3/envs/my_env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 783, in resolve
        replace_conflicting=replace_conflicting
      File "/home/s18002/anaconda3/envs/my_env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1066, in best_match
        return self.obtain(req, installer)
      File "/home/s18002/anaconda3/envs/my_env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1078, in obtain
        return installer(requirement)
      File "/home/s18002/anaconda3/envs/my_env/lib/python3.7/site-packages/setuptools/dist.py", line 754, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/home/s18002/anaconda3/envs/my_env/lib/python3.7/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e))
    distutils.errors.DistutilsError: Command '['/home/s18002/anaconda3/envs/my_env/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpaz5otv11', '--quiet', 'numpy>=1.11.1']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by moha23** [comment]
Turns out I just had to install all other dependencies before installing mmcv.

**Comment by oreo-lp** [comment]
> Turns out I just had to install all other dependencies before installing mmcv.

what dependencies have you installed?

**Comment by moha23** [comment]
I don't remember really, haven't used it since, but I would think the `requirements.txt` file should have all the required dependencies.

**Comment by oreo-lp** [comment]
sure, thank you! I have fixed this problem

**Comment by priyarana** [comment]
> sure, thank you! I have fixed this problem

Hi.
I am facing the similar issue, may i know how did u fix yours

**Comment by XInTheDark** [comment]
Facing same error!
