### ISSUE TITLE
mmcv真是问题多多

### ISSUE THREAD

**Issue by PapaMadeleine2022** [open-mmlab/mmcv#3029]
### What is the feature?

mmcv真的是我这么多年中装库，遇到问题比较多的，耗费时间也很多。

**Comment by zhouzaida** [comment]
你好，遇到问题可以反馈。事实上，mim 这个工具是可以帮大家很方便安装 mmcv 的。你可以尝试：

```bash
pip install openmim
mim install mmcv
```

**Comment by psc0606** [comment]
同理，安装mmcv是最痛苦的，每次总安装不过，一堆奇怪问题：
`      /home/work/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/include/c10/core/DispatchKeySet.h:762:52:   in ‘constexpr’ expansion of ‘c10::DispatchKeySet(AutogradPrivateUse1)’
      /home/work/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/include/c10/core/DispatchKeySet.h:236:42:   in ‘constexpr’ expansion of ‘c10::toBackendComponent(k)’
      /home/work/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/include/c10/core/DispatchKeySet.h:762:52: 错误：常量表达式溢出 [-fpermissive]
           DispatchKeySet(DispatchKey::AutogradPrivateUse1);
                                                          ^
      /home/work/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/include/c10/core/DispatchKeySet.h:764:52:   in ‘constexpr’ expansion of ‘c10::DispatchKeySet(AutogradPrivateUse2)’
      /home/work/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/include/c10/core/DispatchKeySet.h:236:42:   in ‘constexpr’ expansion of ‘c10::toBackendComponent(k)’
      /home/work/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/include/c10/core/DispatchKeySet.h:764:52: 错误：常量表达式溢出 [-fpermissive]
           DispatchKeySet(DispatchKey::AutogradPrivateUse2);
                                                          ^
      /home/work/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/include/c10/core/DispatchKeySet.h:766:52:   in ‘constexpr’ expansion of ‘c10::DispatchKeySet(AutogradPrivateUse3)’
      /home/work/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/include/c10/core/DispatchKeySet.h:236:42:   in ‘constexpr’ expansion of ‘c10::toBackendComponent(k)’
      /home/work/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/include/c10/core/DispatchKeySet.h:766:52: 错误：常量表达式溢出 [-fpermissive]
           DispatchKeySet(DispatchKey::AutogradPrivateUse3);
                                                          ^
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mmcv
  Running setup.py clean for mmcv
Failed to build mmcv
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (mmcv)`

**Comment by psc0606** [comment]
gcc 版本 8.5.0 20210514

**Comment by Saunak626** [comment]
> 你好，遇到问题可以反馈。事实上，mim 这个工具是可以帮大家很方便安装 mmcv 的。你可以尝试：
> 
> pip install openmim
> mim install mmcv

一坨狗屎，昧着良心说话
