### ISSUE TITLE
[Bug] undefined symbol: _ZN3c104cuda9SetDeviceEi

### ISSUE THREAD

**Issue by JTShuai** [open-mmlab/mmcv#3060]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmcv/issues) and [Discussions](https://github.com/open-mmlab/mmcv/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmcv).

### Environment

Pytorch and CUDA installed by docker image.
Ubuntu 20.04
CUDA version: 12.1
torch version: 2.1
mmengine version: 0.10.3
mmcv version: 2.1

mmcv installed by `mim install mmcv`

### Reproduces the problem - code sample

Run the official check file [check_installation.py](https://github.com/open-mmlab/mmcv/blob/main/.dev_scripts/check_installation.py)

### Reproduces the problem - command or script

`python check_installation.py`

### Reproduces the problem - error message

Get error:
```
Traceback (most recent call last):
  File "check_instal.py", line 4, in <module>
    from mmcv.ops import box_iou_rotated
  File "/usr/local/lib/python3.8/dist-packages/mmcv/ops/__init__.py", line 3, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "/usr/local/lib/python3.8/dist-packages/mmcv/ops/active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "/usr/local/lib/python3.8/dist-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /usr/local/lib/python3.8/dist-packages/mmcv/_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda9SetDeviceEi
```

**Comment by mortal-Zero** [comment]
Have you solved the problem? I had the same problem with torch2.3.0

**Comment by xmj-7** [comment]
Have you solved the problem? I had the same problem with torch2.1.0 and python3.8
