### ISSUE TITLE
mmcv.Config: obtain wrong value for some specific keys

### ISSUE THREAD

**Issue by ycxioooong** [open-mmlab/mmcv#308]
Hi,

I'm using ``mmcv.Config`` to create my config object.
When I try to get the value of some specific keys, I receive the wrong values.
Here is an example:
```
>>> cfg = mmcv.Config(dict(filename='file.name', ck='hello')
>>> cfg.ck
hello
>>> cfg.filename
None
```

This is caused by https://github.com/open-mmlab/mmcv/blob/master/mmcv/utils/config.py#L200 that the name ``filename`` is preserved as a property of ``Config``.

Since words like ``filename`` and ``text`` are often used as dictionary keys, my suggestion is that we should avoid using these words as the property names of class ``Config``. 
Or at least, would you consider raise an error when a dictionary with keys like ``filename``is passed to ``Config``?

**Comment by xvjiarui** [comment]
Hi @ycxioooong 
Thanks for reporting. I will open a PR to fix this issue.
