### ISSUE TITLE
How can I install mmcv successfully?

### ISSUE THREAD

**Issue by xiebinghua** [open-mmlab/mmcv#332]
I take 'pip3 install mmcv' as input , but I meet warning:
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fbdf53f8f98>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/mmcv/
How can I fix it???

**Comment by hellock** [comment]
You need to check if your network is available.
