### ISSUE TITLE
Suggest to modified the image showing function from cv2 to another

### ISSUE THREAD

**Issue by afunTW** [open-mmlab/mmcv#34]
When I first test the demo code from `mmdetection` on jupyter notebook, it leads to a dead kernel.
https://github.com/open-mmlab/mmdetection#test-images

```python
import mmcv
from mmcv.runner import load_checkpoint
from mmdet.models import build_detector
from mmdet.apis import inference_detector, show_result

cfg = mmcv.Config.fromfile('configs/faster_rcnn_r50_fpn_1x.py')
cfg.model.pretrained = None

# construct the model and load checkpoint
model = build_detector(cfg.model, test_cfg=cfg.test_cfg)
_ = load_checkpoint(model, 'https://s3.ap-northeast-2.amazonaws.com/open-mmlab/mmdetection/models/faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth')

# test a single image
img = mmcv.imread('test.jpg')
result = inference_detector(model, img, cfg)
show_result(img, result)

# test a list of images
imgs = ['test1.jpg', 'test2.jpg']
for i, result in enumerate(inference_detector(model, imgs, cfg, device='cuda:0')):
    print(i, imgs[i])
    show_result(imgs[i], result)
```

and I found that was occurred by `mmcv.visualization.image.imshow_det_bboxes`
https://github.com/open-mmlab/mmcv/blob/master/mmcv/visualization/image.py#L69

default parameter `show=True` will try to render the image on a new window and it will crash the jupyter or the scenario on a server. 

Whould it be better if it returns the image instead of `cv2.imshow` or implements by `plt.imshow` ?

**Comment by hellock** [comment]
We adopt opencv primarily in consideration of efficiency and consistency. It is indeed not friendly to jupyter notebook. You may add several lines of code to display the image in jupyter with matplotlib after plotting with opencv.
