### ISSUE TITLE
can not install mmcv

### ISSUE THREAD

**Issue by khle08** [open-mmlab/mmcv#345]
follow by the document instruction to install mmcv, when running the step:
`sudo CC=clang CXX=clang++ CFLAGS='-stdlib=libc++' pip3 install -e .`

the error goes like this:
`...
    running egg_info
    writing mmcv.egg-info/PKG-INFO
    writing dependency_links to mmcv.egg-info/dependency_links.txt
    writing requirements to mmcv.egg-info/requires.txt
    writing top-level names to mmcv.egg-info/top_level.txt
    reading manifest file 'mmcv.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'mmcv.egg-info/SOURCES.txt'
    creating build/lib.macosx-10.6-intel-3.6/mmcv/model_zoo
    copying mmcv/model_zoo/deprecated.json -> build/lib.macosx-10.6-intel-3.6/mmcv/model_zoo
    copying mmcv/model_zoo/open_mmlab.json -> build/lib.macosx-10.6-intel-3.6/mmcv/model_zoo
    copying mmcv/video/optflow_warp/flow_warp.hpp -> build/lib.macosx-10.6-intel-3.6/mmcv/video/optflow_warp
    copying mmcv/video/optflow_warp/flow_warp_module.pyx -> build/lib.macosx-10.6-intel-3.6/mmcv/video/optflow_warp
    running build_ext
    skipping './mmcv/video/optflow_warp/flow_warp_module.cpp' Cython extension (up-to-date)
    building 'mmcv._ext' extension
    creating build/temp.macosx-10.6-intel-3.6
    creating build/temp.macosx-10.6-intel-3.6/mmcv
    creating build/temp.macosx-10.6-intel-3.6/mmcv/video
    creating build/temp.macosx-10.6-intel-3.6/mmcv/video/optflow_warp
    clang -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -stdlib=libc++ -I/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/core/include -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c ./mmcv/video/optflow_warp/flow_warp.cpp -o build/temp.macosx-10.6-intel-3.6/./mmcv/video/optflow_warp/flow_warp.o -stdlib=libc++
    clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
    error: command 'clang' failed with exit status 1
    
    ----------------------------------------
Command "/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-yivbb22t/mmcv/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-t5jrpwxm-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-yivbb22t/mmcv/`

My system: MacOS 10.13.3
python version: 3.6.2
gcc version: 8.4.0

**Comment by hellock** [comment]
Just `pip install -e .` should be ok.

**Comment by rumusan** [comment]
I encountered the same problem, and solved it via
`export MACOSX_DEPLOYMENT_TARGET=10.10`  https://github.com/wesm/feather/issues/61

**Comment by khle08** [comment]
Thanks. I also tried this command and the error was changed into the other format. I guess mmdetection can only be installed on the device with GPU?

**Comment by hellock** [comment]
It can be installed without GPU. I have tried it on my mac.
