### ISSUE TITLE
The old API of register_module(module, force=False) is deprecated

### ISSUE THREAD

**Issue by strongwolf** [open-mmlab/mmcv#397]
I have updated mmdetection and mmcv to the latest version but this warning still occurs. I don't know which function has triggered this warning. 

The old API of register_module(module, force=False) is deprecated and will be removed, please use the new API register_module(name=None, force=False, module=None) instead.

**Comment by jwwangchn** [comment]
@strongwolf Hi, I meet the same problem, how to solve it?
