### ISSUE TITLE
Where can i get "faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth" file ?

### ISSUE THREAD

**Issue by blackCmd** [open-mmlab/mmcv#412]
I'm trying `Image demo` in "https://mmdetection.readthedocs.io/en/latest/getting_started.html#image-demo".
But i can't find checkpoints directory and files.
How can i get files?

**Comment by anabiasohail** [comment]
You can download the files from following link and can save them in checkpoints folder by creating make new dir 
'https://s3.ap-northeast-2.amazonaws.com/open-mmlab/mmdetection/models/

or you can directly assign the model link to "cfg.load_from"

**Comment by blackCmd** [comment]
> You can download the files from following link and can save them in checkpoints folder by creating make new dir
> 'https://s3.ap-northeast-2.amazonaws.com/open-mmlab/mmdetection/models/
> 
> or you can directly assign the model link to "cfg.load_from"

oh thank you : )

**Comment by blackCmd** [comment]
ㅙ

**Comment by MyraBaba** [comment]
@anabiasohail 

the link gives access denied error
