### ISSUE TITLE
Error when install mmcv-full offline

### ISSUE THREAD

**Issue by WangLibo1995** [open-mmlab/mmcv#417]
/kaggle/working/mmdetv2models/mmcv-master/mmcv-master
Obtaining file:///kaggle/working/mmdetv2models/mmcv-master/mmcv-master
    ERROR: Command errored out with exit status 1:
     command: /opt/conda/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/kaggle/working/mmdetv2models/mmcv-master/mmcv-master/setup.py'"'"'; __file__='"'"'/kaggle/working/mmdetv2models/mmcv-master/mmcv-master/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-2vxgawnq
         cwd: /kaggle/working/mmdetv2models/mmcv-master/mmcv-master/
    Complete output (39 lines):
    Compiling ./mmcv/video/optflow_warp/flow_warp_module.pyx because it changed.
    [1/1] Cythonizing ./mmcv/video/optflow_warp/flow_warp_module.pyx
    WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f41279a8250>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pytest-runner/
    WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4127a6e510>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pytest-runner/
    WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4127a6e7d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pytest-runner/
    WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4127a0ec50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pytest-runner/
    WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4127a0ee10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pytest-runner/
    ERROR: Could not find a version that satisfies the requirement pytest-runner (from versions: none)
    ERROR: No matching distribution found for pytest-runner
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.7/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/opt/conda/lib/python3.7/subprocess.py", line 363, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/opt/conda/bin/python3.7', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmptzxo07k6', '--quiet', 'pytest-runner']' returned non-zero exit status 1.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/kaggle/working/mmdetv2models/mmcv-master/mmcv-master/setup.py", line 219, in <module>
        zip_safe=False)
      File "/opt/conda/lib/python3.7/site-packages/setuptools/__init__.py", line 143, in setup
        _install_setup_requires(attrs)
      File "/opt/conda/lib/python3.7/site-packages/setuptools/__init__.py", line 138, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/opt/conda/lib/python3.7/site-packages/setuptools/dist.py", line 698, in fetch_build_eggs
        replace_conflicting=True,
      File "/opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 783, in resolve
        replace_conflicting=replace_conflicting
      File "/opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1066, in best_match
        return self.obtain(req, installer)
      File "/opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1078, in obtain
        return installer(requirement)
      File "/opt/conda/lib/python3.7/site-packages/setuptools/dist.py", line 754, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/opt/conda/lib/python3.7/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e))
    distutils.errors.DistutilsError: Command '['/opt/conda/bin/python3.7', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmptzxo07k6', '--quiet', 'pytest-runner']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-0808d70d8cf8> in <module>
      1 get_ipython().run_line_magic('cd', '/kaggle/working/mmdetv2models/mmcv-master/mmcv-master')
      2 get_ipython().system(' MMCV_WITH_OPS=1 pip install -e . ')
----> 3 import mmcv

/kaggle/working/mmdetv2models/mmcv-master/mmcv-master/mmcv/__init__.py in <module>
      6 from .utils import *
      7 from .version import __version__
----> 8 from .video import *
      9 from .visualization import *
     10 

/kaggle/working/mmdetv2models/mmcv-master/mmcv-master/mmcv/video/__init__.py in <module>
      1 # Copyright (c) Open-MMLab. All rights reserved.
      2 from .io import Cache, VideoReader, frames2video
----> 3 from .optflow import (dequantize_flow, flow_warp, flowread, flowwrite,
      4                       quantize_flow)
      5 from .processing import concat_video, convert_video, cut_video, resize_video

/kaggle/working/mmdetv2models/mmcv-master/mmcv-master/mmcv/video/optflow.py in <module>
      2 import numpy as np
      3 
----> 4 from mmcv._flow_warp_ext import flow_warp_c
      5 from mmcv.arraymisc import dequantize, quantize
      6 from mmcv.image import imread, imwrite

ModuleNotFoundError: No module named 'mmcv._flow_warp_ext'

I USE:
%cd /kaggle/working/mmdetv2models/mmcv-master/mmcv-master
! MMCV_WITH_OPS=1 pip install -e . 
import mmcv

**Comment by WangLibo1995** [comment]
I fix it by pip install [pytest runner](https://pypi.org/project/pytest-runner/#files)

**Comment by KangolHsu** [comment]
same error in Windows10
