### ISSUE TITLE
Typo in lr update hook

### ISSUE THREAD

**Issue by sandylaker** [open-mmlab/mmcv#423]
Is the class name [CosineAnealingLrUpdaterHook](https://github.com/open-mmlab/mmcv/blob/7cfc839ea5e6f395682f0af6c63f24500437cef5/mmcv/runner/hooks/lr_updater.py#L227) in `lr_updater`  misspelled?
It should be "Annealing", right?

**Comment by hellock** [comment]
Yes! It would be appreciated if you would like to open a PR to fix it.
