### ISSUE TITLE
Can not install pavi by "pip install pavi"

### ISSUE THREAD

**Issue by facetohard** [open-mmlab/mmcv#425]
When I used `PaviLoggerHook` in log_config, it has thrown out an error about `ModuleNotFoundError: No module named 'pavi'`. 
I have tried to install this package by `pip install pavi` but it failed.

**Comment by hellock** [comment]
This module is only for internal use.

**Comment by facetohard** [comment]
Thanks. May be noting this [here](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/logger/pavi.py#L56) is a good choice.

**Comment by zhao181** [comment]
I have a problem saying:
  File "/mnt/a/sublinux/software/mmcv/mmcv/runner/hooks/logger/pavi.py", line 60, in before_run
    raise ImportError('Please run "pip install pavi" to install pavi.')
ImportError: Please run "pip install pavi" to install pavi.
