### ISSUE TITLE
cannot import name 'Config' from 'mmcv' 

### ISSUE THREAD

**Issue by Euphoria16** [open-mmlab/mmcv#439]
Hello,
I met the error when I run the code train.py, and couldn't import the 'Config':
from mmcv import Config
ImportError: cannot import name 'Config' from 'mmcv' (unknown location)

I am using mmcv 0.2.16

**Comment by hellock** [comment]
I cannot reproduce the error. I install mmcv 0.2.16 and `from mmcv import Config` works well.

**Comment by Euphoria16** [comment]
Thank you very much for the reply. I reinstalled mmcv and solved this error.
