### ISSUE TITLE
Error when using mmcv.ops.DeformConv2dPack: shape '[1, 1, 27]' is invalid for input of size 2464128

### ISSUE THREAD

**Issue by icicle4** [open-mmlab/mmcv#441]
I just use a default google's colab env with the below command.
`!pip install torch==1.5.0+cu101 torchvision==0.6.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html
!pip install mmcv-full==latest+torch1.5.0+cu101 -f https://openmmlab.oss-accelerate.aliyuncs.com/mmcv/dist/index.html`

Code is as below.

```python
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import time
import sys
from mmcv.ops import DeformConv2dPack

class MyModel(nn.Module):
    def __init__(self, scale_factor=2):
        super(MyModel, self).__init__()
        self.conv1 = nn.Conv2d(3, 3, 1, 1, padding=0, bias=False)
        self.dcn = DeformConv2dPack(in_channels=3,
                 out_channels=3,
                 kernel_size=3,
                 stride=1)
        self.conv2 = nn.Conv2d(3, 3, 1, 1, padding=0, bias=False)
       
    def forward(self, x):
        x = self.conv1(x)
        
        x = self.dcn(x)
        x = self.conv2(x)
        return x


model = MyModel().cuda()
b, c, h, w = 64, 3, 64, 48
x = torch.randn(b, c, h, w, device='cuda')
target = torch.randn(b, c, h, w, device='cuda')
optimizer = optim.SGD(
            model.parameters(),
            lr=0.01,
            momentum=0.1)
nb_iters = 100000
torch.cuda.synchronize()
t0 = time.perf_counter()

for _ in range(nb_iters):
    output = model(x)
    loss = F.mse_loss(output, target)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
torch.cuda.synchronize()
t1 = time.perf_counter()
print('Took {}s, {}s per iter'.format((t1 - t0), (t1 - t0)/nb_iters))
```

Below is the error:
```python
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-845bd71b55fa> in <module>()
     44 
     45 for _ in range(nb_iters):
---> 46     output = model(x)
     47     loss = F.mse_loss(output, target)
     48     optimizer.zero_grad()

4 frames
/usr/local/lib/python3.6/dist-packages/mmcv/ops/deform_conv.py in forward(ctx, input, offset, weight, stride, padding, dilation, groups, deform_groups, bias, im2col_step)
     88             group=ctx.groups,
     89             deformable_group=ctx.deform_groups,
---> 90             im2col_step=cur_im2col_step)
     91         return output
     92 

RuntimeError: shape '[1, 1, 27]' is invalid for input of size 2464128
```
More env info is below:

- NVIDIA-SMI 450.51.05    
- Driver Version: 418.67 
- CUDA Version: 10.1
- python=3.6
- torch==1.5.0+cu101
- torchsummary==1.5.1
- torchtext==0.3.1
- torchvision==0.6.0+cu101

**Comment by xvjiarui** [comment]
Hi @icicle4 
You may try to use `pad=1` for `DeformConv2dPack` since you have `kernel_size =3`.

**Comment by icicle4** [comment]
Thanks your reply @xvjiarui 

But with `self.dcn = DeformConv2dPack(in_channels=3,out_channels=3, kernel_size=3, stride=1, padding=1)` the error message changes from `shape '[1, 1, 27]' is invalid for input of size 2464128` to `shape '[1, 1, 27]' is invalid for input of size 2654208`.

**Comment by shreyaskamathkm** [comment]
Could you please try batch size < 32? I think its an indexing error as mentioned in https://github.com/pytorch/pytorch/issues/34540#issue-578699807.

**Comment by icicle4** [comment]
> Could you please try batch size < 32? I think its an indexing error as mentioned in [pytorch/pytorch#34540 (comment)](https://github.com/pytorch/pytorch/issues/34540#issue-578699807).

Yes, I try it with batch size=32, now it can works. Thanks. However, I wish it can work with batch size > 32.

**Comment by ShichenLiu** [comment]
@icicle4 please kindly check [this thread](https://github.com/pytorch/pytorch/issues/34540#issuecomment-692418106), where I managed to run with batch size > 32 with a trick to im2col_step.

**Comment by icicle4** [comment]
> @icicle4 please kindly check [this thread](https://github.com/pytorch/pytorch/issues/34540#issuecomment-692418106), where I managed to run with batch size > 32 with a trick to im2col_step.

I get it. Thanks.
