### ISSUE TITLE
Can not  pip install pip -e .

### ISSUE THREAD

**Issue by zhangjiyuzjy** [open-mmlab/mmcv#445]
when i pip install pip -e . 终端就会卡着不动

环境  linux
      torch1.01
      CUDA Version 9.0.176

**Comment by xvjiarui** [comment]
Hi @zhangjiyuzjy 
First please use English or English/Chinese for the issue. 
You may try `pip install -v -e .` to see where the progress stacked.

**Comment by hellock** [comment]
The installation may take up to 10 minutes if you build it from source.
