### ISSUE TITLE
Bug feedback.

### ISSUE THREAD

**Issue by wdmwhh** [open-mmlab/mmcv#449]
Thanks for your codes. 
In [mmcv/runner/base_runner](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/base_runner.py#L385), 
`    def register_logger_hooks(self, log_config):
        log_interval = log_config['interval']
        for info in log_config['hooks']:
            logger_hook = mmcv.build_from_cfg(
                info, HOOKS, default_args=dict(interval=log_interval))
            self.register_hook(logger_hook, priority='VERY_LOW')
`
.
Only the argument 'interval' in log_config is fed into logger_hook. However, the argument 'by_epoch' is ignored, always true, so that if iter_based_runner is used, the logger will work unexpectedly.

**Comment by hellock** [comment]
`logger_hook = mmcv.build_from_cfg(info, HOOKS, default_args=dict(interval=log_interval))`

Other arguments are in `info`.

**Comment by wdmwhh** [comment]
Thanks.
I check for my issue carefully. In [mmcv/runner/iter_based_runner](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/iter_based_runner.py#L224),
`        if log_config is not None:
            log_config.setdefault('by_epoch', False)
        self.register_logger_hooks(log_config)`, 
the key 'by_epoch' , similar to the key 'interval', is in log_config, instead of in info, which is one item of log_config['hooks']. 
In fact, I add `by_epoch` into default_args, the logger works expectedly.
