### ISSUE TITLE
can deform_conv run fp16?

### ISSUE THREAD

**Issue by twmht** [open-mmlab/mmcv#464]
pytorch1.6 introduced amp.autocast() (https://pytorch.org/docs/stable/amp.html#torch.cuda.amp.autocast) which can running inference with mixed precision.

but with model including deform_conv ops from mmcv, it can't autocast that.

```
  File "/home/acer/acer_mmdetection/mmcv/mmcv/ops/modulated_deform_conv.py", line 247, in forward
    self.deform_groups)
  File "/home/acer/acer_mmdetection/mmcv/mmcv/ops/modulated_deform_conv.py", line 85, in forward
    with_bias=ctx.with_bias)
RuntimeError: expected scalar type Float but found Half
```

any idea?

**Comment by hellock** [comment]
DCN does not support FP16 yet.

**Comment by Charlyo** [comment]
@hellock any updates regarding this?

**Comment by abhiagwl4262** [comment]
I think, it still doesn't support autocast/fp16 ?
