### ISSUE TITLE
stop when build  mvcc-full

### ISSUE THREAD

**Issue by cefengxu** [open-mmlab/mmcv#465]
follow the step of the page to clone  https://github.com/open-mmlab/mmcv.git
cd mmcv ， and then run command ：
·
# MMCV_WITH_OPS=1 pip install -e .
·
**and then the bash always be stopped with a message shown as follow**
`  

Obtaining file:///mmdetection/mmcv
Requirement already satisfied: addict in /opt/conda/lib/python3.7/site-packages (from mmcv-full==1.0.5) (2.2.1)
Requirement already satisfied: numpy in /opt/conda/lib/python3.7/site-packages (from mmcv-full==1.0.5) (1.18.1)
Requirement already satisfied: pyyaml in /opt/conda/lib/python3.7/site-packages (from mmcv-full==1.0.5) (5.3.1)
Requirement already satisfied: yapf in /opt/conda/lib/python3.7/site-packages (from mmcv-full==1.0.5) (0.30.0)
Requirement already satisfied: opencv-python>=3 in /opt/conda/lib/python3.7/site-packages (from mmcv-full==1.0.5) (4.2.0.34)
Installing collected packages: mmcv-full
  Running setup.py develop for mmcv-full

`

**Comment by hellock** [comment]
It may take a long time (10min) up to your hardwares.

**Comment by hellock** [comment]
You can run `MMCV_WITH_OPS=1 pip install -v -e .` to print some information.
