### ISSUE TITLE
install mmcv error

### ISSUE THREAD

**Issue by amberc0730** [open-mmlab/mmcv#467]
Why I tried it for many times and always failing to install 

Building wheels for collected packages: mmcv
  Building wheel for mmcv (setup.py) ... error

Running setup.py clean for mmcv
Failed to build mmcv
**DEPRECATION: Could not build wheels for mmcv which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.**
Installing collected packages: mmcv
    Running setup.py install for mmcv ... error

**Comment by xvjiarui** [comment]
Hi @amberc0730 
May I know the cmd you ran?

**Comment by amberc0730** [comment]
finally I successfully installed it, thanks~

**Comment by zhjw0927** [comment]
How did you solve it?

**Comment by keyNG96328** [comment]
How did you solve it?

**Comment by x33rak** [comment]
@amberc0730 how did you solve this issue?

@zhjw0927 and @keyNG96328 was this issue solved?

**Comment by zhouzaida** [comment]
Hi @x33rak , you can install mmcv-full with the following commands.

```bash
pip install -U openmim
mim install mmcv-full
```
