### ISSUE TITLE
【BUG】DistSamplerSeedHook() doesn't support the customized batch_sampler

### ISSUE THREAD

**Issue by scnuhealthy** [open-mmlab/mmcv#472]
I customize a BatchSampler which based on a DistributedSampler and put it into the dataloader. But when I run my program, an error occurs: AttributeError: 'SequentialSampler' object has no attribute 'set_epoch'. 
After reading the source code of pytorch and mmcv, I find the bug results from the code in DistSamplerSeedHook(). This hook is for shuffle the dataset at every epoch. 
The core code should be _runner.data_loader.batch_sampler.sampler.set_epoch(runner.epoch)_ rather than _runner.data_loader.sampler.set_epoch(runner.epoch)_ (if you customize the batchsampler, batch_sampler.sampler is not euqal to sampler according to the source code of pytorch).

**Comment by hellock** [comment]
Thanks for the report! Would you mind create a PR to fix it?

**Comment by scnuhealthy** [comment]
Sure, I will test and then pull a request.
