### ISSUE TITLE
about cascade rcnn

### ISSUE THREAD

**Issue by baichii** [open-mmlab/mmcv#49]
I'am just looking into the cascade rcnn, I notice that in bbox_head, all of the three part's reg_class_agnostic are True, but in normal rcnn this configuration is False so it could get the bbox of all the classes which in coco is 81。I wonder why the third part in cascade rcnn 's bbox_head is not False so i could get the same result like normal rcnn or in cascade this operation is finished in other place .Thanks.

**Comment by OceanPang** [comment]
@baichii The implementation of Cascade R-CNN follows the original paper, which said `All regressors are class agnostic for simplicity`. You can modify the config by yourself and re-train the model.
Besides, please report the issue related to mmdetection at [mmdetection](https://github.com/open-mmlab/mmdetection). This repo is for mmcv.
