### ISSUE TITLE
Possible bug in CosineAnnealingLrUpdaterHook

### ISSUE THREAD

**Issue by thisisi3** [open-mmlab/mmcv#519]
https://github.com/open-mmlab/mmcv/blob/09b7d6c7dd1a889ce0b798fa8b7f54179d877caf/mmcv/runner/hooks/lr_updater.py#L248

When use cosine annealing, I realize the lr does not reach the final target lr at the last epoch. In the above line, progress / max_progress may never gets 0 as epoch count starts from 0 and ends at max_epoch-1. Is this an issue?

**Comment by ZwwWayne** [comment]
Hi @thisisi3 ,
This should not be an issue for model training as it has been used many times and the models performance is normal. Usually, the LR will be very close to 0 but should not be zero at the end of the training. There might be some slight difference in implementations of CosineAnealing, we will check the implementation in the future and make the module more general for common usages.

**Comment by thisisi3** [comment]
Good to know, thanks.
