### ISSUE TITLE
Maybe meaningless about the assert

### ISSUE THREAD

**Issue by jichilen** [open-mmlab/mmcv#52]
https://github.com/open-mmlab/mmcv/blob/bef7c13a95039e676330d9fc2176b6b4b4d79731/mmcv/image/transforms/geometry.py#L183
`for i in range(len(shape) - 1):`
       ` assert shape[i] >= img.shape[i]`
When the image have the shape of (h,w), the assert will only done on the first dimension.
`for i in range(len(shape)):` may be better

**Comment by hellock** [comment]
Thanks! I guess you are right. Would you like to raise a PR to fix it?

**Comment by jichilen** [comment]
Thank you, it's not a bug, i think.
