### ISSUE TITLE
windows10, compile mmcv-full error, focal_loss_cuda.obj : error LNK2001: unresolved external symbol

### ISSUE THREAD

**Issue by minan19605** [open-mmlab/mmcv#534]
The error as below:
focal_loss_cuda.obj : error LNK2001: unresolved external symbol "public: long __cdecl at::Tensor::item<long>(void)const " (??$item@J@Tensor@at@@QEBAJXZ)

Then I open the file focal_loss_cuda.cu, find there have four long:
AT_ASSERTM(target.max().item<**long**>() <= (**long**)num_classes
AT_ASSERTM(target.max().item<**long**>() <= (**long**)num_classes

I change all "long" to "int64_t" as below. Now I can install the mmcv-full successfully.

AT_ASSERTM(target.max().item<int64_t>() <= (int64_t)num_classes
AT_ASSERTM(target.max().item<int64_t>() <= (int64_t)num_classes

**Comment by ZwwWayne** [comment]
Thanks for your kind suggestion, would you like to create a PR to fix that? Your contribution is very appreciated.
