### ISSUE TITLE
install mmcv in win10

### ISSUE THREAD

**Issue by Shmily-YH** [open-mmlab/mmcv#547]
Hi guys, i tried to install mmcv-full in win10, my enviromnet is as follows:
Python: 3.7.7
Cuda: 10.1
Torch: 1.5.0
i git clone the repo by git clone https://github.com/open-mmlab/mmcv.git,
and i try to install mmcv as the author advised, but some erros:

(torch) D:\git\mmcv\mmcv>pip install -e .
Obtaining file:///D:/git/mmcv/mmcv
Requirement already satisfied: addict in c:\users\yang\anaconda3\envs\torch\lib\site-packages (from mmcv-full==1.1.2) (2.2.1)
Requirement already satisfied: numpy in c:\users\yang\anaconda3\envs\torch\lib\site-packages (from mmcv-full==1.1.2) (1.18.1)
Requirement already satisfied: pyyaml in c:\users\yang\anaconda3\envs\torch\lib\site-packages (from mmcv-full==1.1.2) (5.3.1)
Requirement already satisfied: yapf in c:\users\yang\anaconda3\envs\torch\lib\site-packages (from mmcv-full==1.1.2) (0.30.0)
Requirement already satisfied: opencv-python>=3 in c:\users\yang\anaconda3\envs\torch\lib\site-packages (from mmcv-full==1.1.2) (4.4.0.42
)
Requirement already satisfied: regex in c:\users\yang\anaconda3\envs\torch\lib\site-packages (from mmcv-full==1.1.2) (2020.7.14)
Installing collected packages: mmcv-full
  Running setup.py develop for mmcv-full
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\yang\Anaconda3\envs\torch\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'D:\\git\\mmcv\\mmc
v\\setup.py'"'"'; __file__='"'"'D:\\git\\mmcv\\mmcv\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().repl
ace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: D:\git\mmcv\mmcv\
    Complete output (21 lines):
    running develop
    running egg_info
    writing mmcv_full.egg-info\PKG-INFO
    writing dependency_links to mmcv_full.egg-info\dependency_links.txt
    writing requirements to mmcv_full.egg-info\requires.txt
    writing top-level names to mmcv_full.egg-info\top_level.txt
    reading manifest file 'mmcv_full.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'mmcv_full.egg-info\SOURCES.txt'
    running build_ext
    building 'mmcv._flow_warp_ext' extension
    Emitting ninja build file D:\git\mmcv\mmcv\build\temp.win-amd64-3.7\Release\build.ninja...
    Compiling objects...
    Using envvar MAX_JOBS (4) as the number of workers...
    C:\Users\yang\Anaconda3\envs\torch\lib\site-packages\torch\utils\cpp_extension.py:237: UserWarning: Error checking compiler version f
or cl: 'utf-8' codec can't decode byte 0xd3 in position 0: invalid continuation byte
      warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
    ninja: no work to do.
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2
 /MANIFESTUAC:NO /LIBPATH:C:\Users\yang\Anaconda3\envs\torch\libs /LIBPATH:C:\Users\yang\Anaconda3\envs\torch\PCbuild\amd64 "/LIBPATH:C:\
Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LI
B\amd64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXS
DK\4.6.1\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64" /EXPORT:PyInit__flow_warp_ext D:\git\mmcv\mmcv
\build\temp.win-amd64-3.7\Release\./mmcv/video/optflow_warp/flow_warp_module.obj D:\git\mmcv\mmcv\build\temp.win-amd64-3.7\Release\./mmcv
/video/optflow_warp/flow_warp.obj /OUT:build\lib.win-amd64-3.7\mmcv\_flow_warp_ext.cp37-win_amd64.pyd /IMPLIB:D:\git\mmcv\mmcv\build\temp
.win-amd64-3.7\Release\./mmcv/video/optflow_warp\_flow_warp_ext.cp37-win_amd64.lib
    fatal error C1905: 前端和后端不兼容(必须以同一处理器为目标)。
    LINK : fatal error LNK1257: 代码生成失败
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1257
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\yang\Anaconda3\envs\torch\python.exe' -c 'import sys, setuptools, tokenize; sys.
argv[0] = '"'"'D:\\git\\mmcv\\mmcv\\setup.py'"'"'; __file__='"'"'D:\\git\\mmcv\\mmcv\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', o
pen)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-
deps Check the logs for full command output.

It seems that there is something wrong with the different package version? or anyone who meets the same question?

**Comment by Shmily-YH** [comment]
Just give up the idea to install mmcv-full on windows...the earlier the better

**Comment by wangruohui** [comment]
Hi, 

The error

> 前端和后端不兼容(必须以同一处理器为目标)。

suggests you are trying to linking x86 and x64 libraries together. Its incompatible thus resulting an error. Is there something 32-bit on your computer? 

Some minor improvements:
 
> C:\Users\yang\Anaconda3\envs\torch\lib\site-packages\torch\utils\cpp_extension.py:237: UserWarning: Error checking compiler version f
> or cl: 'utf-8' codec can't decode byte 0xd3 in position 0: invalid continuation byte
> warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))

Currently your system language is Chinese. You can configure your locale to English to surpass this warning and enable an ABI compatibility check. See [here](http://www.unifit-software.de/PDF/How%20to%20Change%20system%20locale%20for%20non-unicode%20programs.pdf) for detail.
