### ISSUE TITLE
[BUG] mmcv.ops.DeformConv2dPack gives issues with multi-GPU training

### ISSUE THREAD

**Issue by akashpalrecha** [open-mmlab/mmcv#548]
Whenever I include an `mmcv.ops.DeformConv2dPack` module inside of any PyTorch Model and train it with multiple GPUs, the training time actually scales **up** by **1X** with every added GPU
For instance, if my training time is 1 hour with 1 GPU, it will become 2 hours with 2 GPUs and so on whenever I have a Deformable convolution inside my PyTorch model.

Anybody has any clue why this happens and how it can be solved?

**Comment by xvjiarui** [comment]
Hi @akashpalrecha 
May I know which task are you applying DCN on? I haven't observed this phenomenon in MMDet.

**Comment by akashpalrecha** [comment]
I'm using this for super resolution. 
It's part of a simple conv net (EDSR) where I've replaced the convs for just one of the resblocks with Deformable Convs.

**Comment by nbei** [comment]
Hi @akashpalrecha , I have discussed with @xinntao and he did not meet similar problem in training edvr. Could you please give us more information, like running command you used, detailed running time for single gpu and multi-gpu and ...?

**Comment by akashpalrecha** [comment]
HI @nbei,
I didn't use the EDVR model. It was an EDSR model with the usual convs replaced with deformable convolutions.
The model is defined here: https://github.com/akashpalrecha/superres-deformable/blob/master/src/model/deformable_edsr.py
This is a model trained for superresolution using the DIV2K dataset.

In my repository, the model can be trained using this command upon entering the `src` directory assuming all the datasets are downloaded: `python main.py --model deformable_edsr --res_scale 0.1 --scale 2 --save one_deformable_edsr_baseline_x2_100 --ext sep --save_results --epochs 100 --one_deformable_block` although I do not think that this is relevant here as this is not using any MMCV model.

As far as the running time is concerned, training the above model takes about `80` seconds per epoch on an NVIDIA V100. When I increase the number of GPUs to 2, keeping everything else including the batch size (16) the same, the time goes up to  close to `160` seconds.

Even if I just replace one of the convs in the whole model with a deformable conv, the effect persists.

The first thought that came to my mind was that it's probably an implementation issue from my side. But every other model I have without deformable convolutions behaves as expected (training time divides itself by the number of GPUs as usual)
