### ISSUE TITLE
warmup decreases lr other than increase it.

### ISSUE THREAD

**Issue by cissoidx** [open-mmlab/mmcv#552]
In the LrUpdaterHook, the current lr will always be multiplied by a fraction. Seems that self.regular_lr should be initialed in before_run.

```python
    def get_warmup_lr(self, cur_iters):
        if self.warmup == 'constant':
            warmup_lr = [_lr * self.warmup_ratio for _lr in self.regular_lr]
        elif self.warmup == 'linear':
            k = (1 - cur_iters / self.warmup_iters) * (1 - self.warmup_ratio)
            warmup_lr = [_lr * (1 - k) for _lr in self.regular_lr]
        elif self.warmup == 'exp':
            k = self.warmup_ratio**(1 - cur_iters / self.warmup_iters)
            warmup_lr = [_lr * k for _lr in self.regular_lr]
        return warmup_lr
```

**Comment by ZwwWayne** [comment]
Warm-up LR should start from a small value and then gradually increase or jump to be the regular LR. Did you meet any unexpected behavior in your config? Could you provide a case that you think is abnormal for us to reproduce and analyse?

**Comment by cissoidx** [comment]
It is my fault. However, the name `StepLrUpdater` is very misleading. I did not expect that `StepLrUpdater` makes lr decrease so fast that warmup cannot increase lr enough to get a finally increasing lr. I suppose that `StepExpLrUpdater` is a better name for this updater.

To provide a reproductive config, add the following in `mmsegmentation/configs/pspnet/pspnet_r50-d8_512x512_80k_ade20k.py` and run training:
```python
lr_config = dict(policy='step', step=2, by_epoch=False, warmup='linear', warmup_iters=200, warmup_ratio=0.1)
```
BTW, the warmup mechanism in mmcv works together with (I mean at the same time) regular lr policy. The lr changes firstly according to the policy no matter warmup is implemented or not.  This is where this issue originated.

cheers.
