### ISSUE TITLE
lite mmvc install error for help

### ISSUE THREAD

**Issue by luke4u** [open-mmlab/mmcv#560]
Hi Guys,

First, thank you for sharing this amazing package. 

I am trying to install the lite version MMVC on my machine. But after a few failures, have to come here for help.

What I want:
- install the lite version on windows 10 In Conda virenv

Command in conda virenv:
- `pip install mmcv`
- also tried to install from source `pip install -e .`

What I have tried to resolve the error:
- read through the install instruction
- reviewed all the install error issues here (surprisingly found so many.... :>): 
  - checked my visual c++ version (2015) 
  - installed pytest-runner

My machine:
- Windows 10
- python==3.7.3

Error message:
![image](https://user-images.githubusercontent.com/45267576/93360447-9385cd80-f83b-11ea-99e5-68e08aa18c22.png)
![image](https://user-images.githubusercontent.com/45267576/93360552-b2845f80-f83b-11ea-878b-4eff9265d9ed.png)

Many thanks in advance. 
Luke

**Comment by RyanXLi** [comment]
Hi! Please check your PyTorch version and CUDA version to make sure both of them are compatible according to the table in the Installation section in README.md of MMCV.

**Comment by wangruohui** [comment]
From the log I think you trigger the full build via environment variable `MMCV_WITH_OPS=1`. If you need only the lite version, try reinstall from a clean environment with:

(within `cmd.exe`)
```shell
set MMCV_WITH_OPS=0
pip install mmcv
```

or (within PowerShell)
```PowerShell
$env:MMCV_WITH_OPS=0
pip install mmcv
```

**Comment by wangruohui** [comment]
Also, it seems the real error is hidden somewhere between these two screenshots. There could be some error reporting from the compiler. Anyway, it relates to pytorch, which deals only with the full version.

**Comment by wangruohui** [comment]
no response for long time, closed.
