### ISSUE TITLE
Error in Installing a cpu version 

### ISSUE THREAD

**Issue by Nickchangqing** [open-mmlab/mmcv#571]
ERROR: Could not find a version that satisfies the requirement mmcv-full==latest+torch1.6.0+cpu (from versions: 1.0rc0, 1.0rc2, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.1.3)

**Comment by RyanXLi** [comment]
1. Please make sure you are using a recent version of Python (e.g. 3.7). MMCV requires Python 3.6+. 
2. If your python is up to date, make sure to check your pip is updated.

**Comment by Nickchangqing** [comment]
Thank your, I am using the newest pip, but I still meet this problem. Instead I directly install by pip install mmcv-full, problems solved. But I don't know whether will other problems occur
