### ISSUE TITLE
could not work with SimpleITK, related to import order

### ISSUE THREAD

**Issue by hubutui** [open-mmlab/mmcv#573]
When I run:
```
import SimpleITK
import mmcv
```
I got `segmentation fault (core dumped)`, but if I import mmcv first, it's OK.

mmcv-full:  1.1.3
simpleitk: 2.0.0
python: 3.8.5

**Comment by zyc-ai** [comment]
![image](https://user-images.githubusercontent.com/28757366/93982108-6abd8500-fdb3-11ea-8170-820163a3876c.png)
![image](https://user-images.githubusercontent.com/28757366/93984507-78283e80-fdb6-11ea-82a7-639bca0c4f29.png)

![image](https://user-images.githubusercontent.com/28757366/93984490-73fc2100-fdb6-11ea-88e9-dd5906a7fc44.png)

It worked quite well for me on Windows 10, Ubuntu 20.04 (WSL), and CentOS, would you mind providing more details?

**Comment by wangruohui** [comment]
It might be an incompatibility on binaries. Are mmcv-full and SimpleITK compiled with different version of compilers? Would you please provide more information on your environment and the way you install these packages?

**Comment by hubutui** [comment]
OS: ArchLinux
pytorch: python-pytorch-cuda 1.6.0
All these pkgs are installed from ArchLinux or ArchLinuxCN's repo.
check [here](https://cowtransfer.com/s/6291e1bf597649) for the coredump file, password to download: `n98vg9`.

**Comment by hubutui** [comment]
It's fixed in SimpleITK, see also https://github.com/SimpleITK/SimpleITK/issues/1208.
