### ISSUE TITLE
help cv2.resize correctly handling more than 3 channels for segmentation masks

### ISSUE THREAD

**Issue by baibaidj** [open-mmlab/mmcv#578]
[https://github.com/open-mmlab/mmcv/blob/50af00991c5b95e8ce8c38d9ec9a5fda9c43e176/mmcv/image/geometric.py#L85](url)
cv2.resize with nearest interpolation can only correctly process segmentation mask of less than 4 channels.   
When it encounters more than 4, the function with nearest interpolation will result in mask of new-added values. 
For instance, a mask has four (0, 1, 2, 3) values, after resize with nearest interop the output should only have these four values. But when the mask is of 5 channels, the output will contains many more values up to 255. 

This issue is addressed by the albumentations package as in this link [https://github.com/albumentations-team/albumentations/blob/97b640fe1fcdc6d991a86bd44ec56cf3c02aae4e/albumentations/augmentations/functional.py#L210](url)

I suggest that mmcv adopts the albu method to solve this issue by replacing the cv2.resize with a newly defined resize function.  The new resize function can be like this: 

```
def resize(img, size, dst=None, interpolation=cv2.INTER_LINEAR):
    resize_fn = _maybe_process_in_chunks(cv2.resize, dsize=size, dst = dst, interpolation=interpolation)
    return resize_fn(img) 

def _maybe_process_in_chunks(process_fn, **kwargs):
    """
    Wrap OpenCV function to enable processing images with more than 4 channels.

    Limitations:
        This wrapper requires image to be the first argument and rest must be sent via named arguments.

    Args:
        process_fn: Transform function (e.g cv2.resize).
        kwargs: Additional parameters.

    Returns:
        numpy.ndarray: Transformed image.

    """
    def get_num_channels(image):
        return image.shape[2] if len(image.shape) == 3 else 1
    def __process_fn(img):
        num_channels = get_num_channels(img)
        if num_channels > 3:
            chunks = []
            for index in range(0, num_channels, 3):
                chunk = img[:, :, index : index + 3]
                chunk = process_fn(chunk, **kwargs)
                chunks.append(chunk)
            img = np.dstack(chunks)
        else:
            img = process_fn(img, **kwargs)
        return img

    return __process_fn
```

**Comment by hellock** [comment]
Good idea. Would you like to create a PR to add this feature? Or we can add it in the next release.

**Comment by baibaidj** [comment]
> Good idea. Would you like to create a PR to add this feature? Or we can add it in the next release.

Hi @hellock. Thank you. As I have no experience with creating Pull Request yet, could you please integrate the suggestion into the package? I guess the latter way may be quicker.

**Comment by ycxioooong** [comment]
Hi @baibaidj, please refer to https://github.com/open-mmlab/mmcv/blob/master/CONTRIBUTING.md to see how to submit your PR. 

Basically, there are x simple steps:
- fork ``mmcv`` and git clone your forked repo to your local machine.
- install the required dependencies (e.g., pre-commit as described in CONTRIBUTING.md)
- create a new branch and add your codes.
- commit and push codes to the forked repo.
- open this forked repo and you'll directly see some information bar on top of the website that tells you to create a PR for your contribution.
- Once the codes are reviewed and tests are passed, we'll merge your PR to the official ``mmcv`` repo.

**Comment by hellock** [comment]
@ycxioooong could create a PR with the suggestion.

**Comment by baibaidj** [comment]
> Hi @baibaidj, if you would like to submit the PR yourself, please refer to https://github.com/open-mmlab/mmcv/blob/master/CONTRIBUTING.md to see how to submit your PR. Actually, it's very simple.
> 
> Basically, there are 6 simple steps:
> 
> * fork `mmcv` and git clone your forked repo to your local machine.
> * install the required dependencies (e.g., pre-commit as described in CONTRIBUTING.md)
> * create a new branch and add your codes.
> * commit and push codes to the forked repo.
> * at GitHub website, open this forked repo and you'll directly see some information bar on top of the website that tells you to create a PR for your contribution.
> * Once the codes are reviewed and tests are passed, we'll merge your PR to the official `mmcv` repo.

Thank you for the instruction.

**Comment by baibaidj** [comment]
> @ycxioooong could create a PR with the suggestion.

I'd love to try this if @ycxioooong is Ok with me. 
I have forked the repo and made the change but did not find time to test it. 
Hopefully, I can create a PR this weekend.

**Comment by ycxioooong** [comment]
Seems like the PR is stuck at linting issues. Anyway, the refactor of transforms is on the way.
