### ISSUE TITLE
advise for config file read function

### ISSUE THREAD

**Issue by www516717402** [open-mmlab/mmcv#589]
**Describe the feature**
About config file read error, like: [Error](https://github.com/open-mmlab/mmdetection/issues/2698#issue-616656357).
Config file error will lead to this error (&eg. `dict([123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)`,less keyword mean).
Hope mmcv afford error instruction specific.

**Comment by hellock** [comment]
The latest mmcv should have raised an error indicating that there are syntax errors in config files, instead of raising errors like temp files not found.
