### ISSUE TITLE
[Installation Issue] zipfile.BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by wdkwyf** [open-mmlab/mmcv#594]
Hi,
It happened during installation:
`pip install mmcv-full==latest+torch1.4.0+cu101 -f https://download.openmmlab.com/mmcv/dist/index.html
`
Error happened during the middle of downloading mmcv-full-1.1.4 wheel and root cause is that speed is very slow(50kB/s) and lose connection suddenly. Also, curl the wheel also occur a error:
`curl -O https://download.openmmlab.com/mmcv/dist/latest/torch1.4.0/cu100/mmcv_full-latest%2Btorch1.4.0%2Bcu100-cp37-cp37m-manylinux1_x86_64.whl`
`curl: (18) transfer closed with 10076203 bytes remaining to read`

I finnaly solved this issue by downloading the wheel by Chrome. May it will be helpful when someone also faces the network issue.

**Comment by hellock** [comment]
I am not sure. This may be just a connection error and you may retry it.

**Comment by MBARK-12** [comment]
g

**Comment by MBARK-12** [comment]
> Hi,
> It happened during installation:
> `pip install mmcv-full==latest+torch1.4.0+cu101 -f https://download.openmmlab.com/mmcv/dist/index.html `
> Error happened during the middle of downloading mmcv-full-1.1.4 wheel and root cause is that speed is very slow(50kB/s) and lose connection suddenly. Also, curl the wheel also occur a error:
> `curl -O https://download.openmmlab.com/mmcv/dist/latest/torch1.4.0/cu100/mmcv_full-latest%2Btorch1.4.0%2Bcu100-cp37-cp37m-manylinux1_x86_64.whl`
> `curl: (18) transfer closed with 10076203 bytes remaining to read`
> 
> I finnaly solved this issue by downloading the wheel by Chrome. May it will be helpful when someone also faces the network issue.
