### ISSUE TITLE
Do you support tensors summary in Tensorboard hook?

### ISSUE THREAD

**Issue by adizhol** [open-mmlab/mmcv#595]
Do you support tensors summary in Tensorboard hook?
I can see only scalar and text

**Comment by hellock** [comment]
Could you describe the usage case more specifically, e.g., what tensors in the model and how would you like to configure it?

**Comment by adizhol** [comment]
Basically outputs like segmentations or intermediate outputs... it depends on the task.
I extended a tensorboard logger class and it worked for me.
