### ISSUE TITLE
ImportError: /usr/local/lib/python3.6/dist-packages/mmcv/_ext.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at5emptyEN3c108ArrayRefIlEERKNS0_13TensorOptionsENS0_8optionalINS0_12MemoryFormatEEE

### ISSUE THREAD

**Issue by neomukul** [open-mmlab/mmcv#596]
Hello All,

I am trying to work with this package but getting this error.

ImportError                               Traceback (most recent call last)
<ipython-input-12-b6d8eacaa0e3> in <module>()
      9 
     10 # Check mmcv installation
---> 11 from mmcv.ops import get_compiling_cuda_version, get_compiler_version
     12 print(get_compiling_cuda_version())
     13 print(get_compiler_version())

3 frames
/usr/local/lib/python3.6/dist-packages/mmcv/ops/__init__.py in <module>()
----> 1 from .bbox import bbox_overlaps
      2 from .carafe import CARAFE, CARAFENaive, CARAFEPack, carafe, carafe_naive
      3 from .cc_attention import CrissCrossAttention
      4 from .corner_pool import CornerPool
      5 from .deform_conv import DeformConv2d, DeformConv2dPack, deform_conv2d

/usr/local/lib/python3.6/dist-packages/mmcv/ops/bbox.py in <module>()
      1 from ..utils import ext_loader
      2 
----> 3 ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
      4 
      5 

/usr/local/lib/python3.6/dist-packages/mmcv/utils/ext_loader.py in load_ext(name, funcs)
      9 
     10     def load_ext(name, funcs):
---> 11         ext = importlib.import_module('mmcv.' + name)
     12         for fun in funcs:
     13             assert hasattr(ext, fun), f'{fun} miss in module {name}'

/usr/lib/python3.6/importlib/__init__.py in import_module(name, package)
    124                 break
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 
    128 

ImportError: /usr/local/lib/python3.6/dist-packages/mmcv/_ext.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at5emptyEN3c108ArrayRefIlEERKNS0_13TensorOptionsENS0_8optionalINS0_12MemoryFormatEEE

**Comment by hellock** [comment]
https://mmcv.readthedocs.io/en/latest/trouble_shooting.html

**Comment by HoBeom** [comment]
Same Import Error in RTX 3080, pytorch-nightly::pytorch-1.8.0.dev20201026-py3.7\_cuda11.0.221\_cudnn8.0.3\_0

```
ImportError: /opt/conda/lib/python3.7/site-packages/mmcv-1.1.5-py3.7-linux-x86_64.egg/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c104impl23ExcludeDispatchKeyGuardC1ENS_11DispatchKeyE
```

**Comment by TTXXXL** [comment]
> Same Import Error in my new card RTX 3080, pytorch-nightly::pytorch-1.8.0.dev20201026-py3.7_cuda11.0.221_cudnn8.0.3_0
> 
> ```
> ImportError: /opt/conda/lib/python3.7/site-packages/mmcv-1.1.5-py3.7-linux-x86_64.egg/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c104impl23ExcludeDispatchKeyGuardC1ENS_11DispatchKeyE
> ```
> 
> MMCV doesn't support CUDA 11.0 ?
> 
> Fix it. reinstall mmcv.. `MMCV_WITH_OPS=1 pip install .` thx

Hi, HoBeom. 
I would like to ask I have the same enviroments except that I used python3.6. 
Did you just download the mmcv-master.zip and go to the file and run 'MMCV_WITH_OPS=1 pip install .' ?
But I still got issues with that. thx
