### ISSUE TITLE
LINK : fatal error LNK1181

### ISSUE THREAD

**Issue by EddieEduardo** [open-mmlab/mmcv#609]
Could anybody help me with these errors ?  I've struggled with them for 2 days. Thanks a looooooooooot.

What I ran was : (Win10, PyTorch1.5.0, Python3.7, cuda10.2)

git clone https://github.com/open-mmlab/mmcv.git
cd mmcv
pip install -e . (Other installing ways I also tried, but none of them worked on my computer)

Then I got errors as follows:
"""
Obtaining file:///J:/MOTS/MOT%20CODES/pedestrian_tracking-master/mmcv
Requirement already satisfied: addict in e:\anaconda3\envs\pycocotools\lib\site-packages (from mmcv==1.1.5) (2.3.0)
Requirement already satisfied: numpy in e:\anaconda3\envs\pycocotools\lib\site-packages (from mmcv==1.1.5) (1.19.1)
Requirement already satisfied: pyyaml in e:\anaconda3\envs\pycocotools\lib\site-packages (from mmcv==1.1.5) (5.3.1)
Requirement already satisfied: yapf in e:\anaconda3\envs\pycocotools\lib\site-packages (from mmcv==1.1.5) (0.30.0)
Requirement already satisfied: opencv-python>=3 in e:\anaconda3\envs\pycocotools\lib\site-packages (from mmcv==1.1.5) (4.4.0.44)
Requirement already satisfied: regex in e:\anaconda3\envs\pycocotools\lib\site-packages (from mmcv==1.1.5) (2020.9.27)
Installing collected packages: mmcv
  Running setup.py develop for mmcv
    ERROR: Command errored out with exit status 1:
     command: 'E:\Anaconda3\envs\pycocotools\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'J:\\MOTS\\MOT CODES\\pedestrian_tracking-master\\mmcv\\setup.py'"'"'; __file__='"'"'J:\\MOTS\\MOT CODES\\pedestrian_tracking-master\\mmcv\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: J:\MOTS\MOT CODES\pedestrian_tracking-master\mmcv\
    Complete output (20 lines):
    running develop
    running egg_info
    writing mmcv.egg-info\PKG-INFO
    writing dependency_links to mmcv.egg-info\dependency_links.txt
    writing requirements to mmcv.egg-info\requires.txt
    writing top-level names to mmcv.egg-info\top_level.txt
    reading manifest file 'mmcv.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'mmcv.egg-info\SOURCES.txt'
    running build_ext
    building 'mmcv._flow_warp_ext' extension
    Emitting ninja build file J:\MOTS\MOT CODES\pedestrian_tracking-master\mmcv\build\temp.win-amd64-3.7\Release\build.ninja...
    Compiling objects...
    Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
    E:\Anaconda3\envs\pycocotools\lib\site-packages\torch\utils\cpp_extension.py:237: UserWarning: Error checking compiler version for cl: [WinError 2] could not find files.
      warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
    1.10.1
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:E:\Anaconda3\envs\pycocotools\libs /LIBPATH:E:\Anaconda3\envs\pycocotools\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64" /EXPORT:PyInit__flow_warp_ext "J:\MOTS\MOT CODES\pedestrian_tracking-master\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/video/optflow_warp/flow_warp_module.obj" "J:\MOTS\MOT CODES\pedestrian_tracking-master\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/video/optflow_warp/flow_warp.obj" /OUT:build\lib.win-amd64-3.7\mmcv\_flow_warp_ext.cp37-win_amd64.pyd "/IMPLIB:J:\MOTS\MOT CODES\pedestrian_tracking-master\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/video/optflow_warp\_flow_warp_ext.cp37-win_amd64.lib"
    LINK : fatal error LNK1181: cannot open input file 'J:\MOTS\MOT CODES\pedestrian_tracking-master\mmcv\build\temp.win-amd64-3.7\Release\./mmcv/video/optflow_warp/flow_warp_module.obj'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1181
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'E:\Anaconda3\envs\pycocotools\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'J:\\MOTS\\MOT CODES\\pedestrian_tracking-master\\mmcv\\setup.py'"'"'; __file__='"'"'J:\\MOTS\\MOT CODES\\pedestrian_tracking-master\\mmcv\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
"""

**Comment by ZwwWayne** [comment]
This bug seems related to the incompatibility between Pytorch & Win10. We are not able to fully produce your bugs since we do not have windows machines. But this [discussion](https://discuss.pytorch.org/t/error-with-cpp-extentions/67559/3) might do some help.

**Comment by wangruohui** [comment]
The error saying that the linker can not find the compiled object file. So first make sure the file does exist at the specified path: `'J:\MOTS\MOT CODES\pedestrian_tracking-master\mmcv\build\temp.win-amd64-3.7\Release./mmcv/video/optflow_warp/flow_warp_module.obj'`

And some guess:
1. Maybe the space in directory name `MOT CODES` cause the error, try modify to `MOT_CODES` or something else.
1. Maybe the full directory is literally too long. Try move the full mmcv code base (or better re-clone a new copy) to J:/ and retry compiling.
 
Moreover, it seems the pre-compiled package is provided only for pytorch 1.5.**1** not 1.5.0. I will update it later.
