### ISSUE TITLE
How to constuct another optimizer? (Two Optimizers totally)

### ISSUE THREAD

**Issue by hello451** [open-mmlab/mmcv#618]
Hi, thanks for this great codebase.

I meet a problem that how to construct two optimizers? (each optimizer optimize different parameters).
I have checked the docs but didn't find the answer.

Moreover, I only can find some comments in 'base_runner.py', however, I tried to construct a dic containing two optimizers in config file but got wrong. Could you please tell me how to build 2 optimizers? Or just give me a simple template? Thanks a lot.

**Comment by ycxioooong** [comment]
Hi @hello451, maybe the codes in the [mmediting](https://github.com/open-mmlab/mmediting/blob/f714ba4f3e6995600919a612a2ba0910c37ca062/mmedit/core/optimizer/builder.py#L4) will bring you some insight to construct two optimizers simultaneously.
