### ISSUE TITLE
time record in iter_based_runner

### ISSUE THREAD

**Issue by zmghub** [open-mmlab/mmcv#619]
as mentioned in the topic,
the "self.call_hook('before_train_iter')" is before "data_batch = next(data_loader)",
so the data_time in the IterTimerHook is close to zero.

**Comment by nbei** [comment]
Thanks @zmghub . After a careful check, I notice that it's a bug in [iter_based_runner](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/iter_based_runner.py#L58). I will fix it ASAP and sorry for the late reply.

Thanks again for your kind help.
