### ISSUE TITLE
Feature request. Transformer in MMCV.

### ISSUE THREAD

**Issue by cissoidx** [open-mmlab/mmcv#621]
Transformer has been proposed since several years ago, and it has been used in some CV tasks recently. Do you have plans to implement transformer based models in your mm-series?

cheers,

**Comment by ycxioooong** [comment]
Hi @cissoidx, We do have a plan to support Transformer. Currently, there are PRs related to DETR (https://github.com/open-mmlab/mmdetection/pull/3955) that support Transformer in mmdetection. We'll further consider adding Transformer into mmcv if it's widely adopted by other mm-series.

**Comment by cissoidx** [comment]
> Hi @cissoidx, We do have a plan to support Transformer. Currently, there are PRs related to DETR ([open-mmlab/mmdetection#3955](https://github.com/open-mmlab/mmdetection/pull/3955)) that support Transformer in mmdetection. We'll further consider adding Transformer into mmcv if it's widely adopted by other mm-series.

Great. BTW, apart from DETR used in detection, are there papers about transformer in other cv tasks such as cls, seg, kpt, etc.?

**Comment by cissoidx** [comment]
Well, found out vit. I am closing this issue.
