### ISSUE TITLE
Image scale

### ISSUE THREAD

**Issue by BLOO69** [open-mmlab/mmcv#622]
### Config File
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1333, 800),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
### Question
May i know where the resize function is located? I want to resize the image such that the short side is 512 pixels. And does the Pad make the dimensions a mutiple of 32? Thank you!

**Comment by ycxioooong** [comment]
One of the core ideas of mmcv that everything could be built from config. 
The mechanism behind this is that the code automatically finds the registered modules from mmcv source.
Hence the way to localize a function like Resize, you only need to simply search from GitHub then you will find where we define the resize function.
