### ISSUE TITLE
pip install mmcv-full error

### ISSUE THREAD

**Issue by luzonghao1** [open-mmlab/mmcv#626]
**cuda：10.0
   pytorch：1.1
   
**

  copying mmcv/video/optflow_warp/flow_warp_module.pyx -> build/lib.linux-x86_64-3.6/mmcv/video/optflow_warp
  running build_ext
  building 'mmcv._flow_warp_ext' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/mmcv
  creating build/temp.linux-x86_64-3.6/mmcv/video
  creating build/temp.linux-x86_64-3.6/mmcv/video/optflow_warp
  gcc -pthread -B /home/lzh/anaconda3/envs/second/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I./mmcv/video/optflow_warp -I/home/lzh/anaconda3/envs/second/lib/python3.6/site-packages/numpy/core/include -I/home/lzh/anaconda3/envs/second/include/python3.6m -c ./mmcv/video/optflow_warp/flow_warp_module.cpp -o build/temp.linux-x86_64-3.6/./mmcv/video/optflow_warp/flow_warp_module.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_flow_warp_ext -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++11
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  In file included from /home/lzh/anaconda3/envs/second/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1822:0,
                   from /home/lzh/anaconda3/envs/second/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                   from /home/lzh/anaconda3/envs/second/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                   from ./mmcv/video/optflow_warp/flow_warp_module.cpp:647:
  /home/lzh/anaconda3/envs/second/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   #warning "Using deprecated NumPy API, disable it with " \
    ^~~~~~~
  gcc -pthread -B /home/lzh/anaconda3/envs/second/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I./mmcv/video/optflow_warp -I/home/lzh/anaconda3/envs/second/lib/python3.6/site-packages/numpy/core/include -I/home/lzh/anaconda3/envs/second/include/python3.6m -c ./mmcv/video/optflow_warp/flow_warp.cpp -o build/temp.linux-x86_64-3.6/./mmcv/video/optflow_warp/flow_warp.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_flow_warp_ext -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++11
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  g++ -pthread -shared -B /home/lzh/anaconda3/envs/second/compiler_compat -L/home/lzh/anaconda3/envs/second/lib -Wl,-rpath=/home/lzh/anaconda3/envs/second/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/./mmcv/video/optflow_warp/flow_warp_module.o build/temp.linux-x86_64-3.6/./mmcv/video/optflow_warp/flow_warp.o -o build/lib.linux-x86_64-3.6/mmcv/_flow_warp_ext.cpython-36m-x86_64-linux-gnu.so
  building 'mmcv._ext' extension
  creating build/temp.linux-x86_64-3.6/mmcv/ops
  creating build/temp.linux-x86_64-3.6/mmcv/ops/csrc
  creating build/temp.linux-x86_64-3.6/mmcv/ops/csrc/pytorch
  gcc -pthread -B /home/lzh/anaconda3/envs/second/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DMMCV_WITH_CUDA -I/tmp/pip-install-0ggfooc5/mmcv-full/mmcv/ops/csrc -I/home/lzh/anaconda3/envs/second/lib/python3.6/site-packages/torch/include -I/home/lzh/anaconda3/envs/second/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/lzh/anaconda3/envs/second/lib/python3.6/site-packages/torch/include/TH -I/home/lzh/anaconda3/envs/second/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/lzh/anaconda3/envs/second/include/python3.6m -c ./mmcv/ops/csrc/pytorch/info.cpp -o build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/info.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++11
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  gcc -pthread -B /home/lzh/anaconda3/envs/second/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DMMCV_WITH_CUDA -I/tmp/pip-install-0ggfooc5/mmcv-full/mmcv/ops/csrc -I/home/lzh/anaconda3/envs/second/lib/python3.6/site-packages/torch/include -I/home/lzh/anaconda3/envs/second/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/lzh/anaconda3/envs/second/lib/python3.6/site-packages/torch/include/TH -I/home/lzh/anaconda3/envs/second/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/lzh/anaconda3/envs/second/include/python3.6m -c ./mmcv/ops/csrc/pytorch/roi_pool.cpp -o build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/roi_pool.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++11
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  In file included from ./mmcv/ops/csrc/pytorch/roi_pool.cpp:1:0:
  ./mmcv/ops/csrc/pytorch/roi_pool.cpp: In function ‘void roi_pool_forward(at::Tensor, at::Tensor, at::Tensor, at::Tensor, int, int, float)’:
  /tmp/pip-install-0ggfooc5/mmcv-full/mmcv/ops/csrc/pytorch_cpp_helper.hpp:10:3: error: ‘TORCH_CHECK’ was not declared in this scope
     TORCH_CHECK(x.device().is_cuda(), #x " must be a CUDA tensor")
     ^
  /tmp/pip-install-0ggfooc5/mmcv-full/mmcv/ops/csrc/pytorch_cpp_helper.hpp:16:3: note: in expansion of macro ‘CHECK_CUDA’
     CHECK_CUDA(x);            \
     ^~~~~~~~~~
  ./mmcv/ops/csrc/pytorch/roi_pool.cpp:33:5: note: in expansion of macro ‘CHECK_CUDA_INPUT’
       CHECK_CUDA_INPUT(input);
       ^~~~~~~~~~~~~~~~
  /tmp/pip-install-0ggfooc5/mmcv-full/mmcv/ops/csrc/pytorch_cpp_helper.hpp:10:3: note: suggested alternative: ‘AT_CHECK’
     TORCH_CHECK(x.device().is_cuda(), #x " must be a CUDA tensor")
     ^
  /tmp/pip-install-0ggfooc5/mmcv-full/mmcv/ops/csrc/pytorch_cpp_helper.hpp:16:3: note: in expansion of macro ‘CHECK_CUDA’
     CHECK_CUDA(x);            \
     ^~~~~~~~~~
  ./mmcv/ops/csrc/pytorch/roi_pool.cpp:33:5: note: in expansion of macro ‘CHECK_CUDA_INPUT’
       CHECK_CUDA_INPUT(input);
       ^~~~~~~~~~~~~~~~
  ./mmcv/ops/csrc/pytorch/roi_pool.cpp: In function ‘void roi_pool_backward(at::Tensor, at::Tensor, at::Tensor, at::Tensor, int, int, float)’:
  /tmp/pip-install-0ggfooc5/mmcv-full/mmcv/ops/csrc/pytorch_cpp_helper.hpp:10:3: error: ‘TORCH_CHECK’ was not declared in this scope
     TORCH_CHECK(x.device().is_cuda(), #x " must be a CUDA tensor")
     ^
  /tmp/pip-install-0ggfooc5/mmcv-full/mmcv/ops/csrc/pytorch_cpp_helper.hpp:16:3: note: in expansion of macro ‘CHECK_CUDA’
     CHECK_CUDA(x);            \
     ^~~~~~~~~~
  ./mmcv/ops/csrc/pytorch/roi_pool.cpp:53:5: note: in expansion of macro ‘CHECK_CUDA_INPUT’
       CHECK_CUDA_INPUT(grad_output);
       ^~~~~~~~~~~~~~~~
  /tmp/pip-install-0ggfooc5/mmcv-full/mmcv/ops/csrc/pytorch_cpp_helper.hpp:10:3: note: suggested alternative: ‘AT_CHECK’
     TORCH_CHECK(x.device().is_cuda(), #x " must be a CUDA tensor")
     ^
  /tmp/pip-install-0ggfooc5/mmcv-full/mmcv/ops/csrc/pytorch_cpp_helper.hpp:16:3: note: in expansion of macro ‘CHECK_CUDA’
     CHECK_CUDA(x);            \
     ^~~~~~~~~~
  ./mmcv/ops/csrc/pytorch/roi_pool.cpp:53:5: note: in expansion of macro ‘CHECK_CUDA_INPUT’
       CHECK_CUDA_INPUT(grad_output);
       ^~~~~~~~~~~~~~~~
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for mmcv-full
  Running setup.py clean for mmcv-full
Failed to build mmcv-full
Installing collected packages: mmcv-full
    Running setup.py install for mmcv-full ... error
    ERROR: Command errored out with exit status 1:
     command: /home/lzh/anaconda3/envs/second/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0ggfooc5/mmcv-full/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0ggfooc5/mmcv-full/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-x2m04spt/install-record.txt --single-version-externally-managed --compile --install-headers /home/lzh/anaconda3/envs/second/include/python3.6m/mmcv-full
         cwd: /tmp/pip-install-0ggfooc5/mmcv-full/
    Complete output (333 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/mmcv
    copying mmcv/version.py -> build/lib.linux-x86_64-3.6/mmcv
	....
	....
	....
	....
    copying mmcv/video/optflow_warp/flow_warp_module.pyx -> build/lib.linux-x86_64-3.6/mmcv/video/optflow_warp
    running build_ext
    building 'mmcv._flow_warp_ext' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/mmcv
    creating build/temp.linux-x86_64-3.6/mmcv/video
    creating build/temp.linux-x86_64-3.6/mmcv/video/optflow_warp
    gcc -pthread -B /home/lzh/anaconda3/envs/second/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I./mmcv/video/optflow_warp -I/home/lzh/anaconda3/envs/second/lib/python3.6/site-packages/numpy/core/include -I/home/lzh/anaconda3/envs/second/include/python3.6m -c ./mmcv/video/optflow_warp/flow_warp_module.cpp -o build/temp.linux-x86_64-3.6/./mmcv/video/optflow_warp/flow_warp_module.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_flow_warp_ext -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from /home/lzh/anaconda3/envs/second/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1822:0,
                     from /home/lzh/anaconda3/envs/second/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                     from /home/lzh/anaconda3/envs/second/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from ./mmcv/video/optflow_warp/flow_warp_module.cpp:647:
    /home/lzh/anaconda3/envs/second/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it with " \
      ^~~~~~~
    gcc -pthread -B /home/lzh/anaconda3/envs/second/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I./mmcv/video/optflow_warp -I/home/lzh/anaconda3/envs/second/lib/python3.6/site-packages/numpy/core/include -I/home/lzh/anaconda3/envs/second/include/python3.6m -c ./mmcv/video/optflow_warp/flow_warp.cpp -o build/temp.linux-x86_64-3.6/./mmcv/video/optflow_warp/flow_warp.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_flow_warp_ext -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    g++ -pthread -shared -B /home/lzh/anaconda3/envs/second/compiler_compat -L/home/lzh/anaconda3/envs/second/lib -Wl,-rpath=/home/lzh/anaconda3/envs/second/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/./mmcv/video/optflow_warp/flow_warp_module.o build/temp.linux-x86_64-3.6/./mmcv/video/optflow_warp/flow_warp.o -o build/lib.linux-x86_64-3.6/mmcv/_flow_warp_ext.cpython-36m-x86_64-linux-gnu.so
    building 'mmcv._ext' extension
    creating build/temp.linux-x86_64-3.6/mmcv/ops
    creating build/temp.linux-x86_64-3.6/mmcv/ops/csrc
    creating build/temp.linux-x86_64-3.6/mmcv/ops/csrc/pytorch
    gcc -pthread -B /home/lzh/anaconda3/envs/second/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DMMCV_WITH_CUDA -I/tmp/pip-install-0ggfooc5/mmcv-full/mmcv/ops/csrc -I/home/lzh/anaconda3/envs/second/lib/python3.6/site-packages/torch/include -I/home/lzh/anaconda3/envs/second/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/lzh/anaconda3/envs/second/lib/python3.6/site-packages/torch/include/TH -I/home/lzh/anaconda3/envs/second/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/lzh/anaconda3/envs/second/include/python3.6m -c ./mmcv/ops/csrc/pytorch/info.cpp -o build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/info.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    gcc -pthread -B /home/lzh/anaconda3/envs/second/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DMMCV_WITH_CUDA -I/tmp/pip-install-0ggfooc5/mmcv-full/mmcv/ops/csrc -I/home/lzh/anaconda3/envs/second/lib/python3.6/site-packages/torch/include -I/home/lzh/anaconda3/envs/second/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/lzh/anaconda3/envs/second/lib/python3.6/site-packages/torch/include/TH -I/home/lzh/anaconda3/envs/second/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/lzh/anaconda3/envs/second/include/python3.6m -c ./mmcv/ops/csrc/pytorch/roi_pool.cpp -o build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/roi_pool.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from ./mmcv/ops/csrc/pytorch/roi_pool.cpp:1:0:
    ./mmcv/ops/csrc/pytorch/roi_pool.cpp: In function ‘void roi_pool_forward(at::Tensor, at::Tensor, at::Tensor, at::Tensor, int, int, float)’:
    /tmp/pip-install-0ggfooc5/mmcv-full/mmcv/ops/csrc/pytorch_cpp_helper.hpp:10:3: error: ‘TORCH_CHECK’ was not declared in this scope
       TORCH_CHECK(x.device().is_cuda(), #x " must be a CUDA tensor")
       ^
    /tmp/pip-install-0ggfooc5/mmcv-full/mmcv/ops/csrc/pytorch_cpp_helper.hpp:16:3: note: in expansion of macro ‘CHECK_CUDA’
       CHECK_CUDA(x);            \
       ^~~~~~~~~~
    ./mmcv/ops/csrc/pytorch/roi_pool.cpp:33:5: note: in expansion of macro ‘CHECK_CUDA_INPUT’
         CHECK_CUDA_INPUT(input);
         ^~~~~~~~~~~~~~~~
    /tmp/pip-install-0ggfooc5/mmcv-full/mmcv/ops/csrc/pytorch_cpp_helper.hpp:10:3: note: suggested alternative: ‘AT_CHECK’
       TORCH_CHECK(x.device().is_cuda(), #x " must be a CUDA tensor")
       ^
    /tmp/pip-install-0ggfooc5/mmcv-full/mmcv/ops/csrc/pytorch_cpp_helper.hpp:16:3: note: in expansion of macro ‘CHECK_CUDA’
       CHECK_CUDA(x);            \
       ^~~~~~~~~~
    ./mmcv/ops/csrc/pytorch/roi_pool.cpp:33:5: note: in expansion of macro ‘CHECK_CUDA_INPUT’
         CHECK_CUDA_INPUT(input);
         ^~~~~~~~~~~~~~~~
    ./mmcv/ops/csrc/pytorch/roi_pool.cpp: In function ‘void roi_pool_backward(at::Tensor, at::Tensor, at::Tensor, at::Tensor, int, int, float)’:
    /tmp/pip-install-0ggfooc5/mmcv-full/mmcv/ops/csrc/pytorch_cpp_helper.hpp:10:3: error: ‘TORCH_CHECK’ was not declared in this scope
       TORCH_CHECK(x.device().is_cuda(), #x " must be a CUDA tensor")
       ^
    /tmp/pip-install-0ggfooc5/mmcv-full/mmcv/ops/csrc/pytorch_cpp_helper.hpp:16:3: note: in expansion of macro ‘CHECK_CUDA’
       CHECK_CUDA(x);            \
       ^~~~~~~~~~
    ./mmcv/ops/csrc/pytorch/roi_pool.cpp:53:5: note: in expansion of macro ‘CHECK_CUDA_INPUT’
         CHECK_CUDA_INPUT(grad_output);
         ^~~~~~~~~~~~~~~~
    /tmp/pip-install-0ggfooc5/mmcv-full/mmcv/ops/csrc/pytorch_cpp_helper.hpp:10:3: note: suggested alternative: ‘AT_CHECK’
       TORCH_CHECK(x.device().is_cuda(), #x " must be a CUDA tensor")
       ^
    /tmp/pip-install-0ggfooc5/mmcv-full/mmcv/ops/csrc/pytorch_cpp_helper.hpp:16:3: note: in expansion of macro ‘CHECK_CUDA’
       CHECK_CUDA(x);            \
       ^~~~~~~~~~
    ./mmcv/ops/csrc/pytorch/roi_pool.cpp:53:5: note: in expansion of macro ‘CHECK_CUDA_INPUT’
         CHECK_CUDA_INPUT(grad_output);
         ^~~~~~~~~~~~~~~~
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/lzh/anaconda3/envs/second/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0ggfooc5/mmcv-full/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0ggfooc5/mmcv-full/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-x2m04spt/install-record.txt --single-version-externally-managed --compile --install-headers /home/lzh/anaconda3/envs/second/include/python3.6m/mmcv-full Check the logs for full command output.

**Comment by ycxioooong** [comment]
Hi @luzonghao1. Pytorch 1.1 is no longer supported by ``mmcv-full``. Please upgrade your PyTorch to at least 1.3.

**Comment by luzonghao1** [comment]
I use other lib need  Pytorch 1.1 .Which version can use??

**Comment by ycxioooong** [comment]
@luzonghao1  The older versions of ``mmcv`` do not support many CUDA operations that compatible with PyTorch 1.1.
So if you'd like to use these ops in ``mmcv-full``, then there is no version that satisfies your requirements.

**Comment by luzonghao1** [comment]
@ycxioooong Thank you.
