### ISSUE TITLE
"warmup_by_epoch" parameter does not work

### ISSUE THREAD

**Issue by shuaizzZ** [open-mmlab/mmcv#633]
mmcv/mmcv/runner/hooks/lr_updater.py
line134: if self.warmup is None or cur_iter > self.warmup_iters:

should be changed to: if self.warmup is None or cur_iter > self.warmup_epochs: ?

**Comment by hellock** [comment]
It should be `warmup_iters`, and `cur_iter` is not comparable to `self.warmup_epochs`.

**Comment by shuaizzZ** [comment]
Thanks, I read the code carefully and now I understand.
