### ISSUE TITLE
adding a progress bar during the train and val stage

### ISSUE THREAD

**Issue by shuaizzZ** [open-mmlab/mmcv#638]
Is there a plan to add a progress bar during the training and verification phase to facilitate observation of the progress?
such as ： 
for i, data_batch in enumerate(tqdm(self.data_loader))

**Comment by nbei** [comment]
Hi @shuaizzZ , thanks for your kind suggestion. We will consider your advice and have a further discussion.

In fact, there exists a customized [progress bar](https://github.com/open-mmlab/mmcv/blob/215a3244142687f2818b07947732ac1b152e8c75/mmcv/utils/progressbar.py) in our MMCV.

For evaluation, other repos based on MMCV is adopting this tool for convenient observation of the progress.
Taking MMDet as an example, they have already used our progress bar in their [test scripts](https://github.com/open-mmlab/mmdetection/blob/ac13907054bf5371dd9580c862b03e08b2a10102/mmdet/apis/test.py#L24).

This modification will influence other repos and we may have a careful discussion on it.
For now, I recommand that you may use our progress bar (just like MMDet) to observe the progress.
