### ISSUE TITLE
When I installed the environment verification, an error occurred: No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'

### ISSUE THREAD

**Issue by githubyaww** [open-mmlab/mmcv#641]
When I installed the environment verification, an error occurred:
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'

**Comment by ZwwWayne** [comment]
This might because your CUDA PATH is not correctly set. Please check your PATH and LD_LIBRARY_PATH.
