### ISSUE TITLE
mmcv.cnn.ConvModule is expected to work with conv3d, right?

### ISSUE THREAD

**Issue by hubutui** [open-mmlab/mmcv#649]
https://github.com/open-mmlab/mmcv/blob/1d5678c9fc6e96561b4ee5a9079d4a19e3da53c5/mmcv/cnn/bricks/conv_module.py#L29-L35
In these lines, the author mention conv2d, but it seems to work with conv3d too. We might need to update the doc.

**Comment by hubutui** [comment]
I found that mmaction2 is using it, see also https://github.com/open-mmlab/mmaction2/blob/303b62bc9dbd81a90bc3890da3a72231c060fbe9/mmaction/models/backbones/resnet3d.py#L95-L118
So, I believe we might need to update the doc.

**Comment by dreamerlin** [comment]
Update it in https://github.com/open-mmlab/mmcv/pull/651, it has been merged.

**Comment by dreamerlin** [comment]
This issue can be closed @hellock.
