### ISSUE TITLE
[feature request] add 3D support to build_upsample_layer

### ISSUE THREAD

**Issue by hubutui** [open-mmlab/mmcv#650]
Currently, `mmcv.cnn.build_upsample_layer` support type `nearest, bilinear, deconv, pixel_shuffle`. It means ` ConvTranspose2d` by deconv. It would be great if we also support `ConvTranspose3d`.

**Comment by dreamerlin** [comment]
Update it in https://github.com/open-mmlab/mmcv/pull/651

**Comment by dreamerlin** [comment]
My bad, I mix up this issue with , the linked PR should be https://github.com/open-mmlab/mmcv/pull/652
