### ISSUE TITLE
Prebuild mmcv_full with cuda110 do not support cuda

### ISSUE THREAD

**Issue by grimoire** [open-mmlab/mmcv#654]
Hi
I am not sure if I should ask this question here.

I am working on a cuda11 docker with mmcv_full. Follow [mmdetection docker](https://github.com/open-mmlab/mmdetection/blob/master/docker/Dockerfile), I trying to install prebuild mmcv_full from [https://openmmlab.oss-accelerate.aliyuncs.com/mmcv/dist/index.html](https://openmmlab.oss-accelerate.aliyuncs.com/mmcv/dist/index.html).

But the the [mmcv_full-1.2.0+torch1.7.0+cu110](https://openmmlab.oss-accelerate.aliyuncs.com/mmcv/dist/1.2.0/torch1.7.0/cu110/mmcv_full-1.2.0%2Btorch1.7.0%2Bcu110-cp36-cp36m-manylinux1_x86_64.whl) in docker does not seems build with cuda. The whl size is 10.5MB, same as cpu version. 

mmcv_full1.2.0+torch1.7.0 with cuda102 and cuda101 have size 19.8MB.

**Comment by ycxioooong** [comment]
Hi @grimoire I'll check out this issue soon. Sorry for my late reply.

**Comment by TTXXXL** [comment]
same problem hope it can fix up soon

**Comment by ycxioooong** [comment]
Solved in recent versions (>1.2.0)
