### ISSUE TITLE
Process of "module" in state_dict.keys in load_checkpoint

### ISSUE THREAD

**Issue by nicheng0019** [open-mmlab/mmcv#658]
Hi, a doubt about implementation of function "load_checkpoint":

https://github.com/open-mmlab/mmcv/blob/ec43b671abd8c60c4763ac26391f9ae31edeb844/mmcv/runner/checkpoint.py#L253-L259

"checkpoint['state_dict'] " may be "state_dict" in Line 259?

**Comment by xvjiarui** [comment]
Hi @nicheng0019 
Could you please elaborate more? `'state_dict'` is the same as `"state_dict"`.

**Comment by nicheng0019** [comment]
Hi @xvjiarui, 'state_dict' means variable state_dict in line 254/256

**Comment by xvjiarui** [comment]
Got you. 
You are correct. Would you like to create a PR to fix it?

**Comment by nicheng0019** [comment]
@xvjiarui ok, I have created a PR.
