### ISSUE TITLE
Error when batch size is 64 using DeformConv2dPack

### ISSUE THREAD

**Issue by pppLang** [open-mmlab/mmcv#661]
In [1]: import torch                                                                                                                                                                          

In [2]: from mmcv.ops import DeformConv2dPack                                                                                                                                                 

In [3]: conv = DeformConv2dPack(64,64,3).cuda()                                                                                                                                               

In [4]: a = torch.randn(64,64,64,64).cuda()                                                                                                                                                   

In [5]: conv(a).shape                                                                                                                                                                         
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-5-59c7cb2bbcec> in <module>
----> 1 conv(a).shape

~/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

~/anaconda3/envs/py37/lib/python3.7/site-packages/mmcv/ops/deform_conv.py in forward(self, x)
    295         offset = self.conv_offset(x)
    296         return deform_conv2d(x, offset, self.weight, self.stride, self.padding,
--> 297                              self.dilation, self.groups, self.deform_groups)
    298 
    299     def _load_from_state_dict(self, state_dict, prefix, local_metadata, strict,

~/anaconda3/envs/py37/lib/python3.7/site-packages/mmcv/ops/deform_conv.py in forward(ctx, input, offset, weight, stride, padding, dilation, groups, deform_groups, bias, im2col_step)
     96             group=ctx.groups,
     97             deformable_group=ctx.deform_groups,
---> 98             im2col_step=cur_im2col_step)
     99         return output
    100 

RuntimeError: shape '[1, 1, 64, 64, 3]' is invalid for input of size 36864

**Comment by chunfuchen** [comment]
I got the same error but it works if I change to batch size 32.

**Comment by ycxioooong** [comment]
Hi, @pppLang @chunfuchen you are right. Currently, bugs exist when using batch size > 32. 
So it's suggested to use batch_size <= 32.

Previously we fix this bug but it causes other errors so we revert the DeformableConv. 
We'll keep tracking this issue and propose better solutions in the future.

**Comment by zimenglan-sysu-512** [comment]
hi @ycxioooong 
did u solve the problem?
any help is appriciated.
