### ISSUE TITLE
How to make the priority of the parameters entered in the terminal higher than the priority of the parameters in the config file.

### ISSUE THREAD

**Issue by shuaizzZ** [open-mmlab/mmcv#664]
I hope to modify some of the parameters reused in the config file on the terminal. For example, the “crop_size ” in datasets, which is reused in “train_pipeline” and “test_pipeline”. I found that after I modified the value of cfg.crop_size through the parameters entered in the terminal, cfg.pipeline.crop_size was not changed.

**Comment by xvjiarui** [comment]
Hi @shuaizzZ 
Modifying intermediate variables won't take effect. See details [here](https://mmdetection.readthedocs.io/en/latest/tutorials/config.html?highlight=config#use-intermediate-variables-in-configs).

**Comment by shuaizzZ** [comment]
Is there any suggested way to modify the intermediate variables first.

**Comment by xvjiarui** [comment]
Currently, modifying intermediate variables are not supported from cmd.
