### ISSUE TITLE
PyTorch initialization

### ISSUE THREAD

**Issue by brdav** [open-mmlab/mmcv#665]
Hello,
when I was looking through the code for initializing ConvModule I was running across this line:
https://github.com/open-mmlab/mmcv/blob/d2fa1abc5358fe146071f4b4f684cc745ea327f5/mmcv/cnn/bricks/conv_module.py#L174
It is mentioned that pytorch Convs will be initialized by their own reset_parameters method. But since they don't have an init_weight attribute, that initialization will be overriden right?

**Comment by nbei** [comment]
Hi @brdav , sorry for the late reply and the confusing description for this function. You are right that the initialization of all of the convolutional layers will be overriden. Even if there exist `reset_parameters()` function in PyTorch's Conv2d, our `ConvModule` will **re-initialize** it in the end. 

If no further questions, this issue will be closed later.
