### ISSUE TITLE
Can you provide the. whl file of mmcv0.5.8

### ISSUE THREAD

**Issue by GitVae** [open-mmlab/mmcv#666]
Hello,
  For some reason, I cannot install mmcv from source. Can you Can you provide the. whl file of mmcv 0.5.8 (not mmcv-full), I want to do some experiments. Just like mmcv-full: https://download.openmmlab.com/mmcv/dist/index.html.
I want mmcv-0.5.8+torch1.3.0+cu100-cp37-cp37m-manylinux1_x86_64.whl.whl  with python 3.7 and cuda 10.0 and torch 1.3.0. Thank you very very much. Best wished to you.

**Comment by ycxioooong** [comment]
this also works: ``pip install mmcv==0.5.8``.
