### ISSUE TITLE
Could you please provide the precompiled file with cuda 11.0 running on windows?

### ISSUE THREAD

**Issue by forallsunday** [open-mmlab/mmcv#667]
My gpu is rtx 3080, and for some reason I have to use windows 10.
I can't compile successfully, and when I tried to using torch1.60 + cuda10.2, precompiled mmcv 1.1.5, it seems that rtx 3080 is not competible with cuda 10.2 . 
So, could you please provide the wheel file with cuda 11.0 of amd64? I really appreciate it.

**Comment by ycxioooong** [comment]
@forallsunday It's in progress, please stay tuned :)

**Comment by forallsunday** [comment]
> @forallsunday It's in progress, please stay tuned :)

Really looking forward to it. I've kept trying to install mmcv-full these days, but failed again and again. Frustrated. :<

**Comment by hellock** [comment]
Already done.
