### ISSUE TITLE
Installing mmcv-full from source code on win10 reports the following error:

### ISSUE THREAD

**Issue by shuaizzZ** [open-mmlab/mmcv#671]
C:/Users/ainnovation/Anaconda3/envs/mv/lib/site-packages/torch/include/torch/csrc/api/include\torch/serialize/output-archive.h(74): warning: field of class type without a DLL interface used in a class with a DLL interface

    1 error detected in the compilation of "C:/Users/AINNOV~1/AppData/Local/Temp/tmpxft_000010c4_00000000-10_psamask_cuda.cpp1.ii".
    psamask_cuda.cu
    error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1\\bin\\nvcc.exe' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\ainnovation\Anaconda3\envs\mv\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\AINNOV~1\\AppData\\Local\\Temp\\pip-req-build-4q78qs_u\\setup.py'"'"'; __file__='"'"'C:\\Users\\AINNOV~1\\AppData\\Local\\Temp\\pip-req-build-4q78qs_u\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\AINNOV~1\AppData\Local\Temp\pip-record-fmiug7kx\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\ainnovation\Anaconda3\envs\mv\Include\mmcv-full' Check the logs for full command output.

**Comment by hellock** [comment]
Did you follow the [installation guide](https://mmcv.readthedocs.io/en/latest/build.html#build-on-windows)?
