### ISSUE TITLE
EMAHook before or after optimizerHook?

### ISSUE THREAD

**Issue by twmht** [open-mmlab/mmcv#689]
Hi,

in most of the implementations, ema should happen after optimizer update. but how can I specify the priority order? if I set emaHook as a HIGH priority, it would run before optimzerHook, but if i set emaHook as a low priority (or same priority with optimizerHook), it would run after optimzerHook but also checkpointHook.

to clarify my quest, how can I specify the emaHook runs after optimizerHook but before the other un-running hook (like checkpointHook)?

**Comment by Johnson-Wang** [comment]
If the priority of a custom hook is set, it is inserted at the end of all existing hooks of the same priority. In your case, OptimizerHook and CheckpointHook are all of 'NORMAL' priority by default. Therefore, there is no such a way to insert a custom hook in between OptimizerHook and CheckpointHook. You may manually insert the EMAHook after [this line](https://github.com/open-mmlab/mmcv/blob/d5241b70871c0664a1584989b58d7c507c240278/mmcv/runner/base_runner.py#L434)
