### ISSUE TITLE
hang in pip install mmcv

### ISSUE THREAD

**Issue by JoyLuo** [open-mmlab/mmcv#69]
use pip install mmcv to install
but hang when finish the downloading mmcv-0.2.7.tar.gz

**Comment by JoyLuo** [comment]
pip install all requires, including install_requires setup_requires and tests_require
use pip install . can install mmcv successful

**Comment by wikiwen** [comment]
Same problem, Worked by ```pip install pytest-runner``` at first

**Comment by cizhenshi** [comment]
> Same problem, Worked by `pip install pytest-runner` at first

I face the same problem when installing mmcv 0.2.14.  But it doesn't worked for me. Do you have any idea?

**Comment by caiqi** [comment]
Creating a file ~/.pydistutils.cfg with content:
```
[easy_install]  
index-url=http://some_pip_mirror_path/pypi/simple
``` 
worked for me. I was installing mmcv on a server that has no public Internet access. The pip source is set to an internal mirror. The problem is that the setup tool during installing uses the default pip mirror which could not be reached.
