### ISSUE TITLE
pip install mmcv-full

### ISSUE THREAD

**Issue by yy18dlz** [open-mmlab/mmcv#697]
hi, when i use pip install mmcv-full.
There seems to be no compilation process.It only takes a second...
and print Successfully installed mmcv-full-1.2.1

**Comment by ycxioooong** [comment]
You may use 
```pip install mmcv-full===1.2.1 -f https://download.openmmlab.com/mmcv/dist/{cuda_version}/{torch_version}/index.html```
to install mmcv-full.
Please specify ``{cuda_version}``(e.g., cu101) and ``{torch_version}``(e.g., torch1.6.0)
