### ISSUE TITLE
pip install mmcv-full==latest+torch1.7.0+cu101

### ISSUE THREAD

**Issue by Karonzhjr** [open-mmlab/mmcv#698]
pip install mmcv-full==latest+torch1.7.0+cu101 -f https://download.openmmlab.com/mmcv/dist/index.html
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Looking in links: https://download.openmmlab.com/mmcv/dist/index.html
ERROR: Could not find a version that satisfies the requirement mmcv-full==latest+torch1.7.0+cu101
ERROR: No matching distribution found for mmcv-full==latest+torch1.7.0+cu101

**Comment by chaowentao** [comment]
You can find your proper version from https://download.openmmlab.com/mmcv/dist/index.html. 
Then, 
`pip install https://download.openmmlab.com/mmcv/dist/latest/torch1.7.0/cu101/mmcv_full-latest%2Btorch1.7.0%2Bcu101-cp36-cp36m-manylinux1_x86_64.whl `
I install the mmcv-full through the way.

**Comment by ycxioooong** [comment]
Please check your pip version first. There is a big change in pip 20.3 which influences the installation.
For pip >= 20.3 please use the following command to install ``mmcv-full``:
```
# please replace mmcv_version, cuda_version, torch_version
pip install mmcv-full==={mmcv_version} -f https://download.openmmlab.com/mmcv/dist/{cuda_version}/{torch_version}/index.html
```

for your case, please use:
```
pip install mmcv-full===1.2.1 -f https://download.openmmlab.com/mmcv/dist/cu101/torch1.7.0/index.html
```

For details, please refer to this PR #703.

**Comment by Kaeseknacker** [comment]
Is that a typo with the three equal signs?!

**Comment by ycxioooong** [comment]
@Kaeseknacker three equals and two equals are both OK. To avoid some corner cases, we use three equals in instructions.
