### ISSUE TITLE
untimeError: nms is not compiled with GPU support

### ISSUE THREAD

**Issue by Chasing987** [open-mmlab/mmcv#704]
hi! I am using the open-mmlab to train the voc2007!Next is my environment:ubuntu16.04,gtx1080ti,pytorch1.5,cuda10.2.Now i planning to use the faster r cnn to train the voc2007.when i use this sentence:
`python tools/train.py ./configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py`,it occurs this error:runtimeError: nms is not compiled with GPU support!
could you tell me how to solve this problem!tks! @nizhib @DXist @tjsongzw @twmht

**Comment by Chasing987** [comment]
@hellock @xvjiarui @ZwwWayne

**Comment by ycxioooong** [comment]
Please refer to this issue: https://github.com/open-mmlab/mmdetection/issues/2686
