### ISSUE TITLE
MMCV_WITH_OPS=1 pip install -e .  ERROR!

### ISSUE THREAD

**Issue by CnybTseng** [open-mmlab/mmcv#712]
root@eb7398d8aac0:/data/tseng/project/thirdparty/mmcv# MMCV_WITH_OPS=1 pip install -e .
Obtaining file:///data/tseng/project/thirdparty/mmcv
Requirement already satisfied: addict in /opt/conda/lib/python3.6/site-packages (from mmcv-full==1.2.1) (2.2.1)
Requirement already satisfied: numpy in /opt/conda/lib/python3.6/site-packages (from mmcv-full==1.2.1) (1.19.2)
Requirement already satisfied: Pillow in /opt/conda/lib/python3.6/site-packages (from mmcv-full==1.2.1) (6.1.0)
Requirement already satisfied: pyyaml in /opt/conda/lib/python3.6/site-packages (from mmcv-full==1.2.1) (5.3.1)
Requirement already satisfied: yapf in /opt/conda/lib/python3.6/site-packages (from mmcv-full==1.2.1) (0.30.0)
Installing collected packages: mmcv-full
  Running setup.py develop for mmcv-full
    ERROR: Command errored out with exit status 1:
     command: /opt/conda/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/tseng/project/thirdparty/mmcv/setup.py'"'"'; __file__='"'"'/data/tseng/project/thirdparty/mmcv/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /data/tseng/project/thirdparty/mmcv/
    Complete output (116 lines):
    running develop
    running egg_info
    writing mmcv_full.egg-info/PKG-INFO
    writing dependency_links to mmcv_full.egg-info/dependency_links.txt
    writing requirements to mmcv_full.egg-info/requires.txt
    writing top-level names to mmcv_full.egg-info/top_level.txt
    reading manifest file 'mmcv_full.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'mmcv_full.egg-info/SOURCES.txt'
    running build_ext
    building 'mmcv._ext' extension
    creating build
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/mmcv
    creating build/temp.linux-x86_64-3.6/mmcv/ops
    creating build/temp.linux-x86_64-3.6/mmcv/ops/csrc
    creating build/temp.linux-x86_64-3.6/mmcv/ops/csrc/pytorch
    /usr/local/cuda/bin/nvcc -DMMCV_WITH_CUDA -I/data/tseng/project/thirdparty/mmcv/mmcv/ops/csrc -I/opt/conda/lib/python3.6/site-packages/torch/include -I/opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/lib/python3.6/site-packages/torch/include/TH -I/opt/conda/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/opt/conda/include/python3.6m -c ./mmcv/ops/csrc/pytorch/psamask_cuda.cu -o build/temp.linux-x86_64-3.6/./mmcv/ops/csrc/pytorch/psamask_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
    ./mmcv/ops/csrc/pytorch/psamask_cuda.cu(21): error: a pointer to a bound function may only be used to call the function

    ./mmcv/ops/csrc/pytorch/psamask_cuda.cu(21): error: type name is not allowed

    ./mmcv/ops/csrc/pytorch/psamask_cuda.cu(21): error: expected an expression

    ./mmcv/ops/csrc/pytorch/psamask_cuda.cu(21): error: a pointer to a bound function may only be used to call the function

    ./mmcv/ops/csrc/pytorch/psamask_cuda.cu(21): error: type name is not allowed

    ./mmcv/ops/csrc/pytorch/psamask_cuda.cu(21): error: expected an expression

    ./mmcv/ops/csrc/pytorch/psamask_cuda.cu(21): error: a pointer to a bound function may only be used to call the function

    ./mmcv/ops/csrc/pytorch/psamask_cuda.cu(21): error: type name is not allowed

    ./mmcv/ops/csrc/pytorch/psamask_cuda.cu(21): error: expected an expression

    ./mmcv/ops/csrc/pytorch/psamask_cuda.cu(21): error: a pointer to a bound function may only be used to call the function

    ./mmcv/ops/csrc/pytorch/psamask_cuda.cu(21): error: type name is not allowed

    ./mmcv/ops/csrc/pytorch/psamask_cuda.cu(21): error: expected an expression

    ./mmcv/ops/csrc/pytorch/psamask_cuda.cu(29): error: a pointer to a bound function may only be used to call the function

    ./mmcv/ops/csrc/pytorch/psamask_cuda.cu(29): error: type name is not allowed

    ./mmcv/ops/csrc/pytorch/psamask_cuda.cu(29): error: expected an expression

    ./mmcv/ops/csrc/pytorch/psamask_cuda.cu(29): error: a pointer to a bound function may only be used to call the function

    ./mmcv/ops/csrc/pytorch/psamask_cuda.cu(29): error: type name is not allowed

    ./mmcv/ops/csrc/pytorch/psamask_cuda.cu(29): error: expected an expression

    ./mmcv/ops/csrc/pytorch/psamask_cuda.cu(29): error: a pointer to a bound function may only be used to call the function

    ./mmcv/ops/csrc/pytorch/psamask_cuda.cu(29): error: type name is not allowed

    ./mmcv/ops/csrc/pytorch/psamask_cuda.cu(29): error: expected an expression

    ./mmcv/ops/csrc/pytorch/psamask_cuda.cu(29): error: a pointer to a bound function may only be used to call the function

    ./mmcv/ops/csrc/pytorch/psamask_cuda.cu(29): error: type name is not allowed

    ./mmcv/ops/csrc/pytorch/psamask_cuda.cu(29): error: expected an expression

    ./mmcv/ops/csrc/pytorch/psamask_cuda.cu(46): error: a pointer to a bound function may only be used to call the function

    ./mmcv/ops/csrc/pytorch/psamask_cuda.cu(46): error: type name is not allowed

    ./mmcv/ops/csrc/pytorch/psamask_cuda.cu(46): error: expected an expression

    ./mmcv/ops/csrc/pytorch/psamask_cuda.cu(46): error: a pointer to a bound function may only be used to call the function

    ./mmcv/ops/csrc/pytorch/psamask_cuda.cu(46): error: type name is not allowed

    ./mmcv/ops/csrc/pytorch/psamask_cuda.cu(46): error: expected an expression

    ./mmcv/ops/csrc/pytorch/psamask_cuda.cu(46): error: a pointer to a bound function may only be used to call the function

    ./mmcv/ops/csrc/pytorch/psamask_cuda.cu(46): error: type name is not allowed

    ./mmcv/ops/csrc/pytorch/psamask_cuda.cu(46): error: expected an expression

    ./mmcv/ops/csrc/pytorch/psamask_cuda.cu(46): error: a pointer to a bound function may only be used to call the function

    ./mmcv/ops/csrc/pytorch/psamask_cuda.cu(46): error: type name is not allowed

    ./mmcv/ops/csrc/pytorch/psamask_cuda.cu(46): error: expected an expression

    ./mmcv/ops/csrc/pytorch/psamask_cuda.cu(54): error: a pointer to a bound function may only be used to call the function

    ./mmcv/ops/csrc/pytorch/psamask_cuda.cu(54): error: type name is not allowed

    ./mmcv/ops/csrc/pytorch/psamask_cuda.cu(54): error: expected an expression

    ./mmcv/ops/csrc/pytorch/psamask_cuda.cu(54): error: a pointer to a bound function may only be used to call the function

    ./mmcv/ops/csrc/pytorch/psamask_cuda.cu(54): error: type name is not allowed

    ./mmcv/ops/csrc/pytorch/psamask_cuda.cu(54): error: expected an expression

    ./mmcv/ops/csrc/pytorch/psamask_cuda.cu(54): error: a pointer to a bound function may only be used to call the function

    ./mmcv/ops/csrc/pytorch/psamask_cuda.cu(54): error: type name is not allowed

    ./mmcv/ops/csrc/pytorch/psamask_cuda.cu(54): error: expected an expression

    ./mmcv/ops/csrc/pytorch/psamask_cuda.cu(54): error: a pointer to a bound function may only be used to call the function

    ./mmcv/ops/csrc/pytorch/psamask_cuda.cu(54): error: type name is not allowed

    ./mmcv/ops/csrc/pytorch/psamask_cuda.cu(54): error: expected an expression

    48 errors detected in the compilation of "/tmp/tmpxft_00002c0b_00000000-6_psamask_cuda.cpp1.ii".
    error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/conda/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/tseng/project/thirdparty/mmcv/setup.py'"'"'; __file__='"'"'/data/tseng/project/thirdparty/mmcv/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
root@eb7398d8aac0:/data/tseng/project/thirdparty/mmcv#

**Comment by ycxioooong** [comment]
Seems like the problem may be caused by the version conflict of CUDA and gcc. Could you report your CUDA version and GCC version?

**Comment by cymdhx** [comment]
I'm the same mistake. How can I solve it

**Comment by cymdhx** [comment]
![Uploading image.png…]()

**Comment by xiaotaoFzzf** [comment]
> I'm the same mistake. How can I solve it

Do you solve it?I am the same mistake.

**Comment by cymdhx** [comment]
> > I'm the same mistake. How can I solve it
> 
> Do you solve it?I am the same mistake.



> > 我也犯了同样的错误。我怎样才能解决这个问题？
> 
> 你解决了吗？我也犯了同样的错误。

没有 我就装了cpu版本的
