### ISSUE TITLE
Feature Request: Support num_channels_per_group in group normalization

### ISSUE THREAD

**Issue by Parskatt** [open-mmlab/mmcv#723]
# Motivation

Certain networks, such as HRNet, have very different numbers of channels depending on the branch. Only being able to supply "num_groups", while ignoring the number of channels could hurt performance.

# Suggestion

Change
https://github.com/open-mmlab/mmcv/blob/508a322fba81aaf9dd0c215ca8fd44a511a53da4/mmcv/cnn/bricks/norm.py#L112-L115

To enable "num_channels_per_group", and setting num_groups to "num_channels//num_channels_per_group"

A more general suggestion for automatically deciding this was proposed recently in this issue: https://github.com/open-mmlab/mmcv/issues/688

**Comment by Erotemic** [comment]
This is related to the issue I raised here: #688

**Comment by Parskatt** [comment]
@Erotemic Woops, sorry for not checking properly! I'll reference it at the top :)

**Comment by ZwwWayne** [comment]
Since this issue duplicates https://github.com/open-mmlab/mmcv/issues/723, we will close this issue and trace the progress in #688. Feel free to reopen this issue if you have any further questions.
