### ISSUE TITLE
Support more pretrained models from mmcls?

### ISSUE THREAD

**Issue by hiyyg** [open-mmlab/mmcv#735]
Currently only a subset of mmcls pretrained models are supported here. For other mmcls pretrained models, I have to use a custom load_checkpoint function because the mmcls models requires a processiong step. I wonder if the mmcv team will include other mmcls models into the model zoo?

**Comment by xvjiarui** [comment]
Hi @hiyyg 
You may use `mmcls://`. You may refer to [here](https://github.com/open-mmlab/mmcv/blob/master/mmcv/model_zoo/mmcls.json) for mapping.

**Comment by hiyyg** [comment]
As I said, this file only includes a subset of mmcls models.

**Comment by xvjiarui** [comment]
I see. @ycxioooong please including new mmcls models in MMCV.

**Comment by hellock** [comment]
Resolved in #741. Thanks @hiyyg
