### ISSUE TITLE
RuntimeError: SigmoidFocalLoss is not compiled with GPU support

### ISSUE THREAD

**Issue by zehuichen123** [open-mmlab/mmcv#736]
Hi, I am trying to install mmcv-full with cuda10.2 and torch1.6, however, I got this error when running mmdet.
```
RuntimeError: SigmoidFocalLoss is not compiled with GPU support
```
Here is some info about my machine:
```
<Trial 1886566 worker_0> mmdetection $ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89
```
GPU: V100; torch version: 1.6.0;
I run mmcv-full by the following command and no mmcv is installed before:
![image](https://user-images.githubusercontent.com/24351120/102684262-0a06e280-4212-11eb-8d3e-d1f8cd9ca37a.png)

**Comment by zehuichen123** [comment]
Hi, this problem disappeared when I use pip < 20.3 to install mmcv-full. Maybe you can have a look at that. Thanks!

**Comment by ycxioooong** [comment]
Sorry for the late reply, you may refer to [this issue](https://github.com/open-mmlab/mmdetection/issues/2686).
