### ISSUE TITLE
Non-portable latest checkpoint symlink

### ISSUE THREAD

**Issue by nizhib** [open-mmlab/mmcv#74]
As for now the latest checkpoint created by [runner.py](../blob/master/mmcv/runner/runner.py#L247) is a symlink to a full path of the target checkpoint. Renaming or moving the original folder results into invalid symlink.

Should we change
```python
filename = osp.join(out_dir, filename_tmpl.format(self.epoch + 1))
linkname = osp.join(out_dir, 'latest.pth')
...
mmcv.symlink(filename, linkname)
```
to
```python
filename = osp.join(filename_tmpl.format(self.epoch + 1))
linkname = osp.join(out_dir, 'latest.pth')
...
mmcv.symlink(filename, linkname)
```
to make it relative and thus moving/renaming-proof?

If it's ok I can create a pull request.

**Comment by hellock** [comment]
It would be nice for a pull request to fix this.

Will this solution work for arbitrary `out_dir`?

**Comment by nizhib** [comment]
Yes it will as the link will point to the file in the same directory.
