### ISSUE TITLE
why mmcv is slow when using torch.cuda.amp.autocast()?

### ISSUE THREAD

**Issue by twmht** [open-mmlab/mmcv#742]
the newer version of pytorch has mixed precision training (https://pytorch.org/docs/stable/notes/amp_examples.html#amp-examples)

I think it's much more convenient and can be easily injected into mmcv.

for example, you can modify the `epoch_base_runner`  (https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/epoch_based_runner.py#L40) as following,

```
        for i, data_batch in enumerate(self.data_loader):
            self._inner_iter = i
            self.call_hook('before_train_iter')
            with torch.cuda.amp.autocast():
                self.run_iter(data_batch, train_mode=True)
            self.call_hook('after_train_iter')
            self._iter += 1
```

but I found out the speed is the same as fp32. I have tried that in my early project without mmcv and mmdetection support, and the experiment shows that fp16 is significantly faster than fp32. 

I am wondering why mmcv does not get speed up.

any idea?

**Comment by hellock** [comment]
MMCV has its own mixed precision training implementation and has been tested on various models in downstream codebases, and significant speedup is observed. It may not be compatible with just a single-line modification shown above.
In fact we are drafting a refactoring which adopts the official implementation in higher pytorch versions and our own implementations in lower versions.

**Comment by twmht** [comment]
@hellock 

the reason why i tried to use official pytorch fp16 is that when using internal mmcv fp16, it would throw an exception that my model is half precision but my input tensor if float precision. And I have no idea where to modify the input tensor to half.

any idea?

**Comment by twmht** [comment]
ok

I have fixed the issue i have when using internal mmcv fp16. but the speed is still the same as fp32.
