### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by xiaowanzizz** [open-mmlab/mmcv#744]
Python: 3.7.0 | packaged by conda-forge | (default, Nov 12 2018, 20:15:55) [GCC 7.3.0]
CUDA available: True
GPU 0: GeForce RTX 3070
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.0_bu.TC445_37.28540450_0
GCC: gcc (Ubuntu 7.5.0-6ubuntu2) 7.5.0
PyTorch: 1.7.0+cu110
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80
  - CuDNN 8.0.4
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.8.1+cu110
OpenCV: 4.4.0
MMCV: 1.2.2
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.0
MMDetection: 2.7.0+

File "/home/zzf/miniconda3/envs/torch1.7.0/lib/python3.7/site-packages/mmdet-2.7.0-py3.7.egg/mmdet/models/dense_heads/anchor_head.py", line 571, in get_bboxes
scale_factor, cfg, rescale)
File "/home/zzf/miniconda3/envs/torch1.7.0/lib/python3.7/site-packages/mmdet-2.7.0-py3.7.egg/mmdet/models/dense_heads/rpn_head.py", line 167, in get_bboxes_single
dets, keep = batched_nms(proposals, scores, ids, nms_cfg)
File "/home/zzf/miniconda3/envs/torch1.7.0/lib/python3.7/site-packages/mmcv/ops/nms.py", line 259, in batched_nms
dets, keep = nms_op(boxes_for_nms, scores, **nms_cfg)
File "/home/zzf/miniconda3/envs/torch1.7.0/lib/python3.7/site-packages/mmcv/utils/misc.py", line 310, in new_func
output = old_func(*args, **kwargs)
File "/home/zzf/miniconda3/envs/torch1.7.0/lib/python3.7/site-packages/mmcv/ops/nms.py", line 113, in nms
inds = NMSop.apply(boxes, scores, iou_threshold, offset)
File "/home/zzf/miniconda3/envs/torch1.7.0/lib/python3.7/site-packages/mmcv/ops/nms.py", line 19, in forward
bboxes, scores, iou_threshold=float(iou_threshold), offset=offset)
RuntimeError: CUDA error: no kernel image is available for execution on the device

Are there any bugs in your library for torch 1.7.0 cuda11.1 that have not been fixed？
hope you can tell me the answer
my english is not good
Please forgive me for any offence

**Comment by TTXXXL** [comment]
I have the same question, it can run gfl but cant run cascade_rcnn or any other two-stage detector,by the way i use cuda 11.0.

**Comment by wangruohui** [comment]
The problems shoule lies at compilation. GeForce RTX 3070 is of compute capacity 8.6, but this version of mmcv may not be compiled with option `sm_86` or `compute_86`. Even from the log I found pytorch itself is not compiled with compute_86. 

As mmcv is already updated to new version, would you please first try the latest version? Its also better to reinstall pytorch too see if compute_86 is supported.

**Comment by xiaowanzizz** [comment]
Pytorch is update to 1.7.1,I can install MMCV by git clone from MMCV-master,and Pytorch 1.7.1 is supporting compute-86
But there are some problems when I import dcn

thank you for your work 
Forgive my bad English
