### ISSUE TITLE
Fusing conv and bn layer does not provide same result ?

### ISSUE THREAD

**Issue by CoinCheung** [open-mmlab/mmcv#747]
Hi,

I tested the fusion method in the mmcv like this:
```
from mmcv.cnn import fuse_conv_bn
seq = nn.Sequential(torch.nn.Conv2d(3, 32, 3, 1, 1), torch.nn.BatchNorm2d(32))
seq.eval()

inten = torch.randn(2, 3, 224, 224)
out1 = seq(inten)

fused = fuse_conv_bn(seq).eval()
out2 = fused(inten)
print((out1 - out2).abs().sum())
```
The result is: `tensor(0.1850)`. What is the problem coming from please? It seems that when I replace one pair of conv-bn operation in a pretrained model, the inference result would be different greatly from the original result.

**Comment by yhcao6** [comment]
Can you print sum of `out1` and `out2`, I guess the relative error should be small.
I test the `fuse-conv-bn` flag of a [detection model](https://github.com/open-mmlab/mmdetection/blob/master/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py) the performance is consistent.
Can you provide more details about how you test?

**Comment by CoinCheung** [comment]
Thanks for replying !! I had some error in my code, the fusing code is working well.

**Comment by jeannotes** [comment]
@CoinCheung where is the error in the code
