### ISSUE TITLE
Why using 'spawn' instead of 'fork' as the start method of multiprocessing?

### ISSUE THREAD

**Issue by leeeeeeo** [open-mmlab/mmcv#749]
In [dist_utils.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/dist_utils.py#L18), 'spawn' is set as the start method of multiprocessing, which may cause OOM when using large scale dataset. 

The default start method is 'fork'. Why set to 'spawn' instead?

Thank you!

**Comment by twmht** [comment]
I tried to replace spawn with fork and it works well.

**Comment by leeeeeeo** [comment]
@twmht That's why I raise this issue. I'm wondering the difference between them, and why using 'spawn' instead of 'fork'? @hellock

**Comment by ycxioooong** [comment]
Hi @leeeeeeo, you may refer to the PyTorch multiprocessing best practice [here](https://pytorch.org/docs/stable/notes/multiprocessing.html). You may notice that: 
> The CUDA runtime does not support the fork start method; either the spawn or forkserver start method are required to use CUDA in subprocesses.

That's why we set start method as 'spawn'.
