### ISSUE TITLE
win10 cuda10.1+pytorch1.6 pip install stopped a very long time

### ISSUE THREAD

**Issue by bbbxixixixi** [open-mmlab/mmcv#756]
my torch vision is 1.6.0+cu101, I tried to install by command 'pip install mmcv-full',  after download mmcv-full-1.2.2.tar.gz , the cmd stopped for a very very long time, maybe 5 hours. I closed the cmd and restart another, I changed the install command to 'pip install mmcv-full===1.2.2 -f https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html -vvv', the process still stopped. I have being waiting for a night and it seems not be able to continue.

the output is below:
Using pip 20.3.3 from d:\python\python37\lib\site-packages\pip (python 3.7)
Non-user install because site-packages writeable
Created temporary directory: C:\Users\ADMINI~1\AppData\Local\Temp\pip-ephem-wheel-cache-ibxw3mx6
Created temporary directory: C:\Users\ADMINI~1\AppData\Local\Temp\pip-req-tracker-vd063ox8
Initialized build tracking at C:\Users\ADMINI~1\AppData\Local\Temp\pip-req-tracker-vd063ox8
Created build tracker: C:\Users\ADMINI~1\AppData\Local\Temp\pip-req-tracker-vd063ox8
Entered build tracker: C:\Users\ADMINI~1\AppData\Local\Temp\pip-req-tracker-vd063ox8
Created temporary directory: C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-52kllgyt
Looking in links: https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html
2 location(s) to search for versions of mmcv-full:
* https://pypi.org/simple/mmcv-full/
* https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html
Skipping link: unsupported archive format: .html: https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html (from -f)
Fetching project page and analyzing links: https://pypi.org/simple/mmcv-full/
Getting page https://pypi.org/simple/mmcv-full/
Found index url https://pypi.org/simple
Looking up "https://pypi.org/simple/mmcv-full/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/mmcv-full/ HTTP/1.1" 304 0
  Found link https://files.pythonhosted.org/packages/40/a9/f1d560b6ed558039a020db617bd643ac434d7407cfedc2073e6385ab22e6/mmcv-full-1.0rc0.tar.gz#sha256=8130210ce29dd22cafec3e0ec8e56a59ee0d7c4990c6b24dbd3884912d0c373a (from https://pypi.org/simple/mmcv-full/), version: 1.0rc0
  Found link https://files.pythonhosted.org/packages/56/e6/a89a4eb939480e8fa10612798387b5d4e60dffd113e868cd4ecafcd39bce/mmcv-full-1.0rc2.tar.gz#sha256=8231315af784a08e098b454cd6a400f6286c7844d99cfc4274f4fec8e60748b6 (from https://pypi.org/simple/mmcv-full/), version: 1.0rc2
  Found link https://files.pythonhosted.org/packages/3a/d8/5d72865a013100ab2a3ae918ba54749d2af8a21bdb4a48766ef685f70f60/mmcv-full-1.0.0.tar.gz#sha256=ed3ddf896d9de9a7ccfba3fb9ef2d8bd977265f9ae8310cf442a4affc59a58ff (from https://pypi.org/simple/mmcv-full/), version: 1.0.0
  Found link https://files.pythonhosted.org/packages/c0/df/06bc9b368b33b34d7910c96def7340ed4e457b89eae33016b4405a7f18e2/mmcv-full-1.0.1.tar.gz#sha256=6f28e5c654146e783ffb2b17b4e43219a44ffd0a8a63313e8b609587604529ed (from https://pypi.org/simple/mmcv-full/), version: 1.0.1
  Found link https://files.pythonhosted.org/packages/af/ac/72d570062951e090139a790acfaca495d655f24f008c8ae0c2140cff0eb9/mmcv-full-1.0.2.tar.gz#sha256=d6dd164a1a44bf6afb7bf0ec4e1a66b655a9819587bbdd19dfa3ed9872facea1 (from https://pypi.org/simple/mmcv-full/), version: 1.0.2
  Found link https://files.pythonhosted.org/packages/8e/b1/5f2f350e6f9595f75447226f023e9fa7a1d11d314af6b72ed7c4afbec0fc/mmcv-full-1.0.3.tar.gz#sha256=14b1157a34d5bea3416db25de16bf5c920900ef5461ec783b7e6ed8fa9fc8790 (from https://pypi.org/simple/mmcv-full/), version: 1.0.3
  Found link https://files.pythonhosted.org/packages/4f/69/4e3105e612f5f7523a4ba801f7de7c95de923e982d4237aa1c62bfba4ba1/mmcv-full-1.0.4.tar.gz#sha256=cb942164341c281f437b295464a76931698c0f34d94e77aa629cde95d26695cb (from https://pypi.org/simple/mmcv-full/), version: 1.0.4
  Found link https://files.pythonhosted.org/packages/81/21/ac881594427f879bc35a0803ad1159c287ebc85b273618fcc622192d7291/mmcv-full-1.0.5.tar.gz#sha256=f1921cf7aae6f169227feeb2c5ad652a1e139f41e3c83399ec1774fbd306f1e0 (from https://pypi.org/simple/mmcv-full/), version: 1.0.5
  Found link https://files.pythonhosted.org/packages/1a/06/bf47a758061f9648893c660325f7fd558b1f0644b0a0a597e7defa6182ab/mmcv-full-1.1.0.tar.gz#sha256=f99f5d02577e5dc1815b03cc5846204fb4b3eafa02742015414471ef8bda2219 (from https://pypi.org/simple/mmcv-full/), version: 1.1.0
  Found link https://files.pythonhosted.org/packages/35/62/18e9bb094f6ef9b6838b182db8f0fac2245583d56c73690b5e2f9422a26d/mmcv-full-1.1.1.tar.gz#sha256=dba45bcc257df0176b3427bf7c374dbeac80089cbea8bc8d20b67c9b3e839596 (from https://pypi.org/simple/mmcv-full/), version: 1.1.1
  Found link https://files.pythonhosted.org/packages/3c/f5/af334f417b10918a1fe7fe66ffc29020abece67e7b57910c084d3f4313f3/mmcv-full-1.1.2.tar.gz#sha256=f3e97ec881fd6030fe0ecf05db339e72fb79653a87e5991b02a7a54b2631b829 (from https://pypi.org/simple/mmcv-full/), version: 1.1.2
  Found link https://files.pythonhosted.org/packages/df/7d/7ecdb0c3e410b865411c5ee6d13f74e5bed353b6beb181e025181452a4ff/mmcv-full-1.1.3.tar.gz#sha256=e4be6aa5cdeaa5336ac303cd4d3fb4a5d5cc84d923a619ddfd71846881b96e5d (from https://pypi.org/simple/mmcv-full/), version: 1.1.3
  Found link https://files.pythonhosted.org/packages/b7/29/55d77ee1697402effc63c2f6442479bf97347ec019a6010c7a22aa26616b/mmcv-full-1.1.4.tar.gz#sha256=ee716fc15d43a53c2630101c444393dbaccf310113549de531f6fecdef69d656 (from https://pypi.org/simple/mmcv-full/), version: 1.1.4
  Found link https://files.pythonhosted.org/packages/a0/07/120272070fd3080d9e950e631ea9bdde19f1dbe7e3d93944509b6528c4f8/mmcv-full-1.1.5.tar.gz#sha256=5000479c6c0f4af79d93a5b7b35737666d58cc57d5468b62e8fd07ecbb6c74d0 (from https://pypi.org/simple/mmcv-full/), version: 1.1.5
  Found link https://files.pythonhosted.org/packages/c1/52/c9912d24524b59e418efccb813cbf5ad96c1d277ddae0d9241a2e32d98b6/mmcv-full-1.1.6.tar.gz#sha256=56cbb116dbd248dc9ef097bacf68b811edf96815977ed91dfdbdc0263211a0d7 (from https://pypi.org/simple/mmcv-full/), version: 1.1.6
  Found link https://files.pythonhosted.org/packages/ef/90/e0e86b22e2acc05c55273a680072d7484630e46b487118ce922a3e285343/mmcv-full-1.2.0.tar.gz#sha256=8824ef3c8b576c20b30dae9ae8dd853628676ba3417b2e1e1a6c5f097d795abf (from https://pypi.org/simple/mmcv-full/), version: 1.2.0
  Found link https://files.pythonhosted.org/packages/d7/ca/fa9f0aedeb6c2f701996a71ef03e365c2870b1bb0ea63f07459b1ef9128e/mmcv-full-1.2.1.tar.gz#sha256=fb434ed1f982db8d8173034b369db4d7eb6c1d96279450197a71d1ebf8386eba (from https://pypi.org/simple/mmcv-full/), version: 1.2.1
  Found link https://files.pythonhosted.org/packages/cf/79/c4dc30e1d01230038eff7179f2e049feac1fcd2f36dcecef9ddf0d25635b/mmcv-full-1.2.2.tar.gz#sha256=c0aef2ce36ba80ff4cd7cb4f61591b4e9bb5b157ddd30575213866e9f62db817 (from https://pypi.org/simple/mmcv-full/), version: 1.2.2
Fetching project page and analyzing links: https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html
Getting page https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html
Looking up "https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): download.openmmlab.com:443
https://download.openmmlab.com:443 "GET /mmcv/dist/cu101/torch1.6.0/index.html HTTP/1.1" 200 None
Updating cache with response from "https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html"
  Skipping link: none of the wheel's tags match: cp36-cp36m-manylinux1_x86_64: https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/mmcv_full-1.0.5-cp36-cp36m-manylinux1_x86_64.whl (from https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html)
  Skipping link: none of the wheel's tags match: cp37-cp37m-manylinux1_x86_64: https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/mmcv_full-1.0.5-cp37-cp37m-manylinux1_x86_64.whl (from https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html)
  Skipping link: none of the wheel's tags match: cp38-cp38-manylinux1_x86_64: https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/mmcv_full-1.0.5-cp38-cp38-manylinux1_x86_64.whl (from https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html)
  Skipping link: none of the wheel's tags match: cp36-cp36m-manylinux1_x86_64: https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/mmcv_full-1.1.0-cp36-cp36m-manylinux1_x86_64.whl (from https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html)
  Skipping link: none of the wheel's tags match: cp37-cp37m-manylinux1_x86_64: https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/mmcv_full-1.1.0-cp37-cp37m-manylinux1_x86_64.whl (from https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html)
  Skipping link: none of the wheel's tags match: cp38-cp38-manylinux1_x86_64: https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/mmcv_full-1.1.0-cp38-cp38-manylinux1_x86_64.whl (from https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html)
  Skipping link: none of the wheel's tags match: cp36-cp36m-manylinux1_x86_64: https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/mmcv_full-1.1.1-cp36-cp36m-manylinux1_x86_64.whl (from https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html)
  Skipping link: none of the wheel's tags match: cp37-cp37m-manylinux1_x86_64: https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/mmcv_full-1.1.1-cp37-cp37m-manylinux1_x86_64.whl (from https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html)
  Skipping link: none of the wheel's tags match: cp38-cp38-manylinux1_x86_64: https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/mmcv_full-1.1.1-cp38-cp38-manylinux1_x86_64.whl (from https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html)
  Skipping link: none of the wheel's tags match: cp36-cp36m-manylinux1_x86_64: https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/mmcv_full-1.1.2-cp36-cp36m-manylinux1_x86_64.whl (from https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html)
  Skipping link: none of the wheel's tags match: cp37-cp37m-manylinux1_x86_64: https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/mmcv_full-1.1.2-cp37-cp37m-manylinux1_x86_64.whl (from https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html)
  Skipping link: none of the wheel's tags match: cp38-cp38-manylinux1_x86_64: https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/mmcv_full-1.1.2-cp38-cp38-manylinux1_x86_64.whl (from https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html)
  Skipping link: none of the wheel's tags match: cp36-cp36m-manylinux1_x86_64: https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/mmcv_full-1.1.3-cp36-cp36m-manylinux1_x86_64.whl (from https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html)
  Skipping link: none of the wheel's tags match: cp37-cp37m-manylinux1_x86_64: https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/mmcv_full-1.1.3-cp37-cp37m-manylinux1_x86_64.whl (from https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html)
  Found link https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/mmcv_full-1.1.3-cp37-cp37m-win_amd64.whl (from https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html), version: 1.1.3
  Skipping link: none of the wheel's tags match: cp38-cp38-manylinux1_x86_64: https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/mmcv_full-1.1.3-cp38-cp38-manylinux1_x86_64.whl (from https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html)
  Skipping link: none of the wheel's tags match: cp38-cp38-win_amd64: https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/mmcv_full-1.1.3-cp38-cp38-win_amd64.whl (from https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html)
  Skipping link: none of the wheel's tags match: cp36-cp36m-manylinux1_x86_64: https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/mmcv_full-1.1.4-cp36-cp36m-manylinux1_x86_64.whl (from https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html)
  Skipping link: none of the wheel's tags match: cp37-cp37m-manylinux1_x86_64: https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/mmcv_full-1.1.4-cp37-cp37m-manylinux1_x86_64.whl (from https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html)
  Skipping link: none of the wheel's tags match: cp38-cp38-manylinux1_x86_64: https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/mmcv_full-1.1.4-cp38-cp38-manylinux1_x86_64.whl (from https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html)
  Skipping link: none of the wheel's tags match: cp36-cp36m-manylinux1_x86_64: https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/mmcv_full-1.1.5-cp36-cp36m-manylinux1_x86_64.whl (from https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html)
  Skipping link: none of the wheel's tags match: cp36-cp36m-win_amd64: https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/mmcv_full-1.1.5-cp36-cp36m-win_amd64.whl (from https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html)
  Skipping link: none of the wheel's tags match: cp37-cp37m-manylinux1_x86_64: https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/mmcv_full-1.1.5-cp37-cp37m-manylinux1_x86_64.whl (from https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html)
  Found link https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/mmcv_full-1.1.5-cp37-cp37m-win_amd64.whl (from https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html), version: 1.1.5
  Skipping link: none of the wheel's tags match: cp38-cp38-manylinux1_x86_64: https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/mmcv_full-1.1.5-cp38-cp38-manylinux1_x86_64.whl (from https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html)
  Skipping link: none of the wheel's tags match: cp38-cp38-win_amd64: https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/mmcv_full-1.1.5-cp38-cp38-win_amd64.whl (from https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html)
  Skipping link: none of the wheel's tags match: cp36-cp36m-manylinux1_x86_64: https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/mmcv_full-1.1.6-cp36-cp36m-manylinux1_x86_64.whl (from https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html)
  Skipping link: none of the wheel's tags match: cp37-cp37m-manylinux1_x86_64: https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/mmcv_full-1.1.6-cp37-cp37m-manylinux1_x86_64.whl (from https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html)
  Skipping link: none of the wheel's tags match: cp38-cp38-manylinux1_x86_64: https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/mmcv_full-1.1.6-cp38-cp38-manylinux1_x86_64.whl (from https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html)
  Skipping link: none of the wheel's tags match: cp36-cp36m-manylinux1_x86_64: https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/mmcv_full-1.2.0-cp36-cp36m-manylinux1_x86_64.whl (from https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html)
  Skipping link: none of the wheel's tags match: cp37-cp37m-manylinux1_x86_64: https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/mmcv_full-1.2.0-cp37-cp37m-manylinux1_x86_64.whl (from https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html)
  Skipping link: none of the wheel's tags match: cp38-cp38-manylinux1_x86_64: https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/mmcv_full-1.2.0-cp38-cp38-manylinux1_x86_64.whl (from https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html)
  Skipping link: none of the wheel's tags match: cp36-cp36m-manylinux1_x86_64: https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/mmcv_full-1.2.1-cp36-cp36m-manylinux1_x86_64.whl (from https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html)
  Skipping link: none of the wheel's tags match: cp37-cp37m-manylinux1_x86_64: https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/mmcv_full-1.2.1-cp37-cp37m-manylinux1_x86_64.whl (from https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html)
  Skipping link: none of the wheel's tags match: cp38-cp38-manylinux1_x86_64: https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/mmcv_full-1.2.1-cp38-cp38-manylinux1_x86_64.whl (from https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html)
  Skipping link: none of the wheel's tags match: cp36-cp36m-manylinux1_x86_64: https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/mmcv_full-1.2.2-cp36-cp36m-manylinux1_x86_64.whl (from https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html)
  Skipping link: none of the wheel's tags match: cp37-cp37m-manylinux1_x86_64: https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/mmcv_full-1.2.2-cp37-cp37m-manylinux1_x86_64.whl (from https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html)
  Skipping link: none of the wheel's tags match: cp38-cp38-manylinux1_x86_64: https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/mmcv_full-1.2.2-cp38-cp38-manylinux1_x86_64.whl (from https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html)
Given no hashes to check 1 links for project 'mmcv-full': discarding no candidates
Collecting mmcv-full===1.2.2
  Created temporary directory: C:\Users\ADMINI~1\AppData\Local\Temp\pip-unpack-pwqhsezv
  Looking up "https://files.pythonhosted.org/packages/cf/79/c4dc30e1d01230038eff7179f2e049feac1fcd2f36dcecef9ddf0d25635b/mmcv-full-1.2.2.tar.gz" in the cache
  Current age based on date: 23427
  Ignoring unknown cache-control directive: immutable
  Freshness lifetime from max-age: 365000000
  The response is "fresh", returning cached response
  365000000 > 23427
  Using cached mmcv-full-1.2.2.tar.gz (214 kB)
  Added mmcv-full===1.2.2 from https://files.pythonhosted.org/packages/cf/79/c4dc30e1d01230038eff7179f2e049feac1fcd2f36dcecef9ddf0d25635b/mmcv-full-1.2.2.tar.gz#sha256=c0aef2ce36ba80ff4cd7cb4f61591b4e9bb5b157ddd30575213866e9f62db817 to build tracker 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-req-tracker-vd063ox8'
    Running setup.py (path:C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-52kllgyt\mmcv-full_ef816f7a5ee44ce19902b62569c0065b\setup.py) egg_info for package mmcv-full
    Created temporary directory: C:\Users\ADMINI~1\AppData\Local\Temp\pip-pip-egg-info-fd30xv6w
    Running command python setup.py egg_info

**Comment by ycxioooong** [comment]
Seems like this issue can not be reproduced on other platforms like Linux...
Please refer to [this doc](https://mmcv.readthedocs.io/en/latest/build.html#build-on-windows) for building mmcv-full on Windows.

**Comment by bbbxixixixi** [comment]
> Seems like this issue can not be reproduced on other platforms like Linux...
> Please refer to [this doc](https://mmcv.readthedocs.io/en/latest/build.html#build-on-windows) for building mmcv-full on Windows.

succeed. but it needs to mind the 'CONSTEXPR_EXCEPT_WIN_CUDA const' problem mentioned in the link. Thanks for your help.
