### ISSUE TITLE
install mmcv-full on windows10

### ISSUE THREAD

**Issue by lujiayou123** [open-mmlab/mmcv#771]
pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory

**Comment by ycxioooong** [comment]
Some resoures that may be helpful:
https://stackoverflow.com/questions/40018405/cannot-open-include-file-io-h-no-such-file-or-directory

**Comment by wangruohui** [comment]
`io.h` should be installed along with the compiler. I use visual studio and the file exist under `C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt`. You can check it in your environment. 

Would you please provide more detailed information, especially the compilation command that lead to this error?
