### ISSUE TITLE
How to update the version, do I have to reinstall it?

### ISSUE THREAD

**Issue by SKBL5694** [open-mmlab/mmcv#773]
I have installed mmcv with the version 1.1.5 but the new version of mmdection needs mmcv-version at least 1.2.4. So is there any convenient way to update the version of mmcv or I must uninstall old version and install the new version?

**Comment by SKBL5694** [comment]
I found that the latest version of mmcv on windows is 1.1.5 which does not satisfy with the latest mmedetion. Because the latest mmdection at least needs mmcv-1.2.4. I'm not sure if I made a mistake. Is there any advice for me? Thanks a lot.

**Comment by minouei-kl** [comment]
you should install mmcv-full as the mmdetection [documentation](https://github.com/open-mmlab/mmdetection/blob/master/docs/get_started.md#installation) suggests i.e:
pip install mmcv-full

**Comment by cl886699** [comment]
hi ,whats the version of mmdetection? when you use  mmcv 1.1.5, does it works well

**Comment by ycxioooong** [comment]
You may refer to https://github.com/open-mmlab/mmdetection/blob/master/docs/get_started.md#prerequisites to find the suitable `mmcv-full` version as required by your `mmdet`. 
Updating mmcv-full is very easy by simply add -U in the command. (https://github.com/open-mmlab/mmcv#installation).
For example, upgrade your mmcv-full from 1.1.5 to 1.2.5:
```bash
pip install mmcv-full==1.2.5 -f https://download.openmmlab.com/mmcv/dist/{cu_version}/{torch_version}/index.html -U
```  

Or if you build mmcv-full from source, then the procedure will be:
1. git clone mmcv with a specified version.
2. `cd mmcv`
3. `MMCV_WITH_OPS=1 pip install -e -U .`
