### ISSUE TITLE
FLOPs or MAC for conv?

### ISSUE THREAD

**Issue by harryhan618** [open-mmlab/mmcv#785]
It seems in [flops_counter.py](https://github.com/open-mmlab/mmcv/blob/f169fb5279c128b84ccfddf971760e5484d6a537/mmcv/cnn/utils/flops_counter.py#L483), multiplication and addition are treated as one operation. So I think it is calculating MAC rather than FLOPs? I think n MAC refers to n multiplication and (n-1) addition operations.

May I ask what's the usual way to calculate FLOPs?

**Comment by dreamerlin** [comment]
Hi! There is no problem here: actually, everywhere variables named flops are handled as macs ([ref](https://github.com/sovrasov/flops-counter.pytorch/issues/40)). But for most CV tasks, we identify FLOPs with MACs.

**Comment by harryhan618** [comment]
Thanks!

**Comment by code-by-jin** [comment]
> Hi! There is no problem here: actually, everywhere variables named flops are handled as macs ([ref](https://github.com/sovrasov/flops-counter.pytorch/issues/40)). But for most CV tasks, we identify FLOPs with MACs.

Shouldn't FLOPs = 2* MACs. I am totally lost here. Should we just use the output macs to get flops, or we need multiply it by 2
