### ISSUE TITLE
win10 ModuleNotFoundError: No module named 'mmcv._ext'

### ISSUE THREAD

**Issue by cl886699** [open-mmlab/mmcv#788]
when i use this(from mmdet.apis import init_detector, inference_detector) to test, i got this problem
i can import mmcv correct.
this is my enviroments
python=3.7.9
cuda=10.1
cudnn=7.6.5
pytorch=1.7.1
mmcv=1.2.5
mmdect=2.8.0
i installed mmcv followed this  [tutories](https://mmcv.readthedocs.io/en/latest/build.html#prerequisite)

**Comment by ycxioooong** [comment]
Did you built `mmcv` with ops?

**Comment by ycxioooong** [comment]
Here are some related issues for your reference:
https://github.com/open-mmlab/mmdetection/issues/3765
https://github.com/open-mmlab/mmcv/issues/204

**Comment by cl886699** [comment]
> Did you built `mmcv` with ops?

sorry， i think i make mistake when build mmcv.

**Comment by SamMohel** [comment]
did you solve it ?
