### ISSUE TITLE
imshow_bboxes does not show bboxes if img is incontiguous 

### ISSUE THREAD

**Issue by LutingWang** [open-mmlab/mmcv#801]
As [DKDKDDK](https://stackoverflow.com/questions/57586449/why-cv2-rectangle-sometimes-return-np-ndarray-while-sometimes-cv2-umat) asked, cv2.rectangle seems unable to draw inplacely on incontiguous arrays. When calling `mmcv.imshow_bboxes` or `mmcv.imshow_det_bboxes`, the contiguousness of argument `img` is consistent with what the user passed in. Would it be convenient to add `img = np.ascontiguousarray(img)` inside `mmcv.imshow_bboxes` and `mmcv.imshow_det_bboxes`?

**Comment by ycxioooong** [comment]
Hi @LutingWang, great suggestions. We'll consider adding this in next versions. @ZwwWayne could you please have a look?

**Comment by ZwwWayne** [comment]
Agree with that. @LutingWang , would you like to create a PR for that?

**Comment by ZwwWayne** [comment]
BTW, MMDetection just switches its visualization backend from OpenCV to matplotlib. We will also migrate it once we are certain that the API is stable for more general usages.
