### ISSUE TITLE
Failed to install mmcv-full==1.2.0 on Windows10

### ISSUE THREAD

**Issue by shuaizzZ** [open-mmlab/mmcv#822]
python==3.6.3
torch==1.6.0+cu101
torchvision==0.7.0+cu101

ERROR：
(manuvision-trainer) D:\work\manuvsion-detection>pip install mmcv-full==1.2.0 -f https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html

Looking in links: https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html
Collecting mmcv-full==1.2.0
  Downloading mmcv-full-1.2.0.tar.gz (241 kB)
     |████████████████████████████████| 241 kB 1.1 MB/s
  WARNING: Generating metadata for package mmcv-full produced metadata for project name mmcv. Fix your #egg=mmcv-full fragments.
WARNING: Discarding https://files.pythonhosted.org/packages/ef/90/e0e86b22e2acc05c55273a680072d7484630e46b487118ce922a3e285343/mmcv-full-1.2.0.tar.gz#sha256=8824ef3c8b576c20b30dae9ae8dd853628676ba3417b2e1e1a6c5f097d795abf (from https://pypi.org/simple/mmcv-full/). Requested mmcv from https://files.pythonhosted.org/packages/ef/90/e0e86b22e2acc05c55273a680072d7484630e46b487118ce922a3e285343/mmcv-full-1.2.0.tar.gz#sha256=8824ef3c8b576c20b30dae9ae8dd853628676ba3417b2e1e1a6c5f097d795abf has inconsistent name: filename has 'mmcv-full', but metadata has 'mmcv'
ERROR: Could not find a version that satisfies the requirement mmcv-full==1.2.0
ERROR: No matching distribution found for mmcv-full==1.2.0

**Comment by ZwwWayne** [comment]
Sorry that we do not provide pre-built MMCV packages for Windows now. You need to compile it by yourself following the [doc here](https://mmcv.readthedocs.io/en/latest/build.html#build-on-windows).

**Comment by shuaizzZ** [comment]
> Sorry that we do not provide pre-built MMCV packages for Windows now. You need to compile it by yourself following the [doc here](https://mmcv.readthedocs.io/en/latest/build.html#build-on-windows).

Thanks, I will try it.
