### ISSUE TITLE
input current_epoch and total epoch into run_iter in the function train  of EpochBasedRunner

### ISSUE THREAD

**Issue by jeffreykuang** [open-mmlab/mmcv#833]
I have a detector with many losses, one of which is very computation expensive. I would like to compute it in the last k epochs when training.  However, I cannot get the training progress (currect_epoch, and total epoch) in the detector.

One way solve it is to feed currect_epoch, and total epoch into self.run_iter(data_batch, train_mode=True) in the function train of 
EpochBasedRunner.

Is it possible to support this feature?

**Comment by Johnson-Wang** [comment]
Building a hook as the following might help
```python
@HOOKS.register_module()
class SetHeadEpochHook(Hook):
    def before_train_epoch(self, runner):
        runner.model.roi_head.bbox_head.epoch = runner.epoch

```
