### ISSUE TITLE
redundant variable assignment

### ISSUE THREAD

**Issue by ZhiyuanChen** [open-mmlab/mmcv#836]
https://github.com/open-mmlab/mmcv/blob/f75a88c2978dec6f2ce74503d9aeb94d76976f5b/mmcv/runner/epoch_based_runner.py#L95-L99

is a bit redundant with

https://github.com/open-mmlab/mmcv/blob/f75a88c2978dec6f2ce74503d9aeb94d76976f5b/mmcv/runner/epoch_based_runner.py#L44

I found there was a [pr](https://github.com/open-mmlab/mmcv/pull/554) with regard to this, but it has closed quite some time ago. I assume it is closed because `runner._max_iters` is referenced before `runner.train()`, and removing the first lines leads to bugs.

**Comment by hellock** [comment]
Yes `before_run` hooks may use this variable.

**Comment by ZhiyuanChen** [comment]
> Yes `before_run` hooks may use this variable.

This approach looks a bit strange... as `workflow` may not contain `train` and it will lead to an Exception.
