### ISSUE TITLE
Change IterTimerHook registration strategy in base_runner.py

### ISSUE THREAD

**Issue by pledgelth** [open-mmlab/mmcv#837]
I found that the function 'register_training_hooks' in mmcv/runner/base_runner.py just use 'register_hook' function to register IterTimerHook Class's instance into runner hook list, unlike other hook such as CheckPointHook use 'register_checkpoint_hook' function to build CheckPointHook Class's instance first and then use register_hook function to register this instance into runner hook list.

code is here: [IterTimerHook](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/base_runner.py#L438)

It will result in a problem that if I just want to override IterTimerHook in my project, I need to override EpochBaseRunner too because the 'register_training_hook' function in the mmcv won't use the IterTimerHook which overrided by me.

So if you guys can change IterTimerHook registration strategy, add a '**register_itertimer_hook**' function in base_runner.py, it will be convenient for us to just use '@HOOKS.register_module(force=True)' decorator to override IterTimerHook in ours upper project.

Thanks!

**Comment by MeowZheng** [comment]
Many thanks for your nice comments. We have added `register_itertimer_hook` for `BaseRunner` in PR [#838](https://github.com/open-mmlab/mmcv/pull/838).
