### ISSUE TITLE
mmcv compile option for Jetson AGX : what should TENSORRT_DIR be?

### ISSUE THREAD

**Issue by YB17** [open-mmlab/mmcv#851]
I'm trying to compile mmcv on Jetson AGX Xavier with Jetpack 4.5, and I would like to compile with TRT. I noticed that the option TENSORRT_DIR should be set. What should be the content of this variable? Thanks in advance!

**Comment by RunningLeon** [comment]
@YB17 
`TENSORRT_DIR ` is the directory to the installed TensorRT on your machine.
Please refer to the [TRT doc](https://github.com/open-mmlab/mmcv/blob/master/docs/tensorrt_plugin.md) for more detailed infomation.

**Comment by RunningLeon** [comment]
closed due to age.

**Comment by dklee98** [comment]
@YB17  Did you solve this problem? I got the same issue.
