### ISSUE TITLE
Question on the auto_fp16 decorator?

### ISSUE THREAD

**Issue by huangh12** [open-mmlab/mmcv#857]
I am very puzzled by the `two if condition` (see below) of the auto_fp16 function, and hopefully someone can clarify it for me.
https://github.com/open-mmlab/mmcv/blob/58a84833520b3b5c71896ae45b9fa09831bd363d/mmcv/runner/fp16_utils.py#L42

```Python
            if not isinstance(args[0], torch.nn.Module):
                raise TypeError('@auto_fp16 can only be used to decorate the '
                                'method of nn.Module')
            if not (hasattr(args[0], 'fp16_enabled') and args[0].fp16_enabled):
                return old_func(*args, **kwargs)
```

Take the mmdet code in https://github.com/open-mmlab/mmdetection/blob/9d47a8a965ba4c45fbc360b7b4162bd769aa1d7d/mmdet/models/roi_heads/mask_heads/fcn_mask_head.py#L117 for example (see below).     

The args[0] of the above code corresponds to the x in the below function. So why x must be a torch.nn.Module and 
why the original old_func is returned directly in condition of `not (hasattr(args[0], 'fp16_enabled') and args[0].fp16_enabled) `.

```Python
    @auto_fp16()
    def forward(self, x):
        for conv in self.convs:
            x = conv(x)
        if self.upsample is not None:
            x = self.upsample(x)
            if self.upsample_method == 'deconv':
                x = self.relu(x)
        mask_pred = self.conv_logits(x)
        return mask_pred
```

**Comment by hiyyg** [comment]
args[0] should be `self`

**Comment by huangh12** [comment]
Thank you, I was too careless..
