### ISSUE TITLE
Question about test_ops

### ISSUE THREAD

**Issue by Looottch** [open-mmlab/mmcv#859]
It's a general question, I'm also writing custome ops for pytorch, may I ask how you get those ground truth of ops in test file

**Comment by ZwwWayne** [comment]
Hi, for ops, if they have math formulas that are not complicated or can be implemented in another way, we usually calculate the results of several simple inputs by our manual calculation (like [this](https://github.com/open-mmlab/mmcv/blob/master/tests/test_ops/test_box_iou_rotated.py)) or with a different way to check the implementation of op. If it also implements the backpropagation process, we will also use the gradcheck API in pytorch to check  the correctness (see [here](https://github.com/open-mmlab/mmcv/blob/master/tests/test_ops/test_carafe.py#L5)).
