### ISSUE TITLE
[Proposal] Roadmap of MMCV?

### ISSUE THREAD

**Issue by daavoo** [open-mmlab/mmcv#870]
Most downstream projects of open-mmlab have a "Roadmap" pinned issue where community and maintainers discuss about the direction of each project. As an user of several of those downstream projects I personally found those roadmap issues very useful for staying updated. 

I think that it could be also useful to have a similar issue for the core project `mmcv`, specially since there are many ongoing efforts that will affect the downstream projects once merged (i.e. #695 #739 #760 #828 #869).

In my opinion, this would help the users of multiple downstream projects to have an unique place to check for the direction of the core codebase.

**Comment by hellock** [comment]
Good idea. We are indeed heading to a new version with some refactoring and features. It would be better to publish our design and roadmap in an issue.

**Comment by ZwwWayne** [comment]
Hi @daavoo ,
We now have an iteration plan for each version now. We are going to put the plans of two versions in one issue, which is a plan for the whole month. Example is https://github.com/open-mmlab/mmcv/issues/870
