### ISSUE TITLE
ImportError: cannot import name 'load_url_dist' from 'mmcv.runner.checkpoint' (/home/ai-pose/mmcv/mmcv/runner/checkpoint.py)

### ISSUE THREAD

**Issue by MaarufB** [open-mmlab/mmcv#874]
/home/ai-pose/anaconda3/envs/open-mmlab-test/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py:41: UserWarning: Cython.Distutils.old_build_ext does not properly handle dependencies and is deprecated.
  "Cython.Distutils.old_build_ext does not properly handle dependencies "
Traceback (most recent call last):
  File "mmskl.py", line 7, in <module>
    import mmskeleton
  File "/home/ai-pose/mmskeleton/mmskeleton/__init__.py", line 1, in <module>
    from . import utils
  File "/home/ai-pose/mmskeleton/mmskeleton/utils/__init__.py", line 3, in <module>
    from .checkpoint import load_checkpoint, get_mmskeleton_url, cache_checkpoint
  File "/home/ai-pose/mmskeleton/mmskeleton/utils/checkpoint.py", line 2, in <module>
    from mmcv.runner.checkpoint import load_url_dist
ImportError: cannot import name 'load_url_dist' from 'mmcv.runner.checkpoint' (/home/ai-pose/mmcv/mmcv/runner/checkpoint.py)

Hi. Anyone knows how to fix this error?

**Comment by ZwwWayne** [comment]
This is because of the incompatibility between mmskeleton and mmcv versions. You may use lower version of MMCV.

**Comment by MaarufB** [comment]
Thanks, I already solved it by lowering the mmcv version
