### ISSUE TITLE
Is print log “Use load_from_torchvision loader” designed on purpose

### ISSUE THREAD

**Issue by irvingzhang0512** [open-mmlab/mmcv#875]
https://github.com/open-mmlab/mmcv/blob/27e9ede5b9ba46097a7f5e8bd652b5794ab07769/mmcv/runner/checkpoint.py#L243

When training mmaction2 models, print log `Use load_from_torchvision loader` shows. ’This line looks like a debug log that someone forgot to delete.

**Comment by ZwwWayne** [comment]
This logger tries to log which loader is used to load the model which may be useful in some cases.
It is indeed kept for debug purposes.

**Comment by irvingzhang0512** [comment]
I do agree this is useful in some cases. Perhaps the way it shows could be more formal...
