### ISSUE TITLE
"epoch_{}.pth" is not a good name

### ISSUE THREAD

**Issue by iamRyanChia** [open-mmlab/mmcv#880]
When running more than one models and setting therir work_dir to one same folder, the checkpoints obtained later will override the previous ones. The log files are distinguished by timestamp, maybe the checkpoints can also be named like this `filename_tmpl=self.timestamp + '_epoch_{}.pth'`.

https://github.com/open-mmlab/mmcv/blob/ce10425d2fdd3fbe6c16b971e6243565c3981e64/mmcv/runner/epoch_based_runner.py#L132

**Comment by zhouzaida** [comment]
It is advised to set up work_dir to isolate different experiments.
