### ISSUE TITLE
bug in ema hook?

### ISSUE THREAD

**Issue by LeoCho1learning** [open-mmlab/mmcv#901]
In runner.EMAHook, warm_up(int, default  to 100) is setted to make momentum smaller at first of trainning. 
But in line 63(runner.EMAHook.py),
momentum = min(self.momentum, (1 + curr_step) / (self.warm_up + curr_step)),
it seems that the warm_up param doesn't work. it will always choose the default momentum unless warm_up is a big value.
so is this a bug? Or did i miss something?

Thanks!

**Comment by zhouzaida** [comment]
https://github.com/open-mmlab/mmcv/blob/933b052d9591ebcb8d37e4c48d4ce5ddc6d4ad5d/mmcv/runner/hooks/ema.py#L59-L65

if self.momentum equals 0.0002 and self.warm_up is 10000, at the beginning, 
momentum will be  (1 + curr_step) / (self.warm_up + curr_step)) .
But, as curr_step goes bigger, such as curr_step is 5000, momentum will be the self.momentum which is constant value.
The process is called warming up.
