### ISSUE TITLE
how to log into one single file when running multiple GPUs

### ISSUE THREAD

**Issue by ChuanyangZheng** [open-mmlab/mmcv#908]
Thank you for your reply. 
I have changed the logger.py in mmcv as following:
```
# if rank == 0 and log_file is not None:
# Here, the default behaviour of the official logger is 'a'. Thus, we
# provide an interface to change the file mode to the default
# behaviour.
# file_handler = logging.FileHandler(log_file, file_mode)
# handlers.append(file_handler)
file_handler = logging.FileHandler(log_file, file_mode)
handlers.append(file_handler)
```
I remove the rank 0 condition because I want to logging information from all processes into one single log_file. The result is in my question. It seems that the log file is bound into rank 0 and can not be changed by other processes. 

And I have tested creating log_file for every process, that workes. But how can I log all data into one single log file?
Please help me out, help!

_Originally posted by @ChuanyangZheng in https://github.com/open-mmlab/mmdetection/issues/4797#issuecomment-803261279_

**Comment by zhouzaida** [comment]
file_mode should be 'a'.

**Comment by ChuanyangZheng** [comment]
Thanks for your reply, It works well
