### ISSUE TITLE
Error running MMDataParallel with CPU device

### ISSUE THREAD

**Issue by namirinz** [open-mmlab/mmcv#922]
I'm trying to run the model on CPU but got the error
> module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cpu

Does MMDataParallel model support on running with CPU #?

```
from mmcv.parallel import MMDataParallel
from mmpose.models import build_posenet
from mmcv import Config
from mmcv.runner import load_checkpoint

cfg = Config.fromfile(cfg_file)
model = build_posenet(cfg.model)
    
load_checkpoint(model, ckpt_file, map_location='cpu')

model = fuse_conv_bn(model)
model = MMDataParallel(model, device_ids=None)
```

**Comment by zhouzaida** [comment]
MMDataParallel only supports single GPU training.
https://github.com/open-mmlab/mmcv/blob/f0c43fdc32d28b3ebca58eadfb54f539fea2fe4a/mmcv/parallel/data_parallel.py#L54-L64
