### ISSUE TITLE
How to use MMCV to open and close the feature map？

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmcv#923]
Hi, dear authors
Sorry to bother you.
Could you tell me how to use MMCV to open and close the feature map？
(Just like`open =CV2.morphologyEx(img,CV2.MORPH_OPEN,kernel)` in opencv?)
Thank you!

**Comment by zhouzaida** [comment]
hi, @zhongqiu1245 , MMCV currently doesn't support it.

**Comment by zhongqiu1245** [comment]
thank you
