### ISSUE TITLE
When will the version 1.3.0 be released to pypi?

### ISSUE THREAD

**Issue by yeliudev** [open-mmlab/mmcv#924]
Hi @zhouzaida ! May I ask that when will the mmcv version 1.3.0 be released to pypi? I'm looking forward to install it from pypi.

**Comment by yeliudev** [comment]
It seems that there is a 400 error in [GitHub Actions](https://github.com/open-mmlab/mmcv/runs/2211049855?check_suite_focus=true)

**Comment by zhouzaida** [comment]
> Hi @zhouzaida ! May I ask that when will the mmcv version 1.3.0 be released to pypi? I'm looking forward to install it from pypi.

hi @yeliudev , the version 1.3.0 has been released last week and you can find it at https://github.com/open-mmlab/mmcv#readme

**Comment by yeliudev** [comment]
> > Hi @zhouzaida ! May I ask that when will the mmcv version 1.3.0 be released to pypi? I'm looking forward to install it from pypi.
> 
> hi @yeliudev , the version 1.3.0 has been released last week and you can find it at https://github.com/open-mmlab/mmcv#readme

Thanks for your reply. I've noticed that 1.3.0 has been released on GitHub, but the latest version on PyPI is still 1.2.7, please check [here](https://pypi.org/project/mmcv/).

**Comment by zhouzaida** [comment]
yep, thanks for your feedback, I will release it later.

**Comment by yeliudev** [comment]
> yep, thanks for your feedback, I will release it later.

Thank you!

**Comment by zhouzaida** [comment]
> > yep, thanks for your feedback, I will release it later.
> 
> Thank you!

hi @yeliudev, mmcv1.3.0 has been released to pypi.

**Comment by yeliudev** [comment]
> > > yep, thanks for your feedback, I will release it later.
> > 
> > 
> > Thank you!
> 
> hi @yeliudev, mmcv1.3.0 has been released to pypi.

Thanks!
