### ISSUE TITLE
（mmcv-full_ version : 1.2.6）KeyError: 'Unrecognized norm type DCN' for build_conv_layer 

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmcv#932]
Hi dear authors
Sorry to bother you
I am trying to use mmcv wrapper build_conv_layer to build DCN following the code in mmseg like this:
![image](https://user-images.githubusercontent.com/48090608/114192984-ac450480-9980-11eb-866d-98018341f734.png)
But the error still exists.(my version of mmcv-full : 1.2.6)
Could you tell me how to deal with it?
Thank you!

**Comment by zhouzaida** [comment]
hi @zhongqiu1245 , have you registered the dcn into CONV_LAYERS?
https://github.com/open-mmlab/mmcv/blob/b5e1facc85219770b6e85a9cfb2ec554167ccedc/mmcv/cnn/bricks/conv.py#L5-L8

**Comment by zhouzaida** [comment]
hi, @zhongqiu1245 , has issue been resolved?

**Comment by zhongqiu1245** [comment]
@zhouzaida 
I'm sorry to reply you so late.
I tried it yesterday. 
Thank you very much.

**Comment by Yuxiang1995** [comment]
Hi, @zhongqiu1245 How do you solve this problem? I meet the same issue as you.

**Comment by songsee** [comment]
> 很抱歉这么晚才回复你。我昨天试过了。 谢谢。

大佬，您怎么解决的啊？给我们指导指导，跪谢！

**Comment by songsee** [comment]
> 嗨，您是否已将DCN注册到CONV_LAYERS？
> 
> https://github.com/open-mmlab/mmcv/blob/b5e1facc85219770b6e85a9cfb2ec554167ccedc/mmcv/cnn/bricks/conv.py#L35-L37

<img width="807" alt="Snipaste_2023-04-28_16-08-25" src="https://user-images.githubusercontent.com/114144026/235280996-413e9da6-a6c7-4058-af8a-ac260caf6bea.png">
<img width="865" alt="Snipaste_2023-04-28_16-11-46" src="https://user-images.githubusercontent.com/114144026/235281003-f4b05658-a204-478a-b81a-4c3b76efceba.png">

作者您好，我也遇到了此类问题，第一次使用mmcv，能不能详细和我说一下遇到这种问题如何解决啊？

**Comment by songsee** [comment]
> Hi, @zhongqiu1245 How do you solve this problem? I meet the same issue as you.

大佬 你这问题解决了吗

**Comment by songsee** [comment]
> Hi dear authors Sorry to bother you I am trying to use mmcv wrapper build_conv_layer to build DCN following the code in mmseg like this: ![image](https://user-images.githubusercontent.com/48090608/114192984-ac450480-9980-11eb-866d-98018341f734.png) But the error still exists.(my version of mmcv-full : 1.2.6) Could you tell me how to deal with it? Thank you!

大佬 讲讲咋解决的啊

**Comment by songsee** [comment]
> hi, @zhongqiu1245 , has the issue been resolved?

大佬 这种问题咋解决啊
