### ISSUE TITLE
I am getting an error while installing mmcv-full

### ISSUE THREAD

**Issue by Rahul2203** [open-mmlab/mmcv#943]
ERROR: Command errored out with exit status 1: /anaconda/envs/open-mmlab/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-z3t5jyb9/mmcv-full_15a96b01709e4933b4f3d8335d3f86a2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-z3t5jyb9/mmcv-full_15a96b01709e4933b4f3d8335d3f86a2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-1faon1bq/install-record.txt --single-version-externally-managed --compile --install-headers /anaconda/envs/open-mmlab/include/python3.7m/mmcv-full Check the logs for full command output.

**Comment by zhouzaida** [comment]
hi, @Rahul2203 , could you provide the command of installing mmcv-full?

**Comment by Rahul2203** [comment]
pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cuda101/torch1.6.0/index.html

**Comment by Rahul2203** [comment]
> hi, @Rahul2203 , could you provide the command of installing mmcv-full?
pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cuda101/torch1.6.0/index.html

**Comment by zhouzaida** [comment]
> > hi, @Rahul2203 , could you provide the command of installing mmcv-full?
> > pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cuda101/torch1.6.0/index.html

https://download.openmmlab.com/mmcv/dist/cuda101/torch1.6.0/index.html should be https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html

**Comment by Rahul2203** [comment]
Thanks

**Comment by jiabeiwangTJU** [comment]
I have the same problem with u, but I compiled locally, what causes this problem?

**Comment by jiabeiwangTJU** [comment]
ERROR: Command errored out with exit status 1: /home/ubuntu/anaconda/envs/alignps92/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/storage/wjb/AlignPS/mmcv/setup.py'"'"'; __file__='"'"'/storage/wjb/AlignPS/mmcv/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

**Comment by zhouzaida** [comment]
> ERROR: Command errored out with exit status 1: /home/ubuntu/anaconda/envs/alignps92/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/storage/wjb/AlignPS/mmcv/setup.py'"'"'; **file**='"'"'/storage/wjb/AlignPS/mmcv/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

hi, @jiabeiwangTJU , Could you provide the command you use and the environment?
