### ISSUE TITLE
Error compiling objects for extension

### ISSUE THREAD

**Issue by jiabeiwangTJU** [open-mmlab/mmcv#955]
ERROR: Command errored out with exit status 1: /home/ubuntu/anaconda/envs/alignps92/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/storage/wjb/AlignPS/mmcv/setup.py'"'"'; __file__='"'"'/storage/wjb/AlignPS/mmcv/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

I download mmcv1.1.5, then  use ''MMCV_WITH_OPS=1 pip install -e .'' , then get the error. pytorch 1.7.0, cuda11.0,9.2 all tried but no work(pytorch change to download with cuda absolutely).

**Comment by zhouzaida** [comment]
Hi, @jiabeiwangTJU , Could you try to install higher version, such as mmcv1.2.7 or 1.3.0

**Comment by zhouzaida** [comment]
hi, @jiabeiwangTJU , has the issue been resolved?

**Comment by jiabeiwangTJU** [comment]
Yes, I rebuild an environment, use 'pip install -v -e',  pytorch=1.9.0.dev20210415=py3.7_cuda11.1_cudnn8.0.5_0, mmcv=1.1.5,mmdetion=2.4.0
