### ISSUE TITLE
win10 build 1.3.1 ninja error

### ISSUE THREAD

**Issue by bbbxixixixi** [open-mmlab/mmcv#960]
I have 
vs2019 commity
Python=3.7
CUDA=10.1
Pytorch=1.6.0
try to build from source but get error message 
python : D:\Python\Python37\lib\site-packages\torch\utils\cpp_extension.py:335: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the sl
ow distutils backend.
I search the issues and find prebuilt whl but no suitable matches >=1.2.4  windows10 prebuilt is 1.1.5 in https://download.openmmlab.com/mmcv/dist/index.html
can you provide more up-to-date whl? Thanks

**Comment by zhouzaida** [comment]
hi, @bbbxixixixi , Could you install ninja?

**Comment by bbbxixixixi** [comment]
> hi, @bbbxixixixi , Could you install ninja?

I install ninja and build 1.3.1 successfully
mmm, I tried pip install ninja before, it told me cannot find suitable packages. I thought ninja is some kind of mysterical part during building process. it tend out to succeed this time...
anyway, it is ok now
