### ISSUE TITLE
`KeyError: "RetinaNet: 'Model  is not in the backbone registry'"`

### ISSUE THREAD

**Issue by mathshangw** [open-mmlab/mmcv#963]
i got this error `/home/user/anaconda3/lib/python3.7/site-packages/mmdet/models/builder.py:72: UserWarning: train_cfg and` `test_cfg is deprecated, please specify them in model`
 ` 'please specify them in model', UserWarning)`
`Traceback (most recent call last):`
 ` File "/home/user/anaconda3/lib/python3.7/site-packages/mmcv/utils/registry.py", line 179, in build_from_cfg`
`    return obj_cls(**args)`
 ` File "/home/user/anaconda3/lib/python3.7/site-packages/mmdet/models/detectors/retinanet.py", line 17, in __init__`
`    test_cfg, pretrained)`
 ` File "/home/user/anaconda3/lib/python3.7/site-packages/mmdet/models/detectors/single_stage.py", line 25, in __init__`
`    self.backbone = build_backbone(backbone)`
 ` File "/home/user/anaconda3/lib/python3.7/site-packages/mmdet/models/builder.py", line 39, in build_backbone`
`    return build(cfg, BACKBONES)`
 ` File "/home/user/anaconda3/lib/python3.7/site-packages/mmdet/models/builder.py", line 34, in build`
`    return build_from_cfg(cfg, registry, default_args)`
 ` File "/home/user/anaconda3/lib/python3.7/site-packages/mmcv/utils/registry.py", line 172, in build_from_cfg`
`    f'{obj_type} is not in the {registry.name} registry')`
`KeyError: 'Model is not in the backbone registry'`
`During handling of the above exception, another exception occurred:`
`Traceback (most recent call last):`
`  File "train.py", line 190, in <module>`
 `   main()`
`  File "train.py", line 164, in main`
 `   cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)`
`  File "/home/user/anaconda3/lib/python3.7/site-packages/mmdet/models/builder.py", line 77, in build_detector`
 `   return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))`
`  File "/home/user/anaconda3/lib/python3.7/site-packages/mmdet/models/builder.py", line 34, in build`
 `   return build_from_cfg(cfg, registry, default_args)`
`  File "/home/user/anaconda3/lib/python3.7/site-packages/mmcv/utils/registry.py", line 182, in build_from_cfg`
 `   raise type(e)(f'{obj_cls.__name__}: {e}')`
`KeyError: "RetinaNet: 'Model  is not in the backbone registry'"`

i have cuda 11 with 
`TorchVision: 0.8.2`
`OpenCV: 4.5.1`
`MMCV: 1.2.7`
`MMCV Compiler: GCC 7.3`
`MMCV CUDA Compiler: 11.0`
`MMDetection: 2.10.0+`

**Comment by zhouzaida** [comment]
hi, @mathshangw , `RetinaNet` is not in the backbone registry but in detector registry. Maybe you could check the config or provide the config here?

**Comment by mathshangw** [comment]
thanks @zhouzaida  i tried to change from backbone to detector but got another error .. the code was work successfully but when I tried to run it again I got this problem .. i mean it is supposed to be backbone not detector as I have in the model . is there another thing I should check it ?

**Comment by zhouzaida** [comment]
Would you provide the config here?

**Comment by zhouzaida** [comment]
hi, @mathshangw , has the issue been resolved?
