### ISSUE TITLE
How to export Pytorch model with custom op to ONNX and run it in TENSORRT?

### ISSUE THREAD

**Issue by ZJU-lishuang** [open-mmlab/mmcv#965]
I have exported Pytorch model with custom op to ONNX.

But I don't know how to export the onnx model with custom op to tensorrt model?

The custom op has added to tensorrt by REGISTER_TENSORRT_PLUGIN.

What else do I need to do?

**Comment by zhouzaida** [comment]
hi, @ZJU-lishuang , you can refer to the link https://github.com/open-mmlab/mmcv/blob/master/mmcv/tensorrt/tensorrt_utils.py

**Comment by RunningLeon** [comment]
@ZJU-lishuang You can refer to the doc https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/onnx2tensorrt.md if you are using mmcv and mmdetection.

**Comment by ZJU-lishuang** [comment]
How does the tensorrt analysis and correspondence the custom op in onnx to itself In mmcv and mmdetection?
I perfer a brief guide.
In where you refer to I can't find the key point and key code.
Maybe the mmcv use onnxruntime rather than onnx-tensorrt to do the work?

**Comment by ZJU-lishuang** [comment]
I find [DEFINE_BUILTIN_OP_IMPORTER(FallbackPluginImporter)](https://github.com/onnx/onnx-tensorrt/blob/master/builtin_op_importers.cpp#L4289) in [onnx-tensorrt](https://github.com/onnx/onnx-tensorrt).
Any ops that are not supported will attempt to import as plugins by utilizing the `fallbackPluginImporter` function.
I want to use it,but I am new in the deployment.
Can anyone else help me?

**Comment by ZJU-lishuang** [comment]
How to connetciton the custom op bewteen ONNX and TENSORRT?
`DEFINE_BUILTIN_OP_IMPORTER` in onnx-tensorrt and `DEFINE_BUILTIN_OP_IMPORTER` in tensorrt?

**Comment by grimoire** [comment]
Hi, @ZJU-lishuang
MMCV did use `onnx-tensorrt` to do the conversion.
We also provide some TensorRT plugins to support custom ops. `getPluginType()` in the plugin returns the ONNX ops type, which will help `onnx-tensorrt` find the right implementation.
Please read [plugin src](https://github.com/open-mmlab/mmcv/tree/master/mmcv/ops/csrc/tensorrt) for more details.

**Comment by ZJU-lishuang** [comment]
Thanks

**Comment by RunningLeon** [comment]
Feel free to reopen it if you still have the issue.
