### ISSUE TITLE
Add custom hook by config file

### ISSUE THREAD

**Issue by mzr1996** [open-mmlab/mmcv#967]
I need to use Exponential Moving Average and noticed that mmcv has provided [EMAHook](https://mmcv.readthedocs.io/en/latest/_modules/mmcv/runner/hooks/ema.html?highlight=hook)
However, as https://github.com/open-mmlab/mmcv/issues/689#issue-756829674 mentioned, EMA should happen after optimizer update and before checkpoint save. But by now, we have to modify the mmcv library file to do this.
Maybe we need a generic way to insert new hooks by configuration and let them work in the right order.

**Comment by zhouzaida** [comment]
Agree, do you have any idea to resolve it?

**Comment by mzr1996** [comment]
> Agree, do you have any idea to resolve it?

I have created a PR to show my idea, please check it.

**Comment by zhouzaida** [comment]
ok, Thanks for your contribution.

**Comment by zhouzaida** [comment]
resolved by #970
