### ISSUE TITLE
More detailed document about config inheritance.

### ISSUE THREAD

**Issue by Wuziyi616** [open-mmlab/mmcv#968]
Hi, I would like to raise an issue about the document of config inheritance. The example provided in the current document ([here](https://mmcv.readthedocs.io/en/latest/utils.html?highlight=config#config)) only covers a few cases. In my usage, I tried `config_a.py`:
```
evaluation=dict(interval=1, xxx=xxx)
```
while ```config_b.py```:
```
_base_ = './config_a.py'
evaluation=dict(interval=2)
```
I discovered that `config_b.evaluation=dict(interval=2, xxx=xxx)`, which means in the inheritance, the dict only overwrite the overlapped keys and will keep the other keys. I also heard that overwriting `List` also has such effects now. I really think these are super cool features, and it would be great if you can mention them in the document. Thanks.

**Comment by zhouzaida** [comment]
yep, extending the document is in our plan.

**Comment by Wuziyi616** [comment]
Great to hear.
