### ISSUE TITLE
A problem about softmax_focal_loss

### ISSUE THREAD

**Issue by LaoYang1994** [open-mmlab/mmcv#986]
https://github.com/open-mmlab/mmcv/blob/5a99f587ed09797ae6720d33888c753ad88f178a/mmcv/ops/csrc/softmax_focal_loss_cuda_kernel.cuh#L55
What's the meaning of `buff` and `grad_input`

**Comment by zhouzaida** [comment]
hi, @LaoYang1994

+ forward
```python
pred = softmax(x)
loss = focal_loss(pred, target)
```
+ backward
```python
buff stores the grad of pred
grad_input stores the grad of x
```
