### ISSUE TITLE
Automatically install cython as a dependency instead of installing manually

### ISSUE THREAD

**Issue by karlind** [open-mmlab/mmcv#99]
I wonder if there is a way to install `cython` as a `mmcv`'s dependency.

Every time I install `mmcv`, I will forget install cython first, which always raise an exception. I find `mmcv`'s `setup.py` requires `cython` to build itself. So is it possible to install `cython` automatically?

**Comment by hellock** [comment]
I tried but failed to find a good way to achieve that. If you have any ideas, you may create a PR to improve the installation.

**Comment by karlind** [comment]
#101 This seems work well.
